### ISSUE TITLE
Proposal Change to Init/Core

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#110]
Currently, models are created in the following way:

1) init, sets up store
2) model, merges into the store

This is both inefficient, and sometimes a problem:
- have to create your own loop for creating models
- merging reducers one by one is slower than adding them as an initial object (like `extraReducers`)
- plugins can't run on the initial set of models (issue with redux-persist plugin)

### Proposal

1) init - pulls reducers out of models
2) setup plugins and store
3) run models through plugin pipeline (except for reducers)

Recommend adding models on startup. I think models should be an object, as each key must be unique.

```js
init({
  models: { count }
})
```

---

This can actually be quite elegant. In another app using Dva, I do it the following way.

/models/index.js
```js
export { default as count } from './count'
export { default as todos } from './todos'
```

Then I import them in.

/index.js
```js
import * as models from './models'

init({
  models,
})
```

**Comment by ShMcK** [comment]
I should add, I'm not proposing that we remove "model". I think it's a cool way to lazy load.

But rather that we should create and recommend the use of `init.models`

**Comment by blairbodnar** [comment]
@ShMcK Awesome! Great thinking on this - I totally agree.
