### ISSUE TITLE
Consider effect/reducer state props

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#125]
A comparison:

##### Dva/Mirror
Reducers(state, action)
Effects(action, state)

##### Rematch
Reducers(state, payload)
Effects(payload, getState)

---

Should effects use `getState` or actually pass in the `state`? What are the benefits/drawbacks of each?

**Comment by blairbodnar** [comment]
Here's a benefit for `getState`. You only call `getState` if you need it, so it's better for performance than having the state snap shot passed in.

```js
effects: {
  dinnerTime: (payload, getState) => {
    if (payload.isHungry) {
      const { pizza } = getState().food
      dispatch.people.blair.eat(pizza)
    }
  }
}
```

**Comment by blairbodnar** [comment]
Wait a sec though... We could just get the state like this if we wanted it:
```js
import { getStore } from '@rematch/core'
getStore().getState()
```
Hang on.. This brings up a question/issue I've been pondering... I'll write up another issue.

**Comment by ShMcK** [comment]
Performance wise, getState() makes more sense. Calling `getState` on every action can be quite costly.

But I do hope there is a happy medium between convenience and performance.

**Comment by blairbodnar** [comment]
Actually, what I'm thinkings makes sense as part of this issue thread.

I'm wondering if we should consider making the effects and subscriptions function signatures as follows:

```js
effects: {
  upByAsync: (payload, getState, exposed) => { ... }
},
subscriptions: {
 'countB/upBy': (payload, getState, exposed) => { ... }
},
```
With that, you can access `exposed.dispatch` and whatever other things plugins have exposed.

... and you don't need to `import anything from '@rematch/core'` when you write you models!


### models/countA.js
```js
// Look ma! No imports!

export default {
  name: 'countA',
  state: 1,
  reducers: {
    upBy: (state, payload) => state + payload
  },
  effects: {
    upByAsync: (payload, getState, exposed) => { ... }
  },
  subscriptions: {
    'countB/upBy': (payload, getState, exposed) => { ... }
  },
  selectors: {
    prependWith: (state, payload) => `${payload}${state}`
  }
}
```

**Comment by ShMcK** [comment]
Which exposed properties would you want access to?

On thing to consider:

1. We should have a way to support `meta` properties on an action, not sure where that will go

I also wonder, if effects/subscriptions are part of a reducer, then state should be passed in to create it. There must be a way that we can reference that state, rather than `getState`

**Comment by blairbodnar** [comment]
I think usually people just want access to `exposed.dispatch` and `getState`... But maybe it would be useful to have access to other things plugins might expose? I'm not sure though... Maybe just giving access to `exposed.dispatch` and  and `getState` is enough.

> We should have a way to support meta properties on an action, not sure where that will go

- Yep, agreed. 

This discussion actually ties a bit in with another thought I've been digesting in the back of my brain...

Is it worth considering a different API, or another way of thinking about `reducers`, `effects`, and `subscriptions`? I was thinking about this the other day. And what problems each are solving. (Or another way of putting it, what questions and answers they are generating...)

I thought about when I'm designing a model. [Then I thought about if I was a model.](http://www.dailymail.co.uk/tvshowbiz/article-2332080/Former-Calvin-Klein-underwear-model-Travis-Fimmel-gets-hairy-makeover-takes-new-role-TV-series-Vikings.html) Then I thought about what questions I ask myself as a model in a Rematch-y best practices kinda way.
1. How do I change myself? Answer: `reducers`
2. How do I change myself, but with information from the outside world? `effects`
3. How do I change myself when something else in the outside world happens? `subscriptions`

So... All these questions are about me changing changing my state. It's just different ways of doing it.

It makes me wonder if `reducers`, `effects`, and `subscriptions` could be combined into a more general concept. At the end of the day, (*Unless I'm missing something*), they all end up changing the model's state.

That being said, let me introduce you...

🥁 *drum roll* 🥁

 ...to Blair's crazy `stateChangers` idea!

💥*cymbal crashes* 💥

### Blair's crazy `stateChangers` idea:
```js
const model = {
  name: 'countA',
  state: 0,
  stateChangers: {
    upBy: (modelState, payload) => modelState + payload,
    upByAsync:  async (modelState, payload, getState, exposed) => {
      await delay(1000)
      exposed.dispatch.countA.upBy(1)
    },
    'countB/upBy': (modelState, payload, getState, exposed) => { ... }
  },
}
/*
Note: `modelState` is the same 'state' we're familiar with. It's just to
remind you that you're dealing with the model's chunk of state, and 
not the entire state tree that you would get with `getState()`.
*/
```


With the above model, here's one way Rematch could know what is a `reducer`, `effect`, or `subscription` when it processes the model:
```js
Object.keys(model.stateChangers|| {}).forEach((stateChanger) => {
  if (stateChanger.includes('/')) {
    // this is a subscription!
  } else if ((model.stateChangers[stateChanger]  === 'some code to tell if async function') {
   // this is an effect!
  } else {
   // this is a reducer!
  }
}
```

Am I crazy? I'm probably crazy.

@ShMcK 
@scottclayton (I know you're busy, but taggin' ya anyways 😜)

**Comment by scottclayton** [comment]
I think grouping subscriptions in there is a little more confusing, since they aren't something that gets explicitly called, unlike effects/reducers—I think of subscriptions as listeners and not dispatchable.

BUT… I hear you on the other ideas to a degree. I often wonder… what if we lived in a world where all reducers were non-blocking during their execution and could affect the state of other models? I love the idea of reducers that I could optionally have an async/await call within and take that information and distribute it out to the models that need it.

e.g. what if reducers could look be written synchronously or asynchronously like this:
```js
reducers: {
  changeThemePreference(state, payload) {
    return {
      ...state,
      // user is a model
      user: { ...state.user, themePreference: payload.themePreference },
      // profile is a model
      profile: { ...state.profile, hasThemePreference: true },

    }
  },
  setDataFromAPI(state, payload) {
    return fetch(`https://www.someapi.com/${payload.id}`)
      .then((data) => {
        return {
          ...state,
          // user is a model
          user: { ...state.user, data },
          // profile is a model
          profile: { ...state.profile, blogPosts: data.blogPosts },
        }
      })
  }
}
```

I suspect I'm missing something fundamental, and I think asynchronicity is also just not how reducers work. I would also have to rewrite everything I've ever done.

**Comment by ShMcK** [comment]
Reducers are based on a concept called "state machine". You set all the knobs you can change on the machine, and how they effect the state. Personally, I often ignore this idea and just call a lot of my reducers "set". However, there may be value in it.

I think "stateChangers" is a crazy idea, but its inspiration is makes sense. 

> Why can't everything change state?

Answer? I dunno. State machine is a concept, so it shouldn't. ?

I have a number of questions along these lines as well.

1. Should effects be able to change state? 
2. Should effects even be actions?

I'll need to organize my thoughts on these a bit more.

**Comment by ShMcK** [comment]
But back to paving over potholes:

` upByAsync: (payload, getState, exposed) => { ... }`

I think if this is the case, it makes more sense to add `getState` to `exposed`.

` upByAsync: (payload, { getState, dispatch }) => { ... }`

+1 simplicity

However, I still think, ultimately it can be something like:

` upByAsync: (payload, state, { dispatch }) => { ... }`

+ 1 performance

**Comment by ShMcK** [comment]
I'll make an argument for why "reducers" and "effects" are the way they are. This is by no means saying this is right, I'm not even sure what I think.

### Reducers
Always need state
Sometimes need payload
Should never call other reducers or redux throws errors about reducers calling reducers
Should not be async, or state becomes unpredictable. For example, an action may be triggered without its state change taking effect until later. 

### Effects
Generally need payload
Sometimes need state
Can call other reducers or effects
Can be async, or not
Should be categorized as effects for plugins like "loading", "lastUpdated", etc.

**Comment by blairbodnar** [comment]
Thanks for the thoughts guys! Good discussion.

> However, I still think, ultimately it can be something like:
`upByAsync: (payload, state, { dispatch }) => { ... }`
+1 performance

Cool - I would have assumed this would be less performant though? Since the state is always being snapshotted no matter what (even if it ends up not being used in the effect)? Probably just have to try it out and see!

Also, would the `state` here be the model state (like in the reducer) or the entire global state that `getState()` gives?

**Comment by ShMcK** [comment]
This morning I looked at effects, and how they're done in Mirror & DVA.

Reducers: have access to state directly

Effects: always an `store.getState()` call to pass the state in. This is because effects are handled in middleware, where there's no access to state.

Maybe adding `getState` to `exposed` is the best solution. Not sure.

```js
upByAsync: (payload, { getState, dispatch }) => { ... }
```

**Comment by blairbodnar** [comment]
> Maybe adding getState to exposed is the best solution. Not sure.
`upByAsync: (payload, { getState, dispatch }) => { ... }`

I do like this idea. Might be our best bet.

**Comment by ShMcK** [comment]
🥁 drum roll 🥁

...Blair's not so crazy exposers idea!

💥cymbal crashes 💥
