### ISSUE TITLE
Temp Logo

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#128]
Just a thought for a temporary logo. Ran a popular logo through an 8bit filter.

![logo8bit](https://user-images.githubusercontent.com/4660659/32687224-df50ce3a-c66c-11e7-908f-a61be2c73147.png)

**Comment by blairbodnar** [comment]
Cool idea, I like it!

**Comment by ShMcK** [comment]
Looking at it... its pretty ugly.
