### ISSUE TITLE
React Native - Persist plugin: PersistGate issue

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#145]
Running into an issue with PersistGate.

```
TypeError: Cannot read property 'subscribe' of undefined
```

Seems like `getPersistor` is not always running after the store is created.

Note: React Native only.

**Comment by ShMcK** [comment]
Work around:

```js
import { getStore } from '@rematch/core'
import { persistStore } from 'redux-persist'

const store = getStore()
const persistor = persistStore(store)
```

Within the app.

**Comment by ShMcK** [comment]
Closed for now, as not much else we can do.

**Comment by Johncy1997** [comment]
configureStore.js:
***************************
      import {createStore, applyMiddleware,compose} from 'redux';
      import thunk from 'redux-thunk';
      import {logger} from 'redux-logger'

       import allReducers from '../reducers';

          const middleware = [ thunk,logger
        ];

           const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;


         export default function configureStore() {
              let store = createStore(
                     allReducers,
                    undefined,
                    composeEnhancers(applyMiddleware(...middleware))
                    );
        console.log("Created store is"+store);
        return store;
             }

PersistedStore.js
**************************
         import configureStore from './configureStore';
       import {persistStore} from 'redux-persist';

           export const store = configureStore();

       const PersistedStore = persistStore(
         store,
         undefined,
       ()=>{
          console.log('rehydration completed!'+store.getState())
       }
      )

      export default PersistedStore;

App.js:
********************
      import PersistedStore, { store } from './components/store/PersistedStore';
     ...
      render() {
       return (
      <Provider store={store}>
        <PersistGate loading={null} persister={PersistedStore}>
          <Routes/>
        </PersistGate>
        </Provider>
    
         );
        }

![screenshot 16](https://user-images.githubusercontent.com/25324938/45586667-2e7c0200-b919-11e8-9952-9533c5310cd0.png)
