### ISSUE TITLE
Model options

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#149]
I think it would be helpful to have a namespace on models for placing plugin options.

Currently I do this:

```js
{
  name: 'counter',
  state: 0,
  persist: true
}
```

Then I map over all models

```js
import * as models from './models'

const whitelist = Object.keys(models).filter(name => models[name].persist)
```

Kind of ugly. Consider an uglier case:

I'd like to change '@rematch/loading' to take options. It doesn't make much sense to add loading indicators to all effects, when you really only want them on 10% of them.

```js
{
  name: 'counter',
  state: 0,
  persist: true,
  loading: ['async', 'upBy'],
  reducers,
  effects,
  etc...
}
```

Then mapping over models with loading, and adding `${name}/${action}` to each. 

It doesn't look great in my code, and it makes the models cluttered.

### Proposal

It would be nicer if options were grabbed from initial models on startup and passed in automatically. This means options need their own namespace

```js
const counter = {
  name: 'counter',
  state: 0,
  pluginOptions: {
      persist: true,
      loading: ['async', 'upBy'],
  }
}
```

Then when plugins are created, the model options are automatically passed in.

Possible names: 'options', 'pluginOptions'?

@blairbodnar, what are your thoughts?

**Comment by blairbodnar** [comment]
@ShMcK 

I haven't used the loading or persist plugins yet, so my thoughts here are from a fresh eyes look at it.

Looking at what you describe... why not just manage this type of stuff outside of the models? And then pass the relevant information into the plugin's options?

For example... looking at your persist whitelist - Why not just manually add which models you want to include in your whitelist as you develop your app? Sure it's not automated, but sometimes maybe not automating it is easier / simpler?

```js
const persistWhitelist = ['todos', 'auth', 'userProfile'] // just add to this list manually

import createRematchPersist from '@rematch/persist'

const persistPlugin = rematchPersist({
  whiteList: persistWhitelist,
  throttle: 5000,
  version: 1,
})

init({
  plugins: [persistPlugin()]
})
```

Same idea with loading... just manage it manually?
```js
import { init } from '@rematch/core'
import createLoadingPlugin from '@rematch/loading'

const loadingWhiteList = {
  counter: ['async', 'upBy'],
  todos: ['addTodo', 'removeTodo']
  // add to this list manually...
  // the models and effects you want to include with the loading plugin
}

const loading = createLoadingPlugin({
  name: 'load',
  whiteList: loadingWhiteList
})

init({
  plugins: [loading]
})
```

So I guess what I suggest here keeps the models uncluttered... and sure it's not automated for making the whitelists. But you still have to type it *somewhere*. You're either typing `persist: true` in the model or adding it to the whitelist manually. I think it might be best to not clutter up the models?

**Comment by ShMcK** [comment]
You make a good point.

It comes down to a question of:

##### Where should plugin options for a model live?
- in the model - more elegant, but possibly more cluttered
- in the plugin config - simpler

I think you can make a good case for either.

The idea of a model is "put everything in one file, so you can see what's happening in one place". But its true, we have to draw a line somewhere before it gets too cluttered.

I'll close this PR and put it on the backburner for now.
