### ISSUE TITLE
model API: Remove `name`

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#152]
As discussed with @ShMcK, Let's remove `model.name`.

Rematch can determine the name from `init.models`
```js
init({
  models: {
    count: { ... },
    todos: { ... }
  }
})
```

**Comment by ShMcK** [comment]
What if someone uses the "dynamic model" API?

```js
model({
 name: 'count',
 state: 0,
})
```

**Comment by blairbodnar** [comment]
I think we should pull out the "dynamic model" into it's own separate plugin. Then that plugin could enforce that `model.name` is implemented on models. (Or it could maybe find another way of dealing with names)
