### ISSUE TITLE
Should plugins use ES6 maps?

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#167]
Plugins like "loading" & "updated" can get pretty heavy, as they are constantly replacing values in objects. They would be more performant, and maybe even easier to use with ES6 maps.

Take a comparison:

### Regular objects
- more familiar
- less performant
```js
state.updated.someModel.someEffect
// returns a date, or undefined
state.updated.notAModel.someEffect
// throws an error
```

### ES6 Maps
- more performant
- less likely to throw
```js
state.updated.get('someModel/someEffect')
// returns a date, or undefined

state.updated.get('notAModel/someEffect')
// returns undefined
```

**Comment by blairbodnar** [comment]
Hmm... I really like using Maps for lots of stuff... but in rematch I really do like like typing dot dot dot and not having to `.get()`

I think I lean a little towards "no" right now. But will have a think on it.

Are you running into performance issues with loading or updated?

**Comment by ShMcK** [comment]
Not really. I'm probably trying to solve the wrong issue here.

I think it would be better improved if you just select which effects should be updated, or loaded. 

```
const config = {
  whitelist: {
    someModel: ['someEffect']
  }
}
```
