### ISSUE TITLE
Init creates store

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#172]
Nan had a good idea.

We could eliminate `getStore` if `init` simply returns the store.

**Comment by blairbodnar** [comment]
Yeah could do...

So far in my playing around with rematch I've only had to use `getStore()` when I pass it to `react-redux`'s `<Provider />`. Having init return the store would be fine I think.

That being said, should init return the store or `getStore` (a function)? I think we might need to return `getStore`, no?

I can't really think of any cases right now where someone might want to `Rematch.getStore()` in other areas of their app which are away from their init logic... so I'd say we go for the change.

**Comment by ShMcK** [comment]
This is possible:

```js
import { init } from '@rematch/core'
import App from './App'

const store = init()

const App = () => {
  <Provider store={store}>
    <App />
  </Provider>
}
```

I also can't think of anywhere getStore is used, other than in unit tests. But init is used in the same tests.

**Comment by ShMcK** [comment]
Looking at the current API reference, it could be distilled down to the following. 

```
dispatch
- action

model
- state
- reducers
- effects

init
- models
- plugins
- redux
```

Anything else to trim away?

**Comment by blairbodnar** [comment]
Nice! Yeah API is starting to look nice and clean.

Can't think of anything else to trim at the moment.
