### ISSUE TITLE
Add Live Example

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#175]
Nan mentioned he had to pull examples to get everything started.

It would likely be easier if we just made some examples in JSFiddle or CodePen to get people started.

**Comment by blairbodnar** [comment]
Totally agree. Want to make it very fast and easy for people to play with an example. It's a pain in the ass to have to pull it just to try out a quick example.

**Comment by ShMcK** [comment]
Any preference of code playgrounds?

**Comment by blairbodnar** [comment]
Hmm, I like codepen best I think! I'm easy!

**Comment by ShMcK** [comment]
Can use unpkg.com: https://unpkg.com/@rematch/core@0.1.0-beta.8/

**Comment by ShMcK** [comment]
close in favor of #191
