### ISSUE TITLE
Redux Devtools history erased

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#180]
On startup, history is getting erased.

May be linked to this [issue](https://github.com/gaearon/redux-devtools/issues/378)

When `replaceReducer` is called, the merging of state replaces state.

**Comment by ShMcK** [comment]
Nevermind, not a bug. Redux devtools just has a limited queue.

**Comment by bdwain** [comment]
hi. where did you see the thing about devtools having a limited queue? I haven't seen that anywhere. it seems like the history gets erased when replaceReducer is called, not when the queue reaches a certain size.

**Comment by ShMcK** [comment]
To be clearer, I had the problem using the Redux Devtools inside of the "React Native Debugger".

**Comment by bdwain** [comment]
hm alirght. so maybe it still is a bug with redux devtools. thanks.
