### ISSUE TITLE
Rethinking `effects`

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#19]
Hmm.

I wonder... do `effects` really belong in a model?

Effects... they do a bunch of impure stuff... and then they call dispatch, multiple dispatches, or not even call dispatch at all. The only real relation with a model is that they sometimes call a dispatch for a model.

The more I think about it, the more I start leaning towards something like this...

#### Idea A: `effects` implemented in `init`.
```js
import { init } from 'rematch'
init({
  effects: {
    doStuff: async (payload, getState) => {...}
  }
})

// elsewhere
import { effects } from 'rematch'
effects.doStuff({ foo: 'bar' })
```

#### Idea B: `effects` are 'registered' like a `model`
```js
import { effect } from 'rematch'
effect({
  doStuff: async (payload, getState) => {...}
})

// elsewhere
import { effects } from 'rematch'
effects.doStuff({ foo: 'bar' })
```

Thoughts?

**Comment by ShMcK** [comment]
What you're describing is kind of the way that sagas are meant to work. They have no relation with any particular data model, but they can make calls to different reducers.

A) It makes sense not to bind effects to models, as they may call multiple models.

B) On the other hand, the goal of an effect is to change particular state, and state is always bound to a model.

As a rough estimate, in my own experience, I would say 90% of my the time I've found the effect bound to the model made good organizational sense, but the other 10% of the time it didn't. I often had to choose between two models that an effect was suited for.

I can forsee a stricter type of architecture where model effects make perfect sense.

1) effects can only change data for a given model
2) "hooks" are used to listen to changes from the outside world. For example, "take" and "takeEvery" listeners on specific actions.

This would keep models isolated from each other.

**Comment by blairbodnar** [comment]
Cool, great thoughts! And yeah, I like the idea of strict isolated models too.

I think that as we develop the framework, and implement different examples and use it, we'll start to sense what is feeling right and wrong... or what feels best practice-ish. I think we'll be able to come up with the happy medium as you mentioned: The framework that lets you do what you want, but guides you the right way.

I'll close this issue for now... but this is great food for thought to keep in mind as we move forward.

🤘
