### ISSUE TITLE
Demo in README

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#191]
How about using [CodePen Projects](https://codepen.io/pro/projects)?

### PROS

Folders and files.
Loads faster than WebpackBin.

##### No NPM modules
BUT: https://blog.codepen.io/2017/08/11/using-resources-npm-codepen/ 
Could use unpkg or a fake node_modules folder

**Comment by blairbodnar** [comment]
Nice, yeah that looks pretty good!

**Comment by ShMcK** [comment]
https://codepen.io/Sh_McK/project/editor/Agpeed# ?

**Comment by blairbodnar** [comment]
Awesome!!! Looks great! 😄

**Comment by levito** [comment]
Nice! FYI: codesandbox.io also allows NPM modules

**Comment by ShMcK** [comment]
Codesandbox.io looks great.

**Comment by oieduardorabelo** [comment]
hey there 👋 , i've migrated the demo example to codesandbox:

**Embedded**
https://codesandbox.io/embed/q84ymw3776

**Editor**
https://codesandbox.io/s/q84ymw3776

seems a cool project, I've been playing with it for the last 2 days,

many thanks for the time you put on it 🙏

**Comment by ShMcK** [comment]
Thanks @oieduardorabelo. Much better.

Would you like to put in a PR to replace the link in the README?

We could always use another contributor :)

**Comment by blairbodnar** [comment]
Awesome @oieduardorabelo ! Thanks!

**Comment by ShMcK** [comment]
I've just updated the example on the README page. Thanks again https://github.com/oieduardorabelo.

I'd like to add examples for Angular & AngularJS as well. Let us know if you know of a good platform similar to codesandbox that might server those environments.
