### ISSUE TITLE
Connect mapDispatchToProps with rematch dispatch

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#200]
Provide a fix for react-redux connect mapDispatchToProps to overwrite dispatch with rematches dispatch.

**Comment by ROB-64** [comment]
I am interested in what benefit this would provide ?

**Comment by ShMcK** [comment]
Currently, most people use `mapStateToProps` to pass in dispatches.

```js
const mapStateToProps = (state) => ({
  onClick: dispatch.button.press,
  onPress: () => dispatch.button.press(),
})

connect(mapStateToProps)(Component)
```

Two downsides to this:

### 1. Simplicity

You have to import both "react-redux" and "rematch" to get things working.

### 2. Performance

Connect checks for a diff when the state changes within mapStateToProps (but not mapDispatchToProps). 

In the example above, `onClick` would be fine, since it references the same function. But any anonymous functions would trigger a re-render. `() => {}` does not equal `() => {}`. I believe `onPress` would always trigger a re-render.

I think people can be aware of how to avoid performance problems in mapStateToProps, but there's probably an easier solution. I'm not entirely sure what this is yet.

**Comment by ROB-64** [comment]
Thank you for the writeup, this makes more sense to me now.
