### ISSUE TITLE
Add support for react-navigation@beta-28

### ISSUE THREAD

**Issue by bohdan-shulha** [rematch/rematch#202]
Hey guys!

The latest react-navigation changed the way it [connects to Redux](https://reactnavigation.org/docs/redux-integration.html). Now it is requires to use middleware from the `react-navigation-redux-helpers` package

**Comment by ShMcK** [comment]
That's great news. That should make the integration much simpler.

Will update sometime early this week.

**Comment by ShMcK** [comment]
I've published a working version @rematch/react-navigation@1.0.0-beta.1.

I'll add it to a larger project at work before publishing as @1.0.0, to ensure everything is working.

But feel free to give it a try.

See the [Changelog](https://github.com/rematch/rematch/blob/update/react-navigation/plugins/react-navigation/CHANGELOG.md) for details.
