### ISSUE TITLE
Investigate using a domain based store

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#209]
There are three main ways to communicate state between components:

### 1. Parent-Child
This is generally by the UI framework. Eg. passing values between components that are close to each other.. 

### 2. Global Connected
Storing and updating data that may be used all over the app. Redux, or Rematch are a great fit.

### 3. Domain Specific
Data that is only needed in one particular area of your app. Often UI, or form data, etc. Think of React's new upcoming [Context API](https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b), or the quite elegant [Unstated](https://github.com/thejameskyle/unstated)). 

Unfortunately, this third scenario likely requires a framework-specific solution. It needs to keep track of the component tree (the "domain"). I'm not sure if Rematch would be a good fit. 

However, I would like to see a solution for React, based on the new context API that uses "models", that can be provided & subscribed to. I think this would create an even simpler API than unstated.

Something to think about.

**Comment by ShMcK** [comment]
### unstated:

```js
class CounterContainer extends Container<CounterState> {
  state = {
    count: 0
  };

  increment() {
    this.setState({ count: this.state.count + 1 });
  }

  decrement() {
    this.setState({ count: this.state.count - 1 });
  }
}
```

### proposed

```js
const counter = new Domain({
  state: {
    count: 0
  },
  reducers: {
    increment(state) {
      return { count: state.count + 1 }
    },
    decrement(state) {
      return { count: state.count - 1 }
    }
  }
})
```

**Comment by blairbodnar** [comment]
Cool stuff @ShMcK . Something to think about!

Playing devil's advocate here: Is there a need for a framework in scenario 3? Comparing your proposed solution to simply using local state in react... it looks very similar:

```jsx

class CounterComponent extends React.Component {

  state = { count: 0 },

  increment() {
    this.setState({ count: this.state.count + 1 })
  }

  decrement() {
    this.setState({ count: this.state.count - 1 })
  }

  render() { 
   return (
    <div>
      Count is {this.state.count}
      <button onClick={this.increment}>increment</button>
      <button onClick={this.decrement}>decrement</button> 
    </div>
    )
  }

}


```

**Comment by blairbodnar** [comment]
Sorry, I edit my comment above quite a bit, Refresh for latest! 😎

**Comment by ShMcK** [comment]
I think in the example above the values may become out of sync as each becomes its own instantiated component with default state.

So the recipe requires:
1) a single place to store data. (aka <Container />)
2) a wrapper to subscribe to that data (aka <Subscribe />)
3) a way to map out the "domain" that a subscription has access to (aka <Provider />).

**Comment by ShMcK** [comment]
But actually, I think I'll use your recommended approach today to clean up some components. Thanks!

**Comment by blairbodnar** [comment]
@ShMcK 

> I think in the example above the values may become out of sync as each becomes its own instantiated component with default state.

Values are [N'sync](https://www.youtube.com/watch?v=Eo-KmOd3i7s)! 🕺🕺🕺🕺🕺

Made a working example here: 
[https://codesandbox.io/s/32kv5j2y56](https://codesandbox.io/s/32kv5j2y56)


I think I hit the three requirements? Unless I'm misunderstanding you?

> 1. a single place to store data. (aka Container)

`<CounterDomain />`

> 2. a wrapper to subscribe to that data (aka Subscribe)
```jsx
<CounterDomain>
  {domain => (
    <div>Prop that I'm subscribing to: {domain.count} </div>
  )}
</CounterDomain>
```
> 3. a way to map out the "domain" that a subscription has access to (aka Provider).
Same as above? Unless I'm not following you? 🙃. There is access to anything the `CounterDomain` passes down in it's render prop.
```jsx
<CounterDomain>
  {domain => {
    const { count, increment, decrement, whateverElseTheDomainGivesYou } = domain
    return (
      <div />
    )
  }}
</CounterDomain>
```

**Comment by ShMcK** [comment]
You kids with your render props. Back in my day, we had to pass state down from our grandparents.

**Comment by blairbodnar** [comment]
👴🏻

Coolz coolz, yeah it will be interesting to see what ideas the new context API brings. And yeah, so far I've been mostly ok with local state + redux/rematch. But most apps I've worked on have been relatively small.

**Comment by ShMcK** [comment]
Closed as out of the scope of a Redux framework.
