### ISSUE TITLE
React Navigation Plugin - add android back

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#211]
Look into optionally adding android back handler 

See [notes](https://reactnavigation.org/docs/redux-integration.html#handling-the-hardware-back-button-in-android)

**Comment by ShMcK** [comment]
Closed as not necessary.

**Comment by levito** [comment]
Could you please provide details on how to handle Android back when using the React Navigation Plugin?

**Comment by levito** [comment]
I found how to handle Android back, `store.getState()` makes this simple and straightforward in the root component:

```js
import { dispatch, init } from '@rematch/core';
import createReactNavigation from '@rematch/react-navigation';
import React, { Component } from 'react';
import { BackHandler } from 'react-native';
import { Provider } from 'react-redux';

import * as models from './models';
import { Routes } from './Routes';

const { Navigator, reactNavigationPlugin } = createReactNavigation({
  Routes,
  initialScreen: 'Home',
});

const store = init({
  models,
  plugins: [reactNavigationPlugin],
});

export class App extends Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBack);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.handleBack);
  }

  render() {
    return (
      <Provider store={store}>
        <Navigator />
      </Provider>
    );
  }

  handleBack = () => {
    if (store.getState().nav.index === 0) {
      BackHandler.exitApp();
    }
    dispatch.nav.back();
    return true;
  };
}
```

Would it make sense to have this in the plugin example?

**Comment by ShMcK** [comment]
You can also use `import { getState } from '@rematch/core'` to access state.

Definitely an example should be added to the readme, or example.

One solution would be as you have it above. Another would be to create a component called "AndroidBack", and wrap your root component with it.

In an app I'm currently working on, I've manually handled back, for uses like closing modals. Which is why I think it shouldn't necessarily be included inside of react-navigation.


TODO
- [ ] add android back handler example to react navigation plugin readme
