### ISSUE TITLE
Add 'withRematch' high order function

### ISSUE THREAD

**Issue by pierissimo** [rematch/rematch#219]
## Motivation
Provide an easier and rematch-specific version of the react-redux 'connect' high order function.
## Examples
Something similar would be very convenient:
```javascript
withRematch(
	({ client }, state) => ({
		// the next line will be mapped to: select.client.allClients
		clients: client.allClients,
	}),
	({ client }) => ({
		// the next line is equivalent to: dispatch.client.addClient
		addClient: client.addClient
	}),
);
```
The concept is similar to 'connect'. 
The first parameter will map the selector/state to properties, the second parameter will bind the effects/actions to properties.
An even easier method, could be to use a string approach, based on the namespace (similar to Vuex).
Something like:
```javascript
withRematch(
	{
		clients: 'client/allClients'
	},
	{
		addClient: 'client/addClient'
	}
);
```

What are your thoughts?

**Comment by ShMcK** [comment]
Any higher order or render prop component would have to be framework specific (eg. React only). If we go down this path, we'd be looking at a "rematch-connect". 

I have some other ideas in regards to a possible "rematch-connect". It could potentially be more elegant, as in your second example. 

I'd also like a feature that checks for connect based re-renders, and visualizes them in tree. This would be very helpful for hunting down performance issues.

**Comment by clucasalcantara** [comment]
I also thought that `rematch-connect` would be more elegant to handle this feature, maybe support decorators like `@withRemacth` as well.

**Comment by ShMcK** [comment]
Is it alright to close this issue as beyond the scope of rematch/core?

I don't disagree that connect could be improved, and perhaps if a good solution is worked out we could add it under the "rematch" organization as "react-rematch", or another framework specific name.

**Comment by pierissimo** [comment]
👍
