### ISSUE TITLE
How does one dispatch single action which takes effect on more than one part of the state?

### ISSUE THREAD

**Issue by methyl** [rematch/rematch#226]
Hey there!

Just read https://medium.com/@ShMcK/redesigning-redux-b2baee8b8a38 and it seems to be a really interesting concept, great job on putting it together.

That said, I have one thing I want to ask about.

Consider a use case, where two parts of your state (eg. two different data entities) are in a way dependent of each other, ie. you have more than one source of truth for some part of data. I know it's a discouraged pattern, but I find it makes sense sometimes. If that happens, you need to keep those multiple sources in sync.

Generally, since actions and reducers are decoupled, it's pretty easy task in Redux. One just have to handle single action across multiple reducers. 

In Rematch on the other hand, reducers and actions are tightly coupled together, so I can't really call one action which will result in updating all data points needed.

One way I can think of to solve it would be to have a "global" model without any reducer. This model would have an effect calling all the individual actions of reducers we need to handle, but I can see it can lead to some confusion. Moreover, I don't see any way of accessing other models in an action:

```js
const counter = {
  state: 0, 
  reducers: {
    increment(state, payload) {
      return state + payload
    },
    reset() {
      return 0
    },
  },
}

export const global = {
  effects: {
    // where do I get store from? it could be probably passed as an argument
    resetCounters(_payload, _rootState, store) {
      store.dispatch.firstCounter.reset()
      store.dispatch.secondCounter.reset()
    },
  },
}

const store = init({
  models: {
    firstCounter: counter,
    secondCounter: counter,
    global
  }
})

```

This shape of the state also raises another question: can I nest models somehow, to get an outer scope where I could handle such effects?

**Comment by ShMcK** [comment]
Great question. 

I think as a best practice, models are great for organizing your code. But there are exceptions.

In my own code base, I have several instances where I have actions that effect multiple models. I've developed a few strategies:

1) There is a plugin called "subscriptions", which allows another model to listen to actions and call a function when it is triggered. https://github.com/rematch/rematch/tree/master/plugins/subscriptions. The benefit of this is that your models remain decoupled, not knowing anything about each other.

2) I have cases where I dispatch actions on another model within an effect. 

```js
import { dispatch } from 'rematch/core'

const someAction = {
  effects: {
    onAction() {
       dispatch.otherAction.doSomething()
    }
  }
}
```

3) You don't actually need a global model. you can just call a function that triggers multiple models

```js
import { dispatch } from '@rematch/core'

const triggerMultipleModels = async () => {
  await dispatch.model1.action()
  dispatch.model2.action()
}
```

There may be more options, but I hope this helps. It has been a common question.

**Comment by methyl** [comment]
Thanks, that helps! But it leads me to another question.

It seems that the store is a singleton, since the dispatch in example 3. has no other way to know what the store is. I'm not a big fan of such design, is this something you can opt-out from?

This is similar to the model lazy-loading:
```
import { init, model } from '@rematch/core'

const store = init({
  models: {
    count: { state: 0 }
  }
})

store.getState()
// { count: 0 }


// where does the model get reference to the store?
model({ name: 'countB', state: 99 })
```

It's even more confusing if you consider README section, wrapping the application in Redux provider, bringing it to more decoupled design:
```
ReactDOM.render(
  <Provider store={store}>
    <CountContainer />
  </Provider>,
  document.getElementById('root')
)
```

**Comment by ShMcK** [comment]
Another good question. 

I wonder first, are you looking to add multiple Redux stores to a project? This will result in your Redux devtools not working correctly.

Is there any reason the store should not be a singleton?

Bear in mind, that there is also the option to [dynamically add models in Rematch](https://rematch.gitbooks.io/rematch/docs/api.html#model). This uses Redux's `replaceReducer` API to add models on the fly.

**Comment by ShMcK** [comment]
Oh sorry, I hadn't read your example clearly. Give me a moment.

**Comment by methyl** [comment]
@ShMcK still doesn't answer how `model` method gets a reference to `store`. In case of `replaceReducer`, you call it on `store` itself, but I can't see that you pass it to the `model`. How does that work? If it's a singleton (which as pattern can be pain in the ass since it's harder to debug it vs. explicit passing and it's troublesome in tests), is there a way to opt-out? Same question for built in `dispatch` from `'@rematch/core'`

**Comment by ShMcK** [comment]
I'll mention that in my own code I don't use "model" or "dispatch", and just rely on "react-redux" connect to pass in dispatch from the store. So both are entirely optional.

The code that sets up "model" can be found here: https://github.com/rematch/rematch/blob/a7e60dc2a566b40597082667eb5821c98e9139bb/src/redux/store.ts#L24-L27

There are also plenty of test examples within the [test directory](https://github.com/rematch/rematch/tree/master/test) if you questions about how testing might work with Rematch. In each of these cases a new store is created. 

Reducers can be tested in isolation of course. They are just pure functions.

```js
const count = {
  reducers: {
    increment: (state, payload) => state + payload
  }
}

// test
const result = count.reducers.increment(0, 1)
expect(result).toBe(1)
```

**Comment by methyl** [comment]
If I call
```
model({
 name: 'count',
  state: 0,
})
```

How does model know what is the state without me passing an explicit reference? That's what I'm trying to understand.

> I'll mention that in my own code I don't use "model" or "dispatch", and just rely on "react-redux" connect to pass in dispatch from the store. So both are entirely optional.

```js
const mapDispatch = dispatch => ({
  increment: () => dispatch.count.increment(1),
  incrementAsync: () => dispatch.count.incrementAsync(1)
})

```

Do you somehow extend original `dispatch` from redux store with models?

**Comment by ShMcK** [comment]
### How model works

When using `model`, there are two steps:
1. the new reducer is merged in with the exisiting reducers
2. update the reducer list using Redux's native "replaceReducers"

There is a local reference to store with the ["store.ts"](https://github.com/rematch/rematch/blob/master/src/redux/store.ts) file. This allows functions to be called with the store reference, after it is created.

---

### How dispatch works

Many people don't realize that a everything in Javascript is an object. Even functions.

We can take a function and add object properties to it, in this case our action creators.

```js
store.dispatch.count = {
  increment: (payload) => dispatch({ type: 'count/increment', payload })
}
```

Of course this can be simplified even further by creating a `generateActionCreator` function.

---

What may be confusing about Rematch is also what makes it so simple. In Rematch, everything on a model becomes a plugin. Rematch is then created out of a kind of plugin pipeline, where the model is passed through and everything is setup from "hooks". The idea is that people can create their own models, without having to alter the underlying Rematch core.

I'd like to write an article explaining how the plugin pipeline works in the near future.

**Comment by methyl** [comment]
So it seems store is really a singleton and it won't be possible to have two rematch instances in one app. This is a bit disappointing, since sometimes it's really useful, ie. if you have some library which would internally use rematch, having it abstracted away from you.

Anyway, even if I don't agree with some design decisions, I really like how you simplified stuff. 

Thanks for patience and keep up great job!

**Comment by ShMcK** [comment]
I think you're right. It was not designed with having multiple stores in mind.

Thanks for the tough questions :)

**Comment by wmertens** [comment]
>  It was not designed with having multiple stores in mind

This is just for features like updating reducers in the store, right? You can just create multiple stores for SSR and pass them to react-redux's Provider, right?
