### ISSUE TITLE
Testing rematch models

### ISSUE THREAD

**Issue by nWidart** [rematch/rematch#229]
Hello,

This library looks very interesting! Good job!
I was wondering how you'd go about testing these models? I can't seem to find anything in the documentation.
Since Redux is fairly easy to test, this would be a critical point required in order to migrate to Rematch.

Thanks!

**Comment by ShMcK** [comment]
HI @nWidart, there are two ways I use for testing models.

1) setup a store and dispatch to the model. See [some examples].(https://github.com/rematch/rematch/blob/master/test/dispatch.test.js)

2) Test the models directly. They're just pure functions.

```js
const count = {
  state: 0,
  reducers: {
    increment: (state, payload) => state + payload,
  }
}

// rough example
const result = count.reducers.increment(0, 1)
expect(result).toBe(1)
```

**Comment by nWidart** [comment]
Awesome this, seems straightforward! 

Thanks!
