### ISSUE TITLE
Consider Zenhub for project boards

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#23]
@blairbodnar, to enable Zenhub:

1) get the [Zenhub chrome extension](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd)

2) reload Github

3) Click on "boards" instead of "projects"

Items will automatically move to categories based on their status.

For example, a PR will move into "Q/A under review", and a closed issue will automatically move to "Completed". 

It's a bit more featured that the basic Github boards.

**Comment by blairbodnar** [comment]
Awesome! Done and done.
