### ISSUE TITLE
Is it possible to have models act on actions within other model

### ISSUE THREAD

**Issue by fkrauthan** [rematch/rematch#231]
Based on the API I couldn't find if this is possible. Scenario could be as follow:

I have a generic Loading Model that every time I load data (`reducers` or `effects` getting called with naming convention) it should change its state.

I have a User Model and a Project Model. Both of them implement the effect `load` and both of them implement the reducer `loaded` and `loadingFailed`.

**Comment by blairbodnar** [comment]
In short, yes you can.

Our loading plugin is an example of this: [`@rematch/loading`](https://github.com/rematch/rematch/blob/master/plugins/loading/README.md). It creates a model called `loading` (you can name it whatever you want though), it's state let's you know if:
- global loading is active (ANY effect in any model is running)
- a specific model is loading (ANY effect in a particular model is running)
- a specific model's effect is loading

Here's an example of it in action: https://codesandbox.io/s/985ok833xp

**Comment by fkrauthan** [comment]
So you have to create a plugin? I just scanned thru the code but it looks like a lot of code for something that should be relative simple. Plus that it has to modify other models wrapper methods does not seem very developer/debug friendly.

**Comment by blairbodnar** [comment]
You don't need to create a plugin:

`effects` have the entire root state of the redux store as the 2nd arg, so you can access any model's state from there. That, combined with the global dispatch should arm you with everything you need to have the models talk with each other, no?

```jsx
import { dispatch } from '@rematch/core'

const exampleModel = {
  state: { ... },
  reducers: { ... }
  effects: {
    doSomething: (payload, rootState) => {
      // access something from the payload and rootState if you need it
      // dispatch to this model if you want:
      dispatch.exampleModel.reducerName() // or this.reducerName() shorthand
      // dispatch to any other model if you want
      dispatch.anotherModel.reducerName()
      dispatch.anotherModel.reducerName()
    }
  }
}

// elsewhere
dispatch.exampleModel.doSomething()


```

**Comment by ShMcK** [comment]
See also [226](https://github.com/rematch/rematch/issues/226)

**Comment by fkrauthan** [comment]
I get what you mean but that is exactly what I don't want. That each of my Models need to know about each other. I want a Model that is the core Domain of data and other models can listen for the same events to sidefill there store without the Data model knowing.

**Comment by ShMcK** [comment]
@fkrauthan - have you looked at the [subscriptions plugin](https://github.com/rematch/rematch/blob/master/plugins/subscriptions/README.md)?

**Comment by fkrauthan** [comment]
Ah yeah that would work. But wouldn't it be possible to allow that syntax within models too? If your action contains `/` then it subscribes to a action from a different model. That way I can instant mutate my state instead of having to dispatch a custom action.

**Comment by ShMcK** [comment]
You're right. That's a good idea. 

I was never quite happy with how subscriptions work. It is unnecessary to call an additional action.

If a better solution can be done without much performance cost, I think it's worth doing.

Can you give an example of what you think a model listener should look like? 
From what I gathered, you were suggesting something like the following:

```js
const count = {
  state: 0,
  reducers: {
    'otherModel/reset': () => 0,
  }
}
```

Perhaps it may be even simpler if there was another model key that could be used:

```js
const count = {
  state: 0,
  reducers: { /* ... */ },
  listeners: {
    'otherModel/reset': () => 0,
  }
}
```

@fkrauthan @blairbodnar love to hear your thoughts.

**Comment by guzart** [comment]
I like @fkrauthan proposal, in my mind regardless of how the function it's executed if it's modifying the state it essentially a reducer. How about using special prefix for this "advanced" scenario, such as an `@` to denote a "root path"

```js
const count = {
  state: 0,
  reducers: {
    increment: (state, payload) => state + payload,
    '@otherModel/reset': () => 0,
  }
}
```

**Comment by fkrauthan** [comment]
I like @guzart s suggestion with a prefix. That makes it easy to spot. The only question is would `/` be allowed in a reducer or is that prohibited (because of the auto action creator) anyways?

In addition what jumped into my mind. Can a reducer also listen for `effects` (In the same Model as well as in different models)?

**Comment by ShMcK** [comment]
Both reducers & effects are just actions. So either can be listened to from any model.

I'll try to weigh in on the two options we have now.

### 1. Adding a `listeners` (name TBA) key to the model

Anything under listeners can be assumed to be listening to an action not included in the model. This way you can just listen and match action types directly.

As a downside, it's not clear that a "listener" is really just a reducer.

As a plus, listeners could become a plugin - meaning that there doesn't have to necessarily be a core solution that some people are unhappy with.

### 2. Reducers with other action types

In this case you have to look to see if an action type is for another model. This can be done on startup, by checking to see if it starts with a `@`, or just to see if it can be split on a `/`. This will come with a small performance cost, though basically negligible.

The logic would have to be changed a bit to say, check for 1. model/action, and then 2. for any additional "model/action"s. This also wouldn't be very expensive performance wise.

---

Either way, I think it's worth a bit more discussion before landing on a solution.

**Comment by ShMcK** [comment]
I'll keep an open PR in #236, feel free to continue any discussion there.

**Comment by magicdawn** [comment]
Since the subscription plugin has been deprecated now (2020-09-19).
I made a tiny plugin to do same. just `listen` the verb.
for anyone looking for this.

```js
// rematch-listen-plugin.js
export default ({onError = console.error} = {}) => {
  const listenRegistry = {}
  const addListen = ({actionType, fn}) => {
    if (!listenRegistry[actionType]) {
      listenRegistry[actionType] = []
    }

    if (listenRegistry[actionType].includes(fn)) {
      return
    }

    listenRegistry[actionType].push(fn)
  }

  return {
    createMiddleware: (bag) => (store) => (next) => (action) => {
      const actionType = action.type
      const shouldHandle = listenRegistry[actionType] && listenRegistry[actionType].length

      if (!shouldHandle) {
        return next(action)
      }

      // reducer first
      next(action)

      // call listening effects function
      const {payload} = action
      const rootState = store.getState()
      return Promise.all(
        listenRegistry[actionType].map(async (fn) => {
          // indepenent
          try {
            return await fn(payload, rootState)
          } catch (e) {
            onError(e)
            return e
          }
        })
      )
    },

    onModel(model, store) {
      const {name} = model
      const {dispatch} = store
      const modelDispatcher = dispatch[name]

      let listen = model.listen
      if (listen) {
        if (typeof listen === 'function') {
          listen = listen(dispatch)
        }

        // listen: { [action]: { xxx } }
        for (let [actionType, fn] of Object.entries(listen)) {
          addListen({
            actionType,
            fn: fn.bind(modelDispatcher),
          })
        }
      }
    },
  }
}
```

```js
// model
export default {
  name: nsp,

  state: {
    inited: false,
  },

  listen: {
    'global/reload'() {
      this.load() // use `this.xxx`
    },
  },

  effects: (dispatch) => {
    return {
      load() {
        // normal effects
      }
    }
  }
}
```
