### ISSUE TITLE
Enhancers seem ignored/broken

### ISSUE THREAD

**Issue by matt-way** [rematch/rematch#232]
Trying to use rematch with `react-redux-firebase`,  but noticed that `enhancers` is not applied.

Looking at the source, it seems as though the enhancers array is completely ignored during `initStore`. Specifically these lines:

```
const enhancers = [redux.devtoolOptions, ...(redux.enhancers || [])]
const composedEnhancers = composeEnhancers(...enhancers)(middlewares)
```

The `composeEnhancers` function does nothing with the actual enhancers.

**Comment by matt-way** [comment]
It appears to be fixed, by replacing the above with:

`var composedEnhancers = devtools.composeEnhancers.apply(void 0, redux.devtoolOptions)(...redux.enhancers, middlewares);`

I'd do a pull request, but just want to make sure i'm not missing anything.

**Comment by ShMcK** [comment]
Hi @matt-way, still thinking of putting in a PR?

Thanks again for your help!
