### ISSUE TITLE
Unhandled promise rejection: Actions must be plain objects

### ISSUE THREAD

**Issue by matt-way** [rematch/rematch#234]
For some reason whenever I run any async effects, I am getting an unhandled promise rejection (yellowbox on react-native):

`Error: Actions must be plain objects. Use custom middleware for async actions.`

This is happening because redux is receiving a promise during the effect processing. I still haven't managed to track down why, but it looks like it might be a transpiling issue for async/await in the effect middleware. The effects appear to still run ok, but the warning was really annoying, and wasted a lot of time trying to resolve.

**Comment by ShMcK** [comment]
I can make some guesses as to what might cause the issue.

The error is triggered in Redux if you dispatch a function as an action, but don't have Redux Thunk middleware setup. In Rematch, you shouldn't need to do either.

Check if you have an effect/reducer that is a function returning a function.

---

If this doesn't help solve your issue...

Could you provide:
- a model example
- your init options
- rematch version

**Comment by ShMcK** [comment]
I'll close this issue as no resolution.
