### ISSUE TITLE
Dynamic importing?

### ISSUE THREAD

**Issue by wmertens** [rematch/rematch#237]
Is there a way to add rematch configuration to the store dynamically?

Something like

```js
import {updateConfig} from 'rematch'

updateConfig({reducers, ....})

...rest of module
```

That way, complex components can be loaded together with their state management code.

**Comment by wmertens** [comment]
Oh, I found https://github.com/rematch/rematch/blob/6d539bc485833c2a70e967a55dfbe155da95ce20/src/redux/store.ts#L24 but I also notice that you use a module variable to store the current reducers.

Doing that might cause problems with SSR, no? What if two renders happen at the same time, each loading different reducers?

**Comment by ShMcK** [comment]
What's you're looking at there is support for loading reducers dynamically.

See [lazy loading models](https://github.com/rematch/rematch/blob/master/docs/api.md#lazy-loading)

Example:

```js
model({ count }) // merges a new model into the config
```

I wonder though, is there a good use case for updating other config?

> Doing that might cause problems with SSR, no? What if two renders happen at the same time, each loading different reducers?

I can't give a clear answer here, as I've only used Redux for client side use. I'd love to learn more.

**Comment by jaywcjlove** [comment]
@ShMcK 
Ah, this is what I want. Thanks!

**Comment by blairbodnar** [comment]
Hi @jaywcjlove 

Just call `model()` every time you want to add a model dynamically. Here's how to do multiple:

```js
import { init, model } from '@rematch/core'

const store = init({
  models: {
    modelA: { state: 0 }
  }
})

model({ name: 'modelB', state: 0 })
model({ name: 'modelC', state: 0 })

store.getState() // { modelA: 0, modelB: 0, modelC: 0 }
```

😀

**Comment by blairbodnar** [comment]
@jaywcjlove no prob! :)

**Comment by wmertens** [comment]
@ShMck Sorry for not responding about the Redux with SSR. It is all
explained at https://redux.js.org/recipes/server-rendering, but the short
version is that each SSR render needs to set up its own store, and if you
are adding/removing reducers in a shared root reducer, it can lead to
problems:

If you remove a used reducer, it won't have the correct state. (very bad)
If you add an unused reducer, it will send more state than needed. (not so
bad)

**Comment by blairbodnar** [comment]
@wmertens Thanks! I also have only been using redux and rematch on the client side... so good catch on this.

Lately we've been talking a lot about supporting multiple stores - #239 

Do you think supporting multiple stores might be a good approach to handling SSR? Or would something like `updateConfig` as you describe above feel more natural when working with SSR?

**Comment by wmertens** [comment]
The best way I can think of, is to extend the redux context that is passed (or add a second one), via which you can declaratively add a reducer.

Something like

```js
import {connect, registerReducer} from 'rematch'
import {default as extraReducer} from './extra-duck'

@registerReducer('extra', extraReducer)
@connect(stateToProps)
class Foo extends React.Component {...}
```

and then if the `extraReducer` wasn't added yet, it gets added to the current store. If the function is no longer the same function (e.g. hot update), you can handle that too…

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/react-dynamic-loadable

lazy loading more model

```js
import React from 'react';
import { model } from '@rematch/core';
import dynamic from 'react-dynamic-loadable';

const dynamicWrapper = (models, component) => dynamic({
  models: () => models.map((m) => {
    return import(`./models/${m}.js`).then((md) => {
      model({ name: m, ...md[m] || md.default });
    });
  }),
  component,
  LoadingComponent: () => <span>loading....</span>,
});

export const getRouterData = () => {
  const conf = {
    '/': {
      component: dynamicWrapper(['user'], () => import('./layouts/BasicLayout')),
    },
    '/home': {
      component: dynamicWrapper([], () => import('./routes/Home')),
    },
    '/login': {
      component: dynamicWrapper(['user'], () => import('./routes/Login')),
    },
  };
  return conf;
};
```

**Comment by wmertens** [comment]
@jaywcjlove thanks, yes that is how it can dynamically add models, but the problem is that the reducer is shared between SSR invocations.

**Comment by Aircity** [comment]
https://redux.js.org/recipes/code-splitting#code-splitting
How to use things like [redux-dynamic-modules](https://github.com/Microsoft/redux-dynamic-modules) in rematch?

**Comment by pjamrozowicz** [comment]
> https://redux.js.org/recipes/code-splitting#code-splitting
> How to use things like [redux-dynamic-modules](https://github.com/Microsoft/redux-dynamic-modules) in rematch?

Rematch provides the ability to dynamically add models/reducers using `store.model` function (https://rematch.github.io/rematch/#/api-reference/api?id=storemodel). Is there a use case where you would like to use specifically redux-dynamic-modules?

**Comment by rayallen001** [comment]
> ```js
> model
> ```

For @rematch/core@1.4.1, the `model` method seems to be removed. Are there any other methods to lazily load models?

**Comment by rayallen001** [comment]
> What's you're looking at there is support for loading reducers dynamically.
> 
> See [lazy loading models](https://github.com/rematch/rematch/blob/master/docs/api.md#lazy-loading)
> 
> Example:
> 
> ```js
> model({ count }) // merges a new model into the config
> ```
> 
> I wonder though, is there a good use case for updating other config?
> 
> > Doing that might cause problems with SSR, no? What if two renders happen at the same time, each loading different reducers?
> 
> I can't give a clear answer here, as I've only used Redux for client side use. I'd love to learn more.

For @rematch/core@1.4.1, the `model` method seems to be removed. Are there any other methods to lazily load models?

**Comment by tianzhich** [comment]
Can you try `rematch@2.0.0-next.6`? You can use [`store.addModel()`](https://rematch.netlify.app/#/api/store?id=store) to lazily load models.

**Comment by tianzhich** [comment]
We are ready to release the rematch@v2, in the first week of Dec. We refactored the codebases and improved the typings experience with typescript. Stay tuned.
