### ISSUE TITLE
Question - Does this framework support use in react-native?

### ISSUE THREAD

**Issue by Acparvis** [rematch/rematch#241]
Awesome work on this, looks amazing. I'd love to implement it in a react-native app!

**Comment by levito** [comment]
Yes, it does, see here: https://rematch.gitbooks.io/rematch/docs/inspiration.html ("mobile ready").

It also has a nice plugin for streamlining integration with react-navigation (https://rematch.gitbooks.io/rematch/plugins/react-navigation/).

I'm currently using it in a react-native project.

**Comment by fkrauthan** [comment]
I can second that. It works amazingly in react native (I currently work on a project that is based on this library for state management)
