### ISSUE TITLE
redux like composition

### ISSUE THREAD

**Issue by F4b1n0u** [rematch/rematch#242]
Hi, sorry in advance if that's not the right place to raise my issue ! :3 

I love redux for his composition of reducers, but when you have a collection, that needs to be handle by hand

let's say you have a array of players and player is quite a complex thing as well

what I usually do is:
* a player reducer: who is in charge of ... well all what is behind the player, let's just assume it's a complex object (so need a reducer)

* a reducer player-list: who is on charge to ADD, REMOVE, UPDATE the player, where I check in my action (via payload.id or meta: playerId) which player need to be updated, and here I passe along the the player reducer

so here is my question: how to I handle that in rematch ?
it seems that for "simple" state it's fine, but it does not seems possible to do composition or even handling collection.

can you give me some hints, on how to do it ?

I'm really keen to have a look to your lib :)

**Comment by ShMcK** [comment]
I think the answer is generally "the same way you would do it in Redux".

In this case, you can consider "normalizing" your data. This is just a fancy way of saying, key each player by an id.

```js
const players = {
  state: {
    '1': {
      name: 'Some Player',
      points: 13
    }
  },
  reducers: {
    add: (state, payload) => {
      state[payload.id] = payload
      return state
    },
   remove: (state, payload) => {
      return omit([payload.id[], state) // See R.omit, lodash.omit
   },
   update: (state, payload) => {
     state[payload.id] = { ...state[payload.id], ...payload }
     return state
   }
  }
}
```

**Comment by F4b1n0u** [comment]
oh I see, thanks :)
