### ISSUE TITLE
Subscription `bind`ed this to store.dispatch.modelName

### ISSUE THREAD

**Issue by crazy4groovy** [rematch/rematch#243]
I noticed that in the tests, for eaxmple:
https://github.com/rematch/rematch/blob/master/plugins/subscriptions/test/subscriptions.test.js#L21
```js
      subscriptions: {
        'second/addOne': () => dispatch.first.addOne(),
      }
```
ie. the response to a subscription always dispatches an action from its own model. This seems like a very common usage pattern.

If `bind`ed correctly, wouldn't this be more convenient?
```js
      subscriptions: {
        'second/addOne': () => this.addOne(), // this is bound to store.dispatch.first
      }
```

Currently, I'm not really sure what `this` is bound to, but didn't seem particularly useful.

**Comment by ShMcK** [comment]
Good call.

It seems we may actually be moving away from subscriptions altogether in favor of this PR:

https://github.com/rematch/rematch/pull/236

Love to hear what you think.

**Comment by crazy4groovy** [comment]
It's pretty cool! That feature might cover most use cases, if not all of them 👍

**Comment by ShMcK** [comment]
I'll close this, with a final note:

There is no clear way to differentiate between anonymous functions and other functions at this time - especially since Babel provides no way. For this reason, `this` is difficult to determine. I've wasted a lot of time trying to find a way.
