### ISSUE TITLE
Multiple Effect Listeners

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#246]
Similar to #236 but for effects.

Multiple effects can be chained together, no issue there. but must handle several situations:

- the root effect doesn't exist
- the root effect is loaded after a listener effect is loaded
- the listener effect is loaded after a root effect

_(Consider the effect on the model to be the "root effect")_

The order of effects fired is likely important. I'd like to see a solution that ensures the root effect fires first.

**Comment by Baldrs** [comment]
Would be it logical if it'd work the same as the reducers? As effects produce actions, other models could've effects triggered by this. 

PS: I need this
