### ISSUE TITLE
Passing initial state

### ISSUE THREAD

**Issue by omaksi** [rematch/rematch#248]
I need to pass initial state from server render, and currently a workaround is needed.
`redux.initialState` will not help here, as it will get overwritten by models, but I need to apply the state after the models are loaded. So currently I define a `redux.rootReducer` which replaces the entire state and launch it after the store is created. 
I think the `init` function should include a config option that would do this automatically as passing initial state is a pretty common requirement. I can do a PR if it'd be helpful.

**Comment by ShMcK** [comment]
Great idea. This sounds similar to "REHYDRATE" in "redux-persist".

And you're right in that `initialState` will get overwritten by default state in models. This essentially makes `initialState` useless.

Do you think it would be better to simply replace "initialState" with your proposed solution?

It would be great if you're up for a PR. Happy to help if you have any questions.

**Comment by omaksi** [comment]
Took a stab at it today and wrote a plugin which should externalize the approach I described above, but it seems the `rootReducer` defined in the plugin doesn't get called when dispatched it in the `onStoreCreated` callback. Do you have any tips why it shouldn't work? Also I'd leave the decision whether to leave this as a plugin or implement into the core to you :)

```javascript
const createInitPlugin = (initialState = {}) => ({
  config: {
    redux: {
      rootReducers: {
        __INIT_STATE: (state, action) => ({ ...state, ...action.payload }),
      },
    },
  },
  init: () => ({
    onStoreCreated: (store) => {
      store.dispatch({ type: '__INIT_STATE', payload: initialState })
    },
  }),
})
const store = init({
  models,
  plugins: [createInitPlugin(initialState)],
})
```

**Comment by jackwilsdon** [comment]
@omaksi it appears that `store.dispatch` is only assigned _after_ `postStore` (i.e. `onStoreCreated`);

https://github.com/rematch/rematch/blob/da1f4e96f28d3b8ea958eecea43ac35d5301a06b/src/init.ts#L65-L71

**Comment by ShMcK** [comment]
I love when a solution fits in a code block. And good catch @jackwilsdon 

Perhaps it would be better if we call it "__SET_STATE", or "@SET_STATE", as it's no longer being init-ed. 

I lean towards "@SET_STATE" as redux already has a built in action called "@INIT".

**Comment by omaksi** [comment]
@ShMcK Can you confirm that this is the actual root cause, and making the change doesn't break anything else?

**Comment by ShMcK** [comment]
I'll have a look later tonight, there may be a more elegant solution given more time.

**Comment by hvsy** [comment]
@ShMcK 
is there any update?

**Comment by Nickersona** [comment]
I'd just like to plus-one this,  I'm attempting to integrate Rematch with Nextjs and without this capability I think I'm dead in the water.  Really like the library but need an option to rehydrate the store on client side initialization from a server generated state tree.

**Comment by ShMcK** [comment]
Sorry, I haven't had time over the past few weeks due to some non-rematch related issues.

I'll make some time tonight and try to close issues. My apologies for the delay.

**Comment by ShMcK** [comment]
I think for now, we can run with @omaksi's plugin as a functional solution.

In reference to @jackwilsdon's comment, there's actually a reference to `dispatch` within the plugin. Plugins have a space where they can share resources with each other called `expose`. 

I wish I knew more about using Next.js in order to understand how to integrate it with Rematch. If someone is more knowledgable on what needs to be done to make a Next.js integration possible beyond @omaksi's plugin patch, we can keep this thread open for discussion.

I'd like an improved initialState moved into core soon and I'm happy to assist or merge any PRs. Thanks again everyone for the suggestions and help :)

**Comment by Nickersona** [comment]
I'll try integrating with the above plugin on Next.js and report back if I find an easy way to do it. Would be nice to get an example of rematch integration with a popular framework like Next.js into the docs!

**Comment by omaksi** [comment]
@Nickersona @ShMcK If you read my comment, the plugin DOES NOT WORK (even though it should) so I don't think we can accept it as a functional solution.

**Comment by ShMcK** [comment]
Sorry about that. I'll look into a solution over the weekend.

**Comment by felipedeboni** [comment]
@omaksi I want to help, but seems that initialState is working for me, however it does a hardSet instead of a merge.

You can see it working here.
[![Demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qrvrn8oy0)

Model:
```javascript
state: {
  1516344826870: { text: 'This is going to be lost', done: false },
  1516344826871: { text: 'do stuff', done: true },
  1516344852231: { text: 'do other stuff', done: false }
}
```

Init:
```javascript
redux: {
  initialState: {
    todos: {
      1516344826871: { text: 'do stuff - initial state', done: false },
      1516344852231: { text: 'do other stuff - initial state', done: true },
      1516344852232: { text: 'added from initial state', done: false },
    }
  }
}
```

Rendered:
```
do stuff - initial state
do other stuff - initial
added from initial state
```

Anyway, can you update the codesandbox so I can see the issue you're facing?

Thanks

**Comment by ShMcK** [comment]
I think the feature request is more related to the ability to update your state by dispatching an action.

Try the following example:

[![Edit Rematch Todos Demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/14j6pvj1m3)

**Comment by alidcastano** [comment]
any update on this? I'm potentially migrating from Vue/Nuxt and would like to try out Rebass in my project

**Comment by ShMcK** [comment]
No updates yet, but it's next on the list. I'll see if I can add an implementation for v1-alpha.

**Comment by linonetwo** [comment]
Hi, I'm using 
```js
// each model
export const defaultState = {
  ...
};
export default (initialState?: Object = {}) => ({
  state: {
    ...defaultState,
    ...initialState,
  },
  reducers: {
  }
}
```
and 
```js
const configureStore = ({ search, info, block, history, transaction, account, message, aggregation, price } = {}) =>
  init({
    models: {
      search: searchModel(search),
      info: infoModel(info),
      block: blockModel(block),
      transaction: transactionModel(transaction),
      account: accountModel(account),
      message: messageModel(message),
      aggregation: aggregationModel(aggregation),
      history: historyModel(history),
      price: priceModel(price),
    },
    plugins: [immer],
  });
```
Lots of boilerplate, hoping there can be a plugin to abstract it.

**Comment by jackwilsdon** [comment]
@linonetwo that can probably be simplified;

```
const configureStore = initialState => {
  const models = {
    search: searchModel,
    info: infoModel,
    ...
  };

  Object.keys(models).forEach(key => {
    models[key] = models[key](initialState);
  });

  return init({ models, ... });
}
```

But I agree it would be nice to have a shorter way of doing it.
