### ISSUE TITLE
Selectors and React example implemented... And I accidentally pushed my branch to master :(

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#25]
@ShMcK I accidentally pushed my branch to master 😞. Sorry about that. I had created a branch and had accidentally set the upstream to origin/master on it. I didn't realize my push would be to master. Ugh! I was all ready for a nice PR!

If you want to review the commits for this "PR", it's the first 6 commits I did today, Oct 14.

Anyways, here is what I was going to say in the PR:

* Selectors are not tied to views anymore
* Now that `getStore` is exposed, I don't think we need to provide a `'view'` in `init` anymore. (See example below). Maybe complex view implementations can be done via plugins or something similar... But maybe it's not even needed! For example, look at the react-redux implementation below!

### From  [examples/react-redux-count/](https://github.com/rematch/rematch/tree/master/examples/react-redux-count)
```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import { connect, Provider } from 'react-redux'
import { init, model, dispatch, select, getStore } from 'rematch-x'

// No need to specify a 'view' in init.
init()

// Create the model
model({
  name: 'count',
  state: 0,
  reducers: {
    increment: state => state + 1
  },
  selectors: {
    doubled: state => state * 2
  }
})

// Make a presentational component.
// It knows nothing about redux or rematch.
const App = ({ value, valueDoubled, handleClick }) => (
  <div>
    <div>The count is {value}</div>
    <div>The count doubled is {valueDoubled}</div>
    <button onClick={handleClick}>Increment</button>
  </div>
)

// Use react-redux's connect
const AppContainer = connect(state => ({
  value: state.count,
  valueDoubled : select.count.doubled(state),
  handleClick: () => dispatch.count.increment()
}))(App)

// Use react-redux's <Provider /> and pass it the store.
ReactDOM.render(
  <Provider store={getStore()}>
    <AppContainer />
  </Provider>,
  document.getElementById('root')
)

```

**Comment by blairbodnar** [comment]
Updated my comment to be more coherent.

**Comment by ShMcK** [comment]
You're right! Excellent work. Specifying the view isn't even necessary.

Something like "react-router" integration can be accomplished by passing plugins in. But there really never was a clear need for "view". We should be more careful in the future before introducing new possibly unnecessary APIs.

**Comment by blairbodnar** [comment]
Thanks man! 

Yeah, I totally agree. We gotta keep this a nice small API. 😎
