### ISSUE TITLE
Issues with TypeScript Typings

### ISSUE THREAD

**Issue by nWidart** [rematch/rematch#250]
Hello,

This is probably a stupid question, but I'm trying to call a reducer method from my effect method.

I tried both ways I could find in the examples, 

```js
export default {
  state: {
    isFetching: false,
    data: [],
  },
  reducers: {
    receivedPrograms() {

    }
  },
  effects: {
    async fetchPrograms() {
      const { data } = await axios.get('my/endpoint');
      this.receivedPrograms()
    }
  }
}
```

[the first one uses `this.reducerName()`](https://github.com/rematch/rematch/blob/master/plugins/loading/examples/react-loading-example/src/example.js#L16)
this says:

```
error TS2339: Property 'receivedPrograms' does not exist on type '{ fetchPrograms(): Promise<void>; }'.
```

I also tried another example, which uses [dispatch](https://github.com/rematch/rematch/blob/master/examples/react/count/src/models.js#L13).

```
// in my effect function
dispatch.Program.receivedPrograms();
```

Which says:
```
error TS2339: Property 'Program' does not exist on type '(action: Action) => Promise<Dispatch<any>>'.
```

I'm sure I missed something, somewhere 😄

**Comment by nWidart** [comment]
I can't log it either, which is causing the same error on building the app. 

Indeed I didn't show the model name, in the store init:

```js
export const store = init({
  redux: {
    reducers: {
      // my old redux reducers
    },
    middlewares: [thunk]
  },
  models: {
    Program,
  },
});
```

Even if I export it named `export const Program : Model = {`, and import it accordingly on my store init location it does the same thing.

Thanks.

**Comment by ShMcK** [comment]
In this case you have a "default export" but you're loading it with a "named export".

Try `import Program from '..'`

**Comment by nWidart** [comment]
Sorry I edited my comment. I have it named because I tried exporting it by name.

Of course, when I was still exporting by default, the import was not using the destructuring syntax.

**Comment by ShMcK** [comment]
out of curiosity, what happens if your model "Program" is lower cased?

**Comment by ShMcK** [comment]
A better guess: is Program still included within your reducers?

**Comment by blairbodnar** [comment]
Another thing to check - could the thunk middleware be messing with it? Try it without the thunk middleware?

**Comment by nWidart** [comment]
With program lowercase it's the same thing too.
![image](https://user-images.githubusercontent.com/882397/37041947-ad14ba7a-215d-11e8-9781-798f2aa23617.png)

My old program reducer is plural so it shouldn't cause conflicts there.
![image](https://user-images.githubusercontent.com/882397/37041989-c32e4254-215d-11e8-81c5-ca46e9bd07c9.png)

**Comment by nWidart** [comment]
I'm not sure thunk could be interfering, this is an error at compile time. It's like typescript doesn't know there's a program key it can access. 🤔

**Comment by ShMcK** [comment]
Oh, okay. This looks like a typescript typings issue.

**Comment by nWidart** [comment]
Indeed. I'm not sure how I can "trick" typescript to let it know there is a `program` key it can use.

**Comment by ShMcK** [comment]
Dispatch is a bit tricky. It's both a function, and an object with unknown keys.

We should have a link to a TypeScript example in the README, both for testing and education.

**Comment by nWidart** [comment]
Oh I see, it tries to find the `program` key here it looks like https://github.com/rematch/rematch/blob/master/typings/rematch/index.d.ts#L9

**Comment by ShMcK** [comment]
I'll update the typings, but having an issue.

```js
export type RematchDispatch = {
  [key: string]: {
    [key:string]: (action: Action) => Promise<Dispatch<any>>
  }
} | (action: Action): Promise<Dispatch<any>>
```

Unfortunately, I'm not proficient enough with TypeScript to make the compiler happy with all of that.

**Comment by ShMcK** [comment]
Perhaps turning off `strict` mode in your compiler may be helpful for now.

I will definitely put in an effort to restructure the typescript typings later today, though after work. 

Sorry again for the headache. It seems TypeScript is not a use case we can support until that work is done.

**Comment by Meroje** [comment]
I'm not familiar with rematch, but do you mean this ?
```
export type RematchDispatch = {
  [key: string]: {
    [key:string]: (action: Action) => Promise<Dispatch<any>>
  }
} | ((action: Action) => Promise<Dispatch<any>>)
```

**Comment by ShMcK** [comment]
One more quick, possibly dumb issue then:

```ts
export type RematchDispatch = {
  [key: string]: {
    [key:string]: (action: Action) => Promise<Dispatch<any>>
  }
} | ((action: Action) => Promise<Dispatch<any>>)

export function dispatch(action: Action): Promise<Dispatch<any>>
export function init(config: Config | undefined): Store<any>

export namespace rematch {
  export function dispatch(action: Action): Promise<Dispatch<any>>
  export function init(config: Config | undefined): Store<any>
}
```

How do you replace the `export function dispatch` with `RematchDispatch`?

**Comment by Meroje** [comment]
I think this would be `export let dispatch: RematchDispatch;`

**Comment by ShMcK** [comment]
I've pushed a release "0.5.2" with improved TypeScript typings for dispatch.

Thanks everyone :)

Note: there may still be TS issues that need to be resolved.

**Comment by nWidart** [comment]
Thanks, I just updated, but error is still there 😞 

```
Property 'program' does not exist on type '{ [key: string]: { [key: string]: (action: Action) => Promise<Dispatch<any>>; }; }'
```

**Comment by Meroje** [comment]
I just had a look a the repo (I was here because of @nWidart) and I didn't realize its written with typesript ;). I'm in no way a typescript contributor or daily user but it is the first time I see a typescript project to not auto-generate its typings, maybe you would benefit from moving them into the source files ?

**Comment by ShMcK** [comment]
It seems we might need a TS ninja.

Changed the title. Will also tag this as "help wanted".

**Comment by ShMcK** [comment]
Help is on the way: I'll close this issue in favor of a current PR underway and discussed at https://github.com/rematch/rematch/issues/244.

**Comment by ccheney** [comment]
I believe this would resolve the typing issue from OP:

```ts
interface DispatchAction {
  [key: string]: (action: Action) => Promise<Dispatch<any>>;
}

export type RematchDispatch = {
  [key: string]: any | DispatchAction;
}
```
