### ISSUE TITLE
How to configure to work with redux-persist

### ISSUE THREAD

**Issue by kenma9123** [rematch/rematch#252]
Persisting data is what I always do when creating an application. Rematch has a potential. I would love to try this out however I can't seem to find a way to make [redux-persist](https://github.com/rt2zz/redux-persist) work. Is there any examples you guys can provide?

Thanks in advance, keep up the good work! :+1:

**Comment by ShMcK** [comment]
Try the persist plugin: https://github.com/rematch/rematch/tree/master/plugins/persist.

**Comment by adrianha** [comment]
hi @ShMcK , Is it possible to handle nested persist using persistPlugin?

**Comment by ShMcK** [comment]
What do you mean by "nested persist"?

**Comment by adrianha** [comment]
I mean this one: https://github.com/rt2zz/redux-persist#nested-persists
Let say, i have user model with some attributes: data, token.
And what i need just to persist user token and ignore data to be persisted

**Comment by ShMcK** [comment]
Interesting. I don't believe this can be supported with models at this time.

Alternatively, you can just use reducers:

```js
import { init } from '@rematch/core'
import { combineReducers } from 'redux'
import { persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

import { authReducer, otherReducer } from './reducers'

const rootPersistConfig = {
  key: 'root',
  storage: storage,
  blacklist: ['auth']
}

const authPersistConfig = {
  key: 'auth',
  storage: storage,
  blacklist: ['somethingTemporary']
}

const store = init({
  reducers: {
      auth: persistReducer(authPersistConfig, authReducer),
      other: otherReducer,
  }
})
```

This a good use case for nested reducers, and I think it should be available in models. Any thoughts on how it might look?

**Comment by adrianha** [comment]
Hi @ShMcK ,
Yeah i think we can specify the config within the model. Maybe like this?
```
const user = {
  state = {
    data: null,
    token: '',
    isLoading: false
  },
  reducers: {},
  persist: {
    whitelist: ['token']
  }
}
```
What do you think?

**Comment by ShMcK** [comment]
I think this will be hard to persist on a more specific than "model" or "reducer" level for now. Not to say that it is a bad idea, but there may be simpler solutions.

There is a pattern that may make this simpler for you. Checkout the "loading" plugin, as an example.
Rather than having "isLoading" in all of your models, you can have a "loading" model. 

Then you can simply persist `user`.

**Comment by andremw** [comment]
@ShMcK any chance we have this configurable on the models?

I'm about to switch back to pure redux because I couldn't figure out how to do it with rematch. :(

**Comment by ShMcK** [comment]
There currently isn't any support for nested reducers other than using:

```js
init({
  reducers: {
    myReducer: someNestedFunc(reducer),
  }
})
```

Personally, I use the persist plugin with models, some of which are white listed. I haven't had the need for white/black listing specific keys. Its always possible to restructure your models where it makes sense.

I don't have any plans for adding reducer functions at this time, though I'm happy to help out with any PRs. If anyone were to explore a PR, I would recommend not making it just "persist" specific, but rather adding a "nestedReducer" key to the model, which calls the reducer with that nestedReducer function. It would cover more use cases.

Of course, pure Redux is a good option as well.
