### ISSUE TITLE
Redux example is overcomplicating things

### ISSUE THREAD

**Issue by markogresak** [rematch/rematch#253]
From the [Purpose](https://github.com/rematch/rematch/blob/master/docs/purpose.md) doc:

``` js
const mapDispatchToProps = (dispatch) => ({
  countUpBy(payload) {
    dispatch(countUpBy(payload))
  },
})

connect(mapStateToProps, mapDispatchToProps)(Component)
```

Doesn't really need to be this verbose, this works the same:

``` js
connect(mapStateToProps, {countUpBy})(Component)
```

> Note: using [object shorthand notation from ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015), ES5 compliant syntax is `{countUpBy: countUpBy}`.

The point that there is a lot of boilerplate in redux still stands, but it's a bit shorter this way. And it shows that one doesn't necessarily need `mapDispatchToProps` function with redux, while it is needed with rematch.

**Comment by ShMcK** [comment]
Good call. I recently started destructuring my dispatches as well. Quite elegant.

@markogresak By any chance, would you like to put in a quick PR to the purpose docs, and anywhere else you think might benefit? Doc PRs can be managed with the "edit" button within Github.
