### ISSUE TITLE
Add a FAQ or Tutorial

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#259]
There are a lot of common questions that appear under the issues. It would be nice to have a place to answer these.

1. How do you listen to actions from other models?
- see (https://rematch.gitbooks.io/rematch/docs/api.html#reducers)
2. Can I use TypeScript?
- not yet, coming soon
3. Redux persist?
- see persist plugin

Etc.

**Comment by raythree** [comment]
For the most part, actions are specific to a given reducers, but there are certain actions/events that may be of interest globally in an app, and "ducks" recommends naming like: 

```const LOAD   = 'my-app/widgets/LOAD';```

or some similar scoped naming. Can this be accomplished with rematch?

**Comment by ShMcK** [comment]
There's a pattern for listening to actions:

```js
reducers: {
  'someOtherModel/someAction'(state, payload) {
      // triggered when that models action is fired
      return state
  }
}
```
