### ISSUE TITLE
jest bug? This `effects` test actually passes... just not in jest

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#26]
I've been trying to fix this one failing effects test:

```js
  test('should be able to trigger another action w/ multiple actions', async () => {
    init()

    model({
      name: 'example',
      state: 0,
      reducers: {
        addBy: (state, payload) => state + payload,
      },
      effects: {
        asyncAddOne: async () => {
          await dispatch.example.addBy(1)
        },
        asyncAddThree: async () => {
          await dispatch.example.addBy(3)
        },
        asyncAddSome: async () => {
          await dispatch.example.asyncAddThree()
          await dispatch.example.asyncAddOne()
          await dispatch.example.asyncAddOne()
        }
      }
    })

    await dispatch.example.asyncAddSome()

    expect(getStore().getState()).toEqual({
      example: 5,
    })
  })
```

It's really odd - The code in the test actually works fine! I tested it out in 'production' and got the results I'd expect when calling `dispatch.example.asyncAddSome()`. (I tested with a create-react-app).

Anyways, I spent some time debugging it and for some reason jest only executes the first two lines of any effect. It's really odd! I'm taking a break from it now... this is a tricky bug!

I'll remove the test from the master branch for now because all other tests are passing. We can add this test back in once we figure out what is going on here.

**Comment by ShMcK** [comment]
Yeah, I realized that as well. It seems for the last two tests that `getState()` receives the previous state. Async Issue.
