### ISSUE TITLE
Stunning

### ISSUE THREAD

**Issue by sospedra** [rematch/rematch#261]
I'm sorry if I'm adding noise to this repo but I just wanted to stop by and say: congratz!
Not so often one find this quality of code and high level of abstraction. This is brilliant.
Alongside with the [hackernoon post](https://hackernoon.com/redesigning-redux-b2baee8b8a38) this library is enlightening 👏

So much appreciated, kudos for all the team ❤️

**Comment by blairbodnar** [comment]
Thanks @sospedra! 😊

**Comment by ShMcK** [comment]
Thanks @sospedra. 

And big thanks to other libs that provided inspiration: dva, mirror, jumpstate, vuex, etc. We are the combiners and modifiers of many existing ideas.

**Comment by ShMcK** [comment]
Safe to say this issue is 100% resolved :)
