### ISSUE TITLE
Composability

### ISSUE THREAD

**Issue by pelotom** [rematch/rematch#263]
Having glanced through the examples I’ve been able to find, I can’t tell if it’s possible to compose models, each of which has their own state, reducers, and async effects. It would be really useful for allowing a module to provide all of these things for a given part of the app in isolation, and then other parts of the application could use it as a sub part. It’s always struck me as a major defect of redux that it’s not possible to achieve this kind of full encapsulation and composition.

**Comment by ShMcK** [comment]
I've seen a few ways of composing models.

### Object Spread
As models are simple objects, its possible to "merge" them together.

```js
const defaultState

const commonReducers = {
  merge(state, payload) => { ...payload, ...state },
  reset() => defaultState,
}

const count = {
  state: defaultState,
  reducers {
    ...commonReducers,
  }
}
```

### Model Wrappers
A function wrapping a model.

```js
const addDefaults = (model)  => { /* some transformation */}

const count = addDefaults({
  reducers: {
    increment: (state) => state + 1
  }
})
```

**Comment by ShMcK** [comment]
I'll close this issue for now, as possibly answered.
