### ISSUE TITLE
Nested models?

### ISSUE THREAD

**Issue by radmen** [rematch/rematch#265]
Hey - for a starter, I'd like to say that I do like `rematch`, awesome work! ;)
Now, the question part - is it possible to nest models? 

In redux one can use `combineReducers` even in "deeper" structure:

```js
const rootReducer = combineReducers({
    nested: combineReducers({
        nestedA,
        nestedB
    })
})
```

Is it possible to achieve something similar in `rematch`?

**Comment by ShMcK** [comment]
Great question, we've had some discussion on this topic: https://github.com/rematch/rematch/issues/230.

**Comment by radmen** [comment]
Thank you. I think this answers my question :)
