### ISSUE TITLE
Effect function with multiple arguments

### ISSUE THREAD

**Issue by slbucur** [rematch/rematch#267]
Hello,

I noticed this odd behaviour when having an effect with multiple arguments.
Example
```js
// alerts model
effects: {
        fetchAlerts: async (filterType, filterId) => {
            console.log(filterType, filterId);
            dispatch.alerts.alertsLoading(true);
            try {
                const result = await(axios.get(`/rims/alerts_json/${filterType}/${filterId}/`));
                dispatch.alerts.alertsSuccess(result.data);
            }
            catch (e) {
                dispatch.alerts.alertsError(true, e.message);
            }
        },
}

//mapping in mapDispatch
```js
dispatch => ({
    fetchAlerts: (filterType, filterId) => {
      console.log(filterType, filterId); dispatch.alerts.fetchAlerts(filterType, filterId)
   },
)
```

When I call the function with `this.props.fetchAlerts(filterType, filterId)`, `filterId` is actually the state object.
```
filterId={
    alerts: {
        loading: true,
        error: false,
       /
    }
}
```
I have to change the function in effects to add an unused `state` second parameter, like so:
```js
fetchAlerts: async (filterType, state, filterId)
```

Is this expected behaviour? If it is, I found it a bit confusing, maybe the state param should be the first parameter, like in the reducers object with sync functions.

**Comment by slbucur** [comment]
I encountered another problem.
I have another function, in `effects` I tried the state trick mentioned above, like so:
```js
changeResolution(alertIds, state, resolutionId, filterType, filterId)
```
But only the third parameter: `resolutionId` is defined.
The fourth and fifth params: `filterType` and `filterId` are undefined.

I suppose I can do something like this:
```js
changeResolution({alertIds, resolutionId, filterType, filterId}, state)
```
And map it properly in mapDispatch, but I'm not sure if this is the desired behaviour.

**Comment by ShMcK** [comment]
I think this one is due to some confusion over the shape of the API. See the [API docs](https://github.com/rematch/rematch/blob/master/docs/api.md)

A brief summary:
- dispatch[model][action](payload, meta) === dispatch({ type: `${model}/${action}`, payload, meta })
- reducer(localState, payload)
- effect(payload, rootState

Using your example, you're probably not getting what you expected:

```js
dispatch.alerts.fetchAlerts(filterType, filterId)
// transformed into
dispatch({ type: 'alerts/fetchAlerts', payload: filterType, meta: filterId })
```

This can be rewritten simply as an object:

```js
dispatch.alerts.fetchAlerts({ filterType, filterId })
```

Then captured within an effect:

```js
effects: {
  fetchAlerts: ({ filterType, filterId }) => { ... }
}
```

**Comment by slbucur** [comment]
Thank you for the clarification :smile:. That's how I did used it in the end, and now I know why it works that way.
