### ISSUE TITLE
Writing Tests: add docs & examples

### ISSUE THREAD

**Issue by BrentonCozby** [rematch/rematch#269]
Documentation with examples of how to test components that use Rematch would be a helpful addition.

Unit tests for the reducers and effects would be a main priority, I imagine.

For example, here is how Redux includes testing in their docs: https://redux.js.org/recipes/writing-tests

**Comment by nWidart** [comment]
Hello,

You might find some info here: https://github.com/rematch/rematch/issues/229

**Comment by ShMcK** [comment]
Perhaps we should add a section to the docs under "recipes" called "testing".

Besides the notes in #229, is there anything else it should cover?

**Comment by nWidart** [comment]
That might be a good idea indeed. This will probably be a recurring question.

I'd say show tests of a real model, something that uses async even maybe to make it all explicit.
Maybe the typical todo app example, where it's tested to add, remove, fetch all todos.

**Comment by ShMcK** [comment]
I think "todo" would make a great tutorial. It's classic.

We could aim for a "quick short term patch" docs solution, and a "long term training" solution.

**Comment by felipedeboni** [comment]
Hey guys,

I can help with it. Can you guys review this and check with we are good to go? [![Edit Rematch Todo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yvpy2zr8mj) 

I will update docs after we agreed on the sandbox code.

Just a side note, for some reason ```jest.resetModules``` is undefined on codesanbox.io, that's why I have used that ugly array reverse 😧

**Comment by ShMcK** [comment]
Some issues with CodeSandbox code so far. Looks like import paths, empty files. 

As a skeleton, I like the structure as an example of different kinds of testing.

**Comment by felipedeboni** [comment]
@ShMcK yep, something went wrong! I have fixed the import paths since the .env file was gone and added the content back again to files that are missing it.

**Comment by ShMcK** [comment]
Thanks @felipedeboni for #304 👍
