### ISSUE TITLE
Immer + Rematch

### ISSUE THREAD

**Issue by bjrmatos** [rematch/rematch#271]
Hi, i've been really curious about rematch (it has been on my bookmark for some time), it really reduces a lot of boilerplate comparing to normal redux usage but i feel like there still a lot of boilerplate in order to ensure a new state is returned from reducers.

do you think it is a good idea to add to docs that in order to reduce even more boilerplate the usage of [immer](https://github.com/mweststrate/immer) can help with that? immer is really great about ensuring a new immutable state is returned with the familiar api of mutable modifications

**Comment by ShMcK** [comment]
The goal of Rematch is two parts:
- reduce boilerplate, simplify the codebase
- reduce the learning curve for those new Redux

Immer looks like it would help with the first part, but perhaps not the second. It could be included with more intermediate examples, as well as within "recipes". Perhaps even recommended.

I'd love to see a codesandbox demo, or example on Github demonstrating immer with rematch.

**Comment by bjrmatos** [comment]
the most complex example that i found with rematch was the Todo example so i changed it to use immer instead of handling inmutability by hand. here is the updated example: https://codesandbox.io/s/o91mq5wnxz


> reduce the learning curve for those new Redux

ok, i think that immer really help with the two goals

for example here is the original `toogleDone` reducer

```js
toggleDone(state, id) {
  const todo = { ...state[id], done: !state[id].done }
  return {
    ...state,
    [id]: todo
  }
}
```

and here is the `toogleDone` reducer with immer:

```js
toggleDone: (state, id) => produce(state, draft => {
  draft[id].done = !draft[id].done
})
```

if you exclude for a second the fact that the `toggleDone` reduce with immer returns the result of `produce` (because you can argue that it can look confusing for someone new) and just focus in the updating logic then it is clear that the immer version looks very easy to follow, after all it is normal mutable code, something that a new user can follow quickly without caring about inmutability and without worrying about returning a new copy of each object when changed.

now, lets imagine that somehow (maybe with a rematch official plugin?) this:

```js
toggleDone: (state, id) => produce(state, draft => {
  draft[id].done = !draft[id].done
})
```

can be handled like this:

```
toggleDone: (draft, id) => {
  // of course internally the plugin will automatically call `produce` and return its result as the new state
  draft[id].done = !draft[id].done
}
```

then it clearly helps a lot with the goals of rematch.

**Comment by mgutz** [comment]
I don't think it's needed. I define a `producer` like this

```js
const producer = (fn) => (state, payload) => {
  return produce(state, (draft) => {
    fn(draft, payload)
  })
}

const model = {
  reducers: {
    foo: producer((draft, payload) => {
       // .. mutate draft
    }
  }
}
```

See it in use [here](https://github.com/mgutz/task/blob/workspaces/workspaces/task-ui/src/store/history.js)

**Comment by bjrmatos** [comment]
@mgutz i agree with you that it is easy, but the whole point of this issue is to just get a recommendation in docs or maybe a 100% easy way for everyone (even for people new to redux) to use immer transparently, your producer can be a plugin of rematch and it will be even more easy for everyone new.

**Comment by ShMcK** [comment]
@blairbodnar and I plan on making a tutorial that covers some recommended best practices in building a semi-complex "Rematch" app. We will certainly try out "immer" and see how it goes.

**Comment by dzz0615** [comment]
I'm using it right now with immer, end result is awesome, no issues so far. I come from MobX so I'm more used to directly modifying the state instead of creating new state or using Immutable.js, this allowed me to get off the ground without retraining myself.

For people who are coming to Rematch from Redux, it'll be a bigger change in mindset though IMO.

Here's a simple example from my project:

```javascript
import produce from 'immer';

export default {

  // state is the array of cell IDs for this page
  state: [ '1' ],

  reducers: {

    reorder: produce((state, { fromIndex, toIndex }) => {
      const [ id ] = state.splice(fromIndex, 1);
      if (id) {
        state.splice(toIndex, 0, id);
      }
    }),

    'cells/create': produce((state, { id, atIndex }) => {
      if (atIndex > state.length) {
        throw new Error('Cell index too high');
      }

      state.splice(atIndex, 0, id);
    }),

    'cells/delete': produce((state, { atIndex }) => {
      state.splice(atIndex, 1);
    }),

  },

};
```

**Comment by jeffreyyoung** [comment]
would it be possible to just create a plugin to get rid of the `produce` boiler plate?  It looks like rematch already supports creating a plugin to override the `combineReducers` fn.  I think we could make a plugin swaps `combineReducers` with something like `combineReducersWithImmer` similar to the persist plugin

**Comment by ShMcK** [comment]
Definitely possible. This can be done with just `init` config, or if it becomes more complicated, a `plugin` config.

**Comment by jeffreyyoung** [comment]
```javascript
import produce from 'immer';
import {combineReducers} from 'redux';

function combineReducersWithImmer(reducers) {
	const reducersWithImmer = {};
	
	Object.entries(reducers).forEach(([key,reducer]) => {
		const reducerWithImmer = {};
		Object.entries(reducer).forEach(([reducerFnKey, reducerFn]) => {
			reducerWithImmer[reducerFnKey] = (state, payload, meta) => {
				return produce(state, draft => {
					reducerFn(state, payload, meta);
				});
			}
			reducersWithImmer[key] = reducerWithImmer;
		});
	});
	
	return combineReducers(reducersWithImmer);
}
```

**Comment by arcthur** [comment]
https://github.com/arcthur/rematch-immer
I wrote a plugin, but @rematch is a private repo, I published to rematch-immer v0.0.1.

**Comment by jackwilsdon** [comment]
@rematch isn't a repo, just an `npm` user. The packages there are published from the `packages` directory in this repository.

**Comment by ShMcK** [comment]
@arcthur, if you'd like you could add an @rematch/immer to the repo as a PR.

Otherwise, feel free to add a link to your plugin in SUMMARY.md & README.md.

**Comment by arcthur** [comment]
@ShMck thanks, I'll add summary, readme, example, and pr to rematch

**Comment by mgutz** [comment]
So I've been writing a non-trivial app, which I will be open sourcing soon, with immer and rematch. It's a great combination however performance became an issue with immer when I was dealing with large log files. My solution above allowed me to opt into immer as a higher order function instead of using it for the entire store as suggested here. For most things, immer is fast enough so it may not be a concern but realize immer is at least 3x slower for the convenience it provides. With that aid, I use immer for at least 80% of my reducer code.

**Comment by ShMcK** [comment]
We now have a package available at @rematch/immer for those that want all reducers to be wrapped with Immer `produce`.

@dzz0615 - I think I'll add your example to a "recipes.md", to help anyone getting started using immer with Rematch.

For now I'll close this issue, as it seems to be covered with a variety of solutions.
