### ISSUE TITLE
Bundle size 4.4KB minified/gzipped

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#272]
According to BundlePhobia, `@rematch/core` can be reduced to 15kb minified or 4.4kb gzipped.

https://bundlephobia.com/result?p=@rematch/core@0.5.2

The current size is around 18kb minified. There may be room to shrink the rollup package further.

**Comment by hiroppy** [comment]
How about introducing [bundlesize](https://github.com/siddharthkp/bundlesize)?
