### ISSUE TITLE
Let’s talk about that logo

### ISSUE THREAD

**Issue by will-stone** [rematch/rematch#274]
Just read the article on Hackernoon about updating Redux: good read. I’m definitely going to give this project a go, thank-you for taking the time to simplify Redux for us mere mortals.

Now, I’m no creative genius but the current logo looks a bit, well, _rushed_? I do like to make a logo for a project, in fact, sometimes I can’t even start a project until it has a half-decent logo. Do you mind if we use this thread for user submissions for a new logo? I’ll have a play tomorrow and see what I can come up with.

**Comment by ShMcK** [comment]
Thanks for noticing. It was a tad rushed. It's quite literally a font. Definitely looking forward to submissions.

**Comment by blairbodnar** [comment]
Sounds great, give it a shot @will-stone ! Thanks 😃

**Comment by will-stone** [comment]
Ok, here's my first attempt. I'm going for rematch of a a fight/boxing match. The png, svg, Affinity Designer files are attached too, in case anyone would like to refine it. The font used is the open source Hack typeface.

![rematch-logo](https://user-images.githubusercontent.com/654103/37251556-344f02de-250a-11e8-9d74-c6231b4aa1f1.png)

[Archive.zip](https://github.com/rematch/rematch/files/1800163/Archive.zip)

**Comment by ShMcK** [comment]
Impressive! Only minor recommendation is the spacing around the "m" character.

If you're interested in trying a different theme, our original intent was around playing 2p video games.

**Comment by will-stone** [comment]
Yeah I noticed the kerning issue, maybe best to use a serif or sans-serif font. Gaming, ok, I’ll give it a go later

**Comment by will-stone** [comment]
Here's another go with the gaming theme. The font is called "Press Start 2P" which is free for personal and commercial use. Again, I've included the files used to make it.

![rematch-logo2](https://user-images.githubusercontent.com/654103/37258134-e4736e7e-256a-11e8-9077-b109835fe437.png)

[Archive 2.zip](https://github.com/rematch/rematch/files/1800846/Archive.2.zip)

**Comment by will-stone** [comment]
Another with slightly thicker cable and gamepad outline. I think the chunkier look goes better with the retro feel.

![rematch-logo2](https://user-images.githubusercontent.com/654103/37259080-cca04fce-2579-11e8-8e43-c8f0c54b6759.png)

[Archive.zip](https://github.com/rematch/rematch/files/1800947/Archive.zip)

**Comment by will-stone** [comment]
And here's a NES version:

![rematch-logo3](https://user-images.githubusercontent.com/654103/37270154-93dd3138-25c5-11e8-85f3-128ffa41b71a.png)

[Archive 2.zip](https://github.com/rematch/rematch/files/1801703/Archive.2.zip)

**Comment by kumarharsh** [comment]
Random stranger here:
Just found this repo from my github feed. The library looks promising, and the logo ghastly ;-) So I came here to open up an issue, and saw yours.

The first one (boxing match) type is best among these - the kerning/width of 'm' is a sore thumb on an otherwise good logo. Maybe you can use a block-face sans-serif proportional-width font instead of monospace one.

Some inspirations (if you go with the fighting theme):
1. https://www.google.co.in/search?q=boxing+match+poster
2. https://www.google.co.in/search?q=mma+poster

**Comment by kumarharsh** [comment]
The NES one has too much noise the horizontal bars in the middle will become nearly melded into a black column on lower resolutions. I appreciate the idea behind linking it with gaming though.

**Comment by ShMcK** [comment]
First off, I just want to say:

Logo design is an iterative process. 
There is no right answer. 
People rarely appreciate good design until they've seen it a dozen times.

I think in order to decide on a logo we first have to define what a good logo should have:
- [ ] represent what it is (eg. wraps Redux)
- [ ] should work as a banner (468 x 60)
- [ ] should work as a smaller icon (48 x 48)
- [ ] be simple, minimalistic
- [ ] be f'n cool

Those are the criteria I go by, but I could be persuaded to include/exclude more. I'm obviously not a designer.

So far I think all of @will-stone's logo examples are great, and certainly all justifiably better than the current logo. 

So far, if I had to pick a favorite I would go with the nostalgic **"Nintendo Controller".** My only concern is point 3, how these icons would look in smaller square like format. 

I hope we can leave this issue open for submissions/alterations until Wednesday at the latest. @blairbodnar and I will be giving a presentation at the Vancouver React Meetup and we would love to unveil our new logo then :)

**Comment by will-stone** [comment]
Thanks @ShMcK Here's the NES one with the additional smaller variation.

![rematch-logo3](https://user-images.githubusercontent.com/654103/37327201-2d6efada-268d-11e8-9f4e-e9987f9c23be.png)

[Archive.zip](https://github.com/rematch/rematch/files/1805833/Archive.zip)

**Comment by will-stone** [comment]
Unfortunately, I think the Redux logo (within the controller) is going to be crap when the logo is scaled down to 48x48. Any ideas?
I was thinking we could just use the normal two dots. It'll mean it won't satisfy the "wraps Redux" requirement, but is that such a bad thing? As long as the logo is memorable enough, people will soon associate it with "that library that makes Redux easier". And this will scale down to 48x48 well.

![rematch-logo3-alt](https://user-images.githubusercontent.com/654103/37329568-3cdebd4e-2696-11e8-887f-55381059837a.png)

![rematch-logo3-alt-48](https://user-images.githubusercontent.com/654103/37329778-eab3478c-2696-11e8-9cec-8c79bae84723.png)

**Comment by ShMcK** [comment]
Made this by accident while doing slides for an upcoming presentation, and thought it looked kind of interesting. Rough version.

![rematchlogo1](https://user-images.githubusercontent.com/4660659/37562734-c692f9a8-2a2c-11e8-96c2-04b9661d5822.png)

**Comment by will-stone** [comment]
I think having the arrow go diagonally so the right-hand side looks more like an R would work.

![index](https://user-images.githubusercontent.com/654103/37567597-2f353450-2ac1-11e8-8dfa-7c59cda1afca.png)

**Comment by ShMcK** [comment]
It's Redux, subtly changed, heading off in another direction.

**Comment by will-stone** [comment]
I can't seem to figure out a way to bend the circle around without it putting the whole logo off-balance. I've made the arrow line slightly thinner. How about an extra colour?

![rematch-logo4](https://user-images.githubusercontent.com/654103/37800980-b6dd853e-2e1c-11e8-8514-d3a47a71890f.png)

**Comment by jackwilsdon** [comment]
Maybe make two of the sections green, completing the 'R'?

![logo](https://user-images.githubusercontent.com/1843197/37803986-ec82d538-2e29-11e8-92e0-b1b2027373e6.png)

**Comment by blairbodnar** [comment]
Nice @will-stone ! Digging these latest ones!

**Comment by will-stone** [comment]
![rematch-logo4](https://user-images.githubusercontent.com/654103/37816579-8222dda4-2e6b-11e8-819f-dfc7a53a62fd.png)

**Comment by will-stone** [comment]
Got a few hearts there. Are we happy with this? I can upload the svg or put in a pull request...? How did the presentation go?

**Comment by ShMcK** [comment]
@will-stone great work. Could you upload the SVG with different sizes maybe to a new folder called 'logo'? We'd like to play with the colors for a bit in Sketch, but I think we're almost there. 

Here's [a link to our presentation](https://www.youtube.com/watch?v=3ezSBYoL5do) if you'd like to have a look.

**Comment by HackedBeat** [comment]
There is a bit more visually balanced version of @will-stone's [last logo](https://github.com/rematch/rematch/issues/274#issuecomment-375566731). Also I have eliminated a skew of the logo and arrow to prevent the pain of perfectionists :D
![balanced_logo](https://user-images.githubusercontent.com/12469814/38162633-5d497ec4-34ed-11e8-8996-63115d19bb83.png)

**Comment by will-stone** [comment]
Ok, pull-request added.

**Comment by ShMcK** [comment]
A new logo has been added to the README & organization. Thank you to everyone for contributing! Special thanks to @will-stone for putting in the bulk of the initiative & effort.

We're still happy to take more feedback.

**Comment by Aerendir** [comment]
Personally I like a lot the gaming font...

Putting together the retro-gaming Rematch text with this logo with the "R" is really really cool in my opinion...

Really a good job!

As a side note: I'm really interested in this library... I'm experimenting with redux-orm and I will find a way to integrate the two once I will have sufficient experience with the ecosystem... In the mean time, thank you for your efforts! ♥️

**Comment by cyrilchapon** [comment]
Just discovered this awesome lib, I'm gland to see it's already branded. But you should post old logo in here, for memory ! 😁

**Comment by ShMcK** [comment]
Added a link to the original logo in a comment on Mar 10. (edited). For the annuls of history.
