### ISSUE TITLE
Annotations/Devtools

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#277]
> The only thing that I’d really be missing is the very human readable log you get from sentence style action names. Maybe we can add annotations or something for the devtools?

Quoted from Adam in "Redesigning Redux" comments.

Interesting idea, how might this work?

**Comment by jackwilsdon** [comment]
I've been thinking about this, and it sounds like what we really want is a way to change the action name for a reducer.

For example;

```JavaScript
const store = init({
  models: {
    counter: {
      state: 0,
      reducers: {
        increment: (state, delta = 1) => state + delta,
        decrement: (state, delta = 1) => state - delta,
      },
      actionTypes: {
        increment: 'INCREMENT_COUNTER'
      }
    }
  }
});

// this should dispatch INCREMENT_COUNTER instead of counter/increment
store.dispatch.counter.increment();
```

One question would be - what should reducers in other stores be called to listen to this action? I'd say it would still be `counter/increment`, but that's just my opinion.
