### ISSUE TITLE
Subscriptions vs Reducers

### ISSUE THREAD

**Issue by jackwilsdon** [rematch/rematch#280]
What is the difference between these two? What is the use case for using subscriptions? Are there any advantages with using subscriptions as opposed to listening to the action from the other store?

```JavaScript
const feed = {
  state: {
    profile: null,
    items: []
  },
  reducers: {
    "profile/load": (state, payload) => ({ ...state, profile: payload })
  }
};
```

```JavaScript
const feed = {
  state: {
    profile: null,
    items: []
  },
  reducers: {
    "loadProfile": (state, payload) => ({ ...state, profile: payload })
  },
  subscriptions: {
    "profile/load": ({ payload }) => this.loadProfile(payload)
  }
};
```

**Comment by ShMcK** [comment]
I would recommend using example 1. It's actually a new feature brought on by popular demand.

Example 1 accomplishes a change in a single action, whereas example 2 requires two actions.

I will put a note at the top of the subscriptions plugin to make it clear that 1 the recommended way to go.

**Comment by jackwilsdon** [comment]
Ah OK - didn't realise that listening to actions from other models was new :) That explains it! It sounds like the only real use for subscriptions now then is the ability to unsubscribe (which could be replicated in state anyway).

**Comment by ShMcK** [comment]
Subscriptions were originally intended for functionality like redux.saga "takeLatest" & "takeEvery". Personally I know longer use them in my code, and it seems simpler.

**Comment by jacklam718** [comment]
Not sure why deprecate the `subscription` pattern. Personally, I think the purpose of `subscription` is different with `reducer` reducer for change state and subscription can be used for handling side-effect.

for example:
```javascript
subscriptions: {
  'users/created': (payload) => {
    notify.success(`Signup Success welcome ${payload.username}`);
  }
}
```

**Comment by jackwilsdon** [comment]
I think we'll be supporting effects listening to actions in the future (see #240).

**Comment by linonetwo** [comment]
So how to ```take latest``` now?

**Comment by ShMcK** [comment]
Good question. 

I think it's a matter of whether you want to debounce/throttle the firing of an action, or the listening of the action.

Personally, I've been using `debounce` or `throttle` on effects. There may be a better solution, but this has worked for well for me.
