### ISSUE TITLE
Recipe for byId allIds pattern

### ISSUE THREAD

**Issue by titouancreach** [rematch/rematch#282]
Hi,

I'm converting my entire codebase from redux to rematch :+1: 
For each entities, I has a state like:

```javascript
const state = {
  byId: {
    '3': {
      //myEntityHere
    }
  },
  allIds: ['3']
};
```
I used everytime `combineReducer` to separate my: ById reducer and my AllIds reducers.

To refactor this in rematch, why would be better:
  - Create a lot of models like: myEntityAllIds and myEntityById
  - put the the byId and allIds in the same model (but the reducer will look ugly)
  - other ?

Thanks :+1:  

I think this is related to: 
https://github.com/rematch/rematch/issues/230

**Comment by jackwilsdon** [comment]
In your case I'd put them in the same model, as it's tightly related data.

```JavaScript
const model = {
  state: {
    byId: {},
    allIds: []
  },
  reducers: {
    load: (state, data) => ({
      byId: data, // Assuming your data is already keyed by ID.
      allIds: Object.keys(data)
    })
  }
};
```

If your data isn't already keyed by ID, it still shouldn't make the reducer too complex;

```JavaScript
const model = {
  state: {
    byId: {},
    allIds: []
  },
  reducers: {
    load: (state, data) => {
      // Assuming data is an array of objects with an "id" attribute.
      const byId = data.reduce((dataById, item) => ({ ...dataById, [item.id]: item }), {});

      return { byId, allIds: Object.keys(byId) };
    }
  }
};

**Comment by titouancreach** [comment]
Yes! Thanks for answering, I went that way. This is maybe a minor but it has changed my reducers from:

```javascript
 updateType(state, {entityId, type}) => ({
    ...state,
    [entityId]: {
      ...state[entityId],
      type
    }
  })
```

to
```javascript
    updateType(state, {entityId, type}) {
      return {
        ...state,
        byId: {
          ...state.byId,
          [entityId]: {
            ...state.byId[entityId],
            type
          }
        }
      };
    },
```
one level deeper. Even if the code is not that much complicated, it could lead to humain errors :(

I would imagine something like:


```javascript
reducers: {
  byId: {
    updateType(state, payload) {
      // state is localState.byId
    }
    add(state, payload) {
      return {
        ...state,
        [payload.id]: payload
      }
    }
  },
  allIds: {
    add(state, payload) {
      // state is my array
        return [...state, payload.id]; // add my id to the list 
    }
  }
}
```

`dispatch.entity.add()` would be handler by allIds and byId with the same payload.
AllIds and byId is something recommended by Redux (with their blog post example).

Does rematch could be interested with the feature ? If yes, I can eventually make a PR

**Comment by jackwilsdon** [comment]
This sounds like you want to nest models in that case, the discussion in #230 is where you want to be :+1:

**Comment by titouancreach** [comment]
#230 globally says that nested entities are an anti pattern, and we should flat our state instead. I'm totally agree with that. 
I think my use case is different than that because AllIds and ById are the same entity. It's just a way to have smaller reducers.

**Comment by ShMcK** [comment]
I might consider only storing the "normalized" data keyed on id with the [selectors](https://github.com/rematch/rematch/tree/master/plugins/select) plugin. 

```js
const modelName = {
 state: {
    '3': {
      //myEntityHere
    }
  },
  selectors: {
    byId: (modelState, id) => modelState[id],
    allIds: (modelState) => Object.keys(modelState),
  }
};
```

I have not been using selectors much in my code, but this strikes me as a good use case.

**Comment by titouancreach** [comment]
We can't assume the keys are in the right order in an array : https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by ShMcK** [comment]
I understand now. @titouancreach it seems you have a strong background in this area.

Would you like to contribute a recipe based on the rematch version of "structuring reducers/normalizing-state-shape" ? Happy to merge it into the docs.

**Comment by titouancreach** [comment]
@ShMcK I've a strong background because I fell down in every Redux pitfall :dancer: 
For me, the recipe for Rematch are the same as for Redux. This is why, I found https://github.com/rematch/rematch/issues/282#issuecomment-372644100 elegant. It's like a automatic combineReducers. One of the problem is that it can encourage newcomers to nest reducers.
The feature would not be very hard to code, the question is: Do we want it ?

**Comment by ShMcK** [comment]
I'm all for enforcing best practices, provided they're fully discussed :)

**Comment by titouancreach** [comment]
@xhite Nice, thanks for feedback. In my case I solved this in using little functions to update my state (that act like reducers. Example:

```javascript
reducers: {
  add(state, {payload}) {
    return {
      byId: myFunctionToUpateMyByIds(state.byId, payload),
      allIds: myFunctionToUpdateMyAllIds(state.allIds, payload)
    }
  }
}
```

it acts exactly as `combineReducers()` but we need to have a to declare those little function outside our model.

**Comment by xhite** [comment]
@titouancreach that's a good point. Looks exactly like what combineReducers does.
Thanks, I will try to use that

**Comment by ShMcK** [comment]
@titouancreach are you interested in creating a recipe for the docs?

**Comment by titouancreach** [comment]
Yes, sure, I'll do this asap :)

**Comment by titouancreach** [comment]
I think we can close this since the doc has been merged :+1:
