### ISSUE TITLE
selectors as first-class citizens instead of a plugin

### ISSUE THREAD

**Issue by mgutz** [rematch/rematch#283]
The select plugin, while useful, is clunky. Both Mobx and Vue treat computed props as first class citizens. Unless I'm misunderstanding something, these are the steps necessary to use selectors for every component.

1) Require the library: `import {select} from '@remtach/select'`
2) Access the selectors not via state but rather select: `select.someModel.selector(state)`

I don't see much benefit in using the selectors plugin. I could just a well use reselect by itself. Are there any thoughts in making selectors a first-class citizen, so we can simply do this

```
const mapState = (state, props) => {
  const payload= {name: props.name}
  return {computed: state.someModel.computedFunc(payload)}
}
```

**Comment by jackwilsdon** [comment]
The issue we'd run into here I think is that `react-redux`'s `connect` method passes the actual Redux state into `mapStateToProps`. The only way we could really implement it how you suggested is to use something like a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

**Comment by blairbodnar** [comment]
@mgutz - Totally agree with you - We've been talking quite a bit about this actually. (I also personally ended up not bothering to use with the select plugin, and I have also just been writing my selectors manually outside of the models. 😝) 
I'll close this in favour of #270 - Check it out for more info if you haven't already. Thanks!
