### ISSUE TITLE
Use selectors inside the model

### ISSUE THREAD

**Issue by titouancreach** [rematch/rematch#284]
Hello :) 

The classic use case of select is in mapStateToProps where we can access to the rootState.

```javascript
const mapStateToProps = state => ({
  mySelectedProperty: select.myModel.mySelector(state)
});
```
And it works perfeclty

but maybe we can pimp this to be accessible in the reducers ?

Here is a use case:

```javascript
{
  state: [{myProperty: myProperty, id: '2', amount: 3}],
  reducers: {
    myAction(state) {
     // bind selectors to this instance 
      return this.getPropertyIdWithAmountGt(3);
    }
  },
  selectors: {
    // my awesome selector here
    getPropertyIdWithAmountGt(state, amount) {
      return state.filter(p => p.amount > amount)
    }
  }
}
```
I'm sorry for this example which is not very relevant. But It could be useful to reuse selectors everywhere.

**Comment by ShMcK** [comment]
I've found similar situations where I'd like to use selectors inside of a reducer.

In my case, I wrote a simple selector that lived outside of the model. Something like the following:

```js
const getPropertyIdWithAmountGt = (state, amount) => {
  return state.filter(p => p.amount > amount)
}

const someModel = {
  state: [{myProperty: myProperty, id: '2', amount: 3}],
  reducers: {
    myAction(state, payload) {
     // bind selectors to this instance 
      return getPropertyIdWithAmountGt(state, payload);
    }
  },
}
```

I agree, there should be a more elegant solution for selectors. There some discussion on this in #270, I'd encourage you to add your feedback there as well.

**Comment by titouancreach** [comment]
Yes, it's what I used (and it works well!). The problems I found with using functions is: 
  - The naming is very hard (you often have to reference the model name in the your function
  - It's hard de define in which file do you put your selectors (some are generic, others are not)

Maybe we should continue the discussion in #270 and close this one :)

**Comment by blairbodnar** [comment]
Yeah, I feel the same way about your two points there @titouancreach. 
Hop on over to #270 @titouancreach, we have some ideas flowing there. 😀
