### ISSUE TITLE
a Roadmap?

### ISSUE THREAD

**Issue by haikyuu** [rematch/rematch#286]
I came across Rematch recently and i find it very simple and delightful. Thanks for the great work. ❤️ 

It is in its early stages, and i'd like to point out an important thing to take into consideration, that is the need for a roadmap, and a proper document that explain the scope of the project and what is **not** in the scope. Because adding a lot of features, although cool, is not beneficial in the long run or comes with tradeoffs. A great example is Elm and how they tackle features, and also Redux .

Here is [a recent tweet from DHH](https://twitter.com/dhh/status/973652134423072769 ) that talks just about that 

> An endless parade of people with really good, concrete reasons will ask you to make your product more "advanced" or "flexible" (i.e. complicated). Listen to them, but balance the feedback with a thought to the many more who won't buy a complicated product.

**Comment by ShMcK** [comment]
Thanks @haikyuu. Your comments are well timed as we see more and more people getitng involved. We definitely are in agreement.

Perhaps this thread can serve to outline a clearer vision of what Rematch is.

### Current Vision
- limited to state management
- view layer agnostic
- should evolve best practices and display them in tutorials/docs

### Future
- support multiple stores
- allow a wild west of plugins, but limit core to evolved best practices
 support improved devtools

**Comment by nWidart** [comment]
Sad to see no typescript support in there 😢

**Comment by ShMcK** [comment]
Edit: `CurrentVision['TS support'] = true`

**Comment by nWidart** [comment]
Haha

![](https://media2.giphy.com/media/NTY1kHmcLsCsg/giphy.gif)
