### ISSUE TITLE
Can't build using npm

### ISSUE THREAD

**Issue by jackwilsdon** [rematch/rematch#290]
Running `npm run build` results in this;

```
> @rematch/core@0.5.2 build /home/jack/dev/rematch
> cross-env rimraf build dist && tsc && rollup -c && node ./scripts/bundles


lib/index.js → dist/cjs/rematch.dev.js...
[!] Error: Could not resolve './init' from lib/index.js
Error: Could not resolve './init' from lib/index.js
    at error (/home/jack/dev/rematch/node_modules/rollup/dist/rollup.js:168:15)
    at /home/jack/dev/rematch/node_modules/rollup/dist/rollup.js:21536:25
    at <anonymous>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rematch/core@0.5.2 build: `cross-env rimraf build dist && tsc && rollup -c && node ./scripts/bundles`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @rematch/core@0.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jack/.npm/_logs/2018-03-15T13_55_35_485Z-debug.log
```

**Comment by jackwilsdon** [comment]
So it looks like this is an issue with `tsc`. I only end up with an `index.js` in `lib`, which causes the issue with rollup.

I find this odd, as the `tsconfig.json` includes `src/index.js`, and [the documentation](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) says that any files imported by files listed in `tsconfig.json` are also built.

**Comment by ShMcK** [comment]
I'e experienced this issue recently as well. It occurred after updating my version of rollup.

Some suggestions:
- clear out "dist"
- remove "node_modules" and "npm install" again
- try running "tsc" in the command line, then running the build script separately.

**Comment by jackwilsdon** [comment]
I re-checked it out and that sorted it! How weird...
