### ISSUE TITLE
Use with redux-offline

### ISSUE THREAD

**Issue by joaopiopedreira** [rematch/rematch#292]
Hi @ShMcK, great package, thank you for this! Do I really have to wait for an "offline" plugin to be created (based on redux-offline) or can I get started right away using your package in an offline-first app? Do you think I can just add redux-offline as a dependency and get started? Would I face any particular challenges? Cheers

**Comment by ShMcK** [comment]
I'll get back to you later today with a fuller response when I have time, but for now a short answer:

As a former user of "redux-offline", and developer of an offline first app --
I believe Rematch can work with "redux-offline", but I don't believe this is the most elegant way to achieve "offline-first".

**Comment by dzz0615** [comment]
@ShMcK What's your recommended way to achieve "offline-first"?

**Comment by ShMcK** [comment]
Surprisingly, I gave a presentation last year on using "redux-offline" with react-native. [slides](http://slides.com/shmck/offline-first-react-native). I'll summarize some notes on how my views have changed, I apologize ahead of time if it degenerates into rambling :)

##### The Good

Redux offline is a quick and easy way to get started with offline support. Largely, the problem I grew to find with "redux-offline" is the way actions are handled.

```js
const asyncAction = () => ({
  type: 'LOADING',
  meta: {
    offline: {
      effect: { url: someURL },
      commit: { type: 'SUCCESS' },
      rollback: { type: 'FAILURE' },
    }
  }
})
```

You pass in an effect, then how to handle it when it's successful or fails based on meta actions. Redux offline gives you an entire "retry" strategy. A slide from the presentation:

<img width="910" alt="screen shot 2018-03-25 at 9 15 23 pm" src="https://user-images.githubusercontent.com/4660659/37886698-bae1fe1a-3071-11e8-9592-ce807936c733.png">

##### The Bad

I've found processing logic within middleware to be harder to debug and even harder to customize. For example, not all retry strategies should be the same, and not all results of effects return a clean single action.

##### The Ugly, but more customizable :)

Personally, I've found "effects" in Rematch to be a more explicit way to handle retry strategies. Granted I have an app with a lot of persisted data, so there is usually a simple fallback.

```js
import retry from './retry'

const someAsyncModel = {
  state: 0,
  effects: {
    async someFetchAction() {
     try {
      const data = await fetchData('someUrl')
      // success
     } catch (error) {
      // failure
       retry({
           status: error.status,
           onRetry: this.someFetchAction,
           attempts: 3,
           delay: 10000,
        )
     }
    }
  }
}
```

##### Something Better

I'm currently looking towards using [Apollo](https://www.apollographql.com/) as a more ideal solution, once I have more time to play with Graphql. I feel like there should be a non-Graphql solution with similar feature parity. If somebody knows of one, let me know.

**Comment by dzz0615** [comment]
Thanks for the detailed answer. After looking at the lib, I agree with you that explicitly handling retry strategies in "effects" is much easier to reason about, even though it may be uglier / slightly more code.

**Comment by acnebs** [comment]
The issue with using rematch's effects is that there doesn't seem to be a good way to perform a rollback.

I mean sure, you could pull in the store and save the previous value in your function from there, but that seems like a very inefficient way of doing this.

**Comment by nahuelb** [comment]
Hello, I would like to know if @ShMcK answer is still the way to go to work with state management on offline first apps. I am starting to work on a project and a I not sure to use Rematch with persist or Redux with redux-offline.

**Comment by semoal** [comment]
> Hello, I would like to know if @ShMcK answer is still the way to go to work with state management on offline first apps. I am starting to work on a project and a I not sure to use Rematch with persist or Redux with redux-offline.

If you can go with rematch and persist, is the way to follow. I didn't tried redux-offline, but if i have to use base redux and not rematch for just using the offline option, i would kill my self.
