### ISSUE TITLE
Question - Login logic with react navigation

### ISSUE THREAD

**Issue by gusleo** [rematch/rematch#297]
Currently, when we create login logic it will dispatch to some navigation if success. How to call dispatch.nav.reset() on effects?

`effects: {
        async loginAsync( username: string, password: string ) {
            this.init();
            await new Promise( resolve => setTimeout( resolve, 5000 ) );
            this.login( {
                accessToken: "12345",
                refreshToken: "456",
                expiredIn: Date.now()
            } );
          //Should call dispatch.nav.reset here?
}`

**Comment by ShMcK** [comment]
Currently, the `dispatch.nav.reset` requires a few more params. 

It follows the same API as "react-navigation": https://reactnavigation.org/docs/navigation-actions.html#reset

Here's an example I used in a project:

```js
dispatch.nav.reset({
  index: 0,
  key: null,
  actions: [NavigationActions.navigate({ routeName: 'Login' })],
})
```

I'd love if someone would work out a more elegant way to handle "reset".

**Comment by gusleo** [comment]
@ShMcK I'm trying adding reset or navigate but their's not going anywhere.
<img width="557" alt="screenshot at mar 18 01-50-40" src="https://user-images.githubusercontent.com/15825376/37558432-f7ea2464-2a4e-11e8-8abd-733219437951.png">

**Comment by ShMcK** [comment]
Try to specify the params within an object of `{ routeName: 'Main' }`

**Comment by gusleo** [comment]
nevermind, I'm forget to change current StackNavigator on the root with Navigator from this code
`const { Navigator, reactNavigationPlugin } = createReactNavigationPlugin({
  Routes,
  initialScreen: 'Landing'
})`

Thank you
