### ISSUE TITLE
Cross-model actions/reducers?

### ISSUE THREAD

**Issue by kiznit** [rematch/rematch#298]
I like what this library is trying to achieve. There is one thing that I couldn't grasp looking at the documentation / examples and code...

Say you have 2 models: A and B. You have some action defined in model A and you want a reducer in model B to listen to that action to mutate model's B state. How do you accomplish this?

This is useful for badges on the taskbar, handling auth actions (login / logout) where you want to clear and mutate state of non-auth related models, etc.

**Comment by jackwilsdon** [comment]
You can name the reducer in Bed `A/actionName`.

**Comment by kiznit** [comment]
Thanks!

**Comment by kdela** [comment]
@jackwilsdon Is that the right thing?
I haven't see that anywhere in docs

**Comment by jackwilsdon** [comment]
@kdela You can find it in the ["reducers" section of the model documentation](https://rematch.gitbooks.io/rematch/docs/api.html#reducers).

**Comment by kdela** [comment]
Oh you're right. Thanks @jackwilsdon
