### ISSUE TITLE
Android Build issue with 0.5.3

### ISSUE THREAD

**Issue by Reesco** [rematch/rematch#299]
I use Expo app to develop. Before update I have problem with effects, because it doesn't ran, but reducers and plugins worked well, but after update any of things works because of:
Unexpected token ','. Expected a ':' following the property name 'type'.

..\node_modules\@rematch\core\dist\umd\rematch.prod.min.js

what I'm doing wrog? Thanks for answer!

**Comment by ShMcK** [comment]
Also using 0.5.3 with Expo, but not having the same issue. 

Perhaps try rolling back to 0.5.0 and see if the issue still exists. If so, we'll have to investigate further.

**Comment by Reesco** [comment]
Ok, thanks! I'll do it just right now.

**Comment by Reesco** [comment]
So, I'm using VS Code with remote redux tool. 

0.5.0 - reducers and effects work well, but I can't setup redux tool
0.5.2 - reducers and redux tool work well, but effects doesn't work. I can see action in redux tool but nothing happend
0.5.3 - also as 0.5.2 but to get it work without error from my first comment I need to enable JS remote debugging in Geny emulator.

Thanks for any advice.

**Comment by ShMcK** [comment]
0.5.0

I'm not sure what you mean "can't setup redux devtool", could you explain a bit more?

0.5.2 - You're right, "effects" are no longer being recorded in redux devtools. I'll create an issue for this.

See #300.

0.5.3 I'm not sure if I can help here.  I have not yet used JS remote debugging with GenyMotion, and often opt for debugging on the android devices directly.

**Comment by gusleo** [comment]
I'm still have this issue with 0.5.3 when exp publish or npm run android -- --no-dev
for now, i'm rolling back to 0.5.0

**Comment by ShMcK** [comment]
Just noticed this issue when building android with 0.5.3. Will definitely try to resolve this soon.

**Comment by ShMcK** [comment]
I believe this is related to a reference to `new Function`, a hack to get around minification mangling variables. Will resolve within a few days.

**Comment by taranda** [comment]
I have the same issue in React Native 0.54.2 (no Expo).  I rolled back to Rematch 0.5.2 and the error went away.  Rematch 0.5.3 compiles fine on iOS and works fine in the Google Chrome V8 engine when remote debugging is turned on.

For some reason, Android does not like the `Function('type',`...`)` syntax in `dist/umd/rematch.prod.min.js` line 133, column 122.   I agree that it is related to the ` new Function('type',`...`)` statement in `src/utils/getActionCreators.js`

**Comment by ShMcK** [comment]
Simple fix. Resolving this issue by marking "type", "payload", "meta" as reserved words for Uglify.

Will publish within a day.
