### ISSUE TITLE
react-navigation nested navigator

### ISSUE THREAD

**Issue by ainulya16** [rematch/rematch#301]
i got an error `Cannot read property 'undefined' of undefined`. 
in my routes:

> const TabScreenNavigator = TabNavigator({
  Home:  { screen: Home, 
              navigationOptions:{
                title:'',
                tabBarLabel:'Beranda',
                tabBarIcon: ({ tintColor }) => (
                  <IconCustom name='home' size={24} color={tintColor} />      
                ),
              }
            },
  Wislist:  { screen: Wishlist, 
              navigationOptions:{
                title:'',
                tabBarLabel:'Beranda',
                tabBarIcon: ({ tintColor }) => (
                  <IconCustom name='home' size={24} color={tintColor} />      
                ),
              }
            },
}, { 
  initialRouteName: 'Home',
});
export default StackNavigator({
  Tab:{
    screen: TabScreenNavigator
  },
  Login:{
    screen: Login
  }
},
{initialRouteName:'Tab'})

**Comment by ShMcK** [comment]
There seems to be a typo "Wislist" -> "Wishlist". Perhaps that is a factor?

**Comment by ainulya16** [comment]
no, it is not. "Wislist" is only name of router.

**Comment by ShMcK** [comment]
Perhaps related to:
- [1919](https://github.com/react-navigation/react-navigation/issues/1919)
- [2456](https://github.com/react-navigation/react-navigation/issues/2456)

What does your rematch setup look like?

**Comment by ainulya16** [comment]
routes.js
`
const TabScreenNavigator = TabNavigator({
  Main:  { screen: Main, 
              navigationOptions:{
                title:'',
                tabBarLabel:'Main',
              }
            },
  Wishlist:  { screen: Wishlist, 
              navigationOptions:{
                title:'',
                tabBarLabel:'Wishlist',
              }
            },
}, { 
  initialRouteName: 'Main',
});
export default StackNavigator({
  Tab:{
    screen: TabScreenNavigator,
  },
  Login:{
    screen: Login
  }
},
{initialRouteName:'Tab'})`

navigator.js
`import createReactNavigationPlugin from '@rematch/react-navigation'
import Routes from '../routes'
import { dispatch } from '@rematch/core'

export const { Navigator, reactNavigationPlugin } = createReactNavigationPlugin({
  Routes,
  initialScreen:'Tab'
})`

**Comment by ShMcK** [comment]
Sorry I can't be more help. I can't seem to find an issue with your code.

I will, however, provide some tips:
- you can setup your own React-Navigation/Redux setup from the react-navigation docs.
- I've spoken with a core developer working on React Navigation, and they do not recommend using it with Redux. They recommend it is easier and more performant to utilize the "navigation" passed in with the `withNavigation` HOC. https://reactnavigation.org/docs/with-navigation.html

I hope this, at least, may be helpful.

**Comment by ShMcK** [comment]
I'll close this issue as possibly no resolution.
