### ISSUE TITLE
Immutable JS support

### ISSUE THREAD

**Issue by taranda** [rematch/rematch#302]
I am new to Immutable JS and Rematch.   My goal is  to using Rematch and Immutable JS together and make the entire state tree an Immutable JS object.  Is this possible?

According an author at [Redux.org](https://redux.js.org), one of the best practices regarding Immutable JS and Redux is to [make your entire Redux state tree an Immutable.JS object](https://redux.js.org/recipes/using-immutable.js-with-redux#make-your-entire-redux-state-tree-an-immutable.js-object).  They recommend replacing Redux's`combineReducers` with one  provided by [redux-immutable](https://github.com/gajus/redux-immutable).

I know rematch supports replacing the `combineReducers` method with  a custom method via the [Redux API](https://github.com/rematch/rematch/blob/master/docs/reduxApi.md#combinereducers).  However, will this affect the  entire Rematch state, or only apply to the reducers/state in the `redux:` section of the `init` configuration?

I would like  to take advantage of the `models` pattern using Immutable JS objects.

**Comment by ShMcK** [comment]
I have not used Rematch with Immutable.js, though I believe this is possible. 

Replacing `config.redux.combineReducers` will replace all state with an Immutable.js state.

If you are looking for a simpler approach to using immutable state with Rematch/Redux, I would suggest trying [Immer](https://github.com/mweststrate/immer).

**Comment by taranda** [comment]
Thanks.  I'll try that.  If I get it to work, I'll submit a documentation PR.
