### ISSUE TITLE
state confused in multiple store

### ISSUE THREAD

**Issue by arcthur** [rematch/rematch#312]
Hi,

When I init two store, I found the state will combine.

```js
const count = {
  state: 0,
  reducers: {
    addOne: state => state + 1
  }
}

const book = {
  state: 0,
  reducers: {
    addOne: state => state + 1
  }
}

const store = init({
  models: { count }
})

const store2 = init({
  models: { book }
})
```

if I used dispatch from one of store, and dispatch another, that will show `{ count: 1, book: 1}`
I think they are two separate store for these state, and I want to this result `{count: 1}` and `{book:1}`

**Comment by jackwilsdon** [comment]
I think rematch has a single internal store at the moment, but it seems to overwrite that when calling `init` multiple times.

https://github.com/rematch/rematch/blob/460e682ef5552dacb427855d2061174bad18dba2/src/redux/store.ts#L8

I think with #254 it's moving to a more OOP approach allowing multiple store instances to exist simultaneously.

**Comment by ShMcK** [comment]
Working on this with #240 as well. Quite close.

Currently Rematch will not work with multiple stores.

**Comment by ShMcK** [comment]
I'll close this issue as linked to @239.
