### ISSUE TITLE
Unable to subscribe to actions from redux.reducers

### ISSUE THREAD

**Issue by miickel** [rematch/rematch#322]
My init looks like this:

```javascript
let store = init({
  redux: {
    reducers: {
      router: router.reducer,
    },
    middlewares: [router.middleware],
    enhancers: [router.enhancer],
  },
  models,
})
```

Here `router` comes from [redux-little-router](https://github.com/FormidableLabs/redux-little-router).

My model looks like this:

```javascript
export const model = {
  state: {},
  reducers: {
    'ROUTER_LOCATION_CHANGED': (state, payload) => {
      // never trigger
    },
  },
}
```

I can see using Redux dev tools that `ROUTER_LOCATION_CHANGED` gets dispatched, yet my rematch reducer function never gets called.

I'm able to subscribe to rematch model actions using the `{model}/{reducer}`-convention, but can't find any way to subscribe to actions dispatched outside of rematch.

Is this supported?

**Comment by ShMcK** [comment]
I think there are a few options here:

1) use "redux.reducers" instead of models.
2) there is a subscriptions plugin, but I think this will get deprecated in the near future.

---

## Proposal

I think a more elegant solution would be if you could map actions to other action names.

```js
export const model = {
  state: {},
  mapActions: {
    'ROUTER_LOCATION_CHANGED': 'routeChange'
  }
  reducers: {
    'routeChange': (state, payload) => {
      // never trigger
    },
  },
}
```

This could be made possible in core or through a plugin. What are your thoughts?

**Comment by miickel** [comment]
I like your mapActions proposal, but perhaps mapping on the model level is a bit too granular? I mean, if I want to map ROUTER_LOCATION_CHANGED to routeChange, wouldn't that be true for all my models in that project?

Another proposal is to simply namespace the actions `@redux/ROUTER_LOCATION_CHANGED `

**Comment by ShMcK** [comment]
That proposal sounds much simpler. @blairbodnar what are your thoughts?

**Comment by blairbodnar** [comment]
I think giving a namespace to those actions is a great idea @miickel! I like how it follows the convention redux uses in [action types](https://github.com/reactjs/redux/blob/master/src/utils/actionTypes.js). 

```js
export const modelA = {
  reducers: {
    'set': // reducer for action type: 'modelA/set' (this model)
    'modelB/set': // reducer for action type: 'modelB/set' (another model)
    '@@redux/something': // reducer for action type: '@@redux/something' (not a model)
  }
}
```
I like it!

**Comment by jackwilsdon** [comment]
The `@@` prefix was meant to designate that it is an internal action in redux and shouldn't really be used I don't think. What about something like `#redux/something` or just `#something` instead?

**Comment by blairbodnar** [comment]
Very nice @miickel!

**Comment by suazithustra** [comment]
@miickel  how did you get this to work with redux-little-router?
