### ISSUE TITLE
use es6 map over objects when dynamic adding/removing

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#33]
According to MDN

> Use maps over objects when keys are unknown until run time, and when all keys are the same type and all values are the same type

This may be a good use case for using ES6 maps over objects for "dispatch", "effects" & "hooks".

We are essentially adding and removing these keys on runtime.

**Comment by ShMcK** [comment]
See an example with hooks in #34.

As hooks are internal, this works. However, it may not work for "dispatch", as we can't really call `dispatch.name.action()` with maps.

**Comment by blairbodnar** [comment]
@ShMcK  Yeah, people (and us, hah) won't be happy doing `dispatch.get('name').get('action')()`
Could consider the best of both worlds? Use Maps, but then transform them to objects for external use?

```js
// internally... maybe also external...
const dispatch = new Map([
  ['count', new Map([
    ['increment', () => {}],
    ['decrement', () => {}]
  ])]
])

// developer sadness 😞
dispatch.get('count').get('increment')()
dispatch.get('count').get('decrement')()


// transform it to an object
// some util function, probably some good npm packages for this, or write it ourselves. 
const niceDisptach = convertNestedMapsToObject(dispatch) 

export {
  niceDisptach as dispatch
}

// developer happiness 😀
dispatch.count.increment()
dispatch.count.decrement()

```

**Comment by ShMcK** [comment]
Not sure if there's really a benefit. Objects work. Keep devs happy, and code simple.

**Comment by blairbodnar** [comment]
Yeah, agreed

**Comment by ShMcK** [comment]
Seems like we've done what we can, when we can in terms of maps over objects.
