### ISSUE TITLE
V1 Warning with Redux v4 

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#331]
Getting the following warning when running v1 in a large app:

```
Possible Unhandle Promise Reject:
Error: You may not call store.getState() while the reducer is executing. 
The reducer has already received the state as an argument. 
Pass it down from the top reducer instead of reading it from the store.
```

**Comment by titouancreach** [comment]
https://gist.github.com/timdorr/f6d76d41508bf5a352846ba685322a6c#file-redux-js-L82

From the code, it happens when dispatch thing during your reducer is being called.

**Comment by ShMcK** [comment]
Possibly with the effects middleware:
https://github.com/rematch/rematch/blob/5f72d9607342a2e8c86e0c564fd8a7f533966cfb/src/plugins/effects.ts#L49
