### ISSUE TITLE
Can this be used together with redux-orm?

### ISSUE THREAD

**Issue by Aerendir** [rematch/rematch#337]
I like a lot this framework, and I like a lot [redux-orm](https://github.com/tommikaikkonen/redux-orm), too.

So, my question is: can they be used together?

I'm in the process of learning React/Redux and so I'm not able to understand by myself the integration possibility.

Maybe someone here with deeper experience can put me on the right way...

**Comment by ShMcK** [comment]
I don't believe Rematch & Redux-ORM can be used together. I've found when you're new to something, trailing a fresh new path for yourself is rarely a good option.

If you're new to Redux-ORM, I would also consider [this opinion on ORMs to be a learned lesson](https://youtu.be/mIoKRyLcIjo?t=240). 

If you're seeking an ideal solution for syncing external data, [apollo](https://www.apollographql.com/) may be a better choice altogether.

**Comment by Cloudo** [comment]
@Aerendir you can use [normalizr](https://github.com/paularmstrong/normalizr) for data normalization

**Comment by ShMcK** [comment]
I would largely agree with @Cloudo. Normalizr, or the patterns that normalizr produces strike me as simpler than using Redux-ORM.

Take this example below: 

```js
{
    todos: [
        {
             id: 1,
             activity: Learn Redux
             user: {
                 id: 1
             },
        {
             id: 2,
             activity: Integrate redux-orm with rematch
             user: {
                 id: 1
             }
        }
    ],
    users: [
        1: {
            name: pinco pallo
        }
    ]
}
```

In its normalized state, it would look more like this: 

```js
{
  "todos": {
    "1": {
      "activity": "Learn Redux",
      "user": 1
    },
    "2": {
      "activity": "Integrate redux-orm with rematch",
      "user": 2
    },
    "users": {
      "1": {
        "name": "pinco pallo"
      }
    }
  }
}
```

From this, you can easily access any item directly, without having to iterate over or manipulate a large data set. For example:

`users[todos[1].user].name // "pinco pallo"`

**Comment by Aerendir** [comment]
Yes, and this is the solution I'm currently using...

But Normalizer has some drawbacks:

1) It requires to be used in conjunction with `reselect` to memoize the results of selections
2) It is intended for a one time normalization
3) Doen't provide tools to deal with data once normalized

I'm [citing Mark Erikson](http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/#why-use-redux-orm):

> However, Normalizr is really only intended for one-time processing of incoming data. It doesn't provide tools for dealing with normalized data once it's in your store. For example, it doesn't include a way to denormalize data and look up related items based on IDs, nor does it help with applying updates to that data. There are a couple of other libraries that can help, such as Denormalizr, but there's a definite need for something that can make these steps easier to deal with.

I found his observations are right.

So, also if currently I'm using normalizr, I'm in the process of switching toward `redux-orm`.

**Comment by d3dc** [comment]
@Aerendir `redux-orm` doesn't have a redux plugin or anything. You just use it the same way no matter what state management you have. [There was a utility function to remove some boilerplate, but the docs now advocate using it explicitly](https://github.com/tommikaikkonen/redux-orm#redux-integration)

I'm not sure why there is debate over things as alternatives. `redux-orm` has a misleading name and is really just a library like `normalizr` or `reselect` and takes the same place in your stack as them, not `redux` or `rematch`. I think @ShMck has a point in that its easy to get confused when you don't know what tools are for.

**Comment by kunaldodiya** [comment]
https://github.com/kunaldodiya/rematch-redux-orm
