### ISSUE TITLE
Complete plugin example not using Typescript

### ISSUE THREAD

**Issue by yougotashovel** [rematch/rematch#343]
Hi, trying to create a plugin.  However the docs don't show a full example, and the plugins are written in typescript (which i'm not using) so it's not easy to determine how exactly to setup a plugin.

Here's a simplified version to test if something is happening.

`plugins/api.js`
```javascript
const api = {
  onModel(model) {
    console.log('api plugin', model);
  },
}

export default api
```

`configureStore.js`
```javascript
import { init } from '@rematch/core'
import * as models from './models'
import api from './plugins/api'

const store = init({
  models,
  plugins: [ api ],
})
```

Then if i add `api: { ... }` to a model, nothing happens.  

Am i missing something?  Do i need to import something for the plugin file to work?

Thanks

**Comment by ShMcK** [comment]
Are you using @rematch/core v0.6 or v1.0.0-alpha?

If v0.6 I recommend going to the [0.x branch and docs](https://github.com/rematch/rematch/tree/v0/docs).

Sorry, this is currently not clear. We're hoping to get out a v1 soon that has some breaking changes some minor breaking changes to the way plugins are written. By minor, I mean the difference is a few lines of code.

**Comment by yougotashovel** [comment]
@ShMcK using 0.5.3 at the moment.

I've been looking at the 0.x docs already, but still can't find the right way to do it.  Just wondered if there was an easy way to instantiate a plugin that i missed.  Something like:

```javascript
import { Plugin } from '@rematch/core'

const api = Plugin({
   ...
})
```
I assumed because the models were basic objects, that the plugin would also be.

**Comment by ShMcK** [comment]
In v1 plugins are objects.
I
n v0, we used an `init` function to pass in data shared between plugins.

```js
const plugin = {
   init: ({ dispatch, validate, effects }) => ({
    onModel(model) {
      // do something
    }
  })
}
```

I agree that this was a less than ideal design. 

What kind of plugin are you trying to make? Perhaps if you share some code we can help you out?

**Comment by yougotashovel** [comment]
Turns out i got messages through in the console, so it appears the plugin is getting activated, but it  isn't updating the model. 

Here's the code i have for my plugin.  
- All the actions/reducers/state that are imported are working independently. 
- `console.log(model)` shows the additions to model
- `return model` doesn't seem to do anything, or without it.

```javascript
import apiActions from './api.actions'
import apiMiddleware from './api.middleware'
import { apiReducers, apiState } from './api.reducers'

export default {
  init: ({ dispatch, validate, effects }) => ({
    onModel(model) {
      if (model.request) {
        // Add state
        model.state = {
          ...model.state,
          ...apiState(),
        }

        // Add reducers
        model.reducers = {
          ...model.reducers,
          ...apiReducers(),
        }

        // Add effects/actions
        model.effects = {
          ...model.effects,
          ...apiActions(),
        }

        console.log(model);
        return model
      }
    },
    middleware: apiMiddleware,
  })
}
```

**Comment by ShMcK** [comment]
`onModel` has no return value, since it may lead to strange bugs.

I believe #323 is related to what you're trying to do.

**Comment by yougotashovel** [comment]
#323 - Looks like the solution is processing models before passing to `init`?

I guess this is what i was already doing with my factory.  

Thought it would be possible/simplest to add a plugin that could add basic structure to a model, but also include middleware, but it seems this isn't possible?
