### ISSUE TITLE
@rematch/loading have trouble with @rematch/immer

### ISSUE THREAD

**Issue by pciapcib** [rematch/rematch#345]
Hello, thanks for amazing rematch and @ShMcK .

I have trouble in using rematch plugins. I found that @rematch/loading and @rematch/immer have conflict when I use both in a project. The strange behavior is that @rematch/loading is always false(0.3.6) or 1(>= 0.4.0) and @rematch/immer is showing empty action in redux devtools.

I am using parcel-bundle for my tiny project, I hope it's not the reason of this issue...

``` js
// store.js
import { init } from '@rematch/core'
import immerPlugin from '@rematch/immer'
import loadingPlugin from '@rematch/loading'
import { routerMiddleware, routerReducer as routing } from 'react-router-redux'

// via babel-plugin-glob-import
import * as models from './models/*.js'

import { history } from './router'

const immer = immerPlugin()
const loading = loadingPlugin()

const store = init({
  plugins: [immer, loading],
  models,
  redux: {
    middlewares: [routerMiddleware(history)],
    reducers: {
      routing
    }
  }
})

export default store
```

**Comment by ShMcK** [comment]
Perhaps an immer `whitelist` or `blacklist` options may help. 

```js
immerPlugin({
  blacklist: ['loading']
})
```

Any better ideas?

**Comment by linonetwo** [comment]
I think this solution is enough, just one line of config. But it needs to be mentioned in loading plugin's documentation.

**Comment by linonetwo** [comment]
Even use [immutable-js-example](https://github.com/rematch/rematch/blob/master/plugins/loading/README.md#immutable-js-example) is impossible:

https://stackblitz.com/edit/react-ussyfk?file=store.js

**Comment by linonetwo** [comment]
@jackwilsdon  Yeah, loading plugin is using copyReducer:
https://github.com/rematch/rematch/blob/faf9db021b843866620da7a8dff4028124f03e68/plugins/loading/src/index.ts#L24-L38
And immer plugin produce it:
https://github.com/rematch/rematch/blob/faf9db021b843866620da7a8dff4028124f03e68/plugins/immer/src/index.ts#L10-L18
The only difference is `cntState`, which is outside of `produce`, but it don't seem to be the problem.

**Comment by linonetwo** [comment]
![wx20180729-164336](https://user-images.githubusercontent.com/3746270/43364539-9727cd2a-934e-11e8-875b-2d80fdcde103.png)

Result returned from loading plugin is correct. It must be immer plugin's fault.

**Comment by linonetwo** [comment]
Why rematch-loading.umd.js has multiple lines, but rematch-immer.umd.js only has one line?
I can't set breakpoints on rematch-immer.umd.js.

**Comment by linonetwo** [comment]
Wait, are we missing a 'return' here?
https://github.com/rematch/rematch/blob/faf9db021b843866620da7a8dff4028124f03e68/plugins/immer/src/index.ts#L13

According to 
https://github.com/mweststrate/immer#returning-data-from-producers
If we want to produce an entirely new state likes:
https://github.com/rematch/rematch/blob/faf9db021b843866620da7a8dff4028124f03e68/plugins/loading/src/index.ts#L24-L38
We should return the `draft`.

**Comment by linonetwo** [comment]
Aha, adding a 'return' actually solve the problem. It works properly now.

![wx20180729-171444](https://user-images.githubusercontent.com/3746270/43364761-fac7fcfc-9352-11e8-9018-0a80d0f8a606.png)

**Comment by linonetwo** [comment]
I think this issue can be closed now.
https://stackblitz.com/edit/react-ksr6xw?file=store.js
Try @rematch/immer@1.1.0.

**Comment by iamvijaydev** [comment]
I have another kind of issue with same plugin mix, both ^1.x.x., in **electron env**. I could create a separate issue if that's required.

When using loading and immer plugin together, `loading.effects.<model>.<effect>` value type changes from `boolean` to `number`. This happens after immer is used to create the draft, for e.g `onFetchSuccess` reducer.

Looking at this code, I ponder how could the internal config of loading, `asNumber`, be modified by the presence of immer and in this specific way `asNumber: true` - https://github.com/rematch/rematch/blob/master/plugins/loading/src/index.ts#L70-L71.

Specifically setting `asNumber: false` in `createLoadingPlugin(config)` doesn't solve it. The only way around it is to use loading as `number`. For this reason I had to drop the immer plugin and use immer directly. I don't suspect **electron env** yet, as I'm using rematch in the renderer files only.

Let me know if anyone else has the same issue, or not.

**Comment by iamvijaydev** [comment]
@linonetwo Yep somehow an older version of @rematch/loading plugin got installed. I removed both plugins and tried again and everything worked fine. Thank you so much for looking into it.
