### ISSUE TITLE
Question about effects

### ISSUE THREAD

**Issue by orangecoding** [rematch/rematch#348]
Hi,

I've just started using rematch, but ran into an issue which I guess is kind of a "you are doing it wrong".

I have a simple model which is collecting stuff from the backend asynchronously. This is done in effects reducer. Do I really need to parse the result into a regular reducer? Can't I just mutate the state from the async reducer? If not I would need to have 2 reducers for every single async action...

This is what I currently do:

```
import { xhrGet } from 'in-services/xhr';

export const contacts = {
  state: {
    contacts: []
  },
  reducers: {
    setContacts(state, payload) {
      return {
        ...state,
        contacts: Object.freeze(payload)
      };
    }
  },
  effects: {
    async getContacts() {
      try {
        const contacts = await xhrGet(`/api/contacts`);
        this.setContacts(JSON.parse(contacts.text));
      } catch (Exception) {
        console.error(
          `Error while trying to get resource for api/contacts. Error:`,
          Exception
        );
      }
    }
  }
};
```

And this is what I want to do:

```
export const contacts = {
  state: {
    contacts: []
  },
  reducers: {},
  effects: {
    async getContacts(state) {
      try {
        const contacts = await xhrGet(`/api/contacts`);
         return {
            ...state,
           contacts: Object.freeze(JSON.parse(contacts.text))
         };
      } catch (Exception) {
        console.error(
          `Error while trying to get resource for api/contacts. Error:`,
          Exception
        );
      }
    }
  }
};
```

Is this somehow possible?

**Comment by kdela** [comment]
Someone in one of GH issues considered create plugin to reduce this boilerplate, but I couldn't find it.
It's seems like a right way for this moment (imho)

**Comment by kdela** [comment]
@orangecoding 
https://github.com/rematch/rematch/pull/323

**Comment by orangecoding** [comment]
wouldn't it be possible to include something into the main lib? This is a common use case from my point of view...

**Comment by blairbodnar** [comment]
@orangecoding Yeah, def a common use case, but it can be handled pretty well via a recipe approach we were talking about in that thread, so that's the approach we're recommending.
