### ISSUE TITLE
TypeError: fe.default is not a function (@rematch/immer)

### ISSUE THREAD

**Issue by linonetwo** [rematch/rematch#349]
Versions:
    "@rematch/core": "^1.0.0-alpha.1",
    "@rematch/immer": "^0.1.0"

Errors:
```js
Uncaught (in promise) TypeError: fe.default is not a function
    at t.(:3000/anonymous function) (http://localhost:3000/static/js/bundle.js:896:11752)
    at rematch-immer.umd.js:1
    at computeNextEntry (<anonymous>:1:34000)
    at recomputeStates (<anonymous>:1:34300)
```

When I:
```js
import { init } from '@rematch/core';
import immerPlugin from '@rematch/immer';
import regex from './regex';

const immer = immerPlugin();

const store = init({
  models: {
    regex,
  },
  plugins: [immer],
});

export default store;


// regex.js
import uuid from 'uuid/v4';

export default {
  state: {
    ID: {
      example: [],
      regex: {},
      result: {},
    },
    byID: {},
  },
  reducers: {
    addExample(state, payload) {
      console.log('payload');
      
      const ID = uuid();
      state.ID.example.push(ID);
      state.byID[ID] = {
        text: payload,
        regex: [],
      };
      return state;
    },
  },
  effects: {},
};

// App.js
const mapDispatch = ({ regex: { addExample } }) => ({
  addExample,
});

@connect(() => ({}), mapDispatch)
export default class App extends Component {
...
  render() {
    console.log(this.props.addExample());
...
}
```

**Comment by linonetwo** [comment]
Thrown from this:
```js
t[e[0]] = function(e, t) {
                                return "object" == typeof e ? **fe.default**(e, function(e) {
                                    n(e, t)
                                }) : n(e, t)
                            }
```
Which I think is this:
https://github.com/rematch/rematch/blob/2bcaf3d3ab9df2b5c905ac261fc7baa448a422cb/plugins/immer/src/index.ts#L12
Where ```produce``` from ```import produce from 'immer'``` is ```e.default```

**Comment by jackwilsdon** [comment]
How are you building this? I can't seem to reproduce it.

**Comment by linonetwo** [comment]
@jackwilsdon  Sure I can't produce it too, but in this example, the rematch seems don't work.
https://stackblitz.com/edit/react-ksr6xw

**Comment by sudheeshcm** [comment]
@linonetwo 
Did you figure out how to solve it?

**Comment by jackwilsdon** [comment]
@sudheeshcm how are you building your application? Do you have a reproducible example?

**Comment by linonetwo** [comment]
Trying again but still unable to use it:
"@rematch/core": "^1.0.0-alpha.4",
"@rematch/immer": "^1.0.1"

```TypeError: L.default is not a function```

**Comment by ShMcK** [comment]
It may be easier to stick with @rematch/core@0.6 & @rematch/immer 0.x for the time being. 

Until core is out of alpha.

**Comment by linonetwo** [comment]
But 
    "@rematch/core": "^0.6.0",
    "@rematch/immer": "^0.1.0",
Still throws ```TypeError: fe.default is not a function```

**Comment by jackwilsdon** [comment]
Looks like adding `"esModuleInterop": true` to the `immer` plugin's `tsconfig.json` fixes this.

This all seems to be caused by something weird that `immer` itself does; it exports an attribute called `default` containing the `produce` function. This seems to really confuse rollup when creating UMD modules.

You can see what's happening by comparing the source of the UMD modules;

#### Without `esModuleInterop`;

```JavaScript
function produce(...) {
  // some code here
}

var immer_module = /*#__PURE__*/Object.freeze({
  setAutoFreeze: setAutoFreeze,
  setUseProxies: setUseProxies,
  default: produce
});

var immer_1 = ( immer_module && produce ) || immer_module;

// some more code here

immer_1.default(...); // oh no! immer_1 is actually the produce function
```


#### With `esModuleInterop`;

```JavaScript
function produce(...) {
  // some code here
}

var immer_module = /*#__PURE__*/Object.freeze({
  setAutoFreeze: setAutoFreeze,
  setUseProxies: setUseProxies,
  default: produce
});

var require$$0 = ( immer_module && produce ) || immer_module;

var __importDefault = (commonjsGlobal && commonjsGlobal.__importDefault) || function (mod) {
  return (mod && mod.__esModule) ? mod : { "default": mod };
};

// this is the magic! a "default" attribute is returned containing the "produce" function
var immer_1 = __importDefault(require$$0);
```

I've not tried importing this elsewhere (i.e. the es6 and cjs builds), but the tests seem to pass fine.

I've opened #378 to add the `esModuleInterop` setting.

**Comment by linonetwo** [comment]
Cool, will you release a 0.1.1 version and a 1.0.2 version?

**Comment by huyansheng3** [comment]
i meet the same problem too! when will the bug fixed?

**Comment by jackwilsdon** [comment]
It looks like it has been released as v1.0.2 https://github.com/rematch/rematch/pull/378#issuecomment-389749025, which is the next major version of Rematch. @ShMcK would it be possible to backport this to v0.1 too?

**Comment by huyansheng3** [comment]
I try to fork rematch/immer， but it dont work well with immer 0.6. Maybe the only way is to use immer directly. if update, please remind me in the first time! Thanks!

**Comment by linonetwo** [comment]
@huyansheng3 Try ```@rematch/immer@next```

**Comment by jackwilsdon** [comment]
@linonetwo They'd have to update their rematch to `@next` too then, and it's still in beta I believe.

**Comment by huyansheng3** [comment]
Great!  @linonetwo 

rematch and rematch/immer update the next version solve the problem. thanks!
