### ISSUE TITLE
Problem testing effects in 1.0 alpha 2

### ISSUE THREAD

**Issue by tkivela** [rematch/rematch#350]
I have a problem when testing effects in 1.0 alpha 2.

The application works as expected in browser but when testing with Jest the state has not been updated after running the effect with await.

Problem can be seen in a test repo I setup for this issue: https://github.com/tkivela/rematcheffecttestproblem

(install packages with "yarn" and then run tests with "yarn test")

Problem comes in row https://github.com/tkivela/rematcheffecttestproblem/blob/f45c2f67ef794c63f0bec072be1eba5ebb5f816a/src/models.test.js#L78 

The effect should just add one object to state's notes array, the effect can be seen working if running the app ("yarn start") and clicking the "Add a latin note" button.

I've looked the test code a while but cannot see the problem could be in it, so I think the problem is in rematch or possibly some babel/jest configuration is needed (?). Anyone that could help with this?

Thanks! :)

**Comment by ShMcK** [comment]
The problem seems to be linked to the test finishing before the state is changed. 

The following below works. Give me a minute, and I may have a better solution.

```js
it('should work with effect which contains await', async () => {
    const store = init({
      models: { exampleModel }
    })
    await dispatch.exampleModel.addNoteAsync()

     // add a timeout
    await new Promise((resolve) => setTimeout(() => resolve(), 1000)) 


    const myModelData = store.getState().exampleModel
    
    expect(myModelData.counter).toEqual(0)
    expect(myModelData.notes.length).toEqual(1)
  })
```

**Comment by tkivela** [comment]
Thank you for a good answer! I think I might go with mocking approach then while I think mocking is not so good because I would like to rather have the test fail in case for example endpoint has changed rather than thinking everythings ok (I know it's more of an integration test, but anyways). I'll probably use axios-mock-adapter for mocking.

I'll close this for now,

**Comment by benpolinsky** [comment]
@tkivela - One way to handle this is to use separate operational tests to test the API endpoints, ensure they're functioning, and that their response(s) are formatted appropriately for your code.

It could even be the same tests that switch on or off real API calls depending on configuration/environment.
