### ISSUE TITLE
Selector Improvements [proposal]

### ISSUE THREAD

**Issue by JPTeasdale** [rematch/rematch#353]
I love rematch. It's drastically cut down the boilerplate overhead of working with react projects. But I think that there is room for improvement with the loading and selector plugins. 

## Selectors
I'll use the following model that just grows an array and returns a number:
```
export const numbers = {
  state: [], // initial state
  reducers: {
    appendNumber(state, payload) {
      return state.concat(payload);
    }
  },
  selectors: {
     sum: state => state.reduce((acc, curr) => acc + curr, 0)
  }
}
```

Currently, if I want to use this selector, I have to:

1. import the selector module in every file I use it from. 
2. Run the selector function in some sort of 'connect' function where I have access to the state variable. 

This feels like the kind of boilerplate that rematch was trying to avoid, where what I'd really like to be able to do is

```
const Sum = props => (<div>The sum is {props.sum}</div>)

const mapState = state => ({
  sum: state.numbers.sum()
})

const SumContainer = connect(mapState)(Sum)
```

The selector would be on the model itself, and would use the global store's main state by default. 

This ties into my problems with the loading plugin:

```
export const shoppingCart = {
  state: {},
  reducers: {
    set(state, payload) {
      return {
         ...state,
         ...payload
       }
    }
  },
  effects: {
    async create(payload, rootState) {
      try {
         await new Promise(resolve => setTimeout(resolve, 1000))
         this.set({created: true})
      } catch(e) {
         this.set({createError: true})
      } 
    },
    async addItem(payload, rootState) {
      await new Promise(resolve => setTimeout(resolve, 1000))
      this.set({items: payload})
    },
  },
  selectors: {
      shouldCreate: (state) => !state.shoppingCart.created && !state.shoppingCart.createError && !state.loading.models.shoppingCart
  }
}
```

With the proposed solution:

```
import {select} from '@rematch/select';
if (select.shoppingCart.shouldCreate(state)) {
   dispatch.shoppingCart.create()
}
```

Would become: (assuming a {...state, dispatch} style props object)
```
if (props.shoppingCart.shouldCreate()) {
   props.dispatch.shoppingCart.create()
}
```

Maybe this breaks some React rule that I'm not aware of, but I do believe this would simplify the use of selectors throughout the application. 

If there is some other method that I haven't considered, I'd love to hear it.

**Comment by blairbodnar** [comment]
Hi @JPTeasdale ,

Glad you're liking rematch, thanks! :) 

Yeah, there has been a lot of discussion around the selectors plugin. Have a read through #270 if you didn't see it already.

For me personally, after playing around with different selector approaches, I find that I just like to keep my selectors outside the models (https://github.com/rematch/rematch/issues/270#issuecomment-372547336). I don't find it too much boilerplate doing it that way.

The thread also throws around some different plugin ideas for the select plugin too - maybe something in there clicks better for ya. 

Hope that helps!
