### ISSUE TITLE
React Navigator Example Plugin Fail To Run

### ISSUE THREAD

**Issue by chongzheng1995** [rematch/rematch#354]
I created a new project and followed the demo of react-navigation plugin from this link below:
- https://github.com/rematch/rematch/tree/master/plugins/react-navigation

 However, I get this error: 

![error](https://user-images.githubusercontent.com/27880708/39665113-7e709386-50c1-11e8-8012-8a869627b7be.PNG)

According to my research on this error, I found this link below. Looks like the update on react-navigation on this February 3, 2018 might be affecting the "rematch-react-navigation-cjs.js" file.

Link: https://stackoverflow.com/questions/48804502/react-native-error-undefined-is-not-a-function-evaluating-addlistener

I apologize in advance if my issue is wrong somehow.

**Comment by ShMcK** [comment]
I'm also using the react-navigation plugin. 

It may be a version issue. This combination is working for me.

```json
  "@rematch/core": "^0.6.0",
  "@rematch/react-navigation": "^1.0.0",
  "react-navigation": "1.5.11",
```

**Comment by chongzheng1995** [comment]
Thanks man 💯 Updating the versions of the react-navigation to 1.5.11 does the trick here. Though I encountered a warning message "isMounted(...) is deprecated warning", it might be related to [this](https://github.com/react-navigation/react-navigation/issues/3956). Regardless, the real issue here is completed. Thanks again master @ShMcK !

**Comment by ShMcK** [comment]
I'm also having the "isMounted()" warning. Based on the link, it seems to be related to the version of React Native. 

If you're using Expo as well, always be sure to check the exact versions of React Navigation & React Native from blog.expo.io when it comes out.
