### ISSUE TITLE
IE11 error - Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by BerndWessels** [rematch/rematch#359]
IE11 error - `Object doesn't support property or method 'includes'`

In `rematch.prod.min.js` line 53
`var T=r(function(e,t){Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){return e.includes("/")}})`

This breaks IE11.

Since IE11 is still a requirement especially in the enterprise space it would be great if you could fix this.

I guess there is some babel or polyfill magic to fix it.

**Comment by ShMcK** [comment]
Currently using the TS compiler set to ES5, I'll look into ensuring it has proper polyfills. IE11 is not unreasonable.

In the meantime, polyfill.io has may be a quick fix: https://polyfill.io/v2/docs/features/.

**Comment by akshay0002** [comment]
# # # #439
