### ISSUE TITLE
getState() returns {0: ...state}

### ISSUE THREAD

**Issue by linonetwo** [rematch/rematch#360]
@rematch/core 1.0.0-alpha.4

```js
console.log(getState());
// {0: {filter: {…}, search: {…}, queryString: {…}}}
```
Why there is a ```0: ```?

**Comment by linonetwo** [comment]
And I can't get state in effects. Second argument is undefined.

**Comment by linonetwo** [comment]
And returned state don't have selector.

**Comment by ShMcK** [comment]
I'd recommend sticking to @rematch/core v0.x & @rematch/select v0.x

It should be sorted out soon, but will take a bit of time to get plugins on board with core 1.x.

**Comment by eric-burel** [comment]
`rootState` is undefined in effects for me too, I am trying to figure this out.

**Comment by linonetwo** [comment]
I'm using ```const { store } = await import('./');``` in model effects now.
What's the difference between this way and using ```getState()```?

**Comment by eric-burel** [comment]
I had issues with circular import using a similar pattern, the store was empty. Importing the dispatch, getState etc. functions directly from `@rematch/code` fixed it. Still not sure about why your syntax did not work for me precisely though.

**Comment by linonetwo** [comment]
@eric-burel  See https://github.com/react-cosmos/react-cosmos/issues/685 In my case, using ```await import()``` will fix circular import.

**Comment by kdela** [comment]
I'm also have the same issues (0 in getState() and empty rootState in effects)

```
    "@rematch/core": "^1.0.0-alpha.4",
    "@rematch/loading": "^1.0.3",
    "@rematch/select": "^1.0.0",
```

**Comment by ShMcK** [comment]
Thanks for pointing this issues out. 

I can tell this issue is related to a problem in global dispatch (aimed at supporting multiple stores). It's not capturing the right "state" within effects, and requires a fix.

If you strictly rely on the local store.dispatch, it would be a good work around, and leads to more modular code.

**Comment by ShMcK** [comment]
Will remove `getState` in the next version of rematch. See #446 for details.
