### ISSUE TITLE
getState question

### ISSUE THREAD

**Issue by bmealhouse** [rematch/rematch#362]
Based on `rematch` switching to a multiple store model, will `getState` sill be deprecated in v1?

**Comment by ShMcK** [comment]
In v1 `getState` can get state from all models as a keyed object.

I would recommend using `store.getState` though, if you require it.

It can always be accessed as

```js
const { getState, dispatch } = init()
export { getState, dispatch }
```

**Comment by bmealhouse** [comment]
Switching to `store.getState()` will work fine for us.

It was just confusing to me that `import {getState} from '@rematch/core'` is deprecated, when it still exists in the v1 API.

**Comment by ShMcK** [comment]
Currently not maintaining two sets of docs. Hopefully we can get v1 out the door soon.
