### ISSUE TITLE
Can't acces store in model to implement effect

### ISSUE THREAD

**Issue by eric-burel** [rematch/rematch#363]
Hi, I have some trouble accessing the store in a model (version 1.0.0-alpha.4).
I need to access the dispatch function in order to trigger an action depending on another model (e.g I want to open a toaster on API fail). However this creates some circular import, since my model needs to know about the store, but the store wants to load my model.
I definitely may have misunderstood something but I can't tell what, so I prefer to raise this as an issue.

I created a whole repo for repro: [https://github.com/lebrun-burel/demo-rematch-fail](https://github.com/lebrun-burel/demo-rematch-fail). You can check the `src/model.js` file. You can see in the log that `store` is undefined, and thus I don't manage to dispatch an action in my effect (not a local action, an action that may be defined in another model for example).

More globally I have some issues with circular dependencies, e.g if I want to dispatch an action when a service fails (so the store is imported by the service), and also to load this service in a model to implement an effect (so the service is imported by a model that is imported by the store). Either the store or the model comes to be undefined and the app fails.

**Comment by ShMcK** [comment]
If you need to dispatch to another model, you can always use:

```js
import { dispatch } from '@rematch/core';
```

Rather loading it from the store.

**Comment by eric-burel** [comment]
Thanks a lot I fought with this for an hour... Works perfectly. Maybe it would be better to present this syntax in the doc instead of `import store from './your-store.js`; const { dispatch } = store`? Because most of the time you'll import the store in a model or somewhere it will provoke a circular import.

**Comment by ShMcK** [comment]
Definitely. Any chance I could bother you to add a quick PR the way you think would avoid the most confusion? The simplest PR can be made from the edit button on Github.

**Comment by eric-burel** [comment]
Definitely, I am closing this in the meantime.

**Comment by eric-burel** [comment]
However I wonder how you would handle multiple store in this case. I had an electron app with 2 stores, one for the "back", one for the "front", but both lived in different process, I think importing dispatch from `@rematch/core` would still be ok. However you could not handle 2 stores in the same process. This is a rare use case I guess though.

**Comment by ShMcK** [comment]
I'll put some thought into a better way to simplify external model dispatches for v1. I agree, there should be a better way to capture dispatch without creating a circular dependency.
