### ISSUE TITLE
[TYPINGS] Conflict with redux connect mapDispatch

### ISSUE THREAD

**Issue by brunolemos** [rematch/rematch#365]
After adding autocomplete on the mapDispatch, redux complain about it, because our type adds `.myModelName` properties that redux doesn't recognize.

#### Error
`Property 'myModelName' is missing in type 'Dispatch<AnyAction>'.`

#### Code

```tsx
const mapDispatch = (dispatch: RematchDispatch<models>) => ({ // works great
  setDarkTheme: () => dispatch.myModelName.setTheme('dark'),
  setLightTheme: () => dispatch.myModelName.setTheme('light'),
})
```

```tsx
export default connect(mapState, mapDispatch)(MyScreen) // error above
```

### Workaround

```diff
-export default connect(mapState, mapDispatch)(SettingsScreen)
+export default connect(mapState, mapDispatch as any)(SettingsScreen)
```

**Comment by inDream** [comment]
Have you tried set `"strict": false` in `tsconfig.json`?

**Comment by brunolemos** [comment]
@inDream it didn't affect (also I'd like to keep it strict)

**Comment by ShMcK** [comment]
Has this issue been resolved?

**Comment by brunolemos** [comment]
@ShMcK no, I don't know if it's possible to fix without a cast (e.g. `as any`), because the `mapDispatch` function from rematch is different from the `mapDispatch` from redux because rematch add the models to it and they become incompatible.
