### ISSUE TITLE
Can I use rematch with react-apollo?

### ISSUE THREAD

**Issue by skout90** [rematch/rematch#366]
I consider using graphql that [react-apollo](https://github.com/apollographql/react-apollo)

can they be used together?

I saw redux migration Documnet. But I woder i could use pure rematch with react-apollo?

I'm in the process of learning React/Redux and so I'm not able to understand by myself the integration possibility.

this is my code!

- store.js
````
import { compose, createStore, applyMiddleware } from 'redux';
import reducer from './reducers';

import ApolloClient, { createNetworkInterface } from 'apollo-client';

const networkInterface = createNetworkInterface({
  uri: config.BASE_GRAPHQL_URL
});

export const client = new ApolloClient({
  networkInterface
});

function configureStore(initialState) {
  const enhancer = compose(
    applyMiddleware(
      client.middleware()
    ),
  );
  return createStore(reducer(client), initialState, enhancer);
}

export default configureStore({});
````

- reducers.js
````
import { combineReducers } from 'redux';

export default client => combineReducers(Object.assign(
  {apollo: client.reducer()},
  // redux reducers here
));
````

**Comment by ShMcK** [comment]
My understanding of, which may be helpful:
- v1 of Apollo Client was originally built on top of Redux
- v2+ of Apollo Client [no longer uses Redux under the hood](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/2.0-migration.md#replacing-redux). Instead, there is something called "Apollo Link"

You might find an easier path if you stick to Apollo conventions at this time.
