### ISSUE TITLE
How To trigger a reducer action from another model?

### ISSUE THREAD

**Issue by canyavall** [rematch/rematch#368]
Hi all, thx for this awesome library!!!

Could someone give me a live example on how to trigger an action in a Model B when I'm inside an action in Model A?

For me it is not clear in the documentation how to do it ^_^

**Comment by ShMcK** [comment]
This should work: 

```js
import { dispatch } from '@rematch/core'

const modelA = {
  effects: {
    callModelB() {
       dispatch.modelB.someAction()
    }
  }
}
```

**Comment by titouancreach** [comment]
I think this is better:

```
const modelA = {
  reducers: {
    doSomething(state) {
      return state;
    }
  },
  effects: {
    doSomethingEffect() {
       // side effect here
       this.doSomething();
    }
  }
}
```
And create a reducer in modelB called `modelA/doSomething`

**Comment by ShMcK** [comment]
I second @titouancreach's proposal. That's a brilliant way to keep everything bound to models.

**Comment by canyavall** [comment]
Thank youu!!! I'll do it this way ^_^

**Comment by grubstarstar** [comment]
do you mean this?? Will the reducers then respond to the `doSomething` action?

```
const modelB = {
  reducers: {
    "modelA/doSomething": state => {
      return state;
    }
  },
```
