### ISSUE TITLE
Loading demo link in the doc is dead

### ISSUE THREAD

**Issue by eric-burel** [rematch/rematch#370]
Hi, on the loading plugin doc ([https://rematch.gitbooks.io/rematch/plugins/loading/](https://rematch.gitbooks.io/rematch/plugins/loading)) the example link is dead right now:[https://rematch.gitbooks.io/rematch/plugins/loading/examples/react-loading-example/](https://rematch.gitbooks.io/rematch/plugins/loading/examples/react-loading-example/).

My `state.loading.effects` and `state.loading.models` are empty right now, hence my willing to check the doc example.

**Comment by ShMcK** [comment]
Will fix... Thanks :)
