### ISSUE TITLE
Support for react-navigation v2

### ISSUE THREAD

**Issue by taranda** [rematch/rematch#374]
React Navigation v2 [changes the way react-navigation integrates with redux](https://v2.reactnavigation.org/docs/en/redux-integration.html).
`addNavigationHelpers` is no longer used in react-navigation and `createNavigationReducer`is now available which eliminates the need to pass an `initialScreen` config. 

In order to be compatible with React Navigation v2 `rematch/plugins/react-navigation/src/Navigation.tsx` should be changed as follows:

```
export default (Routes, addListener, sliceState) => {
  class Navigator extends React.Component<Props> {
    public render() {
      return (
        <Routes navigation={{
          addListener,
          dispatch: this.props.dispatch,
          state: this.props.nav,
        }} />
      )
    }
  }
```

However, this change will not be compatible with react-navigation v1.

What do you think is the best way to make the plugin compatible with both?   Should we use a conditional?  Create a second plugin for react-navigatio v2?

**Comment by ShMcK** [comment]
I believe once Expo moves to v2, it should be alright to update the plugin to v2 as well. Currently Expo is recommending to use exactly 1.5.11.

It can be noted in the docs which versions support 1.5.x and 2.x.

If you or anyone would like to adjust the plugin to support v2 in the meantime, it can be published semantically.

**Comment by taranda** [comment]
I'll work on a PR this week.

**Comment by ShMcK** [comment]
@taranda, there is a promising PR as #415 if you'd like to have a look.
