### ISSUE TITLE
Deprecating the subscriptions plugin results in a loss of functionality

### ISSUE THREAD

**Issue by taranda** [rematch/rematch#376]
The subscriptions plugin provides some functionality that is not available via the `reducers: 'otherModelName/actionName': ...` API:

1. Reducers only have access to the owning model's state slice while subscriptions have access to the entire state tree.  There may be times when having access to the global state within a subscription is desirable.  I have use cases where the value of the  `otherModel`'s state affects how I adjust the current model's state.

2. By design, reducers cannot dispatch effects, but subscriptions can.  I have not tested this myself, but I can foresee the utility of dispatching asyc actions from a subscription.

Therefore, I recommend against deprecating the subscriptions plugin in version 1.0.0.

**Comment by taranda** [comment]
How do I define an effect with the `'otherModelName/actionName': ...` notation?  I can't seem to make it work.

**Comment by 19majkel94** [comment]
@ShMcK 
I am bumping this issue as I also need to do an effect based on subscription from 'otherModelName/actionName'. 
```ts
{
  reducers: {
    datagenFetched(state, payload: Datagen) {
      return payload;
    },
  },
  ['auth/userLoggedIn'](state) {
    dispatch.datagen.loadDataGen();
    return state;
  },
}
```

As you can see, doing this in reducers doesn't make sense as you need to return a state, so no async functions + side effects.

I've tried move it to `effects` but I got this error:
`Invalid effect name (datagen/auth/userLoggedIn)`

**Comment by 19majkel94** [comment]
@ShMcK 
It's even worse, the reducer workaround doesn't work in all. I got this error:
```
Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
```
Because my subscriptions calls dispatching effect and the effect is then calling reducer to set the state.

**Comment by d3dc** [comment]
I'm going through this debate too.  At the end of the day, models represent the reducers - "this model changes state in response to these events". Effects are a way to group those state changes.

I think Subscriptions as a plugin give you a place to define a wholly different event consumer.

But to play devils advocate: Do you really need that inversion? (e.g. dynamic loading?)

Why not just have a model for coordinating effects?
```js
const appModel = {
effects: {
  async loginToApp(...args) {
    const success = await dispatch.auth.login(...args)
  
    if (success) {
      dispatch.data.loadDataGen()
    }
  }
}
```

**Comment by linonetwo** [comment]
@d3dc How about loading data according to route change?
We want data loading logic being separated into different models, and those models can listen to `connected-router`'s action.

**Comment by ShMcK** [comment]
I think if you want to load data based on a route change, that logic may be best suited in one place, likely within a router model.

**Comment by d3dc** [comment]
@linonetwo My two cents on listening to routing in particular is "Don't".
Redux is a loop. The view effects the state and the state is connected to the view.

You're introducing side effects to route changes that further mutate the state. Maybe you can argue that this is just further grouping effects, but I think then you also have to put a lot of UI state into the global store.

Consider having a loading spinner. You could have an `AsyncRoute` component that subscribes to a promise. Its state is entirely within the component and while loading it can display a different component. Now consider doing that purely in the store; you would have to handle the state where data isn't there by either setting a loading flag, or handle null data as a loading state in the component consuming the data.

**Comment by linonetwo** [comment]
@ShMcK I discuss this with my colleague, we agree with you. But even we put all that "load data on route change" logic in one store, we still need a subscription on history (we are currently using this approach), or a subscription on `connected-react-router`'s action.

This is what I'm currently using:
```js
// ./store/index.js
const { store, history } = configureStore();
export { store, history };

history.listen(async location => {
  await followURI(location);
});
followURI(history.location);
```
Where `followURI` is subscripte on route change, and load data based on a route change.
```js
// ./store/history.js
export async function followURI(location: { pathname: string, search?: string, state: any }) {
  const {
    store: { dispatch, getState },
  } = await import('./');

  // if it's store's effect that loading data and push to ?page=2 , causing route change, we won't load data again due to this route change. Only when user is refreshing page, we load data accroading to current route

  if (location?.state?.isFromEffect !== true) {
    const { page: pageString } = queryString.parse(location.search);
    const page = Number.isInteger(Number(pageString)) && Number(pageString) >= 1 ? Number(pageString) : 1;
    const state = await getState();

    if (location.pathname === '/blocks/') {
      return dispatch.block.getBlocksList(page);
    }
    if (/\/transaction\//g.test(location.pathname)) {
      const nextTransactionId = location.pathname
        .split('/transaction/')
        .pop()
        .replace('/', '');
      if (nextTransactionId !== state.transaction.data.transactionId)
        return dispatch.transaction.getTransactionData(nextTransactionId);
    }
   // more if statement...
}
```
You may wonder why there is a `location?.state?.isFromEffect`. It's from `updateURI`. When user click on [table](https://ant.design/components/table/)'s pagination button, it trigger an effect to load data of page 3, and in that effect, I need to call `dispatch.history.updateURI()` to update query string in URI to `?page=3`:
```js
// ./store/history.js
effect: {
  async updateURI(queryOverride?: Object) {
      const {
        store: { getState },
        history,
      } = await import('./');
      const state = getState();
      if (history.location.pathname === '/blocks/') {
        const query = queryString.stringify({
          ...queryString.parse(history.location.search),
          page: state.block.pagination.current,
        });
        history.replace(`/blocks/?${query}`, { isFromEffect: true });
      } else if (history.location.pathname === '/transactions/') {
        const query = queryString.stringify({
          ...queryString.parse(history.location.search),
          page: state.transaction.pagination.current,
        });
        history.replace(`/transactions/?${query}`, { isFromEffect: true });
      }
    // more else if
    },
```

So if a page is refreshed, or user is navigating to a new route by clicking <Link /> in NavBar, `followURI` needs a subscription on route.
Even all these logic is in a single model, I still need a subscription.

**Comment by linonetwo** [comment]
@d3dc  I think clicking <Link to="/block" /> is a thunk: action notify browser history that it should change, and an effect is dispatched to load data.

Oh, I think all these worries and complexity will go if I'm using GraphQL. Then GraphQL will work as a view model to handle data loading. Only a few things should go into `rematch`'s model.

**Comment by d3dc** [comment]
@linonetwo I think you confuse "side-effect" and "effect". This is, again, redux.

Regarding your solution listening to history, I think you just reinvented the wheel. 😅 

There's this great library designed to contextually mount listeners to fragments of the current history location. Its called `react-router`. You can use the function `Route`, and nest it inside other calls to `Route`. When its `path` property matches the current `history.location` it will run the function passed to it.

GraphQL works so well because Apollo provides an `AsyncRoute` 😉 (`ApolloProvider`)

**Comment by ShMcK** [comment]
On that note, I highly recommend [reach router](https://reach.tech/router).

**Comment by DrakeXiang** [comment]
> I think if you want to load data based on a route change, that logic may be best suited in one place, likely within a router model. As mentioned by @d3dc this model could control the actions dispatched.

This could easily bloat the router model file as the routes number grows. and when multiple changes were made by different people, the git diff could be horrible., although the 'hard to debug' problem is true when separate these subscriptions..

**Comment by d3dc** [comment]
@DrakeXiang if your routing is complex, perhaps you should have more than one model.

I don't see the need for any routing models, really.

Route changes can be side-effects in an effect; the resulting view can then request the data it needs - **separating its concerns from the store's**.

**Comment by ghalex** [comment]
I have this example were I need to dispatch an action, do you guys have any suggestion how to do this:

`
reducers: {
    'replaceTodos': (state, payload) => {
    },
    'app/switchUser': (state, user, store) => {
      if (unsubscibe) unsubscibe()

      unsubscibe = firestore
        .collection('todos')
        .where('owner', '==', user.uid)
        .orderBy('createdAt')
        .onSnapshot((snapshot) => {
          const todos = {}
          snapshot.forEach(doc => {
            todos[doc.id] = {...doc.data(), id: doc.id}
          })

          // dispatch ACTION here like dispatch.todos.newTodos(replaceTodos)

        })

      return state
    }
  }
`

**Comment by linonetwo** [comment]
@ghalex  Are you in `todo` store? Why not just `this. replaceTodos(todos)`.

**Comment by ghalex** [comment]
Hi @linonetwo I am in todo model, but this is null as expected. I think best solution will be if I can do this in effects where I have access to dispatch, it dose'n work there.

**Comment by ghalex** [comment]
I think I can write the code like this:

```
'app/switchUser' (state, user, store) {
      console.log('this', this)
      return state
    }
```
and have access to `this` but still feels like a hack.

**Comment by linonetwo** [comment]
I think you should move it into `effect` just likes

```js
reducers: {
    changeNavTab(state: Store, nextNavTab: string) {
      state.navTab = nextNavTab;
      return state;
    },
  },
  effects: {
    /** set nav tab heightlight */
    async updateNavTab() {
      const { history } = await import('./');
      const mainPath = history.location.pathname.split('/')?.[1];
      if (blockChainPath.includes(mainPath)) {
        this.changeNavTab('blockChain');
      } else if (mainPath === 'producer') {
        this.changeNavTab('producers');
      } else {
        this.changeNavTab(mainPath || 'home');
      }
    },
  },
```

Or you can access `store` by:
```js
  const {
    store: { dispatch },
  } = await import('.');
```

And I think you are off-topic, why is this related to `subscriptions plugin`?

**Comment by d3dc** [comment]
@linonetwo This is related to subscription because it is a side-effect chained to another model's action.

@ghalex question really relates to reacting to an internal store model change, not an external source of flux - which IMO is what routing is; routes should just trigger effects (i.e. a full render loop).

I'll try to edit this post with a code example showing how I interpreted what the state transitions over time were.

**Comment by ghalex** [comment]
It is releated to subscription plugin, because I think we should be able to use the subscription plugin like this:

```
{
  name: 'settings',
  state: {},
  reducers: {
    set: (payload) => payload
  },
  subscriptions: {
    'profile/load': (rootState, payload, dispatch) => {
      dispatch.settings.set(action.payload)
    }
  }
}
```

and  I think is much more clear to see the listeners in a subscription area then in the reducers.

**Comment by d3dc** [comment]
![https://camo.githubusercontent.com/655fdfe6e77bf59fde4623dc77a0e8962f6effa5/687474703a2f2f692e696d6775722e636f6d2f4e4a574c58487a2e706e67](redux loop)
I've stolen this image from [redux-loop](https://redux-loop.js.org/); The least troublesome way to do redux is with unidirectional flow, and this should illustrate the same basic idea rematch effects follow. 

If you aren't comfortable with scheduling effects from reducers, there's really only one other place that makes sense to schedule them - a component. A really popular way to request data is using [relay](https://facebook.github.io/relay/). You'll notice subscriptions to the server data store happen as a rendered component. This allows you a few advantages IMO, one of them being that it decouples you from the login event and instead will pre-fetch data only when a specific container is visited.

**Comment by taranda** [comment]
I'll renew my request to keep subscriptions in Rematch.
