### ISSUE TITLE
plugin sequence will occur some error ! 

### ISSUE THREAD

**Issue by huyansheng3** [rematch/rematch#380]
```
const select = selectorsPlugin()
const loading = createLoadingPlugin({})
const immer = immerPlugin()
const persist = createRematchPersist({
  throttle: 1000,
  version: 1,
})

const store = init({
  plugins: [immer, select, loading, persist],
  models,
  redux: {
    devtoolOptions: {},
  },
})
```

when i put immer on the first place, some error accor! but i move it to the last! it works ok!

so maybe you should to reminder this for us.

**Comment by jackwilsdon** [comment]
What's the error you get when doing this?

**Comment by huyansheng3** [comment]
![image](https://user-images.githubusercontent.com/11534583/40286417-58654d66-5cd9-11e8-999e-04f126b9f33d.png)
@jackwilsdon 

i dont know why in development mode, the rematch is the prod.mini.js ,so  i can figure out the error.

**Comment by jackwilsdon** [comment]
This sounds like #349 to me.

**Comment by huyansheng3** [comment]
@jackwilsdon  OK ,the same problem. closed.
