### ISSUE TITLE
remacth select usage !

### ISSUE THREAD

**Issue by huyansheng3** [rematch/rematch#381]
why i need to give the state as params explicitly, then get the selector.

why it dont like a computed property, just use the selector. no need to use store.

Maybe i need to use store anyWhere, but i just want use selector.

is an Anti-pattern ?

**Comment by blairbodnar** [comment]
Hi @huyansheng3 

Yes, this question has come up a lot. I too feel the same way, and we have discussed it s lot in #270. For me personally, I am no longer using the selectors plugin anymore. I just like to keep my selectors outside the models (#270 (comment)). I don't find it too much boilerplate doing it that way. I think in the future we'll look to rewrite the selectors plugin.

Thanks!

**Comment by huyansheng3** [comment]
Great.  i am expect the future version selector plugin .
