### ISSUE TITLE
Use with react-router-redux

### ISSUE THREAD

**Issue by M1chaelChen** [rematch/rematch#384]
Having some issues when trying to use` rematch` with `react-router-redux`.

I have created a store like this
```
import { routerReducer } from 'react-router-redux';
import { routerMiddleware } from 'react-router-redux';
import createHistory from 'history/createBrowserHistory';

import models from '../models';

export default init({
  models,
  redux: {
    reducers: {
      router: routerReducer
    },
    middlewares:[routerMiddleware(createHistory())],
  },
});
```
Then I can get the router object from redux store, which means the reducer is working.
![image](https://user-images.githubusercontent.com/19735641/40517131-920c2454-5f68-11e8-8463-a7a8d873c348.png)

When I tried to dispatch `push` like below, the url is changed in the browser. But the router object in redux store remains the same, and the page is not redirected.
```
import { dispatch } from '@rematch/core';
import { push } from 'react-router-redux';

dispatch(push('/test'));
```
I'm not sure whether this is caused by `rematch` or `react-router-redux`.

**Comment by wojciech-bilicki-oke** [comment]
Please specify the version of rematch. I am also using `react-router-redux` and all is fine with `rematch` on `1.0.0-alpha.2`.

**Comment by M1chaelChen** [comment]
@wojciech-bilicki-oke Here is my `rematch` and `react-router-redux version` version
`"@rematch/core": "0.6.0"`
`"react-router-redux": "5.0.0-alpha.9"`

**Comment by M1chaelChen** [comment]
I fixed this by using `push` from history object instead of from`react-router-redux`
```
props.history.push('/');
```
