### ISSUE TITLE
Instructions on developing against non-minified code

### ISSUE THREAD

**Issue by rheng** [rematch/rematch#388]
Hi,

I think this project is great, and I really like how it is extensible using plugins! I'm try to develop my own plugin, but it is very difficult since by default, the core code is minified. Would it be possible to provide some guidance on how to develop against the source-mapped files? For instance, how would you step through rematch code from a app bootstrapped from create-react-app?

Thanks!

**Comment by ShMcK** [comment]
I think you've identified a problem that just needs to be resolved. Currently "dev" and "prod" builds are using the minified version, and this needs to be fixed.

I'll put out an alpha 6 version today pointing to the unminified code, and hope that helps.

**Comment by rheng** [comment]
Wow, thanks for the quick response! Looking forward to checking it out!

**Comment by ShMcK** [comment]
released as @rematch/core@1.0.0-alpha.6
