### ISSUE TITLE
Complex examples

### ISSUE THREAD

**Issue by metakermit** [rematch/rematch#390]
I like the framework concept. Are there perhaps any examples out there of actions / effects spread out across multiple files? It would be nice if the framework supported some way to *register* actions, effects or even parts of the model in different parts of the codebase. For example:

```js
// myReducer.js
import {reducer} from '@rematch/core'
function myReducer(state, payload) { ... }
// register this reducer and somehow bind it to the state
reducer(myReducer)
```

This way it wouldn't be necessary to hand-collect everything manually into a giant object. Of course, it would be possible to create something like this manually in every project, but if the goal is to reduce boilerplate, I think it would be nice to offer some "opinionated" way to easily manage larger projects.

BTW, I can't get to the examples [in the docs](https://rematch.gitbooks.io/rematch/#examples). The url always takes me to the table of contents.

**Comment by williamconnolly** [comment]
Yeah, I'm absolutely loving how this made Redux easy to integrate. However, it took probably just about as much time to piece together the differences between typescript examples and the react example (that still imports "rematch-x", I guess an outdated name. 

Keep doing what y'all are doing, you're making a kick ass module and I hope I can contribute some day as I get more versed in frontend.

**Comment by ShMcK** [comment]
Thanks @metakermit - I've put a fix in for the examples link.

And @williamconnolly - I've also updated the count README, which was outdated.

**Comment by ShMcK** [comment]
In reference to importing reducers, it might to helpful to note:

- You can trigger reducers/effects in other models
- To reuse reducers or effects you can spread them. They are really just objects

```js
const commonReducers = {
  set(state, payload) {
    return payload
  },
}

const otherModel = {
  reducers: {
    ...commonReducers,
  }
}
```

**Comment by williamconnolly** [comment]
@ShMcK in your updated example, you follow a similar pattern as elsewhere in the docs, with mapDispatchToProps. Is this strictly necessary? 

Since dispatch.modelName.reducerName(...) can be called from anywhere in the code, what's the purpose of providing those methods as props to the main Component?

I've been following the pattern, but I have a subcomponent of my main one, and have been passing IT props with those dispatch methods. Why not simplify it and have every dispatch-interaction be a global dispatch.model.reducer(...) call?

**Comment by ShMcK** [comment]
@williamconnolly I think there's danger in globals, especially when you try to scale your project. For example, you may want to use multiple stores for both organization & performance reasons.

I would consider the global dispatch to be a last resort / hack to get things done.

**Comment by williamconnolly** [comment]
I'm new to the Redux pattern in general. @ShMcK does it make sense to ever have a Model defined thats deeply nested in the overarching, main model? 

i.e. I have the main model, Links. Links have {...variables}, variables have {...values}... etc. My reducer methods are starting to get pretty tedious. I dont know if it is an anti-pattern to have a reducer of one model call a reducer in another... but that would greatly simplify my code.

**Comment by ShMcK** [comment]
I can give a few tips off the top of my head.

##### State Machines
Might be best to start with some basics on how and why "state machines" are useful. Redux was intended to be used as a state machine, but its commonly just used as a way to store and sync data.

If you can shift your focus from "data" to "states", I think you'll find a lot of benefit. The more you can thoroughly plan out the states you need before coding, the better. 

##### Don't Redux All the Things
Data doesn't need to be stored in Redux a lot of the time, it can live in a components state, or in a Context wrapper. Is it being reused in multiple places? No, then no need to use Redux.

##### Flat Models/Reducers
I would avoid having reducers with state that is more than 1 or 2 levels deep. It results in terrible performance with `connect`, and overly complicated reducers.

##### Normalize Your Data
Try to make any data you store in Redux to be objects keyed by id.

##### Don't be afraid to change Database Data & Stored Data
If your data is deeply nested from the server, you can always flatten it for the client. There's a pattern of "serialize" and "deserialize"-ing incoming/outcoming data that may be worth investigating if you aren't in a position to change the API.

##### Break Rules
It's not a great idea to have a reducer call another reducer in another model. But whatever, just get the job done. I'd take code that works over code that grows convoluted and confusing just to ensure it is 100% modular.
