### ISSUE TITLE
rootState is undefined in effects

### ISSUE THREAD

**Issue by lext-7** [rematch/rematch#392]
version: 1.0.0-alpha.6

**Comment by klaemo** [comment]
It looks like this started happening in `alpha.4`. I downgraded version by version and `alpha-3` is where `rootState` still gets passed correctly.

**Comment by lext-7** [comment]
By the way, in `0.5.3`, I can get effects returns. But in ` 1.0.0-alpha.6`, nothing returns.

**Comment by ShMcK** [comment]
I wrote a unit test to test this out, but it seems to be passing. [See test](https://github.com/rematch/rematch/blob/fix/effects-rootstate/test/globalDispatch.test.js#L162-L186).

If you get a chance, could you demonstrate the issue in a test, and I'd be happy to put in a fix.

**Comment by lext-7** [comment]
Just upgrade `@rematch/core` version to `1.0.0-alpha.6` in https://github.com/rematch/rematch/blob/master/examples/react/count/package.json. 

Then add rootState console in https://github.com/rematch/rematch/blob/master/examples/react/count/src/models.js#L7, `undefined` will be the result.

**Comment by scientist1642** [comment]
This happens in 1.0.0-alpha.4 as well for me, ONLY if remote debugging is enabled. Might be related.

**Comment by lext-7** [comment]
Is there any solution to fix it @ShMcK ?

**Comment by ShMcK** [comment]
I'll look into it now.

**Comment by ShMcK** [comment]
Fix should be released for alpha.9 within the hour.
