### ISSUE TITLE
How can I await another model's effect?

### ISSUE THREAD

**Issue by buruss** [rematch/rematch#393]
If I call another effect inside an effect of same model, it returns promise normally,
But If I call an effect of **another model** it returns **undefined**. 

dolphins.ts example

`effects: {

    async incrementAsync() {

      await dispatch.sharks.incrementAsync(5); // <--- do not await

      console.log('dolphin effect'); // <-- this line is executed before sharks.incrementAsync completes.

    },
`

How can I await another model's effect? 
Is there any other way I should try?

I'm using 1.0.0-alpha.5.

**Comment by alozytskyi** [comment]
Did you try alpha.7?

**Comment by buruss** [comment]
Just upgraded to alpha.7 and tested.
But I got the same results though.

**Comment by d3dc** [comment]
@buruss How is incrementAsync implemented? Is it definitely an async function?

`this` and `dispatch['sharks']` are the same object and should work the same: https://codesandbox.io/s/ql6m574l84

**Comment by d3dc** [comment]
@hvsy In your example, you're using the global dispatch `import { dispatch } from '@rematch/core'`

take a look at what that does:
```js
export const dispatch = (action: R.Action) => {
  for (const storeName of Object.keys(stores)) {
    stores[storeName].dispatch(action)
  }
}
```

I'm guess @buruss  posted this a few days before the new effects landed (#399). With the function form of effects, the dispatch that is injected will return a promise.

**Comment by hvsy** [comment]
@d3dc Thanks for reply
I build a test for 1.0.0 alpha (https://codesandbox.io/s/9415nyw2zo)
The global dispatch function return the same result, still undefined. 
If was designed purposely like this.
It is a  breaking change.

**Comment by d3dc** [comment]
@hvsy It is a breaking change. The dispatch code I posted is from the latest alpha. Prior to 1.0, there was only one store, so the library just exported that dispatch.

If you use `connect()`, it receives `store.dispatch` and I think is somewhat cleaner to use over importing the global dispatch.

**Comment by buruss** [comment]
@d3dc 
With 1.0.0.alpha.9, now it works as I expected.
Thank you for your support.
