### ISSUE TITLE
Problems when using both the immer and persist plugin

### ISSUE THREAD

**Issue by grsmvg** [rematch/rematch#395]
# Tested using versions:

```
    "@rematch/core": "^1.0.0-alpha.5",
    "@rematch/immer": "^1.0.2",
    "@rematch/persist": "^1.0.2",
    "redux-persist": "^5.9.1"
```

# Problem:

### When using plugins in this order:

`[persistPlugin, immerPlugin]`

This error is thrown:

```
Error: Given action "categories/loaded", reducer "categories" returned undefined. To ignore an action, you must explicitly return the previous state. 
```

**This is a sign that the immer plugin is not working**

---

### When using plugins in this order:

`[immerPlugin, persistPlugin]`

Bootstrapped always stays false in this piece of code:

```
<PersistGate persistor={persistor}>
    {bootstrapped => <App />}
</PersistGate>
```

**This is a sign that the persist plugin is not properly doing it's job**

Would be awesome if this could get fixed. It's the only thing that's preventing me from using this in a soon-to-be live project, since it feels pretty stable.

**Comment by grsmvg** [comment]
Bumping this, since this is a valid bug that shouldn't be lost in between the closed issues. I haven't tested if the stable release also has this bug, but I assume so, since there hasn't been any activity here.

**Comment by firofame** [comment]
I can confirm that is not working in "react-native": "0.59.5" with "@rematch/core": "^1.1.0", "@rematch/immer": "^1.1.0", "@rematch/loading": "^1.1.3", "@rematch/persist": "^1.1.6", with the following order:

`import { init } from '@rematch/core';
import immerPlugin from '@rematch/immer';
import createRematchPersist from '@rematch/persist';
import createLoadingPlugin from '@rematch/loading';
import * as models from '../models';
import AsyncStorage from '@react-native-community/async-storage';

const immer = immerPlugin();
const loading = createLoadingPlugin({});
const persistPlugin = createRematchPersist({
  key: 'root',
  whitelist: ['app'],
  storage: AsyncStorage,
  version: 1,
  debug: true,
});

const store = init({
  models,
  plugins: [persistPlugin, immer, loading],
});

export const getState = () => {
  return store.getState();
};

export default store;
`

**Comment by wssjq198913** [comment]
I have the same issue,  does anyone have a workaroud?

**Comment by pjamrozowicz** [comment]
@wssjq198913 I would suggest waiting for the version 2 to be released, I fixed this bug there: https://github.com/rematch/rematch/pull/720

**Comment by snipebin** [comment]
@wssjq198913  I resorted to using [immer](https://immerjs.github.io/immer/) directly instead of `@rematch/immer` and so far works without problems. Notice the use of `produce` on example below:

my-tabs-model.ts

```
import { createModel } from '@rematch/core'
import produce from 'immer'
...

export const tabs: ModelConfig<TabsState> = createModel({
  state: {} as TabsState,
  reducers: {
    add: (state: TabsState, payload: CustomerTab): TabsState => produce(state, draftState => {
      draftState[payload.chromeTabId] = payload
    }),
...
```

store.ts

```
import { init, RematchRootState } from '@rematch/core'
import createRematchPersist from '@rematch/persist'
import selectPlugin from '@rematch/select'
...

const store = init({
  models,
  plugins: [persistPlugin, selectPlugin()]
})
```

**Comment by Coder-JJ** [comment]
try this out: [rematch-immer-combine-persist](https://github.com/Coder-JJ/rematch-immer-combine-persist)
