### ISSUE TITLE
Support `redux-thunk` like effects

### ISSUE THREAD

**Issue by d3dc** [rematch/rematch#396]
[A better API got merged!](https://github.com/rematch/rematch/pull/399)

---

@ShMcK I've been reading a few issues such as #363. I'm not a fan of importing `dispatch` from a module, it makes me worry about the setup for testing and SSR.

I think it might make sense to support an API like `redux-thunk` in effects:
```js
const model = {
  state: 0,
  reducers: {
    add: (state, amt) => state + amt
  },
  effects: {
    addAndNotify: function (amt) {
      return async ({ notify }) => {
        await notify.showToast({ message: `Adding ${amt} in 5...`, timeout: 5000 })
        this.add(amt)
      }
    }
  }
}
```

**Comment by ShMcK** [comment]
I definitely agree, `this` as dispatch, or importing dispatch both seem hacky.

Other ideas have been suggested, including below:

```js
{
  effects: (dispatch) => ({
     addAndNotify: function (amt) {
        await dispatch.notify.showToast({ message: `Adding ${amt} in 5...`, timeout: 5000 })
        this.add(amt)
      }
    })
  }
}
```

Ideally, a solution would resolve both external and internal model dispatches. What are your thoughts on this proposed API?

**Comment by d3dc** [comment]
I think your proposed API is pretty great (the one I missed 😛). I followed the discussion on re-usable reducer logic, and I think this touches the other side of that; composing effects. Dispatch probably should be passed as an argument to avoid awkward api differences and passing `this.getDispatch()` a lot.

Putting dispatch first makes it very explicit what effects should be doing.

---

 I haven't thought too much about how you could modify effects after they are bound, but
while rewriting an app, I found myself creating a store model for its `catchError` effect and then a plugin to catch all effects and dispatch that one.

Being able to wrap effects could be an interesting way to go:
```js
const handleErrors = reason =>  effectsCreator => dispatch => {
  const effects = effectsCreator(dispatch)

  for (const effectName of Object.keys(effects)) {
    const effect = effects[effectName]
    effects[effectName] = async (...args) => {
      try {
        return await effect(...args)
      } catch (e) {
        logError(e, reason)

        if (error.response && error.response.status == 403) {
          dispatch.auth.logout()
        }
        
         dispatch.notify.showErrorToast(reason, e)
      }
    }
  }

  return effects
}

{
  effects: handleErrors('Something went wrong...')(
    dispatch => ({
      addAndNotify: function (amt) {
          await dispatch.notify.showToast({ message: `Adding ${amt} in 5...`, timeout: 5000 })
          this.add(amt)
      }
    })
  )
}
```

**Comment by d3dc** [comment]
After playing around with trying to build some larger models with this, I still see some value in this being both optional and something that can be composed at the individual effects level; thunks still feel like a good fit to me.

I started playing around with nesting thunks and quickly got lost in a sea of async wrappers. Maybe it would be best just to have a very long (or grouped) arguments list:

```js
const updateBook = async (book, state, a$, d$) => {
  d$.notify.showToast('updating ${book.name}')
  a$.bookUpdated(await api.books.saveBook(book))
  d$.notify.showToast('${book.name} was updated') 
}

...

const catchWith = (effect, ...catchers) =>
  catchers.reduce((inner, catcher) => (
    async (...args, a$, d$) => {
      try {
        return await inner(...args, a$, d$)
      } catch (error) {
        return catcher(error, ...args, a$, d$)
      }
    }
  ), effect)

...

const model = {
  ...
  effects: {
    updateOwnedBook: catchWith(updateBook, displayError('Error updating your book')),
    updateLibraryBook: catchWith(updateBook, checkoutBook, displayError('Error updating a library book'))
  }
}
```

**Comment by d3dc** [comment]
@ShMcK I was trying to get really DRY with my other comments, and they probably went a little wide. Consider the simplest case - I want to include common functionality like I can for reducers:
```js
reducers: {
   ...commonReducers,
   renamedReducer: otherReducer,
   custom: ...
}
```

With the model-level API, spreading objects works fine, but doing `renamedReducer` would require a wrapper to create the effect.

**Comment by ShMcK** [comment]
@d3dc you've given a lot of great and varied ideas here. 

I may start using your `catchWith` implementation in my own code.

I'm not sure how effects might end up working, you've brought up several good options. As this weekend is going to be all rain, I hope to spend some time exploring a cleaner API for effects.

**Comment by ShMcK** [comment]
I put together a quick PR proposal for fixing effects, see #399.

**Comment by d3dc** [comment]
@ShMcK Someone pointed out that I could just use the promise API. And I guess they are right...
```js
effects (dispatch) {
  return {
    updateLibraryBook: async (book) => {
      dispatch.notify.showToast('updating ${book.name}')
      await api.books.saveBook(book)
        .then(({ data }) => this.bookUpdated(data))
        .catch(() => this.checkoutBook(book))
        .catch((error) =>
          dispatch.notify.displayError({ error, reason: 'Error updating a library book' })
        )
      dispatch.notify.showToast('${book.name} was updated') 
    }
  }
}
```
