### ISSUE TITLE
Incorrect `effect` method signature in `ExtractRematchDispatcherAsyncFromEffect`

### ISSUE THREAD

**Issue by 19majkel94** [rematch/rematch#397]
In `ExtractRematchDispatcherAsyncFromEffect` we have
`E extends (payload: infer P, meta: infer M) => Promise<void> ? RematchDispatcherAsync<P, M> ` but `Model` assumes that `effect` should have signature `(payload: any, rootState: any)`:
```ts
effects?: {
    [key: string]: (
      this: { [key: string]: (payload?: any, meta?: any) => Action<any, any> },
      payload: any,
      rootState: any
    ) => void,
  },
```
Which incorrectly create the `Action<P, M>` function argument.

**Comment by ShMcK** [comment]
Thanks @19majkel94 

I believe this may be correct. Unfortunately, typings are not my strong suit. I'll dump my thoughts below:
- In this case, RematchDispatcherAsync refers to the typing of `dispatch`
- But inside of a model, effects accept params of `(payload, rootState)`

If you have any suggestions on improving typings, PRs are always welcome :)

**Comment by 19majkel94** [comment]
Yes but the `rootState` parameter is used as a `meta` parameter in this type, so it produce the return type like `{ payload: TPayload, meta: RootState }`.

The main case is that `dispatch.myModel.myEffect()` return the same data as `myEffect` methods returns, just like action creators do in normal redux. I use this pattern sometimes, so current typings claim that it returns `Action` which is incorrect.

**Comment by athrunsun** [comment]
@ShMcK @19majkel94 
Is the type restrictions of effects really effective when creating model? I declared my model like this:

```typescript
effects: (dispatch) => ({
    requestCollectionsByPage: async (pageNumber: number, pageSize: number) => {...},
});
```

TS (I'm using 2.9.2) doesn't give me any error, while, when I run my code, the value of `pageSize` is actually root state of my app.

Also, do effects always have to return void to match the type restrictions?

From what I tried, I can return anythinng in effects and the return values are always wrapped in another `Promise`.

**Comment by 19majkel94** [comment]
Because `rootState` is typed to `any` in types definition, so TS accepts `number` as a second argument.

**Comment by ShMcK** [comment]
Currently, effects are always void as they're redux middleware under the hood, and middleware is not designed to return a value. This is not to say that effects shouldn't or can't return a value. I've seen enough use cases (including one today at work) to make me think it would be a good idea to have effects return a value. PRs welcome :)

**Comment by athrunsun** [comment]
@19majkel94 @ShMcK 
Thanks for your replies! I'm just started to learn TS, and I think I'll have to figure out how declaration files work before I can provide any effective contribution. Thanks!

**Comment by 19majkel94** [comment]
> it would be a good idea to have effects return a value

But this is exactly how it works now 😆 At least with `1.0.0-beta.4`:
```ts
import { init } from '@rematch/core';

const testModel = {
  state: null,
  effects: {
    async returnValue() {
      return 3.14;
    },
  },
};

describe('rematch', () => {
  it('should return the value from an effect', async () => {
    const store = init({
      models: {
        testModel,
      },
    });

    const value = await store.dispatch.testModel.returnValue();

    expect(value).toEqual(3.14);
  });
});

```
