### ISSUE TITLE
onError

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#4]
Should handle global errors. The following should work.

```js
init({
  onError: (e) => console.log(e)
})
```

**Comment by ShMcK** [comment]
I'm trying to clarify my thoughts on `onError`.

##### window.onerror - not good ?
If we do something like override `window.onerror`, the app may be catching errors that aren't necessarily even associated with the app itself. Also, doesn't work on mobile.

##### DVA onError - best example?
I looked at how these errors are handled in DVA. It seems they are specifically used to `catch` redux action, middleware and configuration specific errors.

To get this to work in rematch we would have to be able to globally access certain config variables created in `init`. Then pass these into `createAction`, `createEffect`, etc. 

The onError should also use `e.preventDefault()`, as suggested by some issues cleared up on DVA.

##### Question

I suppose what I'm not clear on exactly, is which errors to catch and which to let slide?

@blairbodnar - your thoughts?

**Comment by blairbodnar** [comment]
Yeah, I think window.onerror = not good. 

In keeping with the idea to have rematch as free of dependencies as possible, I think we should go the DVA approach and only deal with a way to handle redux and rematch related errors. Anything specific to the view layer could be implemented via plugins perhaps?

**Comment by ShMcK** [comment]
Alternatively, we could expose configuration settings to plugins.

So when a plugin is created it can be called immediately with rematch config.

```js
// plugin
const plugin1 = (config) => (rematchConfig) => {
  /* ... */
}
```

```js
// on init
const plugin1 = createPlugin1(pluginSpecificConfig)

init({
  plugins: [plugin1],
  onError: console.log,
})
```

```js
// inside of rematch
const rematchConfig = { onError }
plugin1(rematchConfig)
```

**Comment by blairbodnar** [comment]
Nice, yeah I like it!

**Comment by ShMcK** [comment]
Going to icebox this for a while. 

Wrapping effects in try/catch statements is probably redundant, as users will likely want to throw/catch their own errors.

This may be solved more elegantly with #10 if errors are caught within promises.

**Comment by blairbodnar** [comment]
Sounds good, roger that.

**Comment by ShMcK** [comment]
Note: look into how error handling is done in this project: https://github.com/PlatziDev/redux-catch

**Comment by ShMcK** [comment]
Closed for now in favor of an error handling plugin.

**Comment by eric-burel** [comment]
Hi @ShMcK , this plugins talks only about sync reducers, what about Effects? I'd like to implement a basic interceptor to catch uncaught effect error. This way I don't need to add a catch to all effects, I just use a generic function. However I wonder what's the recommanded practice for this.

**Comment by eightyfive** [comment]
Hi, am also interested in knowing what is the best practice for this. Seems like it belongs in a middleware but how do I access the "rematch reducers" inside the middleware?

Looking at that code:
https://github.com/fantua/redux-async-catch

One could imagine a similar app-specific version with rematch:
```js
export default () => store => next => async action => {
  try {
    return await next(action);
  } catch (err) {
    // Very app-specific, but that would meet my needs.
    store.dispatch.ajax.setErrors(await err.response.json());

    return err;
  }
};
```

I get `Uncaught (in promise) TypeError: Cannot read property 'setErrors' of undefined` error. I thought rematch "surcharges" the default redux store with all the goodies. But it does not seem like. I am not sure it is very clean either..

Any help/recommandation appreciated.

**Comment by d3dc** [comment]
@eightyfive Did you create a model named "ajax"?

I went down a similar road and found it more helpful in a larger application to know what effects could fail and how. Uncaught errors were instead just handled in one place for the entire app (Error boundary) and not separate for redux.

**Comment by ShMcK** [comment]
I've been down this road. The hard thing about putting error handling into middleware is that middleware is largely out of your control - you hand it all over to Redux middleware which is not designed to return a value. 

There's always a balance between "code that replaces boilerplate" and "code that's easy to change" - convenience vs. flexibility. With error handling, I want a convenient catch all error solution, with the ability to replace certain errors with better messages. Personally, I found wrapping dispatches within effects with try/catch allowed me the greatest flexibility in this area.

**Comment by eightyfive** [comment]
Ok thanks. I tend to agree that explicit try catch blocks in effects is the way to go, although I can't help myself but think that some nice _one_ place in my code handling all generic _server_ error responses would be a great addition to my app(s).

I will investigate the plugin road, thanks to both of you!

**Comment by rmlzy** [comment]
Can anyone provide an example?

**Comment by d3dc** [comment]
{
  effects: {
    async loadData(payload, rootState) {
      try {
        const response = await fetch('http://example.com/data')
        const data = await response.json()
        dispatch.example.update(data)
      } catch(error) {
        dispatch.errors.handle({ error, withToast: 'an example message' })
      }
    }
  }
}
