### ISSUE TITLE
Accessing other model selectors in a selector

### ISSUE THREAD

**Issue by d3dc** [rematch/rematch#400]
Say I have a normalized state and a selector to denormalize it. Would it be considered a bad pattern to stack these ~~like I do with reselect~~? 

It seems to me like selectors should have the same api as effects:

```js
{
  hydrate: (state, input) {
    return denormalize(input, schema, state)
  },
  getBook(state, id) {
    return this.hydrate(id)
  },
  bookList(state) {
    return this.hydrate(Object.keys(state.books))
  },
  sortedBookList(state) {
     return sortBy(this.bookList(), 'modified')
  }
}
```

And while we're at it, could concerns around accessing external state like #270 be addressed by the DI API you are working on for effects? ~~I don't see a  reason for this other than api parity.~~
```js
  selectors: (select) => ({
    schemaSelector(state) {
      return select.storage.denormalize(state.list, schema)
    }
  })
```

**Comment by d3dc** [comment]
I was thinking having `this` bound lets store model state be built up from smaller pieces. I can decorate a model to provide a default implementation of `hydrate` (and `dehydrate`) and then rely on `this.hydrate` in the specific domain selectors.

But I guess you could also just have a single `storage` model that you select and dispatch to - just like a database. And either I'm forgetting why this is a bad idea, or that seems like nice decoupling. I can have multiple schemas relating to each other and each entity type can still have very unrelated sagas.

**Comment by d3dc** [comment]
[I went ahead and mocked this up here](https://codesandbox.io/s/ql6m574l84)

I'm running into an issue with the `this` binding in selectors and may have just missed something.

**Comment by ShMcK** [comment]
There are currently some issues with the selectors plugin & 1.0.0-alpha. We'd be happy to take in any PRs to fix issues. 

Unfortunately, there are a lot of different people with different use cases and ideas for the selectors plugin. I've found it's just easier to write your own selectors wrapper and use it where needed.

**Comment by d3dc** [comment]
@ShMcK I can understand there's a lot of issues still around with 1.0 looming (I've had to dig a bit to get answers to some of my questions).

My intent is definitely to put in a PR eventually - just trying to spitball first. I'll definitely take a look at #386, #360, and #309. Am I missing any? It doesn't seem like there's any large blockers to what I'm doing.

What would it take to PR an API change to the selector plugin? I've gotten my example working and added a little more state to illustrate being dependent on another reducer - it feels natural to write my outputs the same as my inputs to the state and I don't see how this would interfere with reselect use or anything.

**Comment by d3dc** [comment]
Whelp, I probably broke it.
