### ISSUE TITLE
Use with connected-react-router?

### ISSUE THREAD

**Issue by linonetwo** [rematch/rematch#409]
`react-router-redux` is deprecated https://github.com/supasate/connected-react-router/issues/74
It's preferred to use `connected-react-router`.

But to set up `connected-react-router` we need to pass `rootReducer` to it. https://github.com/supasate/connected-react-router#step-1

So to work with `connected-react-router`, I need to write a plugin?

**Comment by ShMcK** [comment]
I don't think you ever need to write a plugin. Plugins are just a way to make a configuration reusable.

These `redux.rootReducer` docs may help: https://github.com/rematch/rematch/blob/master/docs/reduxApi.md#rootreducers

**Comment by linonetwo** [comment]
But I need to pass `rootReducer` to it
```js
redux: {
        middlewares: [routerMiddleware],
        rootReducers: {
          router: connectRouter(history)(rootReducers)
        },
      },
```
But where can I get this `rootReducers`?
Maybe it's `connected-react-router`'s fault since it's requiring itself to be the root reducer  https://github.com/supasate/connected-react-router/blob/master/src/reducer.js#L37

**Comment by d3dc** [comment]
@linonetwo You can already listen to rootReducers ;)

```js
import { combineReducers } from 'redux'
import { connectRouter, routerMiddleware } from 'connected-react-router'
import { createBrowserHistory } from 'history'
const history = createBrowserHistory()

export default enhanceWithConnectRouter = (config) => ({
  ...config,
  combineReducers: (rootReducers) => connectRouter(history)(combineReducers(rootReducers)),
  middlewares: [...config.middlewares, routerMiddleware(history)]
})
```

**Comment by linonetwo** [comment]
But as https://github.com/rematch/rematch/issues/376#issuecomment-394731320 said, if I want to listen on router change, then loads data according to the new route, I need
```js
{
  effects: {
  ['router/PUSH'](state) {
    ...
    return state;
  },
  },
}
```
It will cause `Invalid effect name` at this time.

**Comment by YanYuanFE** [comment]
```
import { init } from '@rematch/core';
import { connectRouter, routerMiddleware } from 'connected-react-router';
import createLoadingPlugin from '@rematch/loading';
import createHistory from 'history/createHashHistory';

const options = {};
const loading = createLoadingPlugin(options);

export const history = createHistory();

const reducers = { router: connectRouter(history) };

/**
 * 基于 Rematch 实现的 Redux 最佳实践
 *
 * More: https://rematch.gitbook.io/handbook/
 */
export default (models) => init({
    redux: {
        reducers,
        middlewares: [
            routerMiddleware(history)
        ],
        devtoolOptions: {}
    },
    models,
    plugins: [
        loading
    ]
});
```
