### ISSUE TITLE
Listen for actions dispatched from redux reducers?

### ISSUE THREAD

**Issue by alozytskyi** [rematch/rematch#414]
While migrating to Rematch, there is still significant chunk of the state which is managed by the plain reducers and actions, however Rematch doesn't seem to react to them

```javascript
reducers: {
  "REDUX_ACTION": function(state, params) {
    // react to action
  }
}
```
neither as
```javascript
reducers: {
  "REDUX_ACTION"(state, params) {
    // react to action
  }
}
```
However, to ensure seamless transition it would be useful to listen to the reducers that are yet pending  to be converted into models. It might be that plain names won't work here, but what if it'd be something like `__redux/REDUX_ACTION`, a special case?

**Comment by alozytskyi** [comment]
This seems to pass the test:

```patch
Index: test/listener.test.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- test/listener.test.js	(revision 44713f84827d8d9ddbea4fd47e1ec4e510aaafe4)
+++ test/listener.test.js	(date 1528797161000)
@@ -24,4 +24,21 @@
 
     expect(store.getState()).toEqual({ count1: 1, count2: 1 })
   })
+
+  test('should trigger state changes on redux actions', () => {
+    const count = {
+      state: 0,
+      reducers: {
+        '__redux/INCREMENT': (state, payload) => state + payload
+      }
+    }
+
+    const store = init({
+      models: { count }
+    })
+
+    store.dispatch({type: 'INCREMENT', payload: 1});
+
+    expect(store.getState()).toEqual({ count: 1})
+  })
 })
\ No newline at end of file
Index: src/redux.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/redux.ts	(revision 44713f84827d8d9ddbea4fd47e1ec4e510aaafe4)
+++ src/redux.ts	(date 1528797295000)
@@ -36,9 +36,14 @@
 	this.createModelReducer = (model: R.Model) => {
 		const modelReducers = {}
 		for (const modelReducer of Object.keys(model.reducers || {})) {
-			const action = isListener(modelReducer)
+			let action = isListener(modelReducer)
 				? modelReducer
 				: `${model.name}/${modelReducer}`
+
+			if (/^__redux\//.test(action)) {
+				action = action.replace(/__redux\//, '')
+			}
+
 			modelReducers[action] = model.reducers[modelReducer]
 		}
 		this.reducers[model.name] = (
```

**Comment by alozytskyi** [comment]
Another issue with this is that redux does not force an action to follow:

```typescript
interface ReduxPayload {
    type: string;
    payload: any;
}
```
Therefore, only `type` is mandatory, so all other keys, should probably be somehow aggregated into `payload`

**Comment by d3dc** [comment]
@alozytskyi This seems like a great application for a plugin. [I've even made one for my project](https://gist.github.com/d3dc/6ded49538550f32365fc3adcea7fd569)

Your latest comment on combining action properties into payload is interesting. How do we know what keys to select? Perhaps customizing the lift function further would be enough?

**Comment by alozytskyi** [comment]
@d3dc Hey there, good to know it's doable as plugin! 

My thinking was if there is a `payload` key, keep it. Otherwise change it to something: 
```javascript
  const lift = action => ({ payload: action && 'payload' in action ? action.payload : ...action, type: liftType(action.type) })
```

**Comment by d3dc** [comment]
I've updated my gist.

I don't know if encouraging building metadata for the enhancer is a good idea. I think the point of Rematch is not to be working so close to redux.

**Comment by alozytskyi** [comment]
@d3dc sure thing. But might be helpful to migrate existing big apps to rematch, as when replacing existing reducers reacting to something(for example, successful auth), this can be very helpful as it would only require writing new models instead of also placing new action dispatches all over the code, only to remove them again when other reducers are migrated(for example auth reducer to auth model)

**Comment by d3dc** [comment]
@alozytskyi Your use case is the one I thought I was thinking of. I'm specifically referring to using an action's `meta` property when I say "building metadata" might be encouraging too much.

You would have to modify or wrap your action creators to have that proper metadata.

**Comment by linonetwo** [comment]
@d3dc  Will your solution solves https://github.com/rematch/rematch/issues/376#issuecomment-394731320 ?
In your example, async delete seems not working.

**Comment by d3dc** [comment]
@linonetwo *cough* I may have copy pasted the wrong demo. I replaced asyncDelete with the right implementation.
