### ISSUE TITLE
effects not called when using remote-redux-devtools enhancer

### ISSUE THREAD

**Issue by cf-bosung90** [rematch/rematch#419]
If I use remote-redux-devtools enhancer, calling rematch models effects doesn't do anything.

```
// models/count.js
export default {
  state: { count: 0 },
  reducers: {
    countUp(state) {
      return {
        ...state,
      }
    },
  },
  effects: {
    // Not called
    countUpAsync() {
      debugger
      alert('hello')
      this.countUp()
    },
  },
}
```

```
import devToolsEnhancer from 'remote-redux-devtools'

export const store = init({
  models,
  // plugins: [select, loading, reactNavigationPlugin],
  redux: {
    enhancers: [devToolsEnhancer()],
  },
})
```

```
export default class Menu extends React.Component {
  componentDidMount() {
    dispatch.count.countUpAsync()
  }
   ...
}
```

I do see an action fired `type: "count/countUpAsync"`

I tried with both 0.6.0 and 1.0.0-beta.1

**Comment by ShMcK** [comment]
There's a few things this might be:

- a bug in enhancers
- some incompatability between redux devtools and this devtools
- `devtoolsEnhancer` needing to be the final middleware, but overwritten by the redux devtools middleware going last

The problem is likely [here](https://github.com/rematch/rematch/blob/master/src/redux.ts#L79-L82) If you can debug it with a log statement running a local copy with `npm link`.

```js
	const enhancers = composeEnhancersWithDevtools(redux.devtoolOptions)(
		...redux.enhancers,
		middlewares
	)
```

Some ideas off the top of my head to fix this:
- It may be that the basic devtools should be optional
- it may be that `redux.enhancers` need to be called differently

**Comment by dayze** [comment]
Still having this bug, anyone find a solution for this ?

**Comment by dayze** [comment]
After further investigations I find the issue
From **remote-redux-devtools** documentation : 
```
If you setup your store with middlewares and enhancers like redux-saga and similar,
it is crucial to use composeWithDevTools export.
Otherwise, actions dispatched from Redux DevTools will not flow to your middlewares.
```
In rematch, enhancers are always compose with ```Redux.compose``` if **redux-devtools** is disabled

From **redux.ts**
```
const composeEnhancersWithDevtools = (
	devtoolOptions: R.DevtoolOptions = {}
): any => {
	const { disabled, ...options } = devtoolOptions
	/* istanbul ignore next */
	return !disabled &&
		typeof window === 'object' &&
		window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
		? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__(options)
		: Redux.compose
}
```
A way to make rematch works with **remote-redux-devtools** is to expose a **customCompose** property which can be used like this 
```
redux: {
    devtoolOptions: {
        disabled: true,
    },
    customCompose: composeWithDevTools({}),
}
```
and something like this in **redux.ts**

```
	let enhancers
	if (redux.customCompose) {
		enhancers = redux.customCompose(middlewares)
	} else {
		enhancers = composeEnhancersWithDevtools(redux.devtoolOptions)(
			...redux.enhancers,
			middlewares
		)
	}
	
	this.store = createStore(rootReducer, initialState, enhancers)
```

My personal need was to make rematch work with **react native**, if someone encounter the same issue you can use https://github.com/jhen0409/react-native-debugger which run perfectly with rematch
