### ISSUE TITLE
effects always returns Promise regardless of what the actual function returns

### ISSUE THREAD

**Issue by cf-bosung90** [rematch/rematch#420]
Currently calling effects function will always return a Promise.

This promise will resolve to the value that the effects function returns.

This works most of the time, however, it is assuming that all effects are asynchronous, which is not true.

I am trying to create a Component that subscribe to firebase store when it mounts and unsubscribe when the Component unmounts.
Here I decided to put subscribe function inside effects.

```
// models/firebase.js
import { db } from 'src/config/firebase'

export default {
  state: {
    products: {},
  },
  reducers: {
    setProducts: (state, products) => ({
      ...state,
      products,
    }),
  },
  effects: {
    subscribeToFB() {
      const unsubscribe = db.collection('Restaurants')
        .doc('...')
        .collection('Products')
        .onSnapshot(snapshot => {
          const products = {}
          snapshot.forEach(doc => {
            products[doc.id] = doc.data()
          })
          this.setProducts(products)
        })
        return unsubscribe
    },
  },
}

```

```
// Component.js
import React from 'react'

export default class FetchAndSubscribe extends React.Component {
  componentDidMount() {
    const unsubscribePromise = dispatch.firebase.subscribe()
    unsubscribePromise.then(unsubscribe => {
        this.unsubscribe = unsubscribe
    })
  }
componentWillUnmount() {
    this.unsubscribe && this.unsubscribe()
}
  render() {
    return null
  }
}

```

The problem with this code is that unsubscribe method may not be ready by the time the component unmounts. Think about the case that Component mounts and unmounts before subscription is ready.
This will cause subscriptions to happen and never unsubscribed even when component unmounts.

A far better method in my opinion is instead of effects always returning Promise, just return whatever it returns. If people want effects to return Promise, they can just implement their function as async or return Promise on their own.

**Comment by ShMcK** [comment]
I think this may be a good use case for the Context API (aka the topic you (@cf-bosung90)  gave an awesome and helpful presentation on last week 💯 

Another possibility would be to hold the subscription entirely within an effect.

// models/product.js
```js
let productSubscription

export default {
  effects: {
    unsubscribe() {
      productSubscription.unsubscribe()
    },
    subscribeToFB() {
      productSubscription = firebase.subscribe()
  },
}
```

// component.js
```js
export default class FetchAndSubscribe extends React.Component {
  componentDidMount() {
    this.props.subscribeToProducts()
  }
componentWillUnmount() {
    this.props.unsubscribeToProducts()
}
  render() {
    return null
  }
}
```

**Comment by bosung90** [comment]
I am not actually sure how I can use the new Context api here lol.
The problem I can see with the second method is that I will have more than one component calling subscribeToFB. Therefore I need Component to hold onto the unsubscribe ref.
