### ISSUE TITLE
Plugins don't receive store config

### ISSUE THREAD

**Issue by d3dc** [rematch/rematch#421]
Plugins only receive the actual redux store (no metadata). It seems weird that the config is write accessible but isn't read accessible.

Dev tools is able to show the store name because it is explicitly told it in `mergeConfig`:
```js
devtoolOptions: {
  name: initConfig.name,
  ...
}
```

**Comment by d3dc** [comment]
@ShMcK I just threw the metadata into the pluginFactory, but would it be better to expose things like the name on the store itself?

In my `select` branch, I only use the state to store the store name - maybe this should just be happening?

**Comment by ShMcK** [comment]
I think it would be better if `onStoreCreated` passed in the Rematch store, rather than the Redux store.

I can put in a quick PR for this

**Comment by ShMcK** [comment]
nm, it does. Give me a few minutes, I'll throw a PR and tag you in it.

**Comment by ShMcK** [comment]
Will release as beta.2 by the end of the week. There are a couple more improvements I can squeeze in before then.
