### ISSUE TITLE
Remove globals: `getState`, `dispatch`?

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#439]
There are a few issues with `getState` in the current v1.

1. The name implies it should be a single store's state. It may be better to call it `getStates`

2. How to handle TS typings if it returns multiple stores states. Typings are currently created from models for a store, rather than for collection of stores.

**Comment by bosung90** [comment]
I never had more than one redux store in my project

**Comment by bosung90** [comment]
I'm not really familiar with server-side rendering (I'm a react native dev)
I import dispatch and getState from my store.js like so
```
// src/store.js
export const { dispatch, getState } = store
```

and simply import them directly
```
// SomePage.js
import {dispatch} from 'src/store'
```

**Comment by ShMcK** [comment]
I don't think there are any good use cases for providing a single store `getState`. Accessing `getState`  the way @bosung90 recommends is more ideal.

There is, however, a use case if a user with multiple stores wants to access all stores, perhaps to run a selector on them. So I think this may be a case that needs considering.

**Comment by jackwilsdon** [comment]
I feel like it should be the user's job to manage these stores - we shouldn't be keeping a global list of stores that the user has created (and I can imagine that storing all stores the user has created would cause a memory leak, no?).

**Comment by ShMcK** [comment]
@jackwilsdon I agree. I think it's best to recommend the following

```js
// src/store.js
export const { dispatch, getState } = store
```

Global `getState` & `dispatch` were a dangerous idea, and can easily be avoided.

**Comment by krainboltgreene** [comment]
> I never had more than one redux store in my project

There's a lot of value in isolated stores for complex parts of an application. For example, one reason to not use redux for forms is input latency especially on large redux stores (of any vertical). This can be mitigated significantly by having a store for inputs.

**Comment by ShMcK** [comment]
I try to minimize my use of Redux in applications by putting state in components/Context API wherever it isn't shared. It can often be more work to wire everything together, but its worth it if you're developing for mobile where resources are quite limited. Each action is an additional check on every dispatch. Each additional key to the store is an equality check on every update for every connected component.

I do think if were easier to setup multiple stores in Redux, we'd all be using multiple stores already. A single store doesn't scale well.
