### ISSUE TITLE
How to use with redux-thunk?

### ISSUE THREAD

**Issue by krainboltgreene** [rematch/rematch#440]
I'm setting up with:

```
import {init} from "@rematch/core"
import thunk from "redux-thunk"
import logger from "redux-logger"
import environment from "@internal/environment"
import * as models from "./models"
import sdk from "./sdk"

export default init({
  models,
  plugins: [],
  redux: {
    middlewares: [
      thunk.withExtraArgument({client: sdk}),
      logger,
    ],
  },
})
```

and my model:

```
export default {
  state: {},
  reducers: {
    updateFormInputValue (state, payload) {
      const {formSlug} = payload
      const {fieldSlug} = payload
      const {value} = payload

      return mergeDeepRight(
        state
      )(
        objectFrom(
          [formSlug, fieldSlug]
        )(
          {writtenAt: new Date(), value}
        )
      )
    }
  },
  effects: {
    submitRegistration (payload, root) {
      return function thunk (dispatch, {client}) {
		console.log(arguments)
	  }
    }
  }
}
```

However when `submitRegistration()` is dispatched my inner function doesn't get called?

**Comment by d3dc** [comment]
Hey @krainboltgreene, `redux-thunk` is actually not needed for rematch. The new betas landed PR #399 and it hasn't made its way to the gitbook yet.

**Comment by krainboltgreene** [comment]
Does this account for `withExtraArgument()`?

**Comment by krainboltgreene** [comment]
Further this seems like a non-ideal interface? Now when I have one effect that needs dispatch, all effects now have access dispatch. It also means `effects` can't just be an object.

**Comment by d3dc** [comment]
I'm not sure of the advantage of effects just being an object. Rematch will collect an object from factories, and the typing will extract the typings of that object.

Just anecdotal, but most of my dispatch heavy sagas occurred in the same models and before Rematch I wrote a whole lot more thunk boilerplate.

I think ExtraArguments might be a great idea to add if its not there already. At the worst, its a clone of the loading plugin that overloads args. _To beg the question_, what does `sdk` have to do with your application state?

**Comment by krainboltgreene** [comment]
> I'm not sure of the advantage of effects just being an object.

For one it makes splitting up harder:

```
import * as effects from "./effects"

export default {
  state: {},
  reducers: {},
  effects,
}
```

vs 

```
import * as effects from "./effects"

export default {
  state: {},
  reducers: {},
  effects: (dispatch) => effects
}
```

The latter doesn't work.

> To beg the question, what does sdk have to do with your application state?

I use the SDK to talk to my server and my SDK is built at runtime based on a discovery engine talking to my server.

**Comment by d3dc** [comment]
If effects is coming from one file, couldn't you just export a function?
And if you're indexing:
```js

import * as effects from "./effects"

export default {
  state: {},
  reducers: {},
  effects: (dispatch) =>

    Object.assign({},

    ...Object.values(effects).map(e => e(dispatch)))

}

```


Regarding your SDK, I'm pedantically getting at that the action
creators are where the binding to the SDK exists, why should the store
manage the dependencies for it? (I do like the DI)

**Comment by d3dc** [comment]
If effects is coming from one file, couldn't you just export a function?

And if you're indexing:

```js
import * as effects from "./effects"

export default {
  state: {},
  reducers: {},
  effects: (dispatch) =>

    Object.assign(
      {},
      ...Object.values(effects).map(e => e(dispatch))
    )
}
```


Regarding your SDK, I'm pedantically getting at that the action
creators are where the binding to the SDK exists, why should the store
manage the dependencies for it? (I do like the DI)

**Comment by krainboltgreene** [comment]
Ah, now I see what you mean.

**Comment by ShMcK** [comment]
`withExtraArgument` is an interesting idea.

Currently I import dependencies into the model file. I think is clearer, but I can understand why someone may want to pass along an `api` object.

**Comment by krainboltgreene** [comment]
The reason I don't do that is chunking. My SDK is a promise that eventually resolves to a client object. If I use import then I risk, via chunking, waiting multiple times for a server and client to negotiate an interface.
