### ISSUE TITLE
Async dispatch

### ISSUE THREAD

**Issue by spearson23** [rematch/rematch#442]
Why are reducers called asynchronously?  This causes a problem with controlled components (see https://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously/28922465#28922465)

**Comment by ShMcK** [comment]
I'm not sure I understand. `setState` became asynchronous in React 16.

**Comment by DominikSerafin** [comment]
Rematch is great, but this confuses me - why are rematch reducers async? 

Shouldn't they be 100% synchronous, just like using redux dispatch?
