### ISSUE TITLE
@rematch/persist 1.0.0.beta2 does not work after using store.model() method.

### ISSUE THREAD

**Issue by thucxuong** [rematch/rematch#444]
@rematch/core 1.0.0beta2
I tried to init the store with persist plugin, it works.
But when I tried to use store.model() method, it prevent the persist plugin from working immediately

```javascript
// import { createStore, applyMiddleware, compose } from 'redux';
import { routerMiddleware, routerReducer } from 'react-router-redux';
import { init } from '@rematch/core';
import createRematchPersist from '@rematch/persist';
import createLoadingPlugin from '@rematch/loading';
import createHistory from 'history/createBrowserHistory';
import * as rootModels from '../models';

const history = createHistory();
const loadingPlugin = createLoadingPlugin();
const persistPlugin = createRematchPersist({
  whitelist: ['routing'],
  version: 2,
});
const store = init({
  redux: {
    initialState: {},
    middlewares: [
      routerMiddleware(history),
    ],
    reducers: {
      routing: routerReducer,
    }
  },
  models: {
    ...rootModels
  },
  plugins: [persistPlugin, loadingPlugin],
});

store.model({ name: 'lazymodel', state: 10 });

export { store, history };

```

**Comment by ShMcK** [comment]
Was it working with a previous version of rematch?

I made a change to `store.model` around beta.1 or so.

**Comment by d3dc** [comment]
@thucxuong What do you mean when you say:
> it prevent the persist plugin from working immediately

It looks like you have `whitelist: ['routing']` in your config. Which does:
> whitelist?: Array<string>, // only persist these keys

**Comment by thucxuong** [comment]
Hi @ShMcK,
I'm just working with the latest version, not yet previous version.
HI @d3dc ,
For eg: When I call `store.model` right after the init of the store, it prevents the persist plugin to work immediately, without updating the local storage or blank local storage.
When I call `store.model` method in another file, the persist plugin can perform the very first action, which is assign data to local storage of the initial state of the routing `location: null`, then it stop updating the `localstorage`.

Could it be that the store instance the persist plugin keeping is different from the store instance we have after the store.model method is called ?

**Comment by Aircity** [comment]
@rematch/persist 1.1.6 persist does not work after using store.model() method.
 I’ve run into the problem, too.
And it seems run well, when your Redux-DevTools is on. 😅To find the problem, you must turn off your Redux-DevTools.

**Comment by Aircity** [comment]
@ShMcK
