### ISSUE TITLE
Should effects be actions?

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#45]
Looking at this bit of code makes me wonder. I believe its possible to create **effects** that don't require actions, and therefore no middleware.

```js
// creates a bound function with the context of dispatch[model.name]
effects[`${model.name}/${effectName}`] = model.effects[effectName].bind(dispatch[model.name])dispatch[model.name][effectName] = 

// action is dispatched and later picked up in middleware
createDispatcher(model.name, effectName)
```

On one hand, this would restrict actions to only things that change state. Effects would act like regular functions.

On the other hand, you don't get a record of effects in your devtools.

Is this even a good idea?

**Comment by blairbodnar** [comment]
I think I like the idea! I'd say we give it a shot.

**Comment by ShMcK** [comment]
I think I'll close this one for now. It's nice to be able to see your actions in order within the devtools.
