### ISSUE TITLE
Immer plugin can't return data from producers

### ISSUE THREAD

**Issue by Nav4e** [rematch/rematch#454]
>Returning data from producers
It is also allowed to return arbitrarily other data from the producer function. But only if you didn't modify the draft. This can be useful to produce an entirely new state. 

In current version, we can't return an entirely new state

**Comment by mnaughto** [comment]
This bug was fixed by https://github.com/rematch/rematch/commit/1e634e88602535b2d5fb688bd51ed55cfbf7ed2a. It should be in release 1.1.0 of `@rematch/immer`
