### ISSUE TITLE
Why is models rather than modules

### ISSUE THREAD

**Issue by 132yse** [rematch/rematch#457]
emmmm

the API models ，but not modules ，why？
I feel ‘modules’ is more conforming to the meaning of the split

**Comment by d3dc** [comment]
I think of it as modeling the store slice. We aren't directly writing the functionality that is exposed, we are describing it.

**Comment by ShMcK** [comment]
Mostly, `models` are a carry over from [dva.js](https://github.com/dvajs/dva).

We used Dva for nearly a year at work, before deciding it had too many opinionated design decisions that didn't fit our needs/use cases, and often left us puzzled altogether. As an example, you had to install a package called "dva-no-router" when using React Native. Basically, you install React-Router-4, then you uninstall it with another package. That was just the iceberg, and we thought we could make something preferable.
