### ISSUE TITLE
Is there any way to integrate on dva framework?

### ISSUE THREAD

**Issue by wiziple** [rematch/rematch#469]
Hello,
I found out this library from React Vancouver meetup a few months ago and finally have some time to try it out.
I'm currently maintaining a mid-large size react app project built with dva framework.
My concern is that the project is already on production, and it is not a small project. (It has 15 models with 300+ reducers/effects in total), which means it is almost impossible to migrate at once.

My question is, is there any trick to integrate rematch library on dva framework so that I can migrate it from specific models first then slowly move more models to rematch? I've tried a few approaches and didn't work.

Thank you for creating this awesome library. 😄 
I definitely love this approach when using redux. It is way more clear and straightforward than writing tons of redux boilerplate files such as action creators, saga, and reducers.

**Comment by ShMcK** [comment]
If you're migrating from dva, it shouldn't be too hard. There are a few issues to keep in mind:
- no saga support currently in rematch. This is the hardest part about migrating.
- changing generator/yields to async/await
- dva has a built in router, perhaps migrating to dva-no-router first might help

In rematch@next, you can use multiple stores, it may be possible migrate a project by breaking it down into smaller stores.
