### ISSUE TITLE
Rematch/Loading not finding my models/effect

### ISSUE THREAD

**Issue by acnebs** [rematch/rematch#479]
I have a React app that I'm trying to get to work with the Rematch Loading plugin. I already converted all my Redux code to Rematch and it works great. 

However, when I try to use the Loading plugin, my models/effects are not added into the plugin, but the plugin *loads* just fine. So I can see the 'loading' object in `state` with the associated `global`, `models`, and `effects` properties, but models and effects are always empty (and global is always 0).

I've tried changing around the order in init to match the example (plugins first), I've tried the different versions (Rematch 0.6 + Loading 0.5 / Rematch 1.0.X + Loading 1.1.0), but I just can't get the `loading` object to have my models or effects in it. I've confirmed that my effects/actions are firing using the ReduxDevTools.

Any thoughts about what I haven't tried? I've restructured my code to be a nearly exact copy of the Loading React Example but to no avail. I'm really pulling my hair out here.

**Comment by ShMcK** [comment]
I might suggest rather than using the plugin, instead copy the code inside of a model called "loading" in your project. It's essentially the same thing, but will give you more control over debugging.

https://github.com/rematch/rematch/blob/master/plugins/loading/src/index.ts

**Comment by acnebs** [comment]
Unfortunately my project is not configured for TS, so easier said than done, but I'll see what I can do and report back!

**Comment by acnebs** [comment]
Ok, so I fiddled around and it started working. As far as I can tell, this appears to be a case of me not restarting my dev server after adding the Loading plugin. 

So for anyone in the future who is having problems loading plugins: make sure you've at least restarted your server as a first step. That auto-reload / hot loading is great but can bite you if you forget it's there!

**Comment by sven09** [comment]
Hi, thanks for the hint. 
We have renamed a rematch model file and this the only loading effect that is not found afterwards (ts).  
Do you have any hint. It works after clearing site data and then later, it happens again. ... Strange
Thanks
