### ISSUE TITLE
Rename hooks

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#48]
Hooks doesn't really describe what "hooks" do, may be better to rename them. Some ideas:

- subscriptions
- subs
- listeners

**Comment by blairbodnar** [comment]
Agreed. Hmm... Kind of on the fence with debating between "subscriptions" and "listeners".

Will let the thought sit in my brain for a bit.

**Comment by ShMcK** [comment]
I think "subscriptions" may make more sense, once the ability to "unsubscribe" is added.

"listeners" sounds like you can't turn them off.

@blairbodnar What do you think?

**Comment by blairbodnar** [comment]
Sold! Let's go with "subscriptions"

**Comment by ShMcK** [comment]
closed when #56 merges.
