### ISSUE TITLE
Batch Dispatch

### ISSUE THREAD

**Issue by saginadir** [rematch/rematch#482]
Anyone know of a current existing way to implement batch dispatch? I keep getting race conditions because some entities for a model are set before the others. I prefer just send multiple actions to multiple models at once, which will trigger a single subscription event.

This was discussed here on the redux repo about 3 years ago:
https://github.com/reduxjs/redux/issues/911#issuecomment-149361073

maybe we can implement something like:

```
dispatch([
{type: `${model}/${reducer}`, payload, meta},
{type: `${model}/${reducer}`, payload, meta},
{type: `${model}/${reducer}`, payload, meta},
{type: `${model}/${reducer}`, payload, meta}
])
```

**Comment by ShMcK** [comment]
I've implemented something similar, though long ago and wish I had added more comments.

Note that it doesn't use middleware to batch dispatches together. I recall looking into batching dispatches in Redux so that they would only trigger a single re-render to find that it was easier just to use a single action with different payloads.

The code calls the next promise whenever the thread is idle, using `requestIdleCallback`. Works in web & React Native.

```js
// TODO: can be further optimized
// runs in batches, but could be sequenced further
const batchPromise = (batchSize, thenArr, fn) => Promise.resolve(thenArr)
  .then((arr) => arr
    .map((_, i) => (i % batchSize ? [] : arr.slice(i, i + batchSize)))
    .map((group) => (res) => Promise.all(group.map(fn)).then((r) => res.concat(r)))
    .reduce(async (chain, work) => {
      await requestIdleCallback(() => Promise.resolve())
      return chain.then(work)
    }, Promise.resolve([])))
  .catch(console.log)

export default batchPromise
```

See tests to see how it works.

```js
import batchPromise from './batch-promise'

describe('batchPromise', () => {
  it('should return a batch promise of more than the count', async () => {
    const fn = jest.fn((x) => Promise.resolve(x))
    await batchPromise(5, [1, 2, 3, 4, 5, 6], fn)
    expect(fn).toHaveBeenCalledTimes(6)
  })

  it('should return a batch promise of less than the count', async () => {
    const fn = jest.fn((x) => Promise.resolve(x))
    await batchPromise(5, [1, 2, 3], fn)
    expect(fn).toHaveBeenCalledTimes(3)
  })

  it('should return a batch promise of the count', async () => {
    const fn = jest.fn((x) => Promise.resolve(x))
    await batchPromise(5, [1, 2, 3, 4, 5], fn)
    expect(fn).toHaveBeenCalledTimes(5)
  })

  it('should return the value of a batch promise of more than the count', async () => {
    const fn = jest.fn((x) => Promise.resolve(x))
    const result = await batchPromise(5, [1], fn)
    expect(result).toEqual([1])
  })

  it('should return the value of a batch promise of more than the count', async () => {
    const fn = jest.fn((x) => Promise.resolve(x))
    const result = await batchPromise(5, [1, 2, 3, 4, 5, 6], fn)
    expect(result).toEqual([1, 2, 3, 4, 5, 6])
  })
})
```

It can be used with dispatch in the following way, or with the dispatch.model.effect pattern.

```js
const batchSize = 3
const actions = [{ type: `${model}/${reducer}, payload, meta}]
await batchPromise(batchSize, listOfActions, dispatch)
```

**Comment by saginadir** [comment]
Interesting example, but my newbie question is:

Will it trigger only a single re-render for the batchSize given?

**Comment by d3dc** [comment]
@saginadir My two-cents on this are just use an action like @ShMcK mentioned. Consider an action `loadEntities` where the payload is a collection of models keyed by reducer name.

If you have to batch dispatches just to load data, I think you're not using redux right. One of the biggest advantages is that multiple reducers can undergo state changes from one action.

**Comment by saginadir** [comment]
@d3dc 

That debate has been discussed long before this thread, in theory your suggestion will work but as you pointed out it requires me:

1) create a file to store the functions that will load the entities to the correct location
2) change them in each reducer (because I still need to load entities separately sometimes)
3) Create a specific function in root reducer that receives multiple types of entities and saves them to their respected state

it sort of breaking the logic of redux and incentivises the use a rootReducer because if you are planning on changing anything in the structure of your entities it'll be a bit of a pain to figure out which parts has to be changed under each entityReducer and global rootReducer

That's why if there was a functionality to reuse the existing entityReducers but firing a single subscription when done, it greatly simplifies the process above and makes the need for rootReducer reduandant.

**Comment by d3dc** [comment]
@saginadir I'm not sure we're on the same page. If you follow the logic of redux, you don't have to any of those things, and you're actually following the logic of redux...

```js
const bowls = {
  state: {},
  reducers: {
    'api/loadEntities'(state, entities) {
      return { ...state, keyBy(entities.bowls, 'id') }
    }
  },
  effects: dispatch => ({
    async fetchAll() {
      const bowls = await api.bowls.all()
      return dispatch.api.loadEntities({ bowls })
    }
  })
}

const seats = {
  state: {},
  reducers: {
    'api/loadEntities'(state, entities) {
      return { ...state, keyBy(entities.seats, 'id') }
    }
  },
  effects: dispatch => ({
    async fetchAll() {
      const seats = await api.seats.all()
      return dispatch.api.loadEntities({ seats })
    }
  })
}

const toilets = {
  state: {},
  reducers: {
    'api/loadEntities'(state, entities) {
      return { ...state, keyBy(entities.toilets, 'id') }
    }
  },
  effects: dispatch => ({
    async fetchAll() {
      const toilets = await api.toilets.all()
      const seats = await api.seats.find({
        toilet: { in: toilets.map(t => t.seat) }
      })
      const bowls = await api.bowls.find({
        toilet: { in: toilets.map(t => t.seat) }
      })
      
      return dispatch.api.loadEntities({ toilets, seats, bowls })
    }
  })
}

```
