### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by guilhermecomum** [rematch/rematch#485]
Hi,

What is the best way to error handling on effects?
I'm using something like this, I used to do on redux
```
export const apiAction = async options => {
  const { baseURL, prefix, url, method, params, data, payload } = options;
  try {
    const response = await api.request({
      method: method ? method : 'get',
      baseURL: baseURL,
      url: url,
      params: params,
      data: data,
    });

    await dispatch({
      type: `${prefix}Success`,
      payload: response.data,
    });

    return response.data;
  } catch (response) {
    await dispatch({
      type: `${prefix}Failure`,
      payload: response.data,
    });
  }
};
```
Why Everytime I call a effect, a reducer with the same name is triggered?

**Comment by d3dc** [comment]
effects _are_ actions. Its just a middleware. 

Your code looks pretty solid outside of that. 

I've played around with putting error state in its own model like the loading plugin. It seems to work for CRUD.
