### ISSUE TITLE
When can you support  ReactNavigation2？

### ISSUE THREAD

**Issue by huanglei1991** [rematch/rematch#486]
When can you support  ReactNavigation2？
![3e5f27e3-a932-437a-b92d-626ad89bbc09](https://user-images.githubusercontent.com/25176774/43260327-bf8c682e-910b-11e8-90e8-86a2369bd3e8.png)

**Comment by ShMcK** [comment]
There's a PR open for #447.

I haven't been able to test it yet, but if it works without issue, please let me know.
