### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by guilhermecomum** [rematch/rematch#487]
Hi,

Once global import dispatch was removed, which is the best way to call dispatch without cause circular dependency?

I'm using axios and I used to dispatch some actions inside axios interceptors, but I tried many way, but I'm always causing circular dependecy =(

**Comment by ShMcK** [comment]
You can grab the dispatch from the store.

```js
const { dispatch, getState } = init()
```

If you need to access dispatch within an effect, in the latest version it's available as well.

```js
effects: (dispatch) => ({
  effect1() {}
})
```

**Comment by guilhermecomum** [comment]
`const { dispatch, getState } = init()`
Will create  a new store, right?!
I'll get a "useless" store only for use dispatch or I'm wrong?
It's not a problem, but seem bit weird

**Comment by d3dc** [comment]
@guilhermecomum the object returned from `init()` contains those properties. You should not call `init()` again.

**Comment by guilhermecomum** [comment]
Thanks!
