### ISSUE TITLE
How to use Rematch Update & Rematch Loading

### ISSUE THREAD

**Issue by RamdanK** [rematch/rematch#493]
Hi, i need some help and advice about plugin update & loading and have a few questions.
1. Is `@rematch/update` need to be persist?
I tried to persist the `updated` plugin, but it doesn't update the timestamp when `effects` was triggered.
But when I did not persist the `updated` plugin, state.updated.effects on all models is working, but then the `loading` plugin is undefined for all effects model, here is the state:

![image](https://user-images.githubusercontent.com/24414891/43473150-9104c930-9519-11e8-9ff5-11b31a6b2837.png)

![image](https://user-images.githubusercontent.com/24414891/43473260-db63b23e-9519-11e8-9dae-bcd6fbc709bf.png)

that is the case when I setup my plugin in sequence like this:
![image](https://user-images.githubusercontent.com/24414891/43473466-6b4425a0-951a-11e8-8fa5-199de1b2e427.png)

Then, when I change like this, 
![image](https://user-images.githubusercontent.com/24414891/43473554-ae3e8918-951a-11e8-906b-9814b57cf516.png)
the results for updated & loading is vice versa.

2 .Are the sequence of plugins had effect on it?
3. How can I use both plugins to work? is there any example or references?

PS: Sorry for my bad english :smile:

**Comment by d3dc** [comment]
Just gonna leave this here.

```
// copy orig effect pointer
				const origEffect = this.dispatch[name][action]

				// create function with pre & post loading calls
				const effectWrapper = async (...props) => {
					try {
						this.dispatch.loading.show({ name, action })
						// waits for dispatch function to finish before calling "hide"
						const effectResult = await origEffect(...props)
						this.dispatch.loading.hide({ name, action })
						return effectResult
					} catch (error) {
						this.dispatch.loading.hide({ name, action })
						throw error
					}
				}

				// replace existing effect with new wrapper
				this.dispatch[name][action] = effectWrapper
```

```
// copy function
					const fn = this.dispatch[name][action]

					// create function with pre & post loading calls
					const dispatchWithUpdateHook = async props => {
						await fn(props)

						// waits for dispatch function to finish before calling "hide"
						this.dispatch[updatedModelName].onUpdate({ name, action })
					}
					// replace existing effect with new dispatch
					this.dispatch[name][action] = dispatchWithUpdateHook
```

**Comment by ShMcK** [comment]
Having created the update plugin originally, I'm not entirely sure the motivation behind the update plugin was sound. I no longer use it and would not recommend its use at this time. 

Updated comes with a performance cost from triggering additional re-renders. Ideally it should listen to actions from other models and update. Low hanging fruit as @d3dc mentioned :)

**Comment by RamdanK** [comment]
Sorry for late response..
@d3dc , thanks for the explanation.. just like @ShMcK said, for now I'll use one of the plugin, because if I use `updated` plugin without `loading` plugin, it works normally even if i persist it.
so I decided to use `update` plugin only, because i need it for now even it will cost the performance.
Once again thanks for the responses..

**Comment by d3dc** [comment]
@RamdanK I'm academically curious how you're using `updated`. :)

**Comment by RamdanK** [comment]
@d3dc, I use it as parameter wether to fetch data or not from server between exact time.
If you have any suggestion, I'll gladly research and learn it..
