### ISSUE TITLE
Immer plugin typescript typings causes build to fail

### ISSUE THREAD

**Issue by misoguy** [rematch/rematch#495]
It seems that the declaration file made for immer plugin is made with wrong relative path

```js
// node_modules/@rematch/immer/dist/index.d.ts
import { Models, Plugin } from '@rematch/core';
declare const immerPlugin: () => Plugin<Models, import("../node_modules/@rematch/core/src/typings").Action<any, any>>; <-- wrong relative path
export default immerPlugin;
```
It should be fixed if the declaration file made returns something like this

```js
// node_modules/@rematch/immer/dist/index.d.ts
import { Models, Plugin } from '@rematch/core';
declare const immerPlugin: () => Plugin<Models, import("@rematch/core/src/typings").Action<any, any>>; <-- remove relative path
export default immerPlugin;
```

**Comment by parecementeria** [comment]
Same issue with persist and loading plugins.

**Comment by d3dc** [comment]
These plugins used tsc's generated declarations. I looked at this when I started on my typings. Not being an expert, I'm not sure how to configure resolution here. 

You can however just `import { Action } from '@rematch/core'` if you write it by hand.

**Comment by ShMcK** [comment]
I've had similar issues with VS Code auto-changing imports on save. Recently turned this off.

I'll check to see if this might be the issue.
