### ISSUE TITLE
selectors auto bind to getState()

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#50]
Should selectors automatically be passed `getState()` as the first parameter?

##### Current

```js
state = 1
select.count.double(state) = 2
```

##### Proposed
```js
state = 1
select.count.double() = 2
```

---

##### Current

```js
state = { '2': { name: 'Joe' } }
select.user.getById(state, '2') = { name: 'Joe' }
```

##### Proposed
```js
state = { '2': { name: 'Joe' } }
select.user.getById('2') = { name: 'Joe' }
```

**Comment by ShMcK** [comment]
@blairbodnar An interesting selector syntax found in [this link](http://blog.rangle.io/recipes-for-redux/) (using decorators). Not recommending it, just haven't seen anything like it.

**Comment by blairbodnar** [comment]
Interesting with the decorators approach! I haven't seen anything like it either. Good to be aware of different ideas out there though.
