### ISSUE TITLE
[Question] Introspecting action type in a middleware?

### ISSUE THREAD

**Issue by danawoodman** [rematch/rematch#502]
I'm curious if there is a better way to check the action type from a middleware for a rematch action then I am doing below?

```js
export default store => next => action => {
  if (action.type === 'auth/loginSuccess') {
    dispatch.something.fetch()
  }
  return next(action)
}
```

Would there be a way to not use a string in this case?

Thanks!

PS I looked everywhere for recommendations for this including issues but couldn't find anything, hence the issue 👍

**Comment by d3dc** [comment]
Like an action type constant? Just use strings.

I'm pretty sure that Rematch doesn't bother with these, since they are just boilerplate. Rematch takes over and handles namespace collision as well as enforcing how action types are formatted in a deterministic fashion.

**Comment by d3dc** [comment]
I think @ShMcK probably would know more about design decisions.

You could create a plugin that puts a simple function on store, some:
```jsx
{
  onStoreCreated(store) {
    return {
      actionType(model, method) {
        const type = `${model}/${method}`
        if (store.dispatch[model][method]) {
          return type
        }

         throw new Error(`store has no action type for ${type}`)
      }
    }
  }
}
```

**Comment by ShMcK** [comment]
In this case, you could use an effect to capture the action on an `auth` model.

```js
const auth = {
  state: {},
  effects: dispatch => ({
    loginSuccess() {
       dispatch.something.fetch()
    }
  })
}


init({ models: { auth } })
```

But I may be unclear about the question. If the goal is to check for any invalid action types, you could set up middleware for development only, maybe a plugin, that `console.warn`s if an action type is invalid?
