### ISSUE TITLE
[QUESTION] Best practice for return of an effect

### ISSUE THREAD

**Issue by danawoodman** [rematch/rematch#503]
Is there a "best practice" for working with effect return values in Rematch? 

E.g., Is it reasonable to actually `await` a value in your React component to do something when it resolves?

For example, in your component you have a `create` method that creates something via an API, is it reasonable to do the following or is it discouraged?

```js
create(data) {
  this.props.someRematchEffect(data)
    .then((resp) => this.setState({ resp }))
    .catch((error) => this.setState({ error }))
}
```

Of course you could also be setting this data in your store (which I normally do), but sometimes it can be useful to do some bit of local state management within a component without complicating your model. 

Just curious if there is a reason *not* to do this in this case?

**Comment by d3dc** [comment]
I think this pattern is a "best practice" ;)

It let's you asynchronously call effects and know their status. IMO, state is state, even if it's not redux. As long as you are describing a state change when an effect completes, you're just describing a local effect. 

It would be bad to use it to avoid `connect`ing data, as the return value will get out of sync with the store. Don't use it if you selecting redux state.

**Comment by danawoodman** [comment]
Thanks both of you. I was leaning in that direction as well but didn't know if I was missing some unforeseen downside of that approach. Cheers! 🍻
