### ISSUE TITLE
It is not possible to update documentation on Gitbook

### ISSUE THREAD

**Issue by felpin** [rematch/rematch#504]
Well... I tried to update some documentation, but it was asked to login first.
Since I did not had an account, I had to create one, but I had to create in the new gitbook (somehow rematch is using the legacy version)

So I created an account in the new gitbook, but to update documentation on the legacy gitbook the user must have an account on its legacy version...

So... Is it possible to use the new gitbook?

**Comment by ShMcK** [comment]
I'll have to look into that. Currently, I just use Gitbook for displaying markdown from the git repo. Feel free to submit changes to any .md files in the repo. You can also do this directly from Github by clicking the edit icon.
