### ISSUE TITLE
[QUESTION] Proper use of new select plugin?

### ISSUE THREAD

**Issue by danawoodman** [rematch/rematch#505]
I'm quite lost with the proper usage of the new select plugin. I've got a selector working in my model and my test suite has verified it is doing what it is supposed to do. However, I'm getting lost with connecting it to a component. Here is my selector:

```js
  selectors: slice => ({
    selected: () =>
      slice(state =>
        pickBy(state.collection, device => state.selection.includes(device.id))
      ),
  }),
```

The documentation has only this as an example: 

```js
import { connect } from 'react-redux'
import { select } = './store'

connect(select(models => {
  total: models.cart.total,
  eligibleItems: models.cart.wouldGetFreeShipping
}))(...)
```

Which doesn't make things super clear from what I can tell

- How do I pass in data from my stores?
- How do I pass in actions?
- Is it a curried function in which provides the selected state to the next call?

If I use it as though it was replacing `mapStateToProps` I get: 

```
Error: Selector creators expect all input-selectors to be functions, instead received the following types: [object, function]
```

With the code:

```js
export default withRouter(
  connect(
    select(({ contacts, devices }) => ({
      contacts: toArray(contacts.collection),
      devices: devices.selected, // hopefully my select!?
    })),
    ({ devices: { share } }) => ({
      share: (devices, recipients) => share(devices, recipients),
    })
  )(Wrapper)
)
```

Some guidances (and updated docs) would be very helpful, thanks!

**Comment by d3dc** [comment]
It might be in the wording...

`select` creates a structured selector.

A "selector" is the same type everywhere: `state => any`

You can pass this to `connect` as `mapStateToProps`.

That is, `({ [key: string]: state => any }: M) => state => { [key: string in keyOf M]: any }`.

**Comment by danawoodman** [comment]
@d3dc thanks for trying to help clarify things. It still is a bit clear as mud to me right now for some reason. Any chance you can post an example that includes a usage of a selector in combination with regular access of a store's state?

**Comment by danawoodman** [comment]
Ok, so I've gotten something working I believe, but I'm not sure if this is the proper, idiomatic use?

```js
  connect(
    state => {
      const selection = select(models => ({
        devices: models.devices.selected,
      }))

      return {
        contacts: state.contacts.collection,
        ...selection(state),
      }
    },
```

**Comment by d3dc** [comment]
@danawoodman Thats pretty much spot on.

I'm a bit of purist and prefer not to mix raw state mapping with select.

The only bit of magic glue added to `select` is that its lazy. (I'll need to document that) You can create a static selector in your component's file then:

```js
const selection = select(models => ({
  devices: models.devices.selected,
}))

const actions = models => ({ bar: models.foo.bar })

export default connect(
  selection,   // mapStateToProps
  actions  // mapDispatchToProps
)(MyComponent)
```

I'm probably not the only one that thinks this pattern is rife for a convenience function.

**Comment by danawoodman** [comment]
@d3dc cool, I'm glad I stumbled upon it! Maybe adding that to the docs would help others?

Regarding "prefer not to mix raw state mapping with select", what do you mean? Make a component only use selections of state? Could you provide an example of your alternative approach? I'm curious to see it!

**Comment by danawoodman** [comment]
Added my example in a PR #506

**Comment by d3dc** [comment]
I added some comments. I have a lot of editorializing to do later too.

My code example was meant to illustrate everything I was talking about. Most important is that select is called once. But also there is no mapStateToProps arrow function.

**Comment by d3dc** [comment]
How's this for a confusing `componentWillUpdate`
```js
export default connect(
  select({
    shown: state => state.site.updateAvailable
  })
)(Update)
```

**Comment by DAVIDSAMIRCIOCOIU** [comment]
I wonder whether anyone is using this in 2025? I attempted using selectors in my react project but I am struggling to understand how to call selectors in my react components.
