### ISSUE TITLE
[QUESTION] How to use redux-undo with rematch?

### ISSUE THREAD

**Issue by Squeegy** [rematch/rematch#509]
I'm having a doozy of a time trying to get rematch to play nice with [redux-undo](https://github.com/omnidan/redux-undo)

It seems to want you do `undoable(reducer)`, but it expects the reducer to be in redux standard format:

```js
(state, action) => newState
````

Where rematch uses this:

```
{
  [actionType]: (state, actionPayload) => newState
}
```

Is it possible to make this work? Is there a rematch specific undo package people are using?

**Comment by Squeegy** [comment]
That was a good hint!  So I think I'm on the right track with something like this?

```js
import { init } from '@rematch/core'
import { combineReducers } from 'redux'
import undoable from 'redux-undo'
import models from './models'

export const store: Store = init({
  models,
  redux: {
    combineReducers: reducers => {
      return combineReducers({
        ...reducers,
        site: undoable(reducers.site), // only this model should be undoable.
      })
    },
  },
})
```

**Comment by Squeegy** [comment]
Yep that was exactly what I needed. Thanks for telling me to look there!

**Comment by vimcaw** [comment]
> That was a good hint! So I think I'm on the right track with something like this?
> 
> ```js
> import { init } from '@rematch/core'
> import { combineReducers } from 'redux'
> import undoable from 'redux-undo'
> import models from './models'
> 
> export const store: Store = init({
>   models,
>   redux: {
>     combineReducers: reducers => {
>       return combineReducers({
>         ...reducers,
>         site: undoable(reducers.site), // only this model should be undoable.
>       })
>     },
>   },
> })
> ```

I tried this config in rematch 1.2.0 and redux-undo 1.0.0-beta9-9-7, but it doesn't work and cause many problems, such as some component doesn't rerender after the used model updated.

**Comment by vimcaw** [comment]
even I just set `combineReducers` to `reducers => combineReducers(reducers)`, nothing else, it still causes many problems, such as some component doesn't rerender after the model they used updated.

```js
import { init } from '@rematch/core'
import { combineReducers } from 'redux'
import immerPlugin from '@rematch/immer'
import createLoadingPlugin from '@rematch/loading'
import models from './models'

const loading = createLoadingPlugin({});
const immer = immerPlugin();

export const store: Store = init({
  models,
  redux: {
    combineReducers: reducers => combineReducers(reducers)
  },
  plugins: [immer, loading]
})
```

**Comment by vimcaw** [comment]
I found the reason, multiple `combineReducers` config (whether on `init` config or plugin inner) will cause conflict, this is also why `immer` and `persist` plugin can't work together.

**Comment by brownbl1** [comment]
I would like to use redux-undo with rematch. I'm also using typescript and would be interested in contributing a plugin for this. But I'm not that familiar with plugins and don't see any that call combineReducers. @semoal is there a straightforward way to do this? Or could you provide a little guidance to get me started?

**Comment by semoal** [comment]
> I would like to use redux-undo with rematch. I'm also using typescript and would be interested in contributing a plugin for this. But I'm not that familiar with plugins and don't see any that call combineReducers. @semoal is there a straightforward way to do this? Or could you provide a little guidance to get me started?

Something quite similar to this, should work fine. It should accept also the redux-undo configuration, you could look to Rematch persist package which is quite similar (for handling typing).

Always the typing system is the trickiest part because we must do something similar to surfing Redux and Redux-Undo types with our typings, but Zhi Tian is an absolute master.

If you want to collaborate on this, you can join on Rematch discord and we'll be happy to help and release undo as an official plugin.

Also on the official Rematch book which is already available for buying, we teach how to create plugins and what does each lifecycle is and how they run. 

```ts
import { Plugin, Models } from '@rematch/core'
import Redux from 'redux'
import undoable from 'redux-undo'

const undoPlugin = <
	TModels extends Models<TModels>,
	TExtraModels extends Models<TModels> = Record<string, never>
>(): Plugin<TModels, TExtraModels> => {
	return {
		onReducer(reducer: Redux.Reducer): void | Redux.Reducer {
			return undoable(reducer)
		},
		onRootReducer(rootReducer: Redux.Reducer): Redux.Reducer {
			return undoable(rootReducer)
		},
	}
}

export default undoPlugin

```

**Comment by brownbl1** [comment]
Sounds good! I'll jump on the discord server and create a playground for prototyping this out. Will also want to test how well it plays with other plugins like select and persist..
