### ISSUE TITLE
What is chained dispatch?

### ISSUE THREAD

**Issue by koss-lebedev** [rematch/rematch#510]
In the [Inspiration document](https://github.com/rematch/rematch/blob/master/docs/inspiration.md) I saw a mention of "chained dispatch", but couldn't find any examples with it. Could you please explain how to use it, or maybe you have a code snippet that helps to understand what it is? Thanks!

**Comment by ShMcK** [comment]
Each dispatch is a promise, so you can use it as a thenable.

```js
dispatch.do.something()
.then(routeToOtherPage)
```

Note that there currently is no return value, and it resolves after the dispatch is complete.
