### ISSUE TITLE
support IE8 with es5shim

### ISSUE THREAD

**Issue by lee1hang** [rematch/rematch#511]
Hi!

I found that this wonderful library can support IE8 with some modifications and es5shim。

just take a look at [some modifications](https://github.com/lee1hang/rematch/blob/master/rollup.config.js)

[A React16-compat mini library](https://rubylouvre.github.io/anu/index.html) was integrated this library。

There is still a lot of people use IE8 in China!! So, can you make a "offical suppurt"?

BTW: My English sucks...forgive me

**Comment by ShMcK** [comment]
别担心 我的普通话不好

I definitely understand the regrettable need for IE 8 support. 

A few questions first:
- Is it possible for a user to support IE8 without requiring other users to add the same shim?
- What is the size difference of the output library with the shim?

**Comment by lee1hang** [comment]
Let me make more modifications in this coming week.

Maybe we can make a output bundle names "RematchIE", and tell the user what shim/polyfill the have to require if they want to work in IE8. Like [ReactIE](https://github.com/RubyLouvre/anu/blob/master/dist/ReactIE.js)

I think it would be better to let the user require the shim manually because when they work in IE8 they always need so many shim.

I will try my best to minimize the size of the output library

**Comment by ShMcK** [comment]
Sounds good 🙂, happy to publish a `@rematch/coreIE`.
