### ISSUE TITLE
Access params for running effects

### ISSUE THREAD

**Issue by Andreyco** [rematch/rematch#512]
In some situations one effect might be running multiple times in parallel, e.g. “Like” on multiple entities. 

It would be great to access params passed to effect in order to determine on which entities effect runs on in order to disable certain UI elements, eg one not all like buttons in feed.

It could be plain map with generated ids for every run or something similar. 
Currently I solve this be keeping state of entities being processed by effect but as you can imagine it is very repetitive.

If you are open to this idea I might create RFC for this functionality...

**Comment by jackwilsdon** [comment]
That kind of sounds like something you should be storing in state to me - as otherwise your UI is no longer dependant on the application state!

**Comment by ShMcK** [comment]
I don't fully understand the issue, so I may be far off.

But it also seems to me that it may be easier and give you more control if you handle actions within component state.

**Comment by jackwilsdon** [comment]
@ShMcK it sounds like @Andreyco is asking for a way of checking which effects are currently running, as well as a way of getting the arguments passed to the running effects (at least that's how I interpreted it).
