### ISSUE TITLE
[QUESTION] About having only rootState in effects and not having simple/pure methods for the models

### ISSUE THREAD

**Issue by metala** [rematch/rematch#513]
Hey, I have a couple of question about the reducers and effects.

1. Why effects have access to the rootState, but not to model state. When the model has single instance you can hardcode the name of the instance and get it from the rootState, but when I don't know the name it's a bit tricky.

2. I was considering making the rematch model, a fat model. I figured that I would like to have non-destructive methods that return value and have access to a copy of the state, thus it should not be able to modify it unless it calls a reducer. Those methods fall in neither the category of reducer nor effect. E.g. method `totalQuantity(state) => state.items.reduce(prev, x => prev + x.quantity, 0)`. Is there a simple way to do this? If no, should I write a plugin, then?

**Comment by d3dc** [comment]
@metala [Have you taken a look at selectors before?](https://rematch.gitbooks.io/rematch/plugins/select/)

**Comment by ShMcK** [comment]
Good questions.

1. The `modelState` can always be accessed by `rootState[modelName]`. You mentioned you may not know the name, why might that be?

2. see above on the selectors plugin :) In my own code, I often write my own selectors just as pure functions with a similar result.

**Comment by metala** [comment]
Thank you very much to you both. I guess I have somehow missed that plugin, even though I believe I have read the docs.

Back on question 1: It's more of a hypothetical and personal preference. I prefer the effects to be self-contained unless they want to access other models. Basically my models do not keep reference to their model name, thus it allows me to create multiple instances of the same model, if needed.

I guess I would make myself a plugin to bind `getState` to effect's `thisArg`. I think oyu have answered my questions, so if you want you may close the issue.
