### ISSUE TITLE
Effect function with multiple arguments and state

### ISSUE THREAD

**Issue by kkshyu** [rematch/rematch#515]
Related to this issue: #267 
i need the state and the multiple arguments in effects, and i followed the example from [here](https://github.com/rematch/rematch/blob/master/examples/ts/count/src/App.tsx).

the type cannot match in the multiple arguments, but it works in the single argument.
```
[ts]
Argument of type '{ lectureId: string; chapters: IChapter[]; }' is not assignable to parameter of type 'Action<{ lectureId: string; chapters: IChapter[]; }, void>'.
  Object literal may only specify known properties, and 'lectureId' does not exist in type 'Action<{ lectureId: string; chapters: IChapter[]; }, void>'.
```

here are the codes:
// models.ts
![image](https://user-images.githubusercontent.com/8722165/45252932-bd5bae00-b35e-11e8-86c4-97820104746f.png)
// component.ts
![image](https://user-images.githubusercontent.com/8722165/45252961-0e6ba200-b35f-11e8-9d6e-751d70fe13b0.png)
![image](https://user-images.githubusercontent.com/8722165/45252962-10356580-b35f-11e8-811e-215dc1b12848.png)

In `component.ts:36`, the multiple arguments is not working, but in `components.ts:43` the single argument is working. Any wrong configure?

**Comment by kkshyu** [comment]
@ShMcK i just solved this and sent the PR, plz review it can give some feedbacks. thx!

**Comment by ShMcK** [comment]
Issue should be resolved with @rematch/core@1.0.2. Thanks @kkshyu

**Comment by FirsovRG** [comment]
@Krasnov8953, I have the same problem too

**Comment by sup4x** [comment]
Guys, I have the same problem as guys have @Krasnov8953 , @FirsovRG

**Comment by ShMcK** [comment]
Happy to review any PRs that resolve the issue
