### ISSUE TITLE
typescript: how to get `dispatch.model.effect` to show correct type signatures

### ISSUE THREAD

**Issue by derrickbeining** [rematch/rematch#526]
I've been struggling for a while trying to figure out how to set up `rematch` for my Typescript/React project. I followed the [TypeScript recipe in the docs](https://rematch.gitbooks.io/rematch/docs/recipes/typescript.html) and looked through [examples/ts/count](https://github.com/rematch/rematch/tree/master/examples/ts/count) (which isn't compiling because of `selectors` on the `shark` model).  

In particular, I can't figure out how to get `dispatch.<model>.<effect>` to give me the correct function signature for my effects. For instance:

Here's where I defined `dispatch.api.getAllPosts`:

![screen shot 2018-09-29 at 3 06 19 pm](https://user-images.githubusercontent.com/25019711/46249890-c50eef80-c3fe-11e8-9e93-627ad585218b.png)

But when I try to use it, I get this error:

![screen shot 2018-09-29 at 3 23 41 pm](https://user-images.githubusercontent.com/25019711/46249907-29ca4a00-c3ff-11e8-82ff-d8fb3625d52f.png)

Anyone know what I'm doing wrong?

**Comment by derrickbeining** [comment]
looks like this is the same as #478 and #520

**Comment by derrickbeining** [comment]
closing since duplicate

**Comment by derrickbeining** [comment]
Reopened because #478 is closed.

**Comment by derrickbeining** [comment]
See my comments [here](https://github.com/rematch/rematch/issues/478#issuecomment-425691702) and my possible solution [here](https://github.com/rematch/rematch/issues/478#issuecomment-425692278)

**Comment by ShMcK** [comment]
I believe the issue should be resolved in @rematch/core@1.0.2. Thanks @kkshyu
