### ISSUE TITLE
Typescript Tips for the docs in next release

### ISSUE THREAD

**Issue by matt-erhart** [rematch/rematch#527]
I recently tried mobx and mobx-state-tree and ran into some counter intuitive stuff and one show stopper (MST takes 30-60s to compile in TS). Found rematch and it has been very good experience. I know ya'll are working on a few TS issues already, but I wanted to point out a good way to pass types into your react components (from #526 ). 

after you've got your store:
```ts
export default store;
export const {dispatch, getState} = store
export type Store = typeof store
export type Dispatch = typeof store.dispatch
export type iRootState = RematchRootState<typeof models>
```

```ts
import { iRootState, Dispatch } from '@store/createStore';
const mapState = (state: iRootState) => ({
  abstractions: state.abstractions,
  selectedAbstraction: state.userSelected.abstractionId
});

const mapDispatch = ({
  abstractions: {
    deleteTextSelection,
    deleteAbstraction,
    saveToDb,
    loadFromDb
  },
  userSelected: { selectAbstraction, selectTextSelection }
}: Dispatch) => ({
  deleteTextSelection,
  deleteAbstraction,
  selectAbstraction,
  saveToDb,
  loadFromDb,
  selectTextSelection
});

type connectedProps = ReturnType<typeof mapState> &
  ReturnType<typeof mapDispatch>;
type Props = connectedProps & { classes: any };

type State = { expanded: string };
class AbstractionsPanel extends React.Component<Props, State> { }
```

Now you've got intellisense in vscode and typesafe props + connected props. This and rematch makes for an almost perfect DX.

**Comment by ShMcK** [comment]
Thanks for the very clear example of setting up store typings.

Rematch typings continue to be a problem, I don't think I'm the right person to tackle the issue.

**Comment by derrickbeining** [comment]
@matt-erhart , are you not encountering issues described in #478, #520, and #526 ?

**Comment by matt-erhart** [comment]
I did reproduce that, but I don't use dispatch that way yet. I think I added async to an effect and TS was fine.  Iirc, I was doing a non-async effect just to pass something from rootstate into a reducer. Are effects the best way to get at rootstate?

I also had the problems with the persist and select plugin and had to use my own local version of the plugins.
