### ISSUE TITLE
Model API change? A different way to specify name and state?

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#53]
I'm wondering about simplifying model names and state even further...

##### Current
```js
model({
  name: 'count',
  state: 0
})

model({
  name: 'todos',
  state: []
})
```

##### Proposed
```js
model({
  count: 0
})

model({
  todos: []
})
```

Then, in `createModel` we could determine what that "special" key is to derive the model name and initial state.

Something like this...
```js
const corePluginModelKeys = () => ['reducers', 'effects', 'selectors', 'hooks']
const otherPluginModelKeys = () => { // TODO get model keys that other plugins have introduced }

const createModel = (model: $model): void => {
  const pluginKeys = [...corePluginKeys(), ...otherPluginModelKeys()]
  const specialKey = Object.keys(model).find(key => !pluginKeys.includes(key))
  
  const modelName = specialKey
  const state = model[modelName]
 
  // continue on with createModel
 ...
}
```

##### Pros
- Less typing

##### Cons
- Can't use any of the model plugin keys as model name
- A little bit harder to migrate from mirror / dva?
- Harder to understand for the user?

**Comment by ShMcK** [comment]
How might a model with "effects" and "reducers" look ?

**Comment by blairbodnar** [comment]
👀

##### Current
```js
model({
  name: 'count',
  state: 0,
  reducers: {
    increment: (count) => count + 1
  },
  effects: {
    asyncIncrement: async () => {
      await delay()
      dispatch.count.increment()
    }
  },
})
```

##### Proposed
```js
model({
  count: 0,
  reducers: {
    increment: (count) => count + 1
  },
  effects: {
    asyncIncrement: async () => {
      await delay()
      dispatch.count.increment()
    }
  },
})
```

**Comment by ShMcK** [comment]
In this case, how might we differentiate between a mispelling of "reducers" and the initial state?

What do you think about:

```js
model({
  state: {
    count: 0,
  },
  reducers: {
    increment: (count) => count + 1
  },
  effects: {
    asyncIncrement: async () => {
      await delay()
      dispatch.count.increment()
    }
  },
})
```

But then what about scenarios where your state has a lot of keys, what would the name be?

```js
model({
  state: {
    count: 0,
    loading: false,
    lastUpdated: 'Oct 16th',
  },
  reducers: {
    increment: (count) => count + 1
  },
  effects: {
    asyncIncrement: async () => {
      await delay()
      dispatch.count.increment()
    }
  },
})
```

**Comment by blairbodnar** [comment]
I just called first arg in the reducer `count` - it's just the `state` we've always been using. Nothing changed there. 

```js
increment: (count) => count + 1
// same as
increment: (state) => state + 1
```
As for the `model({ state: ... })` approach, I don't think that works because you can't determine a model name. (Like you mentioned.)

**Comment by blairbodnar** [comment]
> In this case, how might we differentiate between a misspelling of "reducers" and the initial state?

Unless I'm not following what you're asking here? I think the misspelling situation applies to both the current and proposed ideas either way.

**Comment by ShMcK** [comment]
I suppose what I mean is, how does the app know what the name of a model is?

**Comment by blairbodnar** [comment]
Ahhhhhh! I think I see the confusion here.

I'm keeping with the design that the user calls model() for each 'chunk' of the global state they are designing. So creating a model...

##### You can do this:
```js
model({
 count: 0,
 ... // other plugin model keys
})

model({
 todos: [],
 ... // other plugin model keys
})
```
##### You cannot do this:
```js
model({
 count: 0,
 todos: [],
 ... // other plugin model keys
})
```

**Comment by blairbodnar** [comment]
With that said, hopefully my original post makes more sense about how the model name is determined? :)

**Comment by ShMcK** [comment]
Say in this scenario, the state becomes what doesn't match existing plugins?

So "count" doesn't match "reducers", "selectors", "effects", "hooks", so we assume its state, and capture the name?

**Comment by blairbodnar** [comment]
Yup yup! And also check that is doesn't match any keys that other plugins might have introduced too.

**Comment by ShMcK** [comment]
I think that might be "too flexible". It would be hard to validate that data is okay. I'm not convinced that its simpler or less confusing than "name" and "state". 

It also introduces possible name conflicts. What if your state holds the key "reducers"?
