### ISSUE TITLE
NODE_ENV related warning when used in minified bundle

### ISSUE THREAD

**Issue by cbovis** [rematch/rematch#534]
I'm noticing an odd issue with Rematch in production whereby I get a console log entry with the following message:

> You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

This message comes from Redux and I believe is something to do with how Rematch is bundling Redux alongside it. Redux includes the following code:

```javascript
if (
  process.env.NODE_ENV !== 'production' &&
  typeof isCrushed.name === 'string' &&
  isCrushed.name !== 'isCrushed'
) {
  warning(
    'You are currently using minified code outside of NODE_ENV === "production". ' +
      'This means that you are running a slower development build of Redux. ' +
      'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' +
      'or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) ' +
      'to ensure you have the correct code for your production build.'
  )
}
```

Rematch appears to be bundling in development mode which removes `process.env.NODE_ENV !== 'production' &&` from the resulting bundle. My code then includes Rematch, passes through webpack, and the resulting bundle is minified causing the message to be displayed.

**Comment by bosung90** [comment]
Happening to me as well when I use create-react-app v2 and deployed to netlify

**Comment by jackwilsdon** [comment]
Just speculating here but it looks like we no longer provide an `esm` production version of `@rematch/core`, just a development one;

https://github.com/rematch/rematch/blob/0b0340057b9543d3c1635d4cd3c834b20d704cd9/rollup.config.js#L18-L25

The issue is that this file is still listed under `module` in our `package.json`;

https://github.com/rematch/rematch/blob/0b0340057b9543d3c1635d4cd3c834b20d704cd9/package.json#L27

It appears that we no longer generate production `esm` modules (or `umd`) since 00975b25dd353addc07f9f9a51789d1a03a0895a.

Pinging @ShMcK :grin:

**Comment by ShMcK** [comment]
I believe the issue is related to changes in Webpack 4. These might be related to esm or umd modules, or related to Rollup plugins, or may require some Webpack config changes. Not sure.

I was able to reproduce the problem with examples after migrating to create-react-app-2. Thanks @bosung90. @cbovis can you verify that you're also using Webpack 4?

```
// https://stackoverflow.com/questions/43694367/you-are-currently-using-minified-code-outside-of-node-env-production-this/43694700

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux

Webpack 4 Update
If you're using webpack >= 4, you can set mode to production. This will automatically define NODE_ENV to production without needing to use the define plugin. https://webpack.js.org/concepts/mode/#mode-production.
```

**Comment by cbovis** [comment]
@ShMcK I can confirm I'm using webpack4 but I'm not using create-react-app

**Comment by ShMcK** [comment]
I'll look into this later today, but will need to set up a demo project for testing. Any recommendations for a minimum webpack boilerplate that would produce this issue?

There may be a problem with how Rollup is resolving Redux in the build process. Will have to look into it more.

**Comment by cbovis** [comment]
@ShMcK it's not a particularly simple example of a codebase but you should be able to replicate with the following:

```
$ git clone https://github.com/cbovis/0x-tracker-client.git 0x-tracker-client
$ cd 0x-tracker-client
$ npm i
$ npm run build:serve
```

The webpack config used for that example can be found at https://github.com/cbovis/0x-tracker-client/blob/master/config/webpack/production.config.js

**Comment by magicspon** [comment]
I'm also seeing this.
Using rematch with gatsby
example: https://wearestraightline.com

**Comment by ShMcK** [comment]
I've made many different failed attempts to resolve this issue by changing the Rollup configuration. 

There is a solution that would be a small breaking change: have users install their own peer dependency for Redux >= v4. As an added benefit, As @cbovis mentioned, users that have both Redux & Rematch would not need to manage two potentially different versions. 

The breaking change would be pretty minimal.

```
npm install redux rematch
```

Love to hear some feedback on this suggestion.

**Comment by jackwilsdon** [comment]
Is there any reason to have it as a `peerDependency` as opposed to a normal `dependency`? If we just don't include it in the rolled up bundle but keep it as a `dependency` then `npm` and the likes will handle it all for us, no?

**Comment by ShMcK** [comment]
I've tried the following with Rollup:

- ensure the dist version of Redux is used by specifying "module" false
- link directly to the dist version of Redux
- explicitly include the dependency in the Rollup config
- don't explicitly include the dependency, only use resolvers
- run compilation after resolving modules
- run compilation before resolving modules
- specify NODE_ENV='production' when building

---

The problem relates to this interesting piece of code inside of Redux. It's really quite clever.

```js
/*
 * This is a dummy function to check if the function name has been altered by minification.
 * If the function has been minified and NODE_ENV !== 'production', warn the user.
 */
function isCrushed() {}

if (
  process.env.NODE_ENV !== 'production' &&
  typeof isCrushed.name === 'string' &&
  isCrushed.name !== 'isCrushed'
) {
  warning(
    'You are currently using minified code outside of NODE_ENV === "production". ' +
      'This means that you are running a slower development build of Redux. ' +
      'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' +
      'or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) ' +
      'to ensure you have the correct code for your production build.'
  )
}
```

I have a quick hack that may work, replacing 'function isCrushed() {}' with another string. I'm not sure that it's the best course of action, but would be a temp fix.

**Comment by ShMcK** [comment]
Found a fix. It seems Webpack 1-3 relied on CJS modules, but as of Webpack 4 UMD modules are used.

Now running a production build for UMD. Will publish soon as @rematch/core @1.0.5

**Comment by oyo-ravi-yadav** [comment]
facing this issue again `"@rematch/core": "^1.3.0",`
sample repo : https://github.com/raven619claw/starter-kit/tree/develop
