### ISSUE TITLE
SyntaxError: unknown: Unexpected token

### ISSUE THREAD

**Issue by nyrf** [rematch/rematch#538]
{ SyntaxError: unknown: Unexpected token, expected ; (1:12)
> 1 | 'use strict'module.exports="development"==='production'?require('./rematch.min.js'):require('./rematch.js')

**Comment by ShMcK** [comment]
Should be resolved in @rematch/core@1.0.6. Drop a message if the problem persists :)

**Comment by nyrf** [comment]
@ShMcK It works now, thanks.
