### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#54]
It seems like publishing docs is coming up. A good solution should:
- use markdown
- be easy to learn
- not look terrible

A suggestion for publishing our own docs. 

This looks like the path of least resistance: [Github Pages with Jekyll](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages). I made something similar with this site: https://coderoad.github.io/tutorial-docs.html

I would however, prefer if the doc templates were in a component based framework, rather than Jekyll.

Any other suggestions?

**Comment by ShMcK** [comment]
Also, create-react-app publishes to github pages. Meaning, that we could use "react" with a simple markdown loader + a stylesheet.

As long as the docs are preserved in simple markdown form, I think it works.

**Comment by blairbodnar** [comment]
The create-react-app + github pages sounds like it might be nice!

I'm pretty easy on this! I don't really have any suggestions as I haven't worked much with publishing docs. I took a look at gitbook, but I think it tends to make docs look too bloated.

**Comment by ShMcK** [comment]
Gitbook looks like the path of least resistance.

We could use the [prism plugin](https://plugins.gitbook.com/plugin/prism) for nice code snippets

This looks also interesting: [exercises](https://plugins.gitbook.com/plugin/exercises). Not so much to use, but looks interestings

**Comment by blairbodnar** [comment]
Cool, I'm up for giving gitbook a shot. Both of those plugins look cool.

And yeah, we'll keep our docs nice and simple.

**Comment by ShMcK** [comment]
Some background reading with a simple template.

http://www.writethedocs.org/guide/writing/beginners-guide-to-docs/

**Comment by ShMcK** [comment]
closing in favor of #74
