### ISSUE TITLE
Reselect v4

### ISSUE THREAD

**Issue by 19majkel94** [rematch/rematch#544]
A few days ago, Reselect 4.00 had came to live:
https://github.com/reduxjs/reselect/blob/master/CHANGELOG.md#v400---20180930

The changes are rather small but it would be better if one of the plugin author could take a look at them and update this dep to the newest version. I've tried to run the tests locally but there's no test script in package.json nor `npx jest` doesn't work.

**Comment by d3dc** [comment]
I never thought about it, but this actually strange: you can run all the plugin tests from the repo root. 

`npm test select` should run.

**Comment by 19majkel94** [comment]
@d3dc 😞 
```
PS C:\#Projekty\rematch> npm test select

> @rematch/core@1.0.6 test C:\#Projekty\rematch
> jest "select"

No tests found
In C:\#Projekty\rematch
  184 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 26 matches
  testPathIgnorePatterns: \\_book\\,\\lib\\,\\plugins,\\plugins\\react-navigation\\examples,\\plugins\\subscriptions,\\plugins\\loading-immutable,\\examples\\ts - 49 matches
Pattern: select - 0 matches
npm ERR! Test failed.  See above for more details.
PS C:\#Projekty\rematch>
```

**Comment by d3dc** [comment]
Indeed. Testing plugins was broken by #528

**Comment by 19majkel94** [comment]
What about this? Is it worth to update?
