### ISSUE TITLE
[Question] How to use flow with rematch?

### ISSUE THREAD

**Issue by yqz0203** [rematch/rematch#547]
I tried typescript with rematch, code type checking works fine.

But it seems no flow definition for rematch so that I have to write a mass of type declaration. This makes me sad.😢

What can I do?

**Comment by jackwilsdon** [comment]
You can contribute some flow types! 😁

You could try running https://github.com/joarwilk/flowgen across our existing TypeScript typings and see how that goes :+1:

**Comment by 19majkel94** [comment]
> What can I do?

Just forget about Flow 😄 It's behind TypeScript in term of features, it has much smaller community support and typings base and it's starting to die as the contributors switched to ReasonML 😝
