### ISSUE TITLE
immer不好用

### ISSUE THREAD

**Issue by ruixiu** [rematch/rematch#549]
用了这个框架，确实很好用，再也不用写字符串的action名称了。

我在使用的时候，定义的state是这样的：
```js
state: {
    topicList: [],
    page: 0,
    total: 0,
}
在reducers的方法中执行state.topicList.push({topic的内容})时没有页面无效。请问是什么原因呢

**Comment by Frank1e0927** [comment]
> 用了这个框架，确实很好用，再也不用写字符串的action名称了。
> 
> 我在使用的时候，定义的state是这样的：
> 
> ```js
> state: {
>     topicList: [],
>     page: 0,
>     total: 0,
> }
> 在reducers的方法中执行state.topicList.push({topic的内容})时没有页面无效。请问是什么原因呢
> ```



> 用了这个框架，确实很好用，再也不用写字符串的action名称了。
> 
> 我在使用的时候，定义的state是这样的：
> 
> ```js
> state: {
>     topicList: [],
>     page: 0,
>     total: 0,
> }
> 在reducers的方法中执行state.topicList.push({topic的内容})时没有页面无效。请问是什么原因呢
> ```

please use english, especially open source libraries other than china, becasue in github chinese is not a common language
请使用英语交流，特别是除了中国之外的开源库，因为中文在github上不是一个通用语言

**Comment by ruixiu** [comment]
With this framework, it is really easy to use, and no longer need to write the action name of the string.

When I was using it, the state I defined was like this:
```js
state: {
    topicList: [],
    page: 0,
    total: 0,
}
There is no invalid page when executing state.topicList.push ({topic content}) in reducers's method. What is the reason?
