### ISSUE TITLE
Discussion: Passing Typesafe Props to Selectors

### ISSUE THREAD

**Issue by 19majkel94** [rematch/rematch#551]
Right now, we have 3 ways to create selectors that take parameters: 
- using normal `return (rootState, props) =>`
- using `createSelector` helper
- using `hasProps` helper

The normal selector and `createSelector` produce selector that we normally call like in v1.0 of select plugin: `select.cart.total(rootState, { shipping: 1000 })`.

But the `hasProps` is different, it acts like a factory: `select.cart.total({ shipping: 1000 })(rootState)`. Mainly because the way how it creates selector:
```js
const hasProps = inner =>
		function(models) {
			return selectorCreator(
				props => props,
				props => inner.call(this, models, props)
			)
		}
```

It could be changed to the standard signature easily:
```js
const hasProps = inner =>
		function(models) {
			return selectorCreator(
                state => state
				(_, props) => props,
				(state, props) => inner.call(this, models, props)(state)
			)
		}
```

I understand that this signature is useful in structured selector:
```js
const selection = store.select(models => ({
  total: models.cart.total({ shipping: 100 }),
}))
```

But I think we should standarize the parametric selectors signature. Maybe we can just transform the `models` parameter, so all parametric selectors `(state, params)` could be detected and transformed to the `(params)(state)` signature.

**Comment by ShMcK** [comment]
@19majkel94 would you be willing to put in a PR?

@d3dc what are your thoughts?

**Comment by d3dc** [comment]
I'll have to actually dig into this. I did notice in the last PR we now have:

```
export interface ModelSelectorFactories<S> {
	[key: string]: SelectorFactory<S> | SelectorParametricFactory<S>
}
```

This makes sense to be propagating the correct state type, I think. But other than return type, is the call signature different between the two types?

**Comment by 19majkel94** [comment]
@d3dc 
In typings, `hasProps` is `Parameterizer` which returns `SelectorFactory`, which returns `Selector<S, P, R>`. So the signature in types is wrong, I've discovered this when I was preparing new typings for the selectors plugin. I can detect that in typings and make it typesafe but I think the signature should be consistent.

> Defeats the purpose of a selector, no? It creates a new cache every time the root state changes.

Yeah, it sucks 😄 But let's think, if we have complicated selector, we use `createSelector` which handles props by itself. `hasProps` is used only for simple selectors, that use `slice` to get model state. So maybe we can just use slice?
```js
const hasProps = inner =>
		function(models) {
			return selectorCreator(
                slice,
				(_, props) => props,
				(state, props) => inner.call(this, state, props)
			)
		}
```
```js
selectors: (slice, createSelector, hasProps) => ({
  total: hasProps((state, props) =>
    state.reduce((t, item) => t + item.value, 0) + props.shipping
  ),
}),
```

Honestly, I don't like the `hasProps` as it's not so helpful and confusing. I stick to `createSelector` in my app but I would like to send a PR with new selector plugin typings and `hasProps` is the only one that left for proper types definition.

**Comment by 19majkel94** [comment]
> The typings are currently incorrect. I'm thinking that if this was a solution to a problem, then we might want to solve the original problem?

Fixing the typings is 5 min of work. This issue is about a runtime API, mostly for JS user that doesn't have red compile error.

Consider this two examples:
```js
foo(models) {
  return createSelector(
    slice,
    models.abc.xyz,
    (_, props) => props,
    (state, xyz, props) => null,
  );
},
bar: hasProps(models, props) {
  return slice(state => null);
}
```

So now it's super easy to call the selector in a wrong way:
```js
const mapState = (state) => ({
  foo: select.sample.foo("foo")(state),
  bar: select.sample.bar(state, "bar"),
})
```

And it would be great if we can convert the `models` in structured selector to act as a curried function, so `select.sample.bar(state, props)` would become `models.sample.bar(props)(state)`. And the mapState example:
```js
const mapState = select(models => ({
  foo: models.sample.foo("foo"),
  bar: models.sample.bar("bar"),
})
```

Also for `createSelector` it would be convenient to have curried `models` function:

```js
return createSelector(
  slice,
  models.foo.bar("bar"),
  (state, bar) => null,
);
```

**Comment by d3dc** [comment]
I'm worried things like currying would overcomplicate what is going on. Right now, the plugin tries to do what it says on the box:
- create selectors using reselect
- wire dependencies

And its really only that second part that is important. Build a function, it gets exposed. Following the best practices means these work well in `connect`.

Some issues then that jump out:
1. Sometimes selectors aren't just decorated functions and sometimes they are. 
2. Which function is being called? There's a ruleset I have to know. We aren't calling the factory again. etc.
3. There are performance implications. Lots of new functions are created every render in a naive case.

And really, I'm not sure the idea is motivated by anything still. Looking at your example, its missing my point.

This should never happen:
```
const mapState = (state) => ({
  foo: select.sample.foo("foo")(state), // whoops
  bar: select.sample.bar(state, "bar"), // whoops again
})
```



1. If you try to write:
```
select.sample.bar("bar")(state)
```
you shouldn't have used `hasProps` - its bad for performance.



2. The typings should still be a hint. This isn't different from any other model with methods. Go read the docs or use a code preview to see the `hasProps` symbol.

**Comment by d3dc** [comment]
I think this might help inform where the currying idea came from - One topic that I struggle to bring up properly is the composition of payload extractors that naturally occurs with reselect.

To start, I really think its much more obvious to write arrow functions when we want to change the behavior:

```
const selection = select(models => ({
  foo: state => models.sample.foo(state, 'foo'),
})
```

So, when we use `createSelector`, we can provide an extractor function for props that chooses a named argument. This is feels pretty similar to something like python kwargs.

```
return createSelector(
  slice,
  models.abc.xyz,
  (_, props) => props.value,
  (state, xyz, value) => null,
)

//models.abc.xyz
return createSelector(
  slice,
  (_, props) => props.value,
  (state, value) => null,
)
```

Now overriding a value is meaningful and explicit **and** we don't have to think about which dependencies take which values:
```
const selection = select(models => ({
  foo: models.def.uwv,
  baz: models.abc.xyz
})

const mapState = (state, props) => selection(state, {
  value: props.value + 42
})
```

**Comment by d3dc** [comment]
extractor function - "props" that change every render. probably from react or vue.
`hasProps` - "props" that never change, but used in more than one way.

**Comment by d3dc** [comment]
The solution I can think of that makes the collection as homogenous as possible would be to maintain two selector collections, one that is higher-order.

This seems like it would just add complexity:
```js
selectedItemSubject({ selected }, { createFirestore }) {
 return createSelector(
    createFirestore('items'),
    selected.id,
    (firestore, id) => firestore.filter({ id: total })
  )
}
```

**Comment by 19majkel94** [comment]
Ok, I think I get it. So basically `hasProps` is a rematch adaptation of selector creator (`makeGetVisibleTodos` in [reselect docs](https://github.com/reduxjs/reselect/tree/v3.0.1#sharing-selectors-with-props-across-multiple-components)) that memoize the selector caching by props, so you don't need to use `re-reselect`, right?

But I still don't like the structured selector API:
```ts
const selection = select(models => ({
  foo: state => models.sample.foo(state, 'foo'),
})
```
and
```ts
const selection = select(models => ({
  foo: models.def.uwv,
  baz: models.abc.xyz
})

const mapState = (state, props) => selection(state, {
  value: props.value + 42
})
```

It's hard to make proper typings for it and use it in app.
For me a better API would be:
```ts
const mapState = select((models, props) => ({
  foo: models.def.uwv(props.foo),
  baz: models.abc.xyz(props.baz),
  bar: models.foo.bar,
})
```

**Comment by d3dc** [comment]
I was going to object to props in a "selector maker", but, AFAICT, using a `structuredSelector` doesn't do much. It avoids creating a new object around the already cached results and then a new object is still created by `connect`.

I guess, in the event a selector is not memoized, it still will be cached at the component level - which is somewhat desirable. (e.g. just using vanilla functions)

I have some thoughts around the specifics of the `curryRight` that would need to happen, but I would have to implement it.

I think the biggest problem here is still the confusion around when selectors are "made". How would you pass props to a dependency of `models.abc.xyz`?

**Comment by d3dc** [comment]
Sidebar: I am beginning to doubt my intuition on the common use-cases for `hasProps`.

It assumes components that are rendered at the same time won't request different expensive computations.
1. In a list view, the database is cached and rows in a table will just select different ids - the first cache holds.
2. In a detail view, derived data is cached based on the subject - the second cache holds.

**If you're selecting dependencies, they can invalidate the first cache, causing future detail selectors to have separate caches. If your components are completely decoupled, there's no detail data passing, so they must all render together and without having a selector dependency that invalidates the cache**

**Comment by d3dc** [comment]
Sidebar: I am beginning to doubt my intuition on the common use-cases for `hasProps`.

It assumes components that are rendered at the same time won't request different expensive computations.
1. In a list view, the database is cached and rows in a table will just select different ids - the first cache holds.
2. In a detail view, derived data is cached based on the subject - the second cache holds.

**If your components are completely decoupled, they must all render together and without having a selector dependency _somewhere_ that invalidates the cache** 

```
hasProps((models, props) => createSelector(
  models.db('A'), // one cache
  models.db('B'), // new cache
  ...
))
```

**Comment by semoal** [comment]
We'll this issue was opaque to me until now.
We're close to release v2.0.0 with a full rewrite of Typescript and the typing system.
But... We have issues with select plugin.. @MichalLytek   already two years passed but probably you could guide us a bit #828 

I currently suck writing complex types and we re abit stuck @tianzhich
