### ISSUE TITLE
TypeScript: dispatcher types aren't properly inferred 

### ISSUE THREAD

**Issue by ancestorak** [rematch/rematch#552]
Basic example:

```typescript
import { init, ModelConfig } from '@rematch/core';

const counter: ModelConfig<number> = {
  state: 0,
  reducers: {
    increment: (state, payload: number) => state + payload,
  },
};

const store = init({ models: { counter } });

store.dispatch.counter.increment;
/*
  ((action: Action<any, void>) => Dispatch<Action<any, void>>) & 
  ((action: Action<any, void>) => Dispatch<Action<any, void>>) & 
  ((...args: any[]) => Action<any, any>)
*/

store.dispatch.counter.foo;
/*
  ((action: Action<any, void>) => Dispatch<Action<any, void>>) & 
  ((action: Action<any, void>) => Dispatch<Action<any, void>>) & 
  ((...args: any[]) => Action<any, any>)
*/
```

typescript 3.1.3
@rematch/core v1.0.6

Am I missing something?

**Comment by ancestorak** [comment]
If I remove the `ModelConfig<number>` annotation then dispatchers are inferred correctly.
```typescript
store.dispatch.counter.increment;
// (property) increment: RematchDispatcher<number, void>

store.dispatch.counter.foo;
// [ts] Property 'foo' does not exist on type 'ExtractRematchDispatchersFromReducersObject<{ increment: (state: any, payload: number) => any; }>'.
```

It seems that `ModelConfig` signature is problematic in that it erases type information which TS can otherwise infer. Obviously I need this annotation to enforce state shape (by the way, createModel() is equivalent and suffers from the same problem).

I've managed to narrow it down by annotating only the reducers object. `ModelReducers` annotation breaks dispatcher type inference:
```
const reducers: ModelReducers<number> = {
  increment: (state, payload: number) => state + payload,
};

const counter = {
  state: 0,
  reducers,
};
```
It seems that [`ModelReducers` type](https://github.com/rematch/rematch/blob/7d65cdf8ac822a97bcd29726d7d56c63a8f4f485/src/typings.d.ts#L124) is the culprit. 

@ShMcK [You wrote the current version](https://github.com/rematch/rematch/commit/48caab0b80dc5afdd27cc5e871c534126b797b02), any ideas how we can improve it futher?

**Comment by ShMcK** [comment]
Have you tried using `createModel`?

See an [example](https://github.com/rematch/rematch/blob/master/examples/ts/count/src/models/dolphins.ts).

**Comment by ancestorak** [comment]
Yes I did.

Passing state type explicitly (i.e. `createModel<ExampleState>()`) in order to enforce state type breaks type inference for dipatchers.

**Comment by ShMcK** [comment]
I wish I could be more help. I'm neither the author or a consumer of the typings. 

Perhaps @brunolemos may offer some greater insight?

**Comment by d3dc** [comment]
Have you tried using a type assertion in createModel?
`state: ... as AType`

**Comment by ancestorak** [comment]
I've just tried it, same result.

**Comment by d3dc** [comment]
I'm trying to wrap up a couple of utilities finally and am running into big typing issues when I start using typescript in my tests. A lot of it revolves around the `RematchDispatcher` types discussed here and other places; I'm piggybacking since this is the latest.

@ShMcK I'm not sure I've seen `ts-jest` used correctly in the current project - is there a reason for all the tests to be in javascript? Would the `'ts-jest'` preset be better to use?

On the topic of `RematchDispatch`, is there a reason for the union on RematchDispatcherAsync?

An effect can never map to:
```
((action: Action<P, M>) => Promise<Redux.Dispatch<Action<P, M>>>) &
((action: Action<P, void>) => Promise<Redux.Dispatch<Action<P, void>>>) &
```

And `Redux.Dispatch` will never map to:
```
(payload: P, meta: M) => Promise<Action<P, M>>)
```

Is this for some sort of library typing compatibility?
