### ISSUE TITLE
Error: Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by Dugnist** [rematch/rematch#555]
![screenshot from 2018-10-23 10-57-55](https://user-images.githubusercontent.com/6489460/47345271-04092b80-d6b3-11e8-9c5a-fc6712aad615.png)
![screenshot from 2018-10-23 10-59-05](https://user-images.githubusercontent.com/6489460/47345272-04092b80-d6b3-11e8-922d-a1d807176443.png)
![screenshot from 2018-10-23 11-00-01](https://user-images.githubusercontent.com/6489460/47345273-04a1c200-d6b3-11e8-9629-ca02833cee71.png)
![screenshot from 2018-10-23 11-04-35](https://user-images.githubusercontent.com/6489460/47345466-7aa62900-d6b3-11e8-815b-373dc932e8c5.png)

**Comment by d3dc** [comment]
I answered a little hastily before. In Rematch, the dispatch function is augmented with pre-bound dispatchers. Passing an object as the second argument to `connect` will attempt to be bind all of it's members. 

You're trying to `bindActionCreators` with functions that do not create actions.

**Comment by Dugnist** [comment]
@d3dc so can you help me with it, please? I can't find the right solution to this problem in your documentation. What do I need to do to pass correct effects to the second argument to connect?

**Comment by Dugnist** [comment]
@d3dc ok I got it)
![image](https://user-images.githubusercontent.com/6489460/47350005-826acb00-d6bd-11e8-8993-671db31acce3.png)
