### ISSUE TITLE
how to load initial state asynchronously

### ISSUE THREAD

**Issue by nyrf** [rematch/rematch#556]
```js
const getCount = async () => {
  const result = await api.getCount()
  return result
}
export const count = {
  state: getResult(),
  reducers: {
    increment: s => s + 1,
    decrement: s => s - 1,
    up: (s, num) => s + num
  },
  effects: dispatch => ({
    async asyncIncrement() {
      await new Promise(resolve => {
        setTimeout(resolve, 1000)
      })

      dispatch.count.increment()
    },
  }),
}
```
the code seems not work. any plugin? Thanks.

**Comment by d3dc** [comment]
What would the app display while loading? 🤔

**Comment by jackwilsdon** [comment]
I think @d3dc is asking what you expect the state to be whilst it's loading — you're currently storing the returned promise in the state which isn't a good idea.

**Comment by nyrf** [comment]
Sorry for my weak english.  i want to load shop cart info from database, the api 
```json
{data: [{id: 1, name:' name', count: 10}, {id: 2, name:' name', count: 1}]}
```
in models.js,
```json
 state: []
```
i want to load cart from the api. any way? thanks.

**Comment by d3dc** [comment]
I'm not too clear on the hold up. Were you not able to find this in the docs? I guess it might be a little in the vein of a stackoverflow question...

**You can do your api request in an effect and call that effect when your application loads.**

This could just be in an `index.js`:
```
render(..., ...)
store.dispatch.count.getCount()
```

You could have a coordinating `app` model:
```
const app = {
  state: {
     // webworker cache status etc.
  },
  effects: dispatch => {
    started() {
      dispatch.count.getCount()
    }
  }
}
```

If your app is modular, you could go with my favorite, a declarative component:
```
const CountModule = routing =>
  <ProvidesModel model={count}>
    <TriggersEffect effect={dispatch => dispatch.count.getCount}>
      {routing}
    </TriggersEffect>
  </ProvidesModel>
```

(I threw up in a gist for an example of `TriggersEffect`)[https://gist.github.com/d3dc/c206a24da8c8ce42115b28d7ec445847]

**Comment by nyrf** [comment]
@d3dc Sorry, I didn't express clearly, i want to initial state in models. 

```js
const app = {
  state: {
     // initial state from api
 },
  reducers: {}
   effects: dispatch => ({

  }),
}
```

**Comment by d3dc** [comment]
Before your api has responded, what do you expect your app to be displaying?

**Comment by nyrf** [comment]
Before api has responded, the initial state can be empty, eg, after user login, cart get data from api. I store cart items in localstorage.
```js
const app = {
  state: window.localStorage.getItem('cartItems') || [],
  reducers: {}
   effects: dispatch => ({

  }),
}
```
when i get data from api,

```js
const app = {
  state: api.getItems(),
  reducers: {}
   effects: dispatch => ({

  }),
}
```
it seems not work.

**Comment by nyrf** [comment]
Thanks, i try to get data from api in `componentWillMount ` and initial state, it seems work.

cart.js
 
```js
const mapState = state => ({
  cart: state.cart
})


async componentWillMount () {
    this.props.initData()
}
```

models.js

```js
export const cart = {
  state: [],
  reducers: {
    init (state, payload) {
      return payload
    }
  },
  effects: dispatch => ({
    async initData () {
      const data = await api.getData()
      dispatch.count.init(data.data)
    }
  }),
}
```
