### ISSUE TITLE
immer and persist can't work together

### ISSUE THREAD

**Issue by nyrf** [rematch/rematch#557]
When use immer and persis together, seems not work.
```js
const store = init({
  models,
  plugins: [selectPlugin(), immerPlugin(), persistPlugin]
})
```

**Comment by beilunyang** [comment]
I also met the same problem, Have you solved it?

**Comment by Coder-JJ** [comment]
try this out: [rematch-immer-combine-persist](https://github.com/Coder-JJ/rematch-immer-combine-persist)
