### ISSUE TITLE
Using selectors inside effects

### ISSUE THREAD

**Issue by ancestorak** [rematch/rematch#558]
As far as I can see, selectors are not provided to effect functions, unlike dispatch. I can't import them from store either because it creates a circular dependency. Am I missing something?

**Comment by d3dc** [comment]
I've had success just using `select` as a circular dependency, as long as its not called until the body of the effect.

There's a little bit of discussion for just using a DI container in [this post I made](https://github.com/rematch/rematch/pull/467#issuecomment-427756662). I'm not sure the best way to implement this. There were a few PRs trying to include a second argument by default and I'm thinking a decorator for opt-in makes sense - so there's no intersection with Rematch really.

**Comment by ptsurko** [comment]
@d3dc  Why not to pass store instead of rootState in effect function? with async effect rootState is changing over time and does makes any sense. when you pass store instead of rootState - we can do `store.getState` and get current actual state at any time. 

How about change effect function api to pass store as 4th parameter to avoid breaking changes?

For me right now I made plugin to inject store:
``` javascript
const injectStorePlugin = {
  onModel(model) {
    for (const effectName of Object.keys(this.effects)) {
      const func = this.effects[effectName];
      this.effects[effectName] = (payload, rootState, meta) => {
        return func(payload, rootState, meta, this.localStore);
      };
    }
  },

  onStoreCreated(store) {
    this.localStore = store;
  }
};

export default injectStorePlugin;
```

**Comment by d3dc** [comment]
@ptsurko I have gravitated toward a similar custom plugin exposing a limited API.

I generally disagree with calling `getState()` in an effect, as, at least to me, that seems like what effects abstract for us. Chaining effects in the actual base model is exactly the same as how other models extend and hook into its flow.

**Comment by slashwhatever** [comment]
> @d3dc Why not to pass store instead of rootState in effect function? with async effect rootState is changing over time and does makes any sense. when you pass store instead of rootState - we can do `store.getState` and get current actual state at any time.
> 
> How about change effect function api to pass store as 4th parameter to avoid breaking changes?
> 
> For me right now I made plugin to inject store:
> 
> ```js
> const injectStorePlugin = {
>   onModel(model) {
>     for (const effectName of Object.keys(this.effects)) {
>       const func = this.effects[effectName];
>       this.effects[effectName] = (payload, rootState, meta) => {
>         return func(payload, rootState, meta, this.localStore);
>       };
>     }
>   },
> 
>   onStoreCreated(store) {
>     this.localStore = store;
>   }
> };
> 
> export default injectStorePlugin;
> ```

Little follow up on this for readers; this no longer works in @rematch/core v2
