### ISSUE TITLE
How to call effects after reducer action ?

### ISSUE THREAD

**Issue by MaronMariusz** [rematch/rematch#561]
Hi.

What I mean in the title is situation like I want to call effect inside some action that modifies store has beed dispatched.

```
init({
  model: {
    first: { reducers: { setName: ... }},
    second: { effects: { getPayload() { ... }} }
  }
})
```

Let's say that I clicked in a button and it calls `setName` but after that call (before the state change) I would like to run `getPayload` from second model which call api immediately (or even the same model). Is it possible ? What's the good practice for that kind of situation ?

Cheers!

**Comment by d3dc** [comment]
you can use a listener reducer:
```
reducers: {
 'otherModel/one': ...
}
```

Naively, this sounds like setName has a side-effect:

```
async setName(name, rootState) {
  const updated = { ...rootState.model.data, name }
  const payload = await api.getPayload(updated)
  return this.loadedData({ ...updated, ...payload})
}
```

You can't batch an effect after a reducer without another dispatch loop - I try to think of it in terms of state transitions and not hooking function calls (which flux tries to avoid imo).

**Comment by koss-lebedev** [comment]
You can define your first model like this:

```ts
{
  reducers: {
    setName: (state, name) => ({ ... }),
  },
  effects: dispatch => ({
    async setNameAsync(name) {
      await dispatch.first.setName(name)
      await dispatch.second.getPayload()      
    }
  })
}
```

And then call `setNameAsync`

**Comment by jackwilsdon** [comment]
Seems like #246 would allow you to achieve this, but it's been closed for some reason.

**Comment by erikmueller** [comment]
If I understood that correctly you could achieve a similar pattern as with sagas take (and then do various things and dispatch other actions) with these effect subscribers (which is in my opinion much more intuitive than using a saga). Am I missing something and can we just reopen #246 (Seems like it fell victim to the stale bot)?
