### ISSUE TITLE
Please polyfill @rematch/core

### ISSUE THREAD

**Issue by hisanshao** [rematch/rematch#564]
The webview of most Android phones cannot use rematch because the kernel version is too low. please do polyfill for those

**Comment by linonetwo** [comment]
Why not bring your own polyfill?

**Comment by hisanshao** [comment]
@linonetwo  I use @babel/preset-env  "useBuiltIns": "usage" , and webpack module.rules include @rematch , but it`s not work. 
only require("@babel/polyfill") is work. but i don`t want to include the whole polyfill which isn't always needed

**Comment by hisanshao** [comment]
here is an issue about babel 7 can't compile in node_modules, i found the solution here [https://github.com/babel/babel/issues/8672](url)

**Comment by hisanshao** [comment]
there is an error 'init is not a function' about @rematch/core  after polyfill by using @babel/preset-env.

**Comment by linonetwo** [comment]
Maybe you are importing an "undefined" so its not a function.
Can you log what is imported? `import aaa from '@rematch/core'; console.log(aaa);`
Try to figure out what's going on.

**Comment by hisanshao** [comment]
import rematch from '@rematch/core'  or
import  * as rematch from '@rematch/core' or
import { init } from '@rematch/core'
yes, after polyfill  is all "undefined". so how to resolve it.
