### ISSUE TITLE
Conflicting LICENSE (MIT LICENSE, ISC SPDX)

### ISSUE THREAD

**Issue by dcousens** [rematch/rematch#565]
In https://github.com/rematch/rematch/pull/24 it is clear you (@blairbodnar, @ShMcK) chose MIT as your license,  and your LICENSE file is that.

But your SPDX identifier on `npm` is released as `ISC`.

**Comment by dcousens** [comment]
Ref: https://github.com/rematch/rematch/blob/b3e809836696dd0b9948a6ddfe7aef268ec5e8bd/package.json#L16

**Comment by dcousens** [comment]
The same is for each of your plugins.
Are they ISC or MIT?

**Comment by millette** [comment]
ISC is npm's (strange) default. A PR would probably be welcome :-)
