### ISSUE TITLE
Reducer action does not pass all parameters

### ISSUE THREAD

**Issue by saraivinha85** [rematch/rematch#569]
Hello,

I'm trying to use this library in a new project.
One issue that I found weird is that if I have a reducer with 3 parameters only the first 2 are populated.

See the counter example to show what I mean:
[demo](https://codesandbox.io/s/x34m04wl0o)

I've added a reducer that takes 3 parameters that are added up to the counter, but since the last one is undefined the counter is now set to NaN.

Please advice.

**Comment by jackwilsdon** [comment]
That's correct - Rematch's dispatch methods accept a payload and meta value as the first two arguments, as can be seen here;

https://github.com/rematch/rematch/blob/b3e809836696dd0b9948a6ddfe7aef268ec5e8bd/src/plugins/dispatch.ts#L37

You're being given those as the first two arguments to your reducer, which has a signature like so;

```JavaScript
function reducer(state, payload, meta) { ... }
```

You can see this from how your reducer is called from Rematch here;

https://github.com/rematch/rematch/blob/b3e809836696dd0b9948a6ddfe7aef268ec5e8bd/src/redux.ts#L54

**Comment by saraivinha85** [comment]
I see.. thanks for the heads up.

I think the information that you provided should be in the documentation as it's really confusing.

**Comment by d3dc** [comment]
This is more of a redux thing than a rematch thing, and that might be why its not well represented in the docs. Of course, if we want to be looked at like a framework, I definitely think we need resources for beginners too.

I think more important than how Rematch wires things might be:

Redux is based on message passing. Every message has the same shape:
```
{ type: string, payload: any, meta: any }
```

All Rematch steps in to do is translates these redux messages to function calls on your models.
