### ISSUE TITLE
.prettierrc overrides global parser

### ISSUE THREAD

**Issue by d3dc** [rematch/rematch#570]
[Currently the root `.prettierrc` has `parser: "flow"` specified](https://github.com/rematch/rematch/blob/master/.prettierrc#L8). This overrides the parser for all file types.

This causes editor plugins to be unable to format json and other formats that aren't parsable by flow.

AFAICT, we don't need this option. Is the fix to remove it?

if it was meant to override parsing for certain file types we can add e.g.:

```
"overrides": [
    {
      "files": "*.test.js",
      "options": {
        "parser": "flow"
      }
    }
  ]
```

**Comment by ShMcK** [comment]
Happy to merge any PR that makes this easier 👍 

I understand the frustrations when supporting plugins within the same repo.
