### ISSUE TITLE
How do you handle authentication

### ISSUE THREAD

**Issue by kane77** [rematch/rematch#573]
I have several models, most of which are 'entities' that all have CRUD endpoints. So I have a Crud class that provides all the functions. This works fine, but recently I've been trying to add authentication to the endpopints and I struggle.
The way it's currently structured gives me circular dependency, because in my Crud class I check for 403 and if received I dispatch logout action. But the Crud class is initialized in each model, and models are initialized when creating store and I use store in Crud class (or dispatch more precisely).

**Comment by kane77** [comment]
So far I've come up with something like that:

effects: (dispatch) => ({
    async deleteLocationAsync (id: string, state: State) {
      const options = {
        endpoint: `/locations/${id}`,
        method: 'delete',
        success: () => this.deleteLocation(id),
        token: token(state)
      }
      await crudAction(options, dispatch)
    }
}

**Comment by d3dc** [comment]
Without seeing an example of your first post, I'm a little lost 😬.

What you're doing in the second post looks right. I like the composability of `crudAction` too - I might have a crud model in the store that's much larger. 

My API is usually setup as methods pre-bound to the end-points - just so my redux isn't too bloated. 

I also use a fetch API that returns `Promise`.

So, my grand change would be:
```js
async deleteLocationAsync (id: string, state: State) {
  try {
    await dispatch.crud.request(locationsAPI.remove)
    return this.deleteLocation(id)
  } catch (e) {
    return dispatch.error.handleWithToast('Try Again, Chump!', e)
  }
}
```

**Comment by semoal** [comment]
I do an async call to my api, that returns a token -> stored on cookies, now I have two things:
1. A high-order component that checks PrivateComponents (Must be logged in)
2. And an interceptor on Axios for every http request, put that Bearer Token (if this returns a 403, it goes directly to an error reducer, that handle this error (delete state, redirect....)

I have to implement yet another high order component that checks session activity, and logouts when token is about to expiry, if the session has activity it's refresh the token.
