### ISSUE TITLE
Destructuring assignment of the dispatch works weird!

### ISSUE THREAD

**Issue by julytang** [rematch/rematch#575]
This problem is quite weird and complex. 
First I initialed my model like this, remember the order of the models' keys,
```
const models = {
  page,
  shop,
  template,
};

const store = init({
  models,
});
```
page->shop-template.
Second, I create effects in model **page** to dispatch a effect or reducer in model **template**
This one works normally.
```
effects: (dispatch) => ({
    acc: () => {
      dispatch.template.useTemplate();
    },
  }),
```
But that one, the useTemplate function is undefined.
```
effects: ({ template: { useTemplate } }) => ({
    acc: () => {
      useTemplate();
    },
  }),
```
But there is a method to make it work. You just change your init code to
```
const models = {
  shop,
  template,
  page,
};

const store = init({
  models,
});
```
That works great.

But I think it is a right behavior for it. So I need your help.
Thanks a lot.

**Comment by ShMcK** [comment]
So destructuring of the dispatch is producing an `undefined` function. 

This is due to some hackery. In JS, everything is an object - even functions.

In order to allow both `dispatch(action)` and `dispatch.model.action` to work, we applied `.model.action` to the function prototype. It was really the only way to avoid a breaking change from normal Redux along with a more desired API.

As we've both just discovered: you can't destructure a function.

**Comment by d3dc** [comment]
@ShMck The dispatch plug-in sets every model's dispatch to an empty object. The effect plug-in is then running, and has not yet run the `template` model effect factory.

**Comment by julytang** [comment]
@d3dc @ShMcK According to the usage of dispatch, it's more likely a combination of actions grouped by models, it's more similar to Object rather than Function. In my opinion, models should load when store initialed instantly. @ShMcK Function is also an Object in javascript, so you can add any property to it just like what you do to Object. More confusion I got is that the two different usage of dispatch a good practice.

**Comment by d3dc** [comment]
@julytang The factories have to be run _in some order_...

The only way I can think of to make the result of every other factory available before they've all been called (intractable) would be to use a `Proxy` to allocate wrappers if a dispatcher hasn't yet been constructed. There's some browser compatibility issues, but it might be worth experimenting with.
