### ISSUE TITLE
React example contains an error

### ISSUE THREAD

**Issue by miraage** [rematch/rematch#577]
https://codesandbox.io/s/92mk9n6vww

The `remove` reducer function violates purity.

```js
remove(state, id) {
  delete state[id] // <<< mutates state
  return {
    ...state
  }
}
```

Should be written in another way, e.g.
```js
remove(state, id) {
  return Object.keys(state).reduce(
    (acc, cur) => {
      if (cur === id) return acc
      acc[cur] = state[cur]
      return acc
    },
    {}
  )
}
```

**Comment by d3dc** [comment]
But that state is immediately replaced with a copy (and a new ref) of that state before anything else could read it...

If a tree falls in the woods and no one is there to hear it, does it make a sound?

**Comment by miraage** [comment]
In the current example it may be okay, but overall it is a bad practice, usually leading to bugs.
Feel free to close this issue if you think that it is not important for this case.

**Comment by ShMcK** [comment]
Closing as already fixed. Thanks!
