### ISSUE TITLE
Fix readme with how to use connected-react-router with rematch

### ISSUE THREAD

**Issue by alexicum** [rematch/rematch#578]
[Should I use this?](https://github.com/rematch/rematch/issues/409#issuecomment-397116435)

or may be there is another way?

And there is an old recipe with [react-redux-router .../redux.md](https://github.com/rematch/rematch/blob/master/docs/recipes/redux.md)

**Comment by d3dc** [comment]
This has reminded me: The recipe doesn't actually call `bindActionCreators` and you would have to wrap the action creators somehow:

```
effects: {
  push: (...args) => dispatch(push(...args))
}
```

Just to advertise: I also spit-balled a way to fix up the encapsulation here and a better way to distribute recipes in #572 - The big unknown of course is the recipe packaging.

**Comment by nuttikung** [comment]
I have the same problem with react router before for my solution I migrate to use ConnectedRouter.

You can try : https://codesandbox.io/s/72o3k1z3nq
