### ISSUE TITLE
[QUESTION] update state direct in effects

### ISSUE THREAD

**Issue by lizheming** [rematch/rematch#581]
As title said, could we update state in effects directly instead of dispatch reducer?

```js
// count.js
export default {
    state: 0,
    reducer: { 
        update(state, val) {
            return state + val;
        }
    },
    effects: dispatch => ({
         async updateAsync(payload, state) { 
              const resp = await fetch(payload);
              //? return state + resp
              dispatch.count.update(resp);
        }
    })

}
```

**Comment by d3dc** [comment]
Late to the party here, but:

Replaying an action log could have different state updates occur depending on how `await fetch(payload)` went.

This has the potential to make state changes non-deterministic, no?

**Comment by lizheming** [comment]
Thank you for your reply, I understand what you said and agree with you very much.
