### ISSUE TITLE
【FYI】If you crashed into the error: 'You may not call store.getState() while the reducer is executing.'

### ISSUE THREAD

**Issue by Jemair** [rematch/rematch#584]
This is not rematch's problem but a redux devTool one. 
Take a look at https://github.com/zalmoxisus/redux-devtools-extension/issues/588#issuecomment-442319942

**Comment by Jemair** [comment]
it has been fixed, seems like no one faced my issue

**Comment by FullStackerWeb** [comment]
Hi @Jemair 

Same issue on here.
I'd like you to let me know how I can fix this issue with a more detail explanation.

Regards.
