### ISSUE TITLE
effect be invoked incremently each request server side with next.js

### ISSUE THREAD

**Issue by garbin** [rematch/rematch#586]
in next.js `getInitialProps` will be invoked server side each request, we can do something data initializing here. it works well with normal `redux action` but rematch `effects`, so I think this issue is `rematch` related no `next.js`.
pseudocode
```js
static async getInitialProps ({store}) {
  store.dispatch.counter.test() // this reducer only be invoked once each request as expected
  await store.dispatch.counter.incrementAsync(1) // this effect will be invoked n+1 times (n is the times you refresh page) as unexpected
return {}
}
```

here is the repo you can reproduce this issue, any idea? https://github.com/garbin/next-rematch-issue
```
$ npm run dev 
```
reproduce step
```
1.`npm run dev`
2. access http://localhost:3000
3. watch console.log in terminal
4. repeat from step 2.
```

**Comment by d3dc** [comment]
This bug seems well documented. I'm tagging it and reopening it.
