### ISSUE TITLE
[QUESTION] Effects axios request cancelation

### ISSUE THREAD

**Issue by Skeeev** [rematch/rematch#587]
Hello there,

I faced a problem with a cancelation of `axios` requests from my `rematch` effects. To be more precise, the problem is that I have a drop-down component, which sends data requests via `effect` on each change. I need to cancel the previous request if I change drop-down item before a request is done. `Axios` has cancel token for such situations and f.e. `redux-saga` has an approach to handle such situations using it. Do we have an existing solution for such cases in `rematch`? Or I should create my own plugin for this?

**Comment by d3dc** [comment]
@Skeeev 

I might naively say there's nothing stopping you from doing this as a side-effect in an effect -
```js
effects: dispatch => {
  const request = null

  return {
    startRequest() {
       if (request) {
         request.cancel()
       }
    }
  }
}
```

You might also be able to return active requests from a selector and consider Ajax requests derived values somehow.
