### ISSUE TITLE
Reverting all models to initial state when logging out.

### ISSUE THREAD

**Issue by suazithustra** [rematch/rematch#595]
How would you guys do this without putting
```
'auth/logout': (state) => {
  state = null
  return { ...state }
}
```
in every model?

**Comment by rmlzy** [comment]
mark

**Comment by semoal** [comment]
You can create a rootReducer, rematch works perfectly with Redux things.
Here you have an example using Redux: https://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store/35641992#35641992

**Comment by d3dc** [comment]
You can also re-use a base reducer per model:

```js
import { resetsOnLogout } from './auth'

const model = {
  baseReducer: resetsOnLogout,
  ...
}
```

**Comment by suazithustra** [comment]
thanks guys

**Comment by gungdeaditya** [comment]
I'm sorry, can you please providing snippet example of doing resetting state with baseReducer ?

**Comment by acnebs** [comment]
Looking to how this would be done in pure Redux is probably needlessly complicated.

@gungdeaditya, this is the solution I'm using, and I think it is fairly elegant / concise.

Init the store with the rootReducer you need.
```
const store = init({
  plugins,
  models,
  redux: {
    rootReducers: {
      RESET_APP: (state, action) => undefined,
    },
    devtoolOptions: {
      disabled: process.env.NODE_ENV === 'production',
    },
  },
});
```

And then call RESET_APP whenever you need to by sending a message, ala classic Redux.
`dispatch({ type: 'RESET_APP' })`
