### ISSUE TITLE
[Issue] has no exported member 'getSelect'.

### ISSUE THREAD

**Issue by canyavall** [rematch/rematch#606]
I was checking the documentaiton and in order to make typescript work with select plugin, the documentation says:

```
To enable autocomplete of select, use getSelect with the select plugin. See example below:
import selectPlugin, { getSelect } from '@rematch/select';
import { init } from '@rematch/core';
import * as models from './models';

export const select = getSelect<models>();

export const store = init({
  plugins: [selectPlugin()],
  models,
});
```

If I do it I get:

```
TS2305: Module '"../node_modules/@rematch/select/src/typings"' has no exported member 'getSelect'.
```

Is the documentation outdated?

**Comment by danawoodman** [comment]
Same issue here. Opening the type file shows that the `getSelect` type definition does not exist.

```js
    "@rematch/core": "1.0.6",
    "@rematch/immer": "1.1.0",
    "@rematch/select": "2.0.3",
```

**Comment by semoal** [comment]
I'll check this asap too!

**Comment by kevinluvian** [comment]
hi, is there any updates? @semoal

**Comment by semoal** [comment]
As you can see in this commit I found, getSelect got removed for getting autocomplete always when using @rematch/select plugin.
https://github.com/rematch/rematch/commit/148e8100cda5a8da4a705d8b261fed8ce5950778#diff-adfd610834090020180c37221296a7e0

I'll open a new issue, for updating the docs.
