### ISSUE TITLE
TypeScript 3

### ISSUE THREAD

**Issue by phmatray** [rematch/rematch#607]
Hello and thank you for this fantastic library. I use it on a daily basis in an open-source project 

With a fresh installation of Rematch, npm gives me the following errors. 

```
npm WARN @rematch/loading@1.1.2 requires a peer of typescript@^2.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN @rematch/select@2.0.3 requires a peer of @rematch/core@>1.0 but none is installed. You must install peer dependencies yourself.
```

Could we consider an upgrade of the peerDeps to TypeScript 3 and rematch/code@^1.0.6?

**Comment by canyavall** [comment]
Ummm, it is strange, for the select plugin it requests the     "@rematch/core": "^1.0.6", you shouldn't have this issue actually

**Comment by ShMcK** [comment]
The latest release `@rematch/core@1.1.0` now uses TS 3+.
