### ISSUE TITLE
Request feature: Using React Hooks (16.8) in Rematch

### ISSUE THREAD

**Issue by semoal** [rematch/rematch#610]
We should try to give this library a push, has a big future, so easy to use and brilliant performance.

- We should see if someone has time, to build a Plugin for use rematch models with React Hooks (16.8), to access stateToProps, and dispatch simpler.
- I think we need some maintainers here, I see the project a bit abandoned.

I'm open to discuss everything, and I'm glad to help If i am able to.

Thanks you guys-

**Comment by jackwilsdon** [comment]
It's probably worth keeping an eye on https://github.com/reduxjs/react-redux/issues/1177, as without it I'm not sure how much we can do (especially if efficiency is a concern).

**Comment by canyavall** [comment]
For what I could read react-redux library has some performance issues, we will have to wait.

Anyway, if I'm not wrong, there is nothing we can do to move rematch into Hooks, actually, rematch is not a project specific for React, as you can see in the package json, it is an abstraction layer for redux. That means (I didn't check it) that the project maybe could be used in Vue, Angular and plain javascript with the corresponding libraries (like react-redux)

I agree with you that the project looks a bit abandoned, despite there are some PR and some ideas on the table (and bugs) and the project has almost 5k stars

**Comment by semoal** [comment]
You're right didn't tough about this was just a framework of redux instead of React, my bad.
