### ISSUE TITLE
New Maintainer(s) Wanted

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#611]
Unfortunately, do a shift in career paths I haven't been doing much frontend work over the past 6 months. My mind is somewhere else. As a result, I haven't invested much time in Rematch - I've fallen behind in responding to issues, merging PRs and publishing on NPM. I'd love to see the project continue to move forward and would be happy to help with any transition. 

If you're interested in being a primary maintainer of Rematch, drop a comment below.

**Comment by H2rmone** [comment]
Hello, I'd like to try it if I can. Last year I migrate from redux to rematch in our productions. And our front-end team found it easier to resolve app state with rematch. Also I created a PR about browser support because one of our production has very low version requirement.

**Comment by SuJunming** [comment]
I would like to try it

**Comment by ShMcK** [comment]
@H2rmone I'll send you an email, let's chat.

**Comment by tanvirraj** [comment]
Hey @ShMcK . 
we are doing a very big project in rematch. and we are very much happy with that. we also decide to do our next project with rematch. actually next all project . 
i would love to contribute

**Comment by ShMcK** [comment]
@tanvirraj I've sent you an email as well, let me know if you're available for a chat.

**Comment by semoal** [comment]
Same here, we're developing all our newest products with Rematch, actually the learning curve and organization of the project much easier than standard redux.

I'm not experimented with TypeScript, but I could help reviewing pull request, and giving some help to people.

We can chat if you want @ShMcK

**Comment by ShMcK** [comment]
@semoal I'll shoot you an email as well.

**Comment by derrickbeining** [comment]
I'd like to give a hand. I've been migrating a project to rematch at work, and I just started a greenfield react-native project that I'm designing with rematch from the get-go. I've also spent a good deal of time trying to get a decent TypeScript experience with rematch, and think I might be able to improve the situation on that front if I can find the time.

**Comment by canyavall** [comment]
In our company we are using rematch every where, I'd like to help but my level is not enogh.... Anyway, I'll try to support as much as I can this library ^_^

**Comment by wenber** [comment]
@ShMcK  I get one problem when I use  rematch。  If use a <Input  value={this.props.inputValue} onChange={this.props.actions.change} />   .when I input chinese . I find  only can input   English alphabet。 I will send you an email to  let  you see。

**Comment by semoal** [comment]
> @ShMcK I get one problem when I use rematch。 If use a （Input value={this.props.inputValue} onChange={this.props.actions.change} ） .when I input chinese . I find only can input English alphabet。 I will send you an email to let you see。

Open an issue for this, don't make a mess of this discussion.

**Comment by abdih** [comment]
I'd be interested in helping out, if you want to send me an email :smiley:. Thanks in advance.

**Comment by kole** [comment]
Oh man, yes let's please keep this project moving forward! SOOOOO much better than redux. I am happy to contribute if you still need people.

**Comment by olso** [comment]
#633

**Comment by HiMrHu** [comment]
I want to be a part of it. I've been using rematch for almost a year now and actively recommend it to others. However, my weakness is that my English is bad

**Comment by Yu1989** [comment]
Have we decided on this? Would love to see an awesome project like this gets maintained properly!

**Comment by hardfist** [comment]
we heavily use rematch in our product and nearly fix rematch's typing problem, and I would like to do some help, especially about typescript problem

**Comment by uy-xela** [comment]
> we heavily use rematch in our product and nearly fix rematch's typing problem, and I would like to do some help, especially about typescript problem

Is it possible that you guys can share a forked version of rematch with better support for typescript? We also heavily use rematch in our typescript project and it would really help us. 😄

**Comment by ShMcK** [comment]
I've added anyone who commented here as wanting to be a collaborator.
This grants you write access for merging PRs (with enough approvals).

I think for security purposes I'll maintain npm publishing control. I've heard some horror stories. If I'm slow to respond, shoot me an email.

Does that sound reasonable?

**Comment by DalderupMaurice** [comment]
> we heavily use rematch in our product and nearly fix rematch's typing problem, and I would like to do some help, especially about typescript problem

What exactly are the TS problems?
We were debating to start using rematch (in a TS project) now that development is active again
