### ISSUE TITLE
Is there no communication group?

### ISSUE THREAD

**Issue by SuJunming** [rematch/rematch#613]
Is there no communication group?

**Comment by SuJunming** [comment]
qq. WeChat.

**Comment by ShMcK** [comment]
There's Github :)

**Comment by SuJunming** [comment]
Can you provide China's exchange group? Or I can create it.

**Comment by SuJunming** [comment]
Do I have to await every interface request. If I don't have to wait, but update the UI when the data request is completed?

**Comment by SuJunming** [comment]
Does multiple waiting block UI rendering? Is there demo?
