### ISSUE TITLE
 Does multiple waiting block UI rendering? Is there demo?

### ISSUE THREAD

**Issue by SuJunming** [rematch/rematch#615]
Do I have to await every interface request. If I don't have to wait, but update the UI when the data request is completed?
Does multiple waiting block UI rendering? Is there demo?

**Comment by jackwilsdon** [comment]
This library is a layer over Redux — it works in a very similar way.

This library shouldn't block UI rendering, as it's just a state management tool. Take a look at the loading plugin see how loading states can be handled.

**Comment by SuJunming** [comment]
But not always use async await. Otherwise, the asynchronous callback data can't be saved. I hope I can still trigger an action to update the UI after I don't wait.

**Comment by canyavall** [comment]
then don't declare the function as an async function so you don't expect a promise and don't have to await ^_^

**Comment by semoal** [comment]
As @jackwilsdon Rematch is a layer over Redux, so the library probably never will block UI rendering, you just have to handle when your state has data or not.
