### ISSUE TITLE
Missing typings definitions for `persist` model

### ISSUE THREAD

**Issue by gungdeaditya** [rematch/rematch#621]
I got warn once installed @rematch/typed-state. But another models got no error since I add typings inside. How to fix this kind of error ?

**Comment by gungdeaditya** [comment]
I'm using `import storage from 'redux-persist/lib/storage/index.native'`

**Comment by semoal** [comment]
Could you provide an example of code?

**Comment by semoal** [comment]
@gungdeaditya can i close this?
