### ISSUE TITLE
Chinese translating to English

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#623]
Issue from @wenber:

If use a `Input value={this.props.inputValue} onChange={this.props.actions.change}` .when I input chinese . I find only can input English alphabet.

**Comment by ShMcK** [comment]
@wenber - that’s very interesting.

Perhaps consider setting your html page to use Mandarin: `<html lang=“zh”>`

What result do you get if you use component `state` instead of Rematch. For example, if you use the `onChange` to set the state of a component.

I don’t believe Rematch manipulates the string values. If I'm wrong, please point me to the code inside of the `src` directory.

**Comment by semoal** [comment]
I've created this Stackblitz @ShMcK, changed my keyboard input to Chinese and without idea of it, in my opinion looks okay.

https://react-pcc6fh.stackblitz.io

**Comment by Binaryify** [comment]
it work fine on my Mac, maybe is your input method software problem
