### ISSUE TITLE
Plugin API finalization

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#64]
I recently tried to write a "loading" plugin, but found it quite hard with the current API.

There are two changes I propose:

1) all plugins should be functions (rather than objects)
2) pass `storeDispatch` in as the first? param
3) pass a config in as the second? param

This is a little simpler, though I'm not entirely happy with it yet. See an outline of changes below:

```js
const plugin = (storeDispatch: $dispatch, config: $pluginConfig) => ({
  onInit() {},                          // removed storeDispatch as param
  onModel(model: $model) {}             // removed storeDispatch as param
  middleware: (store) => (next) => (action) => {}
})
```

I'm not sure what yet constitutes a plugin config, but we can figure that out.

I think this requires more consideration, and we're likely to learn a lot more by making a list of possible plugins and which internals they would need access to.

**Comment by ShMcK** [comment]
##### Loading
- call action when effect is called
- call action when effect is completed
- access to list of effects (or list of dispatches with effects marked) to determine what is an effect (as opposed to a reducer action)

**Comment by ShMcK** [comment]
##### Last Updated
- call action when action triggering reducer is called
- access to list of actions (excluding effects)

**Comment by ShMcK** [comment]
##### React Navigation
- instantiate with `Routes`
- must have "react" & "react-navigation", loaded and possibly even "react-redux"
- navigation model
- access to "dispatch" in order to add NavigationActions dispatch options
- should wrap entire base of React app with its own provider

**Comment by ShMcK** [comment]
##### Persist
- take "redux-persist" config as a param
- init persist store, rehydrate state
- middleware to RESET_STATE. could take optional action name for resetting state
- could add a "persist" key to models. If `model.persist`, the model is whitelisted automatically

**Comment by ShMcK** [comment]
##### Validate
Validate your state based on some kind of simple schema. It makes sense to tie validation to a model if it is always validating state. I haven't thought any more beyond this.

**Comment by ShMcK** [comment]
##### Error Handling
It may make sense to also tie error messaging to a model. Also a thought.

This way if an unhandled error is thrown within an effect, there can be first:
1) a check of an error message for that specific effect
2) a check for an error message for the given model

Again, not sure if this is a good idea.

**Comment by blairbodnar** [comment]
Yes, totally agree. I think making a list of plugins and trying to implement them will really help us iron out the plugin API so that it feels right, and it has everything the user needs.

**Comment by ShMcK** [comment]
##### Redux Offline
A possible plugin that handles offline activity, retry strategy, special dispatches.
- middleware that looks for "meta: offline"
- connection status model

**Comment by ShMcK** [comment]
##### Authentication
Some kind of authentication middleware would be awesome. Needs more thought.

**Comment by ShMcK** [comment]
##### React-Router v4

**Comment by ShMcK** [comment]
##### Apollo integration

**Comment by ShMcK** [comment]
I think I'll move these plugins onto their own board, and close this issue
