### ISSUE TITLE
can rematch offer user auto bind setter

### ISSUE THREAD

**Issue by fantasticsoul** [rematch/rematch#641]
sometimes i just want to modify store state in a simple way, so can rematch offer user auto bind setter? just like below:
https://stackblitz.com/edit/cc-sync-demo

**Comment by semoal** [comment]
I'm not sure what you need mate, more simply to modify state calling a single function.
Could you be more precise? Thanks

**Comment by d3dc** [comment]
[Dan Abromav once tweeted](https://twitter.com/dan_abramov/status/793379336309071872?lang=en):
> I would add that Redux is fairly useless if you treat actions as setters and couple actions directly to reducers.

Given that, this type of mixin behavior is easily achieved when you're building your model:
```
const initialState = {
  ...
}

const model = {
  state: initialState,
  reducers: {
    myReducer() {
       // custom stuff
    },
    ...createSettersFor(initialState)
  }
}
```

**Comment by d3dc** [comment]
Another thought: if you want a root reducer to handle all of the setters, it would be easy to write a plugin that adds a `rootReducer` to the store configuration, and then adds the methods to the store's dispatch when it's ready.
