### ISSUE TITLE
Resetting loading state when using it combination with persist

### ISSUE THREAD

**Issue by sven09** [rematch/rematch#642]
Hi,
we are using rematch (and loving it) together with the loading and the persist plugins in our expo apps. Du to another external component (barcode scanner) that crashed while the app was loading, the loading state was stored in persist and after restart of the app still true.

Is there a way to reset the loading state  (after app start in our situation) or exclude from persist?

Won't it be an idea to add an option to loading: doNotPersist: bool ?

Thanks for your advice!

**Comment by semoal** [comment]
Hi Sven, on your persist plugin initializer, you can put [redux persist options](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md#type-persistconfig) like this:
``` 
blacklist?: Array<string>, // do not persist these keys
whitelist?: Array<string>, // only persist these keys
```

```jsx
import createRematchPersist from '@rematch/persist'

const persistPlugin = createRematchPersist({
  blacklist: ['loading'],
  throttle: 5000,
  version: 1,
})

init({
  plugins: [persistPlugin]
})
```

Probably this will work for you problem mate.
