### ISSUE TITLE
RematchDispatch doesn't inject types

### ISSUE THREAD

**Issue by xahon** [rematch/rematch#648]
so I have in my store code
```typescript
export type RootState = RematchRootState<typeof models>;
export type RootDispatch = RematchDispatch<typeof models>;
```

sample model
```typescript
type State = { [page: number]: ReadonlyArray<MessageModel> };

export const messages: ModelConfig<State> = {
  state: {},

  reducers: {
    addMessage: (state: RootState, payload: { message: MessageModel; page: number }): State => ({
      ...state.messages,
      [payload.page]: [...state.messages[payload.page], payload.message]
    })
  },
};
```
state passed into `mapStateToProps` autocompleted fine,
but `mapDispatchToProps` autocompletes only to model's instance but not its inner `reducers` property
![image](https://user-images.githubusercontent.com/18731681/61023429-53cc8600-a3ed-11e9-8b12-217ff557bcec.png)
the same applies to `effects`

I also tried to install all versions of `react`,`react-redux`,`rematch` and their types from here https://youtu.be/f06elAAbb60?list=PLNG2YBDrzK-w1VSeDpMxdGwkb4L6hDy8Z&t=74 but no luck

**p.s.**
I replaced `RootDispatch` with `export type RootDispatch = typeof store.dispatch;` and now it injects fine but with extra stuff that should not be there (Like another models)
![image](https://user-images.githubusercontent.com/18731681/61023697-482d8f00-a3ee-11e9-92ca-2be79bd7174a.png)

**Comment by fnknzzz** [comment]
hi, I found same cases like you. I would pull request for this.

**Comment by semoal** [comment]
Probably close on the last version
