### ISSUE TITLE
I want to participate in the development of rematch

### ISSUE THREAD

**Issue by HiMrHu** [rematch/rematch#651]
I want development rematch, But what do i do. I've started reading the source code.

**Comment by canyavall** [comment]
I'd start checking the open issues and trying to fix them.

If there's not, then, try to improve the code or think/ask for ideas to implement in rematch as a plugin

**Comment by HiMrHu** [comment]
ok， i can try

**Comment by ShMcK** [comment]
@HiMrHu I've added you as a contributor with write access recently. Thank you for the interest :)
