### ISSUE TITLE
AsyncStorage has been extracted from react-native core and will be removed into its own module

### ISSUE THREAD

**Issue by Javi** [rematch/rematch#653]
Currently, the persist plugin checks out if AsyncStorage is available from redux-persist, but it'll stop working soon. It should use https://github.com/react-native-community/async-storage as a dependency instead.

**Comment by thinhtran3588** [comment]
You could change the storage like this:

> import createRematchPersist from '@rematch/persist';
> import { models } from './models';
> import { init, RematchRootState } from '@rematch/core';
> import storage from '@react-native-community/async-storage';
> import { persistStore } from 'redux-persist';
> 
> const persistPlugin = createRematchPersist({
>   whitelist: ['currentUser', 'settings', 'sharks'],
>   throttle: 1000,
>   version: 1,
>   storage,
> });
