### ISSUE TITLE
This should be the official Redux

### ISSUE THREAD

**Issue by pawelotto** [rematch/rematch#654]
Guys, I can't even find words to express how amazing this library is and it's beyond me why on Earth anyone would still use raw Redux when we have this.

This should be the official implementation of Redux and I want to express my gratitude for your hard work making my life so much easier.

Thank you so much for Rematch.

**Comment by BeKnowDo** [comment]
I'm trying to find "gotchas" and...I can't.

**Comment by Izhaki** [comment]
The official Redux Toolkit seems to have many parallels to this project.

See https://github.com/rematch/rematch/issues/735
