### ISSUE TITLE
fix: better typescript experience

### ISSUE THREAD

**Issue by fnknzzz** [rematch/rematch#656]
Our team has been migrating into rematch for about two month,  feels excellent. But finding some typing confusing. 

- Now in the repo running `npm run test:ts` would not passed. 

- When dispatching, it seems lost typing constrains. For example, now in `example/ts/count/src/App.tsx`, in  `mapDispatch`, you can dispatch whatever you want and not receive any errors. Like dispatching an string, but number is what we want.
![image](https://user-images.githubusercontent.com/22239935/61991905-7a471e00-b089-11e9-844b-56e95c3025f2.png)

- Lost model fileds constrains like this in same file:
![image](https://user-images.githubusercontent.com/22239935/61991923-d3af4d00-b089-11e9-822a-3a7a23448cc9.png)

**Comment by ShMcK** [comment]
Should be resolved with @rematch/core v1.2 in #657.
