### ISSUE TITLE
Rematch documentation

### ISSUE THREAD

**Issue by dcefram** [rematch/rematch#669]
It seems like the documentation in gitbooks just got broken. Not sure where to report this, just putting it here as there are no other "community" links in the readme.

Vid: https://1drv.ms/u/s!An91-OBinmQQmzFbajU1lE-udFVf

**Comment by semoal** [comment]
As you can see we migrated from Gitbook to a self-hosted solution: https://rematch.github.io/rematch/

**Comment by dcefram** [comment]
oh my bad, didn't notice the updated link in this repo's description. Updating bookmarks. Thanks! :)
