### ISSUE TITLE
404 error when trying to access the Migration Guide

### ISSUE THREAD

**Issue by AdrianMF** [rematch/rematch#675]
**Describe the bug**
The link to the Migration Guide in the README give a 404 error:
https://rematch.github.io/rematch/#/migrating-from-redux

**To Reproduce**
1. Go to https://github.com/rematch/rematch
2. Click on 'Migration Guide'
4. See error 404

**Expected behavior**
I would expect a link to the Migration Guide. I also tried Googling for "rematch migration guide" and saw this link: https://rematch.gitbooks.io/rematch/migration-guide.html
Which also results in 404

**Comment by semoal** [comment]
Try this url: https://rematch.github.io/rematch/#/migration-guide

Fixed on the pr i submitted right now! Thanks for the ping!
