### ISSUE TITLE
scoreboard labels

### ISSUE THREAD

**Issue by avindra** [rematch/rematch#678]
https://rematch.github.io/rematch/#/purpose?id=scoreboard

![image](https://user-images.githubusercontent.com/126848/65288562-43373b00-db15-11e9-990f-2ee3ae3c0b47.png)

Exactly what is meant by the label `async` ?  I find myself confused here. "thunks" are also not the only way to manage side effects with redux. [redux-saga](https://github.com/redux-saga/redux-saga) has been around for 2 years now.

**Comment by semoal** [comment]
For handling async request on redux you need a external library like redux-saga, redux-thunks.
On Rematch, it's just effects with async await. Example:

```jsx
export const user = {
  // initial state
  state: {
    userLogged: null,
    isAuthenticated: false,
  },
  reducers: {
    // handle state changes with pure functions
    SUCCESS_LOGIN(state, payload) {
      return {
        ...state,
        userLogged: payload,
        isAuthenticated: true
      }
    }
  },
  // you can use dispatch or destructure it, ({ user })
  effects: (dispatch) => ({
    // use async/await for async actions, like an API.get
    // payload: { username: 'test', pwd: 'test' }
    async doLogin(payload, rootState) {
      const data = await http.get(`${API}/login`, {
        username: payload.username,
        pwd: payload.pwd,
      });
      dispatch.user.SUCCESS_LOGIN(data);
    }
  })
}
```

With just 30 lines we have implemented a login structure, in a single file.
