### ISSUE TITLE
how to getState from redux api?

### ISSUE THREAD

**Issue by Frank1e0927** [rematch/rematch#682]
i have a old redux-saga application, 
i saw the migration of rematch.

when i code 
```js
const rematchStore = init({
  redux: {
    reducers: {
      reducer
    },
    middlewares: [saga]
  }
})


saga.run(rootSaga);
```

but when i use getState() api, i can not get the origin(redux) reducer node
i use getState()  got this structure
```js
{
 ...
 reducer: {...my old reducers}
}
```

here is some problem

my old app, mapStateToProps have a lot code like this
```ts
function mapStateToProps(state: State) {
  console.log(state)
  return {
    clientList: state.clients.list,
    currentClient: state.clients.current,
  };
}
```

it means i should do a lot of remodeling... may be state.XX -> state.reducer.XX

is there something good suggestion for me?

**Comment by semoal** [comment]
Now you have this: 
```jsx
const store = init({
  models: {
    sharks,
  },
  redux: {
    reducers: {
      dolphins,
    },
    middlewares: [thunk]
  },
});
```

But rematch doesn't work in that way, you need to specify models:
```jsx
const store = init({
  models: {
    sharks,
    dolphins,
  },
});
```

Of course you'll need to migrate all your async actions to effects, your reducers to reducers, and state to state in your $(model).js file.

mapStateToProps **never** will contain .reducer
