### ISSUE TITLE
add RematchProvider components

### ISSUE THREAD

**Issue by hardfist** [rematch/rematch#684]
**Is your feature request related to a problem? Please describe.**
It seems that lots of dispatch typescript problems caused by the incompatible api  between React-redux and rematch ,We may provide another Provide component to solve these problems, while keep the origin provider for backward compatible, just like what easy-peasy's doing https://easy-peasy.now.sh/docs/api/store-provider.html
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HiMrHu** [comment]
thanks

**Comment by shierro** [comment]
Hi, I'm having the same issue

"@rematch/core": "^2.0.0-next.10"
"react-redux": "^7.2.2"

```
No overload matches this call.
  Overload 1 of 2, '(props: ProviderProps<AnyAction> | Readonly<ProviderProps<AnyAction>>): Provider<AnyAction>', gave the following error.
    Type 'RematchStore<RootModel, Record<string, any>>' is missing the following properties from type 'Store<any, AnyAction>': getState, subscribe, replaceReducer, [Symbol.observable]
  Overload 2 of 2, '(props: ProviderProps<AnyAction>, context: any): Provider<AnyAction>', gave the following error.
    Type 'RematchStore<RootModel, Record<string, any>>' is not assignable to type 'Store<any, AnyAction>'.ts(2769)
index.d.ts(472, 5): The expected type comes from property 'store' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<AnyAction>> & Readonly<ProviderProps<AnyAction>> & Readonly<...>'
```

anyway you'd recommend to overcome this?

**Comment by tianzhich** [comment]
Can you provide the reproduce repo? We've refactored many types since v2.

**Comment by shierro** [comment]
Hi @tianzhich can you please try this?
https://github.com/shierro/react-boilerplate

Error will appear once you remove casting of store to "any"
https://github.com/shierro/react-boilerplate/blob/master/src/store/index.tsx#L7

**Comment by tianzhich** [comment]
I removed the casting but there were no type errors:

![image](https://user-images.githubusercontent.com/33218310/104283272-449b2c80-54eb-11eb-9199-bd2063d2949f.png)

**Comment by shierro** [comment]
ok that's interesting. It looks like my deprecated tslint vscode extension caused the issue. thanks for looking into this @tianzhich
