### ISSUE TITLE
Can reducers be dynamically added into a model by using a custom plugins?

### ISSUE THREAD

**Issue by sdujack2012** [rematch/rematch#688]
Hi there,

I am trying to add some dynamic reducers to a model by creating a custom plugin. I have tried modifying reducers in onModel function and it didn't work. Then I went through the source code and found out that onModel only uses copied version of the reducers from the model so modifying reducers in onModel function won't work. Can anyone help and suggest some alternative ways of doing it?

Cheers,

**Comment by canyavall** [comment]
It is funny, I was thinking on that, try to create a plugin that can create one effect + reducer + state + selector only defining the minimum (the selector, reducer and state would be created dynamic).

I'll check it this week, if someone has any idea, please, share it ^_^

**Comment by sdujack2012** [comment]
I quickly realised we can create a function that accepts models and adds reducers in these models and then passes the modified models to the config object in the plugin. This way the added reducers will be taken into consideration when creating the store. Hope this helps.

**Comment by canyavall** [comment]
THx, i'll check, right now I want to create a plugin for error handle, if I can ^_^. Then will focus on this topic
