### ISSUE TITLE
Effect that shares a name with a reducer is not called

### ISSUE THREAD

**Issue by hirikarate** [rematch/rematch#689]
I want to trigger an effect when the reducer has caught an action from another model, but all my attempts failed.

**First attempt:**

```javascript
import { LOCATION_CHANGE } from 'connected-react-router'

const watcherModel = {
   reducers: {
      [LOCATION_CHANGE](state, payload) {
         /* some condition check */
         return {
            ...state,
            miracleHappened: true,
         }
      }
   },
   effects: (dispatch) => ({
      [LOCATION_CHANGE](...args) {
            console.log(args)
      }
   })
}
```
It throws error `Invalid effect name (watcher/@@router/LOCATION_CHANGE)`

**Second attempt:**

```javascript
import { LOCATION_CHANGE } from 'connected-react-router'

const watcherModel = {
   reducers: {
      [LOCATION_CHANGE](state, payload) {
         /* some condition check */
         return this['watcher/recordMiracle'](state, true)
      },
      recordMiracle(state, miracleHappened) {
         return {
            ...state,
            miracleHappened,
         }
      }
   },
   effects: (dispatch) => ({
      recordMiracle(...args) {
            console.log(args)
      }
   })
}
```
In this case, the reducer `recordMiracle` is invoked, but the effect with same name isn't but it should be, as [the docs](https://rematch.github.io/rematch/#/api-reference/api)

> effects that share a name with a reducer are called after their reducer counterpart

**Third attempt:**

```javascript
import { LOCATION_CHANGE } from 'connected-react-router'
import { store } from './store'
/* Causes circular reference between "store.js" and "watcherModel.js" */
/* Calling "store.dispatch" in reducer is anti-pattern. I know */
```

---
Please show me a way to trigger effect after the reducer has caught an action from another model, or when a reducer is internally called by its sibling reducer.

Thank you.

**Desktop (please complete the following information):**
 - @rematch/core@1.2.0

**Comment by andrejunges** [comment]
I don't think this issue should be closed.
I believe this is a valid bug and the expected behaviour would be having the effect listeners being triggered, no matter the model.

**Comment by Misinin** [comment]
I face with similar problem. Both reducers called, but effect with identical name not call. Somebody can explain me why it is work like this?

**Comment by tianzhich** [comment]
> @semoal I face with similar problem. Both reducers called, but effect with identical name not call. Somebody can explain me why it is work like this?

Could you share a code example? In the effect middleware, the effect with an identical name should be called after its reducer counterpart. See https://github.com/rematch/rematch/issues/912 for more details.

**Comment by Misinin** [comment]
> Could you share a code example? In the effect middleware, the effect with an identical name should be called after its reducer counterpart. See #912 for more details.

`const modelTwo = {
  state: {
    title: '',
    objects: []
  },
  reducers: {
    setObjects: (state, payload) => {
      console.log('setObjects');
      return {
        ...state,
        objects: payload
      };
    },
    'modelOne/setData': function(state, payload) {
      this['modelTwo/setObjects'](payload);

      return state;
    },
    setTest: function(state, payload) {
      return {
        ...state,
        title: payload
      };
    }
  },
  effects: dispatch => ({
    setObjects: () => {
      console.log('START_ SETOBJECT_EFFECT');
    },
    setTest: () => {
      console.log('START_TEST_EFFECT');
    }
  })
};

export default modelTwo;
`

When i called setTest function from button click, i saw in console 'START_TEST_EFFECT'.
If i subscribe on reducer from modelOne and in this reducer i called setObjects, i saw in console 'setObjects', but 'START_ SETOBJECT_EFFECT' i didn't see.

**Comment by Misinin** [comment]
> > @semoal I face with similar problem. Both reducers called, but effect with identical name not call. Somebody can explain me why it is work like this?
> 
> Could you share a code example? In the effect middleware, the effect with an identical name should be called after its reducer counterpart. See #912 for more details.

![image](https://user-images.githubusercontent.com/56192086/125024342-3b011480-e089-11eb-8d2f-d3979c9caa69.png)

When i called setTest function from button click, i saw in console 'START_TEST_EFFECT'.
If i subscribe on reducer from modelOne and in this reducer i called setObjects, i saw in console 'setObjects', but 'START_ SETOBJECT_EFFECT' i didn't see.

**Comment by tianzhich** [comment]
Yes, because the `this` in your `modelOne/setData` reducer only points to the surrounding reducer object,  not contain the effects. And also, you'd better not trigger effects within reducer.

**Comment by Misinin** [comment]
> Yes, because the `this` in your `modelOne/setData` reducer only points to the surrounding reducer object, not contain the effects. And also, you'd better not trigger effects within reducer.

In documentation wrote that _effects functions that share a name with a reducer are called after their reducer counterpart_. Reducer 'modelOne/setData' is calling reducer 'setObjects' who share name with effect 'setObjects', i expect that it will be work like wrote in documentation. Why it's not work, can you explain me please?

**Comment by semoal** [comment]
I was not going to lose my time here, since isn't an issue, it's just a bad use but..

1º https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this. Read about `this`, NEVER, and never is never worked like that the Rematch `this`. `this` on Rematch it's useful for dispatching reducers and effects ON THE SAME MODEL, it never will work with external models. (That's why is this). The only way to call effects/reducers or other models is using the dispatch argument passed to effects, and running them inside an effect, or in a lifecycle of your React/Vanilla components using the global dispatch.

2º *Effects functions that share a name with a reducer are called after their reducer counterpart*, THIS IS ABSOLUTELY TRUE, but you're code is totally wrong. `this` never called an external model.

3º There're plenty of ways of doing what you try to do, an using the technique you're trying to do, is highly not recommended, since you're code it's some magical, if someone who don't know Rematch tries to debug an issue probably will be hard. Just run your effects, reducers with the global dispatch and create declarative code. 

Thanks for using Rematch.
