### ISSUE TITLE
Doc links not working

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#691]
On the docs site, links pointing to the same page don't work.

See https://rematch.github.io/rematch/#/api-reference/api and click on "init".

Let's look at the link in api.md.

```
* [init](api.md#init)
```

The link compiles to:

```
https://rematch.github.io/rematch/#/api?id=init
```

Which results in a 404. The link should actually point to:

```
https://rematch.github.io/rematch/#/api-reference/api?id=init
```

---

The same-page link bug may be an issue in our implementation or a bug in Docsify itself. 

@semoal what are your thoughts?

**Comment by semoal** [comment]
@ShMcK fixed Shawn, was pointing to a wrong .md section, now all that api reference sections works nice
