### ISSUE TITLE
Can't pass payload as Object to actions

### ISSUE THREAD

**Issue by Gerlison** [rematch/rematch#695]
**Describe the bug**
I have an async action and I pass it to component via mapDispatch (like DOC says to do). When I pass the payload like a String or an Array it's work beautifuly. But if the payload passed is an Object or a variable that contains an Object it throws `arguments[0].indexOf is not a Function`

**To Reproduce**
1. Setup rematch as Doc leads 
2. Call a action on component
3. Pass a Object as payload

**Desktop (please complete the following information):**
 - OS: Windows
 - Version latest

I tested something that made think

### It did not work
```

props.setUserAsync( {
  user: 'John Doe'
} )
```

But 

### It did work
```
props.setUserAsync( [{
  user: 'John Doe'
}] )
```

**Comment by semoal** [comment]
Could you provide a minimal example to reproduce? Like a codesandbox, o stackblitz

**Comment by Gerlison** [comment]
> Could you provide a minimal example to reproduce? Like a codesandbox, o stackblitz

The first time I experienced the issue in a RN project, I could not reproduce it on codesandbox. I'll recreate the same situation of the first time, publish it to a repo and pass the link here as soon as possible. Thanks for support.
