### ISSUE TITLE
[Question] How to use dispatch type without exporting with typeof?

### ISSUE THREAD

**Issue by simonsmith** [rematch/rematch#712]
All the examples I see show the following type exported from the `./store` file:

```js
export type Dispatch = typeof store.dispatch
```
My issue is I'm creating my store in a function like the below:
```js
export function createStore(initialState: unknown): RematchStore {
  return init({
    models,
    redux: {
      initialState,
    },
  });
}
```
The reason for this is so it can be created fresh each time when server rendered (as seen in the [Next example](https://github.com/zeit/next.js/tree/canary/examples/with-rematch))

Is there a way for me to achieve the same typing without accessing the return value from `init`? I've studied the typings but not found an obvious answer. 

This same issue also seems to  apply to accessing `getState`:

> Breaking changes with v1.0.0. Global imports of dispatch and getState have been removed. Instead, you can export and import your store, capturing store.dispatch, store.getState.

Again, I'm struggling with not having `store` as a singleton I can export

Any help appreciated!

Edit:
I've had some success with the following when using Hooks, but not connect:

```js
const models = {
  channel,
  cms,
};

export type Dispatch = RematchDispatch<typeof models>;
```

Does this seem correct?

**Comment by sdujack2012** [comment]
Hi @simonsmith,
 It looks correct to me.
The value from init() is of type RematchStore which has dispatch as type RematchDispatch<Models>. 
RematchDispatch<Models> automatically derives reducers and effects for dispatch according to Models.

Please refer to https://github.com/rematch/rematch/blob/master/src/typings/index.d.ts#L129 for reference.

Cheers,
Kai
