### ISSUE TITLE
[Question] Getters for models

### ISSUE THREAD

**Issue by dakiesse** [rematch/rematch#713]
I have a model: 
```
export const creatingOrder = {
  state: { currentStage: 1 },
  reducers: {},
  effects: (dispatch) => ({})
}
```
I've wanted to include in the model a new property for getting calculated values the are connected with this model. For example, I wanted to get one of several text for button depending on the currentStage. And I've decided to make a new plugin for adding new property 'getters':
```
export const creatingOrder = {
  state:  { currentStage: 1 },

  getters: {
    textForSubmitButton (payload, { creatingOrder }) {
      if (creatingOrder.ui.loading) return 'Processing...'
      if (creatingOrder.currentStage === 4) return 'Create order'
      return 'Next Stage'
    }
  },

  // ...
}
```

This plugin does the same thing as 'effects' but only for 'getters' property and has non-async middleware. I've tried to use it in render method like that:
```
const { creatingOrder } = useDispatch()

return (<button>{creatingOrder.textForSubmitButton()}</button)
```
But the method returns a promise because the middleware of my plugin is behind the middleware of effects plugin where it's async.

Is there way to make calculated properties for model which will return non-promise value?

**Comment by canyavall** [comment]
Maybe I missunderstood what you want to do, but it looks like the select plugin to me
