### ISSUE TITLE
[Question] Check loading inside effect

### ISSUE THREAD

**Issue by chenjizhao** [rematch/rematch#715]
One important purpose for loading handling is to avoid calling one effect the second time when there is already another call undergoing for same effect. Before using rematch, this logic is done like below with redux-thunk:
```
{
  if(!state.someReducer.loading){ // check 'loading' flag
    dispatch(someActionStart()); // set 'loading' flag to 'true'
    //api fetch
    dispatch(someActionComplete()); //set 'loading' flag to 'false'
  }
}
```
By using rematch loading plugin, the code looks like:
```
{
  const loading = state.loading.effects.someModel.someEffect;
  if(!loading) //api fetch
}
```
Now the problem is that I found when the effect is been called. Loading flag for that effect is directly changed to 'true'. So the api is not called even once.

I found that this loading is correct if the check is put directly in component. But I insist this logic should be in the effect because the only job for component is to call the effect. Whether effect will trigger a new fetch or wait for the data of current fetch to return, they are all about api handing. The api effect should be responsible to handle it.

I would like to know if there are any good ways to use loading plugin in effect. Thank you very much

**Comment by thinhducngo** [comment]
Instead of using loading plugins, u can use your local loading.
```
state: {
    loading: false
},
reducers: {
    loading: (state, value) => ({
        ...state,
        loading: value
    })
},
effects: () => ({
    async test(payload, state) {
        // get loading from local state, update loading at the same time with your async action
    }
})
```
