### ISSUE TITLE
Add types for React-Navigation

### ISSUE THREAD

**Issue by Oba-One** [rematch/rematch#717]
Hi! I love rematch and typescript, and currently I'm using the persist, immer, and navigation plugins. The navigation plugin doesn't have a `index.d.ts` file when importing it. I manually added it in my `node_modules` and was going to make a pull request to add it to the plugin but wasn't sure how to approach it. It's probably a quick fix and is more of a convenience than an issue.

**Comment by semoal** [comment]
Feel free to create a fork with your index.d.ts implemented, and we'll review it!
