### ISSUE TITLE
When using store.model typescript drives crazy

### ISSUE THREAD

**Issue by canyavall** [rematch/rematch#721]
**Describe the bug**
When using store.model to add a model to an existing store, the store types don't include the new model

**Expected behavior**
After using store.model() and add a new model, the store.dispatch didn't recognize the new model in the store. Is expected that types are working properly and the new model can be recognized

**Comment by QuentinouLeTwist** [comment]
Could you share your piece of code ?

**Comment by canyavall** [comment]
`
import React from 'react';
import {ImageProps} from "./ImageTypes";
import {dispatch, store} from "../../store";
import ImageStoreModel, {isImageIdInFailedImages} from './ImageStoreModel'

store.model(ImageStoreModel)

const ReactImage: React.FC<ImageProps> = (props) => {
    const {src, imageId, fallbackUrl, width, height, alt} = props

    let imageSrc = src
    if (isImageIdInFailedImages(imageId)) {
        // Set the src as fallback
        if (fallbackUrl) {
            imageSrc = fallbackUrl
        }
        // Request the image again, if it works, remove from failedImages
        const newImage = new Image()
        // @ts-ignore
        newImage.onload = () => store.dispatch.failedImages.removeFailedImage(i)
        newImage.src = src
    }

    return (
        <>
            <img width={width}
                 height={height}
                 src={imageSrc}
                 alt={alt}
                 onError={(event) => {
                     // @ts-ignore
                     dispatch.failedImages.addFailedImage(imageId)
                     // @ts-ignore
                     event.target.src = fallbackUrl
                 }}/>
        </>
    )
}

export default ReactImage
`
