### ISSUE TITLE
[Question] How to properly mutate the state in a reducer ?

### ISSUE THREAD

**Issue by QuentinouLeTwist** [rematch/rematch#722]
Hey guys,

I was trying to update an element in array of objects. Basically I have an array of object and each object has a `status` property. I'm looking for updating the `status` property using a reducer.

This is pretty straightforward but I'm missing something. So first I was trying this : 

```
updateStatus: (state: SearchState, index: number, status: number) => {
  state.results[index].status = status;
      
  return {
    ...state,
  }
},
```

But that does not affect the state in my model so then I tried the following : 

```
updateStatus: (state: SearchState, index: number, status: number) => {
  const results = [...state.results];
  results[index].status = status;
      
  return {
    results,
  }
},
```

And that works. So what's wrong with the first piece of code ?

**Comment by hardfist** [comment]
```
const state1 = {results: [1,2,3]}
const state2 = {...state1} 
state1.results === state2.results // will always true
const state1 = {results:[1,2,2]}
const state2 = {results: ...state1.resutls}
state1.results === state2.results // will return false
```
just use immer

**Comment by QuentinouLeTwist** [comment]
Ok so If I summurize, the state is not getting updated when returned like in the first piece of code because rematch compares the object returned to the model's state and since this last has already been updated directly in the method (because passed by reference I guess), it does nothing. Am I correct?

**Comment by hardfist** [comment]
yes， but it's redux do the optimization to pass unnecessary rerender
