### ISSUE TITLE
How to access state from an effect

### ISSUE THREAD

**Issue by daveowenatl** [rematch/rematch#725]
Redux Thunk documentation provides the following example:

```
function incrementIfOdd() {
  return (dispatch, getState) => {
    const { counter } = getState();

    if (counter % 2 === 0) {
      return;
    }

    dispatch(increment());
  };
}
```
I am curious how to achieve a similar conditional dispatch using Rematch.

I see a number of old questions asking the same thing, but I'm thus far not able to find anything that works.

**Comment by thinhducngo** [comment]
Your question is not clear. Try this (I think this can solve your problem):

`
effects: dispatch => ({
        async incrementIfOdd(payload, state) {
            const { counter } = state;
            if (counter % 2 !== 0) {
                this.increment()    // or dispatch.counters.increment()
            }
        }
    })
`

**Comment by crazy4groovy** [comment]
Nice, the answer that I was I was looking for now! :)

(`this` only contained namespaced dispatchers from the effects' model)
