### ISSUE TITLE
Rematch loading plugin return integer values instead of boolean values

### ISSUE THREAD

**Issue by duyphanz** [rematch/rematch#736]
**Describe the bug**
I've tried to reset the store by following [this](https://github.com/rematch/rematch/issues/663). And, I found that the value types from rematch loading plugin have been changed from boolean to integer.

I have an [example](https://github.com/phanduy12214/test-rematch) based on an [nextjs-with-rematch example](https://github.com/zeit/next.js/tree/canary/examples/with-rematch), using this snippet below to reset the store:

`const store = init({
  models,
  redux: {
    devtoolOptions: {},
    rootReducers: { RESET_APP: () => undefined }
  }
});`

**To Reproduce**

1. Clone my [custom code](https://github.com/phanduy12214/test-rematch)
2. Run `yarn`
3. Run `yarn dev`
4. Access to: http://localhost:3000
5. Click on the `incrementAsync` button
6. Click on the `Reset App` button
7. Observe the [Redux devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)

**Expected behavior**
The value of `loading.effects.counter.incrementAsync` changes from `false` to `0`. It should keep that boolean value.

**Screenshots**

![image](https://user-images.githubusercontent.com/13731780/72201742-c0523b80-3489-11ea-86e4-9095982d6983.png)

**Desktop:**

- OS: macOS Mojave
- Browser: Chrome
- Version: 79

**Comment by vanzi6** [comment]
Hello all, I have the same problem.

[codesandbox example](https://codesandbox.io/s/rematch-loading-test-zyovu)

Not the best quality, but you can see that `state.loading.effects.count.addByAsync ` is changing from `boolean` to `number`
![image](https://user-images.githubusercontent.com/21037158/94296648-d8acac80-ff6b-11ea-8189-6a7194aa7f83.png)

**To replicate** 
1. Go to example link, open console 
2. Click login button
3. Click counter button few times
4. Click logout button
5. Click login button
6. Click Click counter button few times

**Where did I found how to reset whole state?**
[Link](https://github.com/rematch/rematch/issues/663)

I would like to know is this a bug or not? 

If this is not a bug is there any other similar way to reset whole state?
I know i can write reset function for each model and call them when needed, but then I need to keep track of them all.
