### ISSUE TITLE
Cannot get mapState data

### ISSUE THREAD

**Issue by zhangshichuan** [rematch/rematch#737]
hello everyone.
![image](https://user-images.githubusercontent.com/8280832/72494470-ea777500-385e-11ea-8383-48a7c02fe352.png)
![image](https://user-images.githubusercontent.com/8280832/72494479-f19e8300-385e-11ea-8500-6d3941aaa896.png)
![image](https://user-images.githubusercontent.com/8280832/72494524-172b8c80-385f-11ea-8e1e-354a98f50546.png)

**Comment by zhangshichuan** [comment]
I wrote according to the official document example. But I can't get the data in mapState through props. Print the state to delete undefine. But the method in my mapDispatch can be called normally. The first time I use rematch. Please give pointers!

**Comment by zhangshichuan** [comment]
I wrote according to the official document example. But I cannot get the data in mapState through props. The state output is undefined. But the methods in my mapDispatch can be called normally. The first time I use rematch. Please give pointers!

**Comment by zhangshichuan** [comment]
![image](https://user-images.githubusercontent.com/8280832/72494734-c700fa00-385f-11ea-81c0-35269b102cf7.png)

**Comment by zhangshichuan** [comment]
![image](https://user-images.githubusercontent.com/8280832/72494801-f3b51180-385f-11ea-9692-590aad8dab96.png)
![image](https://user-images.githubusercontent.com/8280832/72494819-016a9700-3860-11ea-8201-961142506225.png)

**Comment by semoal** [comment]
Are you still having problems?
I'm not sure if that type of reducers works well.
