### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#74]
*(Thoughts sorted out with @blairbodnar.)*

### Tagline
"Rematch. Rethink Redux"

### Purpose
Say this is a few sentences so anybody can understand.

- data layer. wrapper around redux.
- better app organization
- simplifies better app architecture
- easier API
- easier refactoring
- does the same thing

- opinionated about Redux
- not opinionated about the other stuff you do

- for small apps made easier, big apps made simpler

### Built In
- store setup
- devtools

### Example
- A complete example

### Examples with view layer
- React
- Vue
- Preact
- jQuery
- vanilla JS
- ember?
- angular?

### Setup
Installation

##### Level 1: 
- init
- model
- name
- state
- reducers

##### Level 2:
- effects
- selectors
- subscriptions

##### Level 3:
- plugins

### Inspiration
Dva, Mirror.

**Comment by ShMcK** [comment]
### Blog Articles
- migration from redux
- migration from dva, mirror

**Comment by ShMcK** [comment]
### Readme

**Comment by blairbodnar** [comment]
@ShMcK  Not really sure where I'm going with this... I'm just trying to find a short nice way to explain the concepts of rematch. Just a brain dump I want to jot down:

## Rematch

Rematch is Redux best practices without the boilerplate.

In Redux, the state of your whole application is stored in an object tree within a single store. 

In Rematch, we refer to the top level keys of that state tree as `models`.

### Models

When you build your apps, you are designing these models. To design these models, you should answer these questions:

1. What's the name of this model? `name`
2. What does it's state look like? `state`
3. How does the _inner world_ change that state? `reducers`
4. How does the _outer world_ change that state? `effects` and `subscriptions`
5. How do you read values of that state? `selectors`

### Dispatch
Once you've implemented your models, Rematch make is easy to dispatch state changes to those models from anywhere in your app.

### Select
Once you've implemented your models, Rematch make is easy to access values from the models' state from anywhere in your app.
