### ISSUE TITLE
Equivalent to redux's store.subscribe()?

### ISSUE THREAD

**Issue by avrame** [rematch/rematch#756]
I'm working to replace Redux in a complex web app with Rematch. The existing code is using `store.subscribe()` to attach listeners for when certain models are updated. I'm guessing that the "Rematch way" of doing this is to add effects to the Rematch models, but I don't want to radically alter the structure of the app - state watch handlers should be able to be added anywhere in the code. Does rematch have something like `store.subscribe()` that I can use?

**Comment by avrame** [comment]
Thanks @semoal  but I think my scenario is different. I need a way of subscribing to any change to any of the models.

**Comment by pjamrozowicz** [comment]
@avrame rematch store is basically a redux store with extra properties so it also has the very same `store.subscribe` method. I've never used this approach personally but in general, every action, from effect or not, reaches the store, so I guess the subscribe approach should trigger for any action.

**Comment by avrame** [comment]
ok, thanks @pjamrozowicz - I'll take another look and see if I can get it working.

**Comment by bitlab-code** [comment]
@avrame 
> [...] to attach listeners for when certain models are updated.
You can create your own plugin.

In my case I needed to attach a listener whenever a field in the model are updated, so i've created a simple plugin that use [redux-whenever](https://github.com/caiogondim/redux-whenever.js).

but it must be said that the documentation on plugins should be improved
