### ISSUE TITLE
Using rematch with Redux Hooks

### ISSUE THREAD

**Issue by reflash** [rematch/rematch#758]
Hi,

I was checking out documentation and I'm wondering if rematch supports redux hooks at the moment. I can't find any examples in the docs. Currently Redux can use hooks like `useSelector, useDispatch, useStore`, so what is the approach with rematch?

Also [https://rematch.github.io/rematch/#/recipes/typescript?id=select-plugin](https://rematch.github.io/rematch/#/recipes/typescript?id=select-plugin) mentions some sample in `examples/cart` which seem to not exist anymore

**Comment by tangdw** [comment]
`import { useDispatch, useSelector } from 'react-redux'
`

**Comment by Hainesy** [comment]
How do we use `useSelector` in conjunction with the selectors plugin?

**Comment by d3dc** [comment]
right now:
```js
import { useStore } from 'react-redux'

const Comp = () => {
  const { select, dispatch } = useStore()
  const data = useSelector(select.model.selector)
  ...
}
```
