### ISSUE TITLE
Plugins vs. Packages

### ISSUE THREAD

**Issue by ShMcK** [rematch/rematch#76]
I wondered if calling everything a "package" or a "plugin" makes sense.

### Plugin
Runs as a plugin in init
Example: Loading, reactRouter4, etc.

### Package
Works with rematch, but doesn't run as a plugin
Example: ReactRematch

Should we differentiate between the two? If so, how?

**Comment by blairbodnar** [comment]
Hmm. I'm ok with "plugin" for now I think.

As for the package... I'm wondering if we even need them? I think They might just be recipes or examples? I'm thinking we probably don't need ReactRematch anymore... I think for using rematch with React it should just be an example or recipe showing how to use rematch with `react-redux`. 

Thoughts?

**Comment by ShMcK** [comment]
I think having no "RematchReact" is definitely the simplest solution. 

Lets call it plugins then.

I do think we should preserve the existing rematch-react somewhere, in case we take up the cause again. Though it should be preserved in the git history if we ever come back to it.

**Comment by ShMcK** [comment]
Some more options arise now:

##### should our existing plugins move into plugins?
This may cause issues with the webpack build.

##### should new plugins be npm packages?
I'm thinking so, as they may have their own dependencies.
