### ISSUE TITLE
Model missing on dispatch object in effects.

### ISSUE THREAD

**Issue by Hainesy** [rematch/rematch#760]
Using the effects API like such:

`effects: ({ model1, model2, model3 }: Dispatch) => ({ ... })`

In one particular scenario I am finding one of my model's effects is not defined on the dispatch object.

Is there anything that would prevent one of the models appearing?

It works fine when using `useDispatch<Dispatch>().model3`.

**Comment by Hainesy** [comment]
Is there a way round this? At the moment this is blocking me completely.

**Comment by pjamrozowicz** [comment]
> Is there a way round this? At the moment this is blocking me completely.

Could you include some code example so we could replicate your problem?

**Comment by semoal** [comment]
Hi mate, could you give a try to our next version? We fixed all the issues with typescript typings.

```bash
npx update-by-scope -t next @rematch
````
I added a pinned issue where you can report all the things you find, or create individual issues with the label v2.

**Comment by Hainesy** [comment]
Hi, well the issue I raised isn't a typings issue; its an issue with the injected effect dispatcher being undefined.

After upgrading I'm getting an issue with a reducer being of type `never` from `useDispatch`. I don't think I'll be taking the upgrade right now...

**Comment by tianzhich** [comment]
> Hi, well the issue I raised isn't a typings issue; its an issue with the injected effect dispatcher being undefined.

Yes, I have found this issue. Suppose you define the following models: `{ model1, model2, model3 }`. You can now only use the destructed `model1` and `model2` from `model2`, you can't access `model3` which is undefined. 

We will try to fix it.


> After upgrading I'm getting an issue with a reducer being of type `never` from `useDispatch`. I don't think I'll be taking the upgrade right now...

Could you provide a reproduce? I haven't run into this. I created a [CodeSandbox](https://codesandbox.io/s/rematchv2-typescript-mpos8) which you can use for this.

**Comment by Hainesy** [comment]
Yes I just came to the same conclusion: you can only use models that have been declared before the current model.

I'll try upgrading again when this bug is fixed and try to provide a reproduce for the other issue.

**Comment by Hainesy** [comment]
@tianzhich Are you able to provide an ETA on the fix?

**Comment by semoal** [comment]
> @tianzhich Are you able to provide an ETA on the fix?

https://codesandbox.io/s/rematchv2-typescript-forked-kr8ly?file=/src/models/sharks.ts

Check this example, i'm using three models, calling dispatch actions of all models, and apparently works well.

if the issue is destructing the dispatch models from effects: ({ model1, model 2 }) =>, we're actively thinking on a solution but we got in troubles because typescript closed our issue on typescript codebase. So probably we'll document that the only solution to destructure the method actions is inside each effect.

**Comment by semoal** [comment]
> @tianzhich Are you able to provide an ETA on the fix?

As the #792 said, I estimated to release the next version to mid-end october. 
Our focus is giving full compatibility with typescript, and avoid too much breaking changes for elevating the adoption process.
Feel free to collaborate if you're interested =)
