### ISSUE TITLE
Issue migrating from Vanilla Redux TS -> Rematch TS

### ISSUE THREAD

**Issue by kingdavidmartins** [rematch/rematch#761]
**Describe the bug**
Seems that in Rematch core currently as is init({}) can't merge inferred types from `models` and ported over types from `reducers`. 

**To Reproduce**
```ts

interface LegacyStore {
  reducerA: ReducerA;
  reducerB: ReducerB;
}

const store = init({
  models,
  redux: {
    reducers: {
      reducerA,
      reducerB,
    },
    middlewares,
  },
});
```

Anywhere we do the following
```ts
      const state = store.getState();
      state.reducerA,
```

We get the following

```ts
Property 'reducerA' does not exist on type ExtractRematchStateFromModels<RootModel>
```

Ideally I would like to do something like 

```ts
const store  = init<RootModel, LegacyStore>({})`
```

Any suggestions with getting `LegacyStore` to play nice with init?
- iOS
- Browser chrome

**Comment by semoal** [comment]
Hi mate, could you give a try to our next version? We fixed all the issues with typescript typings.

```bash
npx update-by-scope -t next @rematch
````
I added a pinned issue where you can report all the things you find, or create individual issues with the label v2.

**Comment by kingdavidmartins** [comment]
Thanks, the issues were resolved
