### ISSUE TITLE
Adding a method to actions

### ISSUE THREAD

**Issue by slashwhatever** [rematch/rematch#762]
I'm using rematch in a new project which relies on an older library which uses [redux-act](https://github.com/pauldijou/redux-act) internally. One of the things redux-act does is add a `getType` method to action creators - this method just returns the string name of the action.

I need to create a plugin to enhance "actions" in rematch so when the older library goes to call `getType()` on an action that it's passed, it doesn't error out.

So far I have this (which doesn't work):

```
const addGetTypePlugin = {
  onModel(model) {
    for (const effectName of Object.keys(this.effects)) {
      this.effects[effectName].getType = () => effectName;
    }
    for (const reducerActionName of Object.keys(this.reducers)) {
      this.reducers[reducerActionName].getType = () => reducerActionName;
    }
  },
};

export default addGetTypePlugin;

```

I guess my primary question would be whether this is even able to be supported in rematch, aside from the obvious question of how?

**Comment by semoal** [comment]
Hi mate, could you give a try to our next version? We fixed all the issues with typescript typings.

```bash
npx update-by-scope -t next @rematch
````
I added a pinned issue where you can report all the things you find, or create individual issues with the label v2.

Feel free to try to create a plugin with the new codebase, super easy with lerna and typescript code base !!

**Comment by slashwhatever** [comment]
I worked around the issue in the end but I'm more than happy to try v2 - when we have a little breathing space from release windows :) 

Congrats on getting to v2 - I'm very much enjoying using the library 👍
