### ISSUE TITLE
Re-use selector from another selector?

### ISSUE THREAD

**Issue by JEkedorff** [rematch/rematch#763]
Hi!

I love the lib. Great work!

I need some minor guidance, any help would be very appriciated.
I am trying to re-use my first selector 'selectedItemKey' from my second selector 'selected**Sub**ItemKey, to navigate to the correct sub-item in a deep object in store '.

I was hoping below code would work, but it fails in 'selectedItemKey' saying my model name is not a member of the provided state.
I believe the problem is that the state in 'selected**Sub**ItemKey' only include the model's state, while when calling models.bom.selectedItemKey(state) a full rootState is expected.

```
selectors: (slice, createSelector, hasProps) => ({

        selectedItemKey() {
            return slice(state => get(state, ['layout', 'selectedItemKey']))          
        },
        selectedSubItemKey(models) {
            return slice(state => get(state, ['layout', 'selectedSubItemKeys', models.bom.selectedItemKey(state) ])) 
        },
        ...
```

This works, but it feels like a ugly hack which I also suspect looses the memoize benefits:

```
selectors: (slice, createSelector, hasProps) => ({

        selectedItemKey() {
            return slice(state => get(state, ['layout', 'selectedItemKey']))          
        },
        selectedSubItemKey(models) {
            return slice(state => get(state, ['layout', 'selectedSubItemKeys', models.bom.selectedItemKey.resultFunc(state) /* <- not good */])) 
        },
        ...
```

I see it is possible to change the sliceState setting to always use rootState but I don't know if that is a good way forward? 

Thanks!

**Comment by slashwhatever** [comment]
Assumes initial state is something like:

`
{
  items: {
    byId: {}
  },
  lastQuery: {}
}
`

You're using the select plugin which means you have access to `createSelector` and you can use other selectors to create another new one:

`selectors: (slice, createSelector) => ({
  _items() {
    return slice(({ items }) => items.byId);
  },
  _lastQuery() {
    return slice(({ lastQuery }) => lastQuery);
  },
  // get an individual item from state when passed an itemId in the dispatched action payload
  itemById() {
    return createSelector(
      this._items,                                      // this references the _items() selector above
      (state, itemId) => itemId,               // this accepts the passed in itemId from the dispatched action payload
      (items, itemId) => items[itemId]    // this method takes the items and the itemId from the previous two arguments and uses them to return the desired item.
    );
  },
  sortedItems() {          // similar idea to above but using state to return a sorted list of items
    return createSelector(
      this._items, 
      this._lastQuery, 
      (items, lastQuery) =>
        _.orderBy(items, lastQuery.sort, lastQuery.order)
      );
  },
})
`

**Comment by JEkedorff** [comment]
Thanks a lot!
