### ISSUE TITLE
initial state overwrite models

### ISSUE THREAD

**Issue by Micev** [rematch/rematch#764]
Hi it seems that initial state overwrite models

Here is my example:
`const store = (init({`
    `name: 'test',`
    `redux: { initialState },`
    `models: ({ ...models} as unknown) as RematchModels`
  `}) as unknown) as Store;`
`store.select.getState = (state: RootState) => state;`
`

Where `initialState = { currency: 'USD' } ` and `models: {currency: 'USD', selected: 'PM' }`

After invoke store.getState() it's returns me initialState, but in https://rematch.github.io/rematch/#/api-reference/reduxapi?id=initialstate says the opposite.

What is wrong here?

**Comment by semoal** [comment]
Hi mate, could you give a try to our next version? We fixed all the issues with typescript typings.

```bash
npx update-by-scope -t next @rematch
````
I added a pinned issue where you can report all the things you find, or create individual issues with the label v2.
