### ISSUE TITLE
Rematch can not extract dispatchers's type from model

### ISSUE THREAD

**Issue by tianzhich** [rematch/rematch#787]
**Describe the bug**
I followed the [recipe about using rematch with TypeScript](https://github.com/rematch/rematch/tree/master/examples/ts/count/). It seems that TS can not extract the correct types from model dispatchers. Please see below.

**To Reproduce**

1. You can check out the source code on [my codesandbox](https://codesandbox.io/s/rematch-typescript-8mit8), it's a copy from the doc site.

2. Open `src/models/dolphins.ts` and `src/App.tsx`.

3. See error below

> Property 'x' does not exist on type 'never'.

**Expected behavior**
There would be no error and type inference is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/33218310/88539833-7fe09680-d044-11ea-8c09-238302a8a833.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.4
- Browser Chrome 84.0.4147.89

**Additional context**
I found the definition below:

```typescript
export type ExtractRematchDispatchersFromModels<M> = {
	[modelKey in keyof M]: M[modelKey] extends ModelConfig ? ExtractRematchDispatchersFromModel<M[modelKey]> : never
}
```

When doing some extraction of dispatchers' type, TS doesn't think `RootModel[modelKey] extends ModelConfig`, it will use `never` to match the model type, so calling `model.someEffect` will fire the compile error *Property `someEffect` does not exist on type 'never'*.

**dolphins.ts**, you can see `RootModel[modelKey]['effects']` is a function with param `dispatch` which is `RematchDispatch<RootModel>`(infer from `Dispatch`).

```typescript
export const dolphins = {
  state: 0,
  reducers: {
    increment: (state: DolphinsState, payload: string) => state + 1
  },
  effects: (dispatch: Dispatch) => ({
    async incrementAsync(pay: { dolphins: number }) {
      await delay(500);
      dispatch.dolphins.increment("1");
    },
    async incrementSharksAsync() {
      await delay(500);
      dispatch.sharks.incrementAsync(1);
    }
  })
};
```

**index.d.ts**, you can see `ModelConfig['effects']` is `(<M extends Models<K> | void = void>(dispatch: RematchDispatch<M>) => ModelEffects<any>)` , so the function param's type is `RematchDispatch<M>`.

```typescript
export interface ModelConfig<S = any, SS = S, K extends string = string> {
	name?: string
	state: S
	baseReducer?: (state: SS, action: Action) => SS
	reducers?: ModelReducers<S>
	effects?:
		| ModelEffects<any>
		| (<M extends Models<K> | void = void>(dispatch: RematchDispatch<M>) => ModelEffects<any>)
}
```

`RootModel[modelKey]` can not extend from `ModelConfig` because `RootModel[modelKey]['effects']` can not extend from `ModelConfig['effects']`. 

And because the function param is bivariant in TS, so `RematchDispatch<M>` can not extend from `RematchDispatch<RootModel>`. But why?

I think the reason is using the restriction `M extends Models<K>`. `RootModel` cant extend from `Models`, and vice versa. If we leave this restriction and let TS infer type param `M` from itself, there would be no errors.

If you think it is possible, I want to initiate a PR about this.

**Comment by tianzhich** [comment]
PR #788

**Comment by semoal** [comment]
Hi mate, could you give a try to our **next** version? We fixed all the issues with typescript typings.
```
yarn add @rematch/core@next
--
npm install --save @rematch/core@next
```

I added a pinned issue where you can report all the things you find, or create individual issues with the label v2.
