### ISSUE TITLE
@rematch/persist

### ISSUE THREAD

**Issue by heny** [rematch/rematch#791]
When using @rematch/persist, localStorage did not save it. Please help to see what is wrong. Thank you
demo url：https://codesandbox.io/s/friendly-leaf-1qj6h

**Comment by pjamrozowicz** [comment]
> When using @rematch/persist, localStorage did not save it. Please help to see what is wrong. Thank you
> demo url：https://codesandbox.io/s/friendly-leaf-1qj6h

Are you just starting up a new project? You could consider giving a try the new version of Rematch (https://rematch.netlify.app/#/quick-start) and see if you have any issues.

**Comment by semoal** [comment]
@heny hi mate, you are not using correctly the plugin.

white should match the model name, if you change ["persisted"] to ["list"], will work correctly.

Anyways, you should try our new version of rematch@next. We reimplemented some features, and improved typrescript typings.

Here you have a working example:
https://codesandbox.io/s/weathered-firefly-wbj4p?file=/src/store/index.js

**Comment by heny** [comment]
@pjamrozowicz Thank you, I will try to use it. I found that the installation document of this link you gave was written incorrectly. Two NPMS appeared

**Comment by semoal** [comment]
> @pjamrozowicz Thank you, I will try to use it. I found that the installation document of this link you gave was written incorrectly. Two NPMS appeared

You're right i'll fix it asap, thanks mate
