### ISSUE TITLE
[V2]-Type 'RootModel' is not assignable to type 'Models'.

### ISSUE THREAD

**Issue by zhangjing28** [rematch/rematch#796]
**Describe the bug**
error: 'Type 'RootModel' is not assignable to type 'Models'.' when run examples/ts/hooks 

**To Reproduce**
just cd example/ts/hooks and `npm i && npm run start`
**Expected behavior**
no error

**Comment by semoal** [comment]
Are you using the next version?

**Comment by semoal** [comment]
<img width="776" alt="Screenshot 2020-08-10 at 11 28 16" src="https://user-images.githubusercontent.com/22656541/89768941-9edb3000-dafc-11ea-9b45-8e16ab5258f8.png">

For me compiled succesfully, steps i did:

- On root: npm install & npm run bootstrap
- After that moved on that example folder and run: npm start

0 fails.
````
hooks-react-ts git:(next) ✗ tsc -v
Version 3.9.3
```

**Comment by zhangjing28** [comment]
@semoal Thanks, it was my mistake! I did not run the example on the brunch 'next'
