### ISSUE TITLE
_this is undefined - in example scripts

### ISSUE THREAD

**Issue by AUTOi** [rematch/rematch#798]
New to React but trying out your example scripts, but cant get them to work, any ideas why its broken:

`TypeError: _this is undefined
onModel/<
F:/Repos/reactselect/src/index.ts:101
onModel
F:/Repos/reactselect/src/index.ts:99
prepareModel/<
F:/Repos/reactselect/src/rematchStore.ts:94

  91 | 		model
  92 | 	)
  93 | 
> 94 | 	bag.forEachPlugin('onModel', (onModel) => onModel(model, rematchStore))
  95 | }
  96 | 
  97 | /**

forEachPlugin
F:/Repos/reactselect/src/bag.ts:27

  24 | ): void {
  25 | 	for (const plugin of config.plugins) {
  26 | 		if (plugin[method]) {
> 27 | 			fn(plugin[method] as NonNullable<PluginHooks[Hook]>)
     | ^  28 | 		}
  29 | 	}
  30 | },

prepareModel
F:/Repos/reactselect/src/rematchStore.ts:94

  91 | 		model
  92 | 	)
  93 | 
> 94 | 	bag.forEachPlugin('onModel', (onModel) => onModel(model, rematchStore))
  95 | }
  96 | 
  97 | /**

createRematchStore
F:/Repos/reactselect/src/rematchStore.ts:57

  54 | 
  55 | // generate dispatch[modelName][actionName] for all reducers and effects
  56 | for (const model of bag.models) {
> 57 | 	prepareModel<TModels & TExtraModels, typeof model>(rematchStore, bag, model)
     | ^  58 | }
  59 | 
  60 | bag.forEachPlugin('onStoreCreated', (onStoreCreated) => {

init
F:/Repos/reactselect/src/index.ts:12

   9 | 	initConfig?: InitConfig<TModels>
  10 | ): RematchStore<TModels & TExtraModels> => {
  11 | 	const config = createConfig(initConfig || {})
> 12 | 	return createRematchStore<TModels, TExtraModels>(config)
  13 | }
  14 | 
  15 | export const createModel = <TState, TBaseState = TState>() => <

./src/store.js
F:/Repos/reactselect/my-app/src/store.js:5

  2 | import selectPlugin from '@rematch/select'
  3 | import * as models from './models'
  4 | 
> 5 | export const store = init({
  6 |     models,
  7 |     plugins: [selectPlugin()],
  8 | })

__webpack_require__
F:/Repos/reactselect/my-app/webpack/bootstrap:784

  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;

fn
F:/Repos/reactselect/my-app/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

./src/index.js
http://localhost:3000/static/js/main.chunk.js:173:83
__webpack_require__
F:/Repos/reactselect/my-app/webpack/bootstrap:784

  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;

fn
F:/Repos/reactselect/my-app/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

1
http://localhost:3000/static/js/main.chunk.js:275:18
__webpack_require__
F:/Repos/reactselect/my-app/webpack/bootstrap:784

  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;

checkDeferredModules
F:/Repos/reactselect/my-app/webpack/bootstrap:45

  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 

webpackJsonpCallback
F:/Repos/reactselect/my-app/webpack/bootstrap:32

  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:65`

**Comment by semoal** [comment]
Could you provide the steps that you done?
I can't see anything in the things you pasted

**Comment by haikyuu** [comment]
@AUTOi a codesandbox would be very helpful

**Comment by AUTOi** [comment]
New React App via:
npx create-react-app my-app --template redux
npm install @rematch/core@next

Then copied these files:
https://github.com/rematch/rematch/tree/next/examples/select-react/src

My package.json


{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@reduxjs/toolkit": "^1.4.0",
    "@rematch/core": "^2.0.0-next.1",
    "@rematch/select": "^2.0.5",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.1",
    "react-scripts": "3.4.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by AUTOi** [comment]
Fixed, by adding "@reduxjs/toolkit": "^1.4.0", to your package.json and using that instead of mine.

**Comment by semoal** [comment]
You don't need reduxjs toolkit if you're planning to use rematch. Actually toolkit was built thinking in alternatives to redux boilerplate like rematch.

This issue is not related to rematch. Thanks for using @rematch mate, if you find any issue, or improvement feel free to open other issue
