### ISSUE TITLE
rematch next effects argument error

### ISSUE THREAD

**Issue by JoviCheng** [rematch/rematch#808]
**Describe the bug**
I am using **2.0.0-next.2.**, i trying a demo with DOCS.Quick Start,

when i give the rootState declarations RootState,

like this:

`effects: (dispatch) => ({
    async add(payload: number, rootState) {
      const { count } = rootState.main
      dispatch.main.setFields({
        count: Number(count + payload)
      })
    }
  })`

to

`effects: (dispatch) => ({
    async add(payload: number, rootState: RootState) {
      const { count } = rootState.main
      dispatch.main.setFields({
        count: Number(count + payload)
      })
    }
  })`

and the ts will report error.

**Expected behavior**
ts dont report the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8762574/91120840-231adf00-e6c9-11ea-9e49-02f09c67fe1a.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by semoal** [comment]
State is automatically infered you dont need to type It.

Look the documentation, on quick start section!

**Comment by JoviCheng** [comment]
> State is automatically infered you dont need to type It.
> 
> Look the documentation, on quick start section!

![image](https://user-images.githubusercontent.com/8762574/91132870-e3132680-e6df-11ea-8563-9241f5df96ef.png)

thanks! 
you mean like this ?

**Comment by tianzhich** [comment]
We fixed the auto inference of `rootState` param on the next version, stay tuned.

**Comment by JoviCheng** [comment]
> We fixed the auto inference of `rootState` param on the next version, stay tuned.

got it,thanks!

**Comment by semoal** [comment]
Released the fix on next tag. 2.0.0-next.4

1. You need the as on the rootState param it's automatically inferered.
2. If you're state is complex, you must use the as on state object, if not, just let typescript infer the types.

Check https://rematch.netlify.app/#/quick-start for more documentation also you can look examples folder count-react-ts and hooks-react-ts are tested on our testing suite so feel free to use them as a boilerplate.
