### ISSUE TITLE
Type 'RootModel' does not satisfy the constraint 'string'.ts(2344)

### ISSUE THREAD

**Issue by linonetwo** [rematch/rematch#813]
**Describe the bug**
I'm trying to setup as ts example:

```
export interface RootModel extends Models<RootModel> {
  debug: typeof debug;
}
const models: RootModel = { debug };
export const store = createStore(models);

export type Store = typeof store;
export type Dispatch = RematchDispatch<RootModel>;
export type RootState = RematchRootState<RootModel>;

```

But I get `Type 'RootModel' does not satisfy the constraint 'string'.ts(2344)`

Because 

```
export type Models<K extends string = string> = {
	[key in K]: ModelConfig
}
```

**To Reproduce**

Try example

https://github.com/rematch/rematch/blob/df373bddd487bd2d4467df13ee071f2eae28acba/examples/hooks-react-ts/src/models/index.ts#L5-L8

**Expected behavior**
It should allow example to pass

**Comment by semoal** [comment]
Hm, are you using next version?

npm install --save @rematch/core@next

**Comment by linonetwo** [comment]
Thank you! I should have tried this first...
