### ISSUE TITLE
 Remove @ts-ignore on codebases

### ISSUE THREAD

**Issue by tianzhich** [rematch/rematch#816]
In the previous refactor, too much `@ts-ignore` was used. We are thinking to remove them before the stable release. We need to consider all the packages following: 

- [x] core
- [x] immer
- [x] loading
- [x] persist
- [x] select
- [x] updated

**Comment by semoal** [comment]
Only core & select has pending @ts-ignores 👍🏻

**Comment by tianzhich** [comment]
I removed the ts-ignore from `core` and improved typings based on that. Have a look Sergio 😄

If there is no error, the only left package was `select` which was more complex than others, we are near!

**Comment by tianzhich** [comment]
I came to some problem with `select`. It differs much from other plugins, on typings and designs. And I'm not familiar with reselect. Some help needed.

**Comment by tianzhich** [comment]
I need some guides from `reselect` and `select` plugin users.

**Comment by tianzhich** [comment]
Only a few problems with select plugin typings. It is better to track new issues with more feedbacks.
