### ISSUE TITLE
[@rematch/loading] effects always be loading if they were unresolved before.

### ISSUE THREAD

**Issue by tianzhich** [rematch/rematch#821]
**Describe the bug**
I found if there was an unresolved effect, then `state.loading.model.effects.effect` will always being true.

**To Reproduce**
I accidentally ran into an unresolved promise returned by one of my effects. And I found the loading of it will always be true even it was resolved in the next effect call.

I found a code snippet of loading package: 

```ts
try {
    // show loading
    rematch.dispatch[loadingModelName].show({ name, action })
    // dispatch the original action
    const effectResult = origEffect(...props)

    // check if result is a promise
    if (effectResult?.then) {
        // hide loading when promise finishes either with success or error
        effectResult
            .then((r: any) => {
                rematch.dispatch[loadingModelName].hide({ name, action })
                return r
            })
            .catch((err: any) => {
                rematch.dispatch[loadingModelName].hide({ name, action })
                throw err
            })
    } else {
        // original action doesn't return a promise so there's nothing to wait for
        rematch.dispatch[loadingModelName].hide({ name, action })
    }

    // return the original result of this reducer
    return effectResult
} catch (error) {
    rematch.dispatch[loadingModelName].hide({ name, action })
    throw error
}
```

If there was an unresolved promise, it will never be hidden. In the loading package, zero was used for loading and non-zero for unloading. So the value would be non-zero forever.

Can we just use 0 for unloading and 1 for loading, not the plus 1 for loading and minus 1 for unloading?

```ts
const loading: LoadingModel<TModels, typeof isAsNumber> = {
    name: loadingModelName,
    reducers: {
        // use 0 instead
        hide: createLoadingAction(converter, -1, cntState),
        // use 1 instead
        show: createLoadingAction(converter, 1, cntState),
    },
    state: loadingInitialState as LoadingState<TModels, typeof isAsNumber>,
}
```

In `createLoadingAction`: 

```ts
const createLoadingAction = <
	TModels extends Models<TModels>,
	AsNumber extends boolean = false
>(
	converter: Converter,
	i: number,
	cntState: InitialState<true>
): Reducer<LoadingState<TModels, AsNumber>> => (
	state,
	payload: Action<{ name: string; action: string }>['payload']
): LoadingState<TModels, boolean> => {
	const { name, action } = payload || { name: '', action: '' }

        // just set to 0 or 1
	cntState.global += i
	cntState.models[name] += i
	cntState.effects[name][action] += i

	return {
		...state,
		global: converter(cntState.global),
		models: {
			...state.models,
			[name]: converter(cntState.models[name]),
		},
		effects: {
			...state.effects,
			[name]: {
				...state.effects[name],
				[action]: converter(cntState.effects[name][action]),
			},
		},
	}
}
```

**Comment by semoal** [comment]
This would be a breaking change, because right now if someone is using loading plugin for handling situations with many promises running.

I'm thinking in situations where this can be useful (in my opinion there isn't, i didn't thought yet too much) 

For me should be:  
- asNumber : 1 loading - 0 not loading
- asBoolean : `true` loading - `false` not loading

**Comment by tianzhich** [comment]
You are right. I have not fully understood the purpose. There shouldn't be an unresolved promise, I asked for my service provider to return the error message and resolve the promise.

**Comment by semoal** [comment]
We'll release a Major version with brraking chances so if we consider something is better than the actual codebranch, just lets improve it

**Comment by semoal** [comment]
I'm goin' to change this @tianzhich the correct way is 1 loading, 0 not loading, true loading false not loading.

Shouldn't be incrementers.

**Comment by semoal** [comment]
Well, looking and the examples folder i saw the logic of this.

Some users are using this to loading.model.effects, asNumber to know how many promises are running at x time. 

So probably this behaviour should be the standard way of doing the things.

**Comment by tianzhich** [comment]
> Well, looking and the examples folder i saw the logic of this.
> 
> Some users are using this to loading.model.effects, asNumber to know how many promises are running at x time.
> 
> So probably this behaviour should be the standard way of doing the things.

Yep, this was the original purpose! I'll closed this.
