### ISSUE TITLE
1.x to 2.x migration effect does not return promise

### ISSUE THREAD

**Issue by saraivinha85** [rematch/rematch#823]
**Describe the bug**
In v2.0 the effect function does not return a promise.

In version 1.x I have this code that works fine.
```
model.js
effects: (dispatch) => ({
        async first(payload, state) {
              await ...
        },

        async second(payload, state) {
             await ...
        }
})

component.js
useEffect(() => {
        first().then(() => {
             second()
        }
})

const mapDispatch = (dispatch) => ({
   first: dispatch.first(),
   second: dispatch.second()
})
```

In v2.x it complains that first.then is not a function.

**To Reproduce**
Try the code above

**Expected behavior**
I want to be able execute the second effect after the first one succeeded.

**Comment by somenugget** [comment]
Shouldn't it be?
```js
const mapDispatch = (dispatch) => ({
   first: dispatch.model.first, 
   second: dispatch.mode.second
})
```
with model name specified and without `()`

**Comment by saraivinha85** [comment]
Please check example:
https://github.com/saraivinha85/rematch-next-test

**Comment by semoal** [comment]
reducers are not promises, if you use effects you will get that wanted promise,
I'll create a pull request to your codebase with some best practices later tonight

**Comment by semoal** [comment]
https://github.com/saraivinha85/rematch-next-test/pull/1/files @saraivinha85 here you have mate

**Comment by saraivinha85** [comment]
Thanks for the explanation and example.
But can you tell me why my example worked with version 1.x?

**Comment by semoal** [comment]
Probably in version 1.x reducers were also promises, but that's not correct
