### ISSUE TITLE
[@rematch/loading] effect returning integer instead of boolean

### ISSUE THREAD

**Issue by vanzi6** [rematch/rematch#824]
Hello all, I have the same problem.

[codesandbox example](https://codesandbox.io/s/rematch-loading-test-zyovu)

Not the best quality, but you can see that `state.loading.effects.count.addByAsync ` is changing from `boolean` to `number`
![image](https://user-images.githubusercontent.com/21037158/94296648-d8acac80-ff6b-11ea-8189-6a7194aa7f83.png)

**To replicate** 
1. Go to example link, open console 
2. Click login button
3. Click counter button few times
4. Click logout button
5. Click login button
6. Click counter button few times

**Where did I found how to reset whole state?**
[Link](https://github.com/rematch/rematch/issues/663)

I would like to know is this a bug or not? 

If this is not a bug is there any other similar way to reset whole state?
I know I can write reset function for each model and call them when needed, but then I need to keep track of them all.

_Originally posted by @vanzi6 in https://github.com/rematch/rematch/issues/736#issuecomment-699056424_

**Comment by semoal** [comment]
Could you try to install the next version if the issue persists?
We're actively working on the next branch so a faster fix probable will come in that branch

Thanks

**Comment by vanzi6** [comment]
I change versions [codesandbox](https://codesandbox.io/s/rematch-loading-test-forked-nqoh0)

@rematch/core 1.4.0 -> 2.0.0-next.5
@rematch/loading 1.2.1 -> 2.0.0-next.5

I can not reproduce the problem.

In my project I will have to rewrite some code in order to do some more testing, since I am using typescript.

In [documentation](https://rematch.netlify.app/#/quick-start) I see you are actually advising `npm install @rematch/core@next`.
Is this safe for production mode?

**Comment by semoal** [comment]
Actually yes, we are just improving examples, improved typescript experience
https://github.com/rematch/rematch/issues/792

> I change versions [codesandbox](https://codesandbox.io/s/rematch-loading-test-forked-nqoh0)
> 
> @rematch/core 1.4.0 -> 2.0.0-next.5
> @rematch/loading 1.2.1 -> 2.0.0-next.5
> 
> I can not reproduce the problem.
> 
> In my project I will have to rewrite some code in order to do some more testing, since I am using typescript.
> 
> In [documentation](https://rematch.netlify.app/#/quick-start) I see you are actually advising `npm install @rematch/core@next`.
> Is this safe for production mode?

Actually yes, we are only working on improving typescript experience, the codebase is fully rewriten to typescript & lerna.
At the end of october we'll release v2 as a stable version, so probably is not going to change more.
https://github.com/rematch/rematch/issues/792

**Comment by semoal** [comment]
Also 1.4.0 version is not compatible with newer typescript, so if you're codebase is written in typescript, you must use `next`, and follow the new documentation

**Comment by vanzi6** [comment]
> Also 1.4.0 version is not compatible with newer typescript, so if you're codebase is written in typescript, you must use `next`, and follow the new documentation

I have compared next with 1.4.0 that I am currently using, regarding typescript. I can mostly rewrite it using regex, so not really a big deal.
On the other hand typescript support is way better.

Whether you want to close the issue or leave it open for reference I'll leave it up to you. Thank you.
