### ISSUE TITLE
Question: how to update a value in the store based on other values being set

### ISSUE THREAD

**Issue by alexb148** [rematch/rematch#825]
Hello, I'm not quite sure how best to explain what I'm looking for, so my terminology may not be quite right, but essentially...

What's the best way to have a property in my store update based on the value of other properties? For example, I have boolean properties a, b and c, and a 4th property "all" which should be true if each a, b and c are all true, otherwise false.

My basic model looks like this:

```
const model = {
  state: {
    a: false,
    b: false,
    c: false,
    all: false // if a, b and c are all true, this should be true
  },
  reducers: {
    setA(state, payload) {
      return { ...state, a: payload };
    },
    setB(state, payload) {
      return { ...state, b: payload };
    },
    setC(state, payload) {
      return { ...state, c: payload };
    }
  }
};
```

I'm wondering the best/recommended way to listen to achieve this? Perhaps, I should be checking the 3 values within my reducers, before returning, although that doesn't sound right? Or maybe use effects instead, and check the 3 values here?

I have seen that when I setup my store, I can subscribe to the changes e.g.

```
import * as models from 'models';
const store = init({
  models
});
store.subscribe(() => {
});
```
Would this be a recommended place to do what I want? I worry if it's inefficient here, as the logic would be running when any other property updates also, or whether it's wrong to update the state directly where I'm listening to the state (risk of loops?)

I obviously only really want my logic in one place and not duplicated - the 3 values I need to check could easily be 30 values.

Hopefully I've just missed a simple concept that I need to learn, but if anyone can help out that'd be great, thank you.

**Comment by semoal** [comment]
Hello mate, you could create selectors
https://rematch.netlify.app/#/plugins/select?id=select-plugin
https://github.com/reduxjs/reselect

- Selectors can compute derived data, allowing Redux to store the minimal possible state.
- Selectors are efficient. A selector is not recomputed unless one of its arguments changes.
- Selectors are composable. They can be used as input to other selectors.

If you're codebase is written in typescript, our codebase isn't still 100% compatible wit selectors (on types side), but with javascript you will got a fully powered setup!

An example of use of selectors is a shopping cart that recomputes the price of the cart only when the cart array changes.

**Comment by alexb148** [comment]
@semoal thanks, that does sound like it should do what I want, although I've been experimenting for a while trying to integrate it into my code without much success.

So far I have the following, where I'm trying to create the selector in models.js and map this to my component in App.js.
https://codesandbox.io/s/rematch-select-test-54j5c?file=/src/models.js

Have tried a lot of variations based on what I can see in examples and documentation, but I'll have to keep experimenting another time.

**Comment by semoal** [comment]
https://codesandbox.io/s/rematch-select-test-forked-uz2vc?file=/src/store.js.  @alexb148  here you have mate, you should use the next version

**Comment by alexb148** [comment]
@semoal thank you, this was very helpful and I've got it all working in my app now. There was a little more to importing the selectors into my app than I had expected, I was trying to treat them the same way I map state and dispatch. Getting the hang of it all now though, thanks again!

**Comment by semoal** [comment]
I'm glad I coulda help, We're still improving the compatibility with typescript + re-select(select), if you're experimented on Typescript we're looking for contributors to help =)
