### ISSUE TITLE
v2 - dispatch.<invalid-property> doesn't emit typescript error

### ISSUE THREAD

**Issue by brownbl1** [rematch/rematch#830]
**Is your feature request related to a problem? Please describe.**
First of all, fantastic project. I've really enjoyed using it for a while now and just upgraded to the latest as part of a typescript revamp. But I've noticed a typings issue and I'm not sure if it's a bug or intended behavior, but I think it could improved either way. I've created a sandbox using the latest of everything and I'm seeing this issue where in an effect, the `dispatch` argument will not emit a typescript error when a missing property is referenced (until runtime) but instead that property shows up as an `any` type, even if `useStrict` is set to true. I used your count sample from Getting Started, and added one line in `count.ts`: https://codesandbox.io/s/objective-diffie-w2o01?file=/src/count.ts

**Describe the solution you'd like**
It would be nice if we could error out at compile time for something like this? This becomes a major issue for large scale refactorings. If you change the type, you should get compile time errors.

**Describe alternatives you've considered**
I've tried to find a typescript option to turn on for this, but haven't found relevant.

**Comment by semoal** [comment]
Yes you're absolutly right, it shouldn't return any, should return typescript error

**Comment by brownbl1** [comment]
Thanks.. I am still learning how to write typescript types. I tried to figure out how to change the generics but couldn't quite figure it out.

**Comment by semoal** [comment]
This can be improved on https://github.com/rematch/rematch/blob/next/packages/core/src/types.ts#L427 where ReduxAction is returning any always, there we should do a mapper to check if that effect exists, in that case add any to provide compatibility with Redux Dispatch, if not exists just return never/or unknown as you want.

**Comment by tianzhich** [comment]
I couldn’t find a way. We can’t override the type of redux-dispatch, and we can’t keep the compatibility between rematch-dispatch and redux cause we must keep the type param the same with redux. So we cant pass rootModel to patch redux-dispatch as we do in rematch-dispatch

**Comment by semoal** [comment]
Closed because we can't fix this until typescript design limitations gets resolved
