### ISSUE TITLE
Allow numerous Redux Store instances

### ISSUE THREAD

**Issue by paulmcconico** [rematch/rematch#832]
**Is your feature request related to a problem? Please describe.**
Currently, when I create 2 Rematch stores via the 'init' function exported from @rematch/core, the dispatch methods of the first Rematch store are overwritten with the dispatch methods generated for the second store.

I'm testing the functionality of my application and for each test I need a clean Redux Store. Due to the need for async tests (to test fetch) I cannot necessarily reset state at the beginning of a test and hope that a race condition does not occur (eg. state for one test is modified while another test is taking place). Instead, I suggest creating a new Redux Store with new dispatch methods for each test.

**Describe the solution you'd like**
I'd like a new Dispatch instance for each store generated using the 'init' function.

**Additional context**
Consider the following:

```
import { init } from '@rematch/core';

const myModel= {
  name: 'myModel',
  state: { text: '' },
  reducers: {
    myReducer(state, text) {
      return { ...state, text };
    },
  },
}

const a: Store<any> = init({ models: { myModel } });
const b: Store<any> = init({ models: { myModel } });

a.dispatch.myModel.myReducer('my text');
console.log(b.getState().myModel.text);
// prints 'my text'
console.log(a.getState().myModel.text);
// prints ''
```

**Comment by semoal** [comment]
Hm, looks an interesting situation. I'll take a look on it.
Did you tried with next version or latest?
Thx mate for using rematch

**Comment by semoal** [comment]
You also can take a look to rematch testing suite, that probably will help you creating good tests.

Also I see some errors in your example
- models: must be an object
- const a.dispatch is not written correctly.


On Rematch v2.x.x@next every init functions returns a new store with `Rematch store ${count++}` so any instance is different. Give it a try!

**Comment by paulmcconico** [comment]
@semoal Using version: 0.6.0
Indeed, both are errors. The code above is not what is found in my codebase. The codebase has correct implementation. I will correct the code above.

**Comment by paulmcconico** [comment]
@semoal I read through the example here [](https://rematch.netlify.app/#/quick-start?id=basic-usage) for initializing Rematch. Just a heads up, there is a circular dependency. The 'count.ts' cannot import from 'models.ts' if 'models.ts' imports from 'count.ts'.

May cause some issues when typing models but I haven't tried writing code using this new pattern.

**Comment by semoal** [comment]
The rootModel must be passed to createModel to make it work.

You can look at examples folder where is a https://github.com/rematch/rematch/tree/next/examples/all-plugins-react-ts, full suite with typescript.

**Comment by paulmcconico** [comment]
@semoal My concern is that this version of Rematch JS, a widely adopted framework, suggests a programming pattern that contradicts basic principles of programming. It may be worthwhile to rewrite some of these methods/patterns so that the end-user does not have to introduce a dependency cycle into their application.

**Comment by semoal** [comment]
> @semoal My concern is that this version of Rematch JS, a widely adopted framework, suggests a programming pattern that contradicts basic principles of programming. It may be worthwhile to rewrite some of these methods/patterns so that the end-user does not have to introduce a dependency cycle into their application.

We didn't see any dependency cycle in any application, Typescript setup is "complex", because Redux typing aren't easy, and we try to make it as easy as possible. 

Here you have, https://codesandbox.io/s/flamboyant-germain-n8pq1 we're still improving the examples

**Comment by paulmcconico** [comment]
@semoal Take a look at the example above. Clearly, count.ts imports models.ts AND models.ts imports count.ts.

**Comment by semoal** [comment]
I didnt' say coding is complex, but that import internally is not a dependency cycle, because it's just importing types that internally are resolved from the same file.

Anyways, I'll look into it, if we can look to a better solution to this. Feel free to provide any pull request with your suggerences.

**Comment by paulmcconico** [comment]
@semoal So, you're suggesting that importing types doesn't cause a dependency cycle because the types (imports) are stripped during transpile process?

**Comment by semoal** [comment]
Yes, basically that.

**Comment by paulmcconico** [comment]
@semoal Ok fair enough.

**Comment by paulmcconico** [comment]
Thanks @semoal !

**Comment by semoal** [comment]
Thanks to you for using Rematch Paul
