### ISSUE TITLE
Select plugin working with NextJS Example

### ISSUE THREAD

**Issue by jamesguan** [rematch/rematch#836]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out the best pattern to implement select with nextjs. With the SSR, it complicates things, especially when you have to rehydrate the client with a new store.

**Describe the solution you'd like**
A clearcut example and pattern of working with selectors and nextjs/SSR.
**Describe alternatives you've considered**

**Additional context**

**Comment by semoal** [comment]
Hm, I didn't tried selectors with Nextjs but they should work as Redux works with SSR. We have an example with nextjs in examples folders if you want to improve that example adding selectors and what you find. Will be incredible.

Under the hood Rematch selectors are just `reselect` so they should work out of the box :)

**Comment by jamesguan** [comment]
I guess the issue is the example states to export the select from the store file by doing the following:

`export const { select } = store;`

The problem with SSR is that the store could change which means whatever select was referencing will not be pointing to the correct store.

What I've done is opted for regular selector creation instead of coupling the selector with my model. However, the only downside is that I get extra boilerplate which I guess isn't too bad.

**Comment by semoal** [comment]
Hm, could you provide a repo mate? I'm really interested in your approach

**Comment by jamesguan** [comment]
https://github.com/jamesguan/material-nextjs-foundation

**Comment by semoal** [comment]
Happy to see that you could get it working. Feel free to re-open any issue you found or any improvement that could help Rematch =)

**Comment by hovoaep** [comment]
Guys can you suggest how can change [store](https://github.com/vercel/next.js/blob/canary/examples/with-rematch/shared/store.js) example, for use with the select plugin like this 

store.js
```
export const { select } = store;
```



login.js
```

import { select } from "store";

const user = useSelector(select.auth.userSelector);
```

I need an export select method in store, but the next.js example can't do this. 

Thanks for any help.

**Comment by d3dc** [comment]
@jamesguan @hovoaep 

You can always `useStore()` from `react-redux` if you need the currently rendering store:

```ts
export const Component = () => {
  const { select } = useStore()
  const user = useSelector(select.auth.userSelector)
  
  ...
}
```

**Comment by hovoaep** [comment]
@d3dc @jamesguan 

I create context and pass select to context. For me it's working fine.

_app.tsx
```
export const SelectContext = createContext(null);


   <AuthProvider session={pageProps.session}>
      <Provider store={store}>
        <SelectContext.Provider value={store.select}>
        ...
        </SelectContext.Provider>
    </Provider>
  </AuthProvider>
```

rematch.utils.ts
```
export const getSelect = (): RematchSelect<RootModel> => {
  const select: RematchSelect<RootModel> = useContext(SelectContext);
  return select;
};
```

login.tsx
```
const select = getSelect();
const isLoaded = useSelector(select.auth.isLoadedSelector);
```

**Comment by d3dc** [comment]
It looks like the only reason you would need a separate context is to make Typescript happy.

Is it possible to just type the select in your hook?
```js
export const useSelect = () => {
  const store: RematchStore<RootModel> = useStore(); // <-- this only takes RootState and Actions as generics
  return store.select;
};
```
