### ISSUE TITLE
[Discussion] Confuse Me in Big Model

### ISSUE THREAD

**Issue by alex-zhang** [rematch/rematch#837]
**Is your feature request related to a problem? Please describe.**

hi, rematch team,

First of all, thanks for this library.  

Our team has used it for a while, but I have a question of the best partices of using rematch for nesting model.

For Example, there is  a featureDiablog, FeatureDiablogView and  featureDiablogModel in the folder

|--featureDiablog
|----------------FeatureDiablogView
|----------------featureDiablogModel

But a few time later,  we add a lot of features, and the folder comes below:

|--featureDiablog
|----------------FeatureDiablogView
|----------------views
|---------------------FeatureAView
|---------------------FeatureBView
|---------------------FeatureCView
|----------------featureDiablogModel
|----------------models
|--------------------featureAModel
|--------------------featureBModel
|--------------------featureCModel

and the featureDiablog folder becomes complex. And the view FeatureAView,  FeatureBView, FeatureCView are children of FeatureDiablogView.  And the featureAModel, featureBModel, featureCModel are the sub model of featureDiablogModel.

so for this struct how can we cut the complex model to smaller ones.  specially we want the sub model of the featureDiablogModel are registed when the diablog is openned and un-registed when diablog is closed.

what's best partices for neseting model(or dynamic model), it's confuse me for a while.

or it just only support the flatten mode?

thanks.

**Comment by semoal** [comment]
For me which has sense is to contain a FeatureDiablogModel that imports little Feature-N-Diablog, and just object spreads that features in the main model. For example 


There isn't a BEST-BEST practice just do it like you feel comfortable with it and MAINTAINABLE. 
`FeatureDiablogModel.js`: 

```js
import {
    reducers as featureOneReducers,
    effects as featureOneEffects
  } from "diablog/features/one"

import {
    reducers as featureTwoReducers,
    effects as featureTwoEffects
  } from "diablog/features/two"

export const featureDiablogModel = {
  // I'll store all the state related to this feature here..
  state: {
    data: [],
    // blablabla
  },

  reducers: {
    passData(state, payload) {
      return state + payload
    },
    ...featureOneReducers,
    ...featureTwoReducers,
  },
  effects: (dispatch) => ({
    ...featureOneEffects,
    ...featureTwoEffects,
    someInternalEffect(payload, rootState) {
      dispatch.any.any()
    }
  })
}
```

FeatureOne will export reducers and effects with little logic that can be unit-tested :)

Hope this feel useful for your team, and thanks for using Rematch!

**Comment by alex-zhang** [comment]
ok,  thanks for ur reply.

it make sense.

**Comment by semoal** [comment]
You're welcome =)
