### ISSUE TITLE
Remove immer from immer plugin dependency

### ISSUE THREAD

**Issue by xeoneux** [rematch/rematch#842]
https://github.com/rematch/rematch/blob/next/packages/immer/package.json

Using the immer plugin and then immer in the application bundles two different instances of immer. One is ^7 and the other is ^8.

Is it possible to remove the dependency altogether and just use peer dependency with a warning if immer is not installed?

**Comment by semoal** [comment]
Yes absolutly It should be just a peer.

**Comment by semoal** [comment]
Fixed here https://github.com/rematch/rematch/commit/819d76654779d883379e3f2e25270a45f8ab72c1

We'll release this on tuesday :)

**Comment by semoal** [comment]
Released mate, also we included some overall decreases of size. On @rematch/core we got a reduction of 25% :)
