### ISSUE TITLE
Redux devtools: example for actionSanitizer / stateSanitizer or deactivate entirely for production

### ISSUE THREAD

**Issue by benomatis** [rematch/rematch#843]
Can I receive some help / an example on how to introduce actionSanitizer / stateSanitizer for Redux devtools in Rematch, or how I could maybe deactivate it completely for production?

**Comment by semoal** [comment]
I have to check actionSanitizer but you can disable reduxdevtools easily through Rematch init.
```js
import { init } from '@rematch/core'
export const store = init({
	models,
	redux: {
		devtoolOptions: {
			disabled: false,
		},
	},
})
```
