### ISSUE TITLE
About 'removed `meta` parameter from action'

### ISSUE THREAD

**Issue by pup** [rematch/rematch#844]
from [2.0.0] - 2020-03-29 , the meta is removed from action.
I like meta parameter, some services are frequently used like network request, text/date formatting.
To reduce template code like 'import network from service',  
I will create a plugin to inject these serveices to effects, its very convenient.
Below is the plugin code for old version Rematch.
```
export default function injectServicePlugin(services = {}) {
  return {
    middleware(store) {
      return next => async (action) => {
        action.meta = Object.assign(
          {},
          action.meta,
          services
        );
        await next(action);
      }
    }
  }
}
```

So can you guys consider to add 'meta' feature back to the lib please?

**Comment by semoal** [comment]
Yes probably it's a good idea to keep it if it's useful

**Comment by semoal** [comment]
Released mate :)
