### ISSUE TITLE
When creating multiple instances of the Rematch/Redux Store, invoking an effect method of 'Store A' will in turn invoke the same effect method found in 'Store B'.

### ISSUE THREAD

**Issue by paulmcconico** [rematch/rematch#853]
**Describe the bug**
When creating multiple instances of the Rematch/Redux Store, invoking an effect method of 'Store A' will in turn invoke the same effect method found in 'Store B'.

**To Reproduce**

```
// rootModel.ts
import myModel from './myModel';

export interface RootModel extends Models<RootModel> {
  myModel: typeof myModel;
} 

```
```
// myModel.ts
import { createModel } from '@rematch/core';
import { RootModel } from './RootModel';

export default createModel<RootModel>()({
  name: 'myModel',
  state: { count: 0 },
  reducers: { inc(state) { return { ...state, count: state.count + 1 } } },
  effects: (dispatch) =>({
    incAsync: async () {
      console.log('dispatch id', dispatch.id);
    }
  })
});
```

```
// globalStore.ts
import { createStore as createReduxStore } from 'redux';
import { init } from '@rematch/core';
import myModel from './myModel';
import { RootModel } from './RootModel';

let storeCount = 0;

export const createStore = () => (
  init<RootModel, RootModel>({
    models: { myModel },
    redux: {
      reducers: {},
      middlewares: [],
      createStore: (rootReducer, initialState, enhancers) => {
        const reduxStore = createReduxStore(rootReducer, initialState, enhancers);
        reduxStore.dispatch.id = storeCount++;
        return reduxStore;
      },
    },
  })
);
```

```
// main.ts
import { createStore } from './globalStore.ts';

const storeA = createStore();
const storeB = createStore();

storeA.dispatch.myModel.inc();
console.log('storeA count', storeA.getState().myModel.count);
console.log('storeB count', storeB.getState().myModel.count);

// outputs (EXPECTED)
// storeA count, 1
// storeB count, 0

storeA.dispatch.myModel.incAsync();
// outputs (UNEXPECTED)
// 'dispatch id', 0
// 'dispatch id', 1
```

**Expected behavior**
I would expect that the invocation of a model's effect method found in store A would not trigger the invocation of the same effect method found in store B.

I've tried deep cloning the model before creating the stores to no avail. Any ideas? Perhaps I can fix this issue with a change during the store creation process..?

**Comment by semoal** [comment]
Hm, i can't reproduce that error on our test suite. 

```ts
	const count1 = {
			state: { count: 0 },
			reducers: {
				change(state: any, payload: number) {
					return { ...state, count: payload }
				},
			},
			effects: (dispatch: any) => ({
				async increment(payload: number): Promise<void> {
					dispatch.count.change(payload)
				},
			}),
		}

		const store1 = init({
			models: { count: count1 },
		})
		const store2 = init({
			models: { count: count1 },
		})

		await store1.dispatch.count.increment(1)
		await store2.dispatch.count.increment(5)

		expect(store1.getState().count).toEqual({ count: 1 })
		expect(store2.getState().count).toEqual({ count: 5 })

```

This works as expected. Feel free to fork Rematch and introduce an example on our test suite (you can introduce it inside `core/multiple.ts` and iterate over there

**Comment by paulmcconico** [comment]
@semoal I think the issue is related to the fact that my example passes a singleton (myModel) when creating the Rematch Store  whereas your test example above defines two separate objects as models. The effect methods within your models are unique (different locations in memory).

My use case for multiple Rematch stores requires that the structures of the global stores are identical. To define this structure I need only define a single module per model. What I'm getting at is that maybe we should begin to define our models as classes. Then we can have separate instances of effect methods. Something like this:

```
// myModel.ts
class MyModel extends RematchModelBase {
  effects = {
    increment: async () => {
      ...
    }
  }
}
```

Then Rematch can instantiate the model (using the 'new' operator) while parsing the models found in config during the store creation process using.

**Comment by semoal** [comment]
Yes, i understand the problem, but could you provide a mnimal setup on our test suite and we iterate over there, probably We could help much more
