### ISSUE TITLE
Get rootState in effects

### ISSUE THREAD

**Issue by oeddyo** [rematch/rematch#854]
Hi there,

Great project! Love it!

I have a general question: how could I get rootState (or specific model state is fine too) in effects?

The code below works totally fine but to use the function in components, I will need to pass down a state which feels cumbersome. What I would like is to NOT pass a rootState in my components if possible
```
 effects: (dispatch) => {
    return {
      async doSomething(state: MyCoolState): Promise<void> {
        ...
        return Promise.resolve();
      },
    };
  },
```

 I saw in quick-start and some issues that there's a "rootState" somehow but I just can't figure out how. 

```
export const count = {
	state: 0, // initial state
	reducers: {
		// handle state changes with pure functions
		increment(state, payload) {
			return state + payload
		},
	},
	effects: dispatch => ({
		// handle state changes with impure functions.
		// use async/await for async actions
		async incrementAsync(payload, rootState) { // WHERE IS THE rootState HERE FROM?
			await new Promise(resolve => setTimeout(resolve, 1000))
			dispatch.count.increment(payload)
		},
	}),
}
```

I also tried to use "this" but in typescript I cannot seem to access the "state" inside effects. Probably that's a TS scope thing?

Will appreciate if you can give me some pointers :)

**Comment by oeddyo** [comment]
Searched around a bit more and I just saw that you have to provide a "payload" parameter to effects function, and rootState is the second param in the signature. Does that mean I have to pass the rootState from component?

```
export type ModelEffect<
	TModels extends Models<TModels> = Record<string, any>
> = (
	payload: Action['payload'],
	rootState: RematchRootState<TModels>,
	meta: Action['meta']
) => any

```

**Comment by oeddyo** [comment]
I believe I just figured it out. So in my react component I did 

doSomething(payload)

and in "effects" upon debugging I actually saw a "rootState" provided somehow. 
```
      async doSomething(
        payload: {
          blah: string;
        },
        rootState: RootState
      ): Promise<void> {
```

So here rootState has value even if I call doSomething({"blah": "123"}). Is it expected?

**Comment by semoal** [comment]
`state` in effects is automatically infered by typescript for autocompletation you need to type it. 
And yes, internally effects already pass the global state to all effects methods :)

The only issue you will get if you pass:

```js
model.dispatch(someParam, otherParam)
```

won't work because we always set 2nd param to the global state

**Comment by oeddyo** [comment]
Got it. Thanks for the quick response @semoal !

While I have you here, another quick question: I don't seem to be able to clear store states between unit-tests. I saw you had something like a rootReducer which returns undefined to clear it. But it doesn't really work on my end:

```
describe("Test my model", () => {
  let store: RematchStore<RootModel>;
  beforeEach(() => {
    store = init<RootModel>({
      models: {
        mymodels,
      },
      redux: {
        rootReducers: {
          "@@RESET": (): undefined => {
            console.log("executing!!!!!!");
            return undefined;
          },
        },
      },
    });
  });
  it("test1", () => {});
  it("test2": () => {});
```
I can confirm the reset part is executed each time before the next run, but the state is still kept. Is there anyway to make it clear the whole store? Also i intentionally put store outside but also tried to scope the "store" in each test. The result is the same and no states cleared between each run

**Comment by oeddyo** [comment]
OK I understand the problem now. The reason is when I'm creating store, I'm importing the "mymodels" from another file. But in that file I have 

```
export const mymodels = createModel<RootModel>()({
...blahblah
});
```

So when store1 and store2 (in two test cases) are creating, they use the same {models: mymodels} which is probably where the state lives?

If I replace {models: mymodels} with {models: _.cloneDeep(mymodels)} then things are fine. 

Is this expected & a good practice? Any suggestions?

**Comment by tianzhich** [comment]
> So when store1 and store2 (in two test cases) are creating, they use the same {models: mymodels} which is probably where the state lives?

Redux update state immutably so the state shouldn't be the same. You can do more checks on your test. 

And also, we import the same model in our [tests](https://github.com/rematch/rematch/blob/next/packages/loading/test/loading-asBoolean.test.ts#L19) of `@rematch/loading`, the state was not kept.
