### ISSUE TITLE
How to delay persist?

### ISSUE THREAD

**Issue by danielchan303** [rematch/rematch#855]
I am using the keychain to store my data for security purpose, then I found somthing tricky that the iOS keychain is not deleted when uninstalling the app.

I want to reset the data when the user reinstall the app, however the persist plugin didn't seems to provide me any ways to delay the rehydration. I cannot check whether the user just reinstall the app and so I can clear the data before the rehydration. Any ideas?

**Comment by semoal** [comment]
Under the hood we're using redux-persist, so probably reading the `redux-persist` documentation will help you a lot.
In their documentation says:
>Redux persist ships with react integration as a convenience. The PersistGate component is the recommended way to delay rendering until persistence is complete. It works in one of two modes

Probably this could be useful for you

**Comment by danielchan303** [comment]
PersistGate let me know whether the rehydration is finished, but it isn't what I wanted. I want to prevent rehydration in case the app is reinstall, in that case the data in the keychain should not be restored to the store, the app should look like fresh-install.

**Comment by danielchan303** [comment]
What I think might be helpful is the { manualPersist: true } option of persistStore, but it cannot be used in the persist plugin of the rematch.

**Comment by semoal** [comment]
Rematch accepts passing as third argument to the plugin persistStoreOptions so, yes, it can be used perfectly on Rematch plugin

**Comment by danielchan303** [comment]
Typescript warn me that manualPersist is not there so I thought it cannot be used there, but I tried and found it actually works.

Thank you very much semoal!

**Comment by semoal** [comment]
https://github.com/rematch/rematch/commit/21b13715d1bb5f4cec979f1cb2f6c3cf61c45709
I've introduced a little change to autocomplete this type .
Actually `redux-persist` doesn't expose `manualPersist` as a type :)

Thanks for using Rematch!
