### ISSUE TITLE
feat: @rematch/codemods :)

### ISSUE THREAD

**Issue by semoal** [rematch/rematch#856]
**Is your feature request related to a problem? Please describe.**
I want to create a codemod for migrating Redux projects to Rematch with just one command.

**Describe the solution you'd like**
- Redux-thunks and redux-sagas to effects
- Reducers to reducers
- Typescript to typescript

**Additional context**
I'll post here some guidelines if someone wants to pick this amazing feature.

**Comment by sunOpar** [comment]
Would you write some guidelines? I'm interested in this.
