### ISSUE TITLE
Cannot add property companyDeal, object is not extensible

### ISSUE THREAD

**Issue by yatessss** [rematch/rematch#858]
**Describe the bug**

```js
Uncaught TypeError: Cannot add property companyDeal, object is not extensible
    at onModel (loading.esm.js:113)
    at core.esm.js:289
    at core.esm.js:214
    at Array.forEach (<anonymous>)
    at Object.forEachPlugin (core.esm.js:212)
    at prepareModel (core.esm.js:288)
    at Object.addModel (core.esm.js:250)
```

**To Reproduce**

1. use loadingPlugin
2. addModel in store （add more than one Model  will throw error ） 

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/13636879/106241453-0a4ac280-6241-11eb-9345-95bdac8f0114.png)

**Desktop (please complete the following information):**

 "@rematch/core": "2.0.0-next.10",
    "@rematch/immer": "2.0.0-next.1",
    "@rematch/loading": "2.0.0-next.10",

**Additional context**

**Comment by tianzhich** [comment]
Can you provide a reproduce demo using [CodeSandbox](https://codesandbox.io/)?

**Comment by semoal** [comment]
https://codesandbox.io/s/rematch-todos-demo-forked-xlq9k?file=/App.js Here you have a base project where you can reproduce the issue @yatessss
