### ISSUE TITLE
Circular reference error when defining effect in model (Typescript)

### ISSUE THREAD

**Issue by andrejpavlovic** [rematch/rematch#864]
**Describe the bug**
Unable to create model due to circular reference error.
```
Type of property 'myModel' circularly references itself in mapped type '{ [x: string]: any; myModel: any; }'.ts(2615)
```

**Reproduce Link**
https://codesandbox.io/s/rematch-model-circular-reference-fibjz?file=/src/index.ts

**To Reproduce**
1. Open the link to codesandbox and look at the compile time errors.

**Expected behavior**
No compile-time errors present

![2021-02-15_092214](https://user-images.githubusercontent.com/983644/107957956-569b3f80-6f6f-11eb-8158-2bf41c57034e.png)

**Desktop**
- OS: Win10
- Browser: Edge
- Version: 88

**Comment by semoal** [comment]
Andrej, thanks for pointing this out, we'll look asap to fix the issue!

**Comment by TC-mSundaram** [comment]
I was following the Typescript documentation [1] and came across this as well. 

[1] https://rematchjs.org/docs/getting-started/typescript

**Comment by semoal** [comment]
Yes, we're already working on this, probably in a few days we'll ship the fix. We did a hard work with typescript and this case was totally forgot.

**Comment by semoal** [comment]
Alright, this issue is a design limitation of Typescript, meanwhile Typescript don't improve this behaviour Rematch "can't type properly" effects *THAT RETURN SOMETHING*.

Returning data inside effects isn't an usual behaviour and IS NOT RECOMMENDED, let me explain why:

If we accept returning data inside effects functions as a usual way to work, we could derive in bugs pretty complicated to debug because React or other similar frameworks won't know if something has changed. It's more intelligent to move pure functions that return something just be outside of Redux|Rematch ecosystem.

If you need to store something on the state you can easily use the reducers methods (Redux way of doing this, but easier on Rematch)

Taking the example you proposed @andrejpavlovic :

```ts
import { createModel } from "@rematch/core";
import { RootModel } from "./";

type IdsType = {
  [name: string]: {
    enabled: boolean;
  };
};
interface IModelState {
  ids: IdsType;
}

export const myModel = createModel<RootModel>()({
  state: {
    ids: {}
  } as IModelState,
  reducers: {
    setIdEnabled(state, payload: IdsType) {
      // whatever you want with the payload and the state :)
      return { };
    }
  },
  effects: (_dispatch) => ({
    async isIdEnabled(payload: { name: string }, rootState) {
      const { myModel } = rootState;
      const id = myModel.ids[payload.name];
      _dispatch.myModel.setIdEnabled({ id });
    }
  })
});
```

You will get autocomplete of myModel effects and reducers, and payload typing also will work.

Anyways, if you still are thinking about returning data inside effects... you can type the rootState to `any` and Typescript compiler won't be mad about that.

```ts
 async isIdEnabled(payload: { name: string }, rootState: any) {
    const id = rootState.ids[payload.name];
    _dispatch.myModel.setToState({ id });
    return id
  }
```

@TC-mSundaram was your issue also related to returning data inside effects? is it anywhere in the documentation?, could be apotential bug on the documentation and is missleasing

**Comment by andrejpavlovic** [comment]
Thanks @semoal, that kind of makes sense. Do you know of any issues opened in typescript repo that are relevant to this issue? Just thought it would be useful to include them here for completeness.

I'll look into restructuring the code to avoid returning values from effects directly. We've been using rematch v1 for a while with custom typing and I wanted to move to v2 for the better typing support.

**Comment by andrejpavlovic** [comment]
After playing around with it some more, looks like the best workaround is to explicitly define the type returned by the effect.
https://codesandbox.io/s/rematch-model-circular-reference-forked-dfvst?file=/src/index.ts

So instead of
```typescript
async isIdEnabled(payload: { name: string }, rootState) {
   // ...
}
```
define the return value
```typescript
async isIdEnabled(payload: { name: string }, rootState): Promise<boolean> {
  // ...
}
```

**Comment by semoal** [comment]
> After playing around with it some more, looks like the best workaround is to explicitly define the type returned by the effect.
> https://codesandbox.io/s/rematch-model-circular-reference-forked-dfvst?file=/src/index.ts
> 
> So instead of
> 
> ```ts
> async isIdEnabled(payload: { name: string }, rootState) {
>    // ...
> }
> ```
> 
> define the return value
> 
> ```ts
> async isIdEnabled(payload: { name: string }, rootState): Promise<boolean> {
>   // ...
> }
> ```

Oh much better than my workaround, Ill speak with @tianzhich if we can solve this internanlly

**Comment by tianzhich** [comment]
Hi all, I'm at the Chinese Spring Festival now. I may try to fix this next week. And also, we need help from other TS contributors. If you can help much appreciated. @andrejpavlovic

**Comment by TC-mSundaram** [comment]
@semoal Thanks for asking. I think I was mistaken. I was trying to upgrade `rematch` in an old project, so maybe something was misaligned, as when I try it now with a fresh project I am not able to reproduce. I'll keep looking.

**Comment by semoal** [comment]
> @semoal Thanks for asking. I think I was mistaken. I was trying to upgrade `rematch` in an old project, so maybe something was misaligned, as when I try it now with a fresh project I am not able to reproduce. I'll keep looking.

Probably when you upgraded to a new project is the case of returning values on effects, as @andrejpavlovic said you can force the type on the effect and will be solved. Anyways probably tianzhin will take a look if we can resolve this by our own. 

I've created a section on Typescript page to help future users:
https://rematchjs.org/docs/getting-started/typescript#effects-returning-values

Feel free to create a new issue if you find something =) Pretty appreciated the feedback guys
