### ISSUE TITLE
Error in all-plugins-react-ts selectors example and my production project !

### ISSUE THREAD

**Issue by masiya255** [rematch/rematch#865]
Hello everyone ! The error occurs when trying to call a neighboring selector, this applies to our project in production, please tell me when you will fix it or how to fix it, please ...

[https://codesandbox.io/s/small-river-irwld
](url)

![image](https://user-images.githubusercontent.com/11834317/108113393-8863f180-70a8-11eb-9638-09ee7abca625.png)

- Chrome

**Comment by semoal** [comment]
Does this error occurs on older version of Rematch? It's just to ensure that isn't a regression or a breaking change from v1 to v2.

We'll investigate it!

**Comment by masiya255** [comment]
> Эта ошибка возникает в более старой версии Rematch? Это просто для того, чтобы убедиться, что это не регресс или критическое изменение с v1 на v2.
> 
> Мы расследуем это!

Last versions
![image](https://user-images.githubusercontent.com/11834317/108117987-c401ba00-70ae-11eb-99ca-7a60ede3c21c.png)

**Comment by masiya255** [comment]
@semoal Hi ! Are there any results on this issue? It's just that it is essential for the further movement of our company. We really love rematch!

**Comment by semoal** [comment]
Yes we'll solve this ASAP, i need to find some free time this weekend. Im right now the only contributor

**Comment by semoal** [comment]
The key is we're executing `this.totalWithShipping()`, you just need to pass the function not executing, change it to: `this.totalWithShipping` and will work.

https://codesandbox.io/s/brave-firefly-1kv57?file=/src/models/cart.ts

**Comment by semoal** [comment]
You can take a look to the new example i've introduced 👍🏻 feel free to reopen or create a new issue you find with select (is the most complex plugin with typescript types..)

**Comment by masiya255** [comment]
> The key is we're executing `this.totalWithShipping()`, you just need to pass the function not executing, change it to: `this.totalWithShipping` and will work.
> 
> https://codesandbox.io/s/brave-firefly-1kv57?file=/src/models/cart.ts

@semoal 
Hi! I am not getting structured typing of selectors within the model, i.e. I cannot reuse selectors.
This problem was solved in version 3.0.1 only for the method store.select. Please fix this too! Thanks !
![image](https://user-images.githubusercontent.com/11834317/108907240-e9547200-7632-11eb-8e9e-708e5b34db41.png)
