### ISSUE TITLE
bind here does nothing

### ISSUE THREAD

**Issue by objectisundefined** [rematch/rematch#872]
https://github.com/rematch/rematch/blob/917b50eeeb73ad222068726060643a60a455295c/packages/core/src/rematchStore.ts#L54

should it be replaced by `rematchStore.addModel = rematchStore.addModel.bind(rematchStore)` or just replace `this` to `rematchStore` in function `addModel`?

https://github.com/rematch/rematch/blob/917b50eeeb73ad222068726060643a60a455295c/packages/core/src/rematchStore.ts#L43-L50

And there are no `addModel` test cases like assigning `rematchStore.addModel` to a a new function.

**Comment by semoal** [comment]
Yes, looking at the code probably it should be like this:
```ts
		addModel(model: NamedModel<TModels>) {
			this.addModel.bind(rematchStore)
			validateModel(model)
			createModelReducer(bag, model)
			prepareModel(this, bag, model)
			this.replaceReducer(createRootReducer(bag))
			reduxStore.dispatch({ type: '@@redux/REPLACE' })
		},
	} as RematchStore<TModels, TExtraModels>
```

I don't understand the case of adding addModel to a new function. Contributions are welcome, if you want to submit this changes, we'll be great =)
