### ISSUE TITLE
Add the ability to implement transform for persist as part of the model

### ISSUE THREAD

**Issue by MOZGIII** [rematch/rematch#875]
**Is your feature request related to a problem? Please describe.**
I don't like to manage serializers / deserializers separately from the model.

**Describe the solution you'd like**
Add a subobject under the key `transform` to the model definition, and make `createModel` to build a persist-suitable transform from it. Then automatically provide use them either via nested persists or via a combined transform for the main reducer. 

**Describe alternatives you've considered**
1. Implementing transforms separately - that's what I don't like in the first place.
2. Implementing a custom hack and not adding this to rematch - this is bad in many ways, mainly I want this to be in the rematch core for the reusability purposes for other projects.

**Additional context**
-

**Comment by semoal** [comment]
Contributions are welcome mate, feel free to submit a pull request and we'll review it.

**Comment by MOZGIII** [comment]
I'm having trouble with the setup:

```
$ cd rematch
$ yarn install
$ cd packages/persist
$ yarn test
...
  ● Test suite failed to run

    test/persist.test.ts:2:22 - error TS2307: Cannot find module '@rematch/core' or its corresponding type declarations.

    2 import { init } from '@rematch/core'
                           ~~~~~~~~~~~~~~~
...
```

Not sure what's wrong (maybe the linking step is missing), but seems like the `CONTRIBUTING.md` is outdated. Tried both locally and via gitpod - same result.

**Comment by semoal** [comment]
Run a `yarn build` for bundling the initial /dist folder, pleas

**Comment by semoal** [comment]
Once you run the first build you don't need to do it anymore if you use `yarn watch` for auto reloading, your tests will run on every change.

**Comment by MOZGIII** [comment]
Thx, I didn't realize a build is required, but it makes sense.
Another issue I found is that Slack link doesn't allow signing up - just signing in. It's a thing with Slack, you need an inviting app of some kind. Discord is a more approachable decent alternative.

**Comment by semoal** [comment]
Yeah I’m agree with that too
We’ll move to discord soon

**Comment by sunOpar** [comment]
Is there any update?

**Comment by MOZGIII** [comment]
On my end the development stalled, as I've implemented a dirty hack at the app level and moved to other stuff for now.
Feel free to pick this issue up if you're interested.

**Comment by sunOpar** [comment]
My solution for this issue is to identify `persistPlugin` and the model's transform property. If they both exist, then pass transform to `persistPlugin`. But the problem is I can't identify `persistPlugin`. It just an object that has `onReducer, onRootReducer, onStoreCreated` property. Do you have any idea? Maybe there has a better solution for this issue.
