### ISSUE TITLE
Suggestion: Error/success handling plugin

### ISSUE THREAD

**Issue by keithpickering** [rematch/rematch#877]
I love the way the  `@rematch/loading` plugin keeps my app's loading state all in one place. Something that stuck out to me as odd was that there's no similar plugin for handling error/success state. So I can now avoid writing a `{ loading, error, success }` object for every reducer, but `error` and `success` are still required if I want to perform some action after the effect finishes, so the returns are diminished. It would be amazing to have a plugin (or plugins) for these as well.

I understand there's a pretty robust plugin API for Rematch, so I'll probably end up creating this myself if it doesn't exist already, but I'm wondering if someone else has already built one and is willing to share.

**Comment by semoal** [comment]
That's a such great idea!

There's two options:
- create a new plugin
- modify loading plugin to handle this

I'm not sure which is the best. I like the 2nd one because users could do:

```ts
const CM = () => {
 const { error, loading, success } = useSelector(state => state.loading.modelx.effectx)
}
```

If we create another plugin with other state, we force the user to:

```ts
const CM = () => {
 const { error, success } = useSelector(state => state.pluginname.modelx.effectx)
 const { loading } = useSelector(state => state.loading.modelx.effectx)
}
```
or 
```ts
const CM = () => {
 const { error, success, loading } = useSelector(state => ({
  ...state.pluginname.modelx.effectx,
  ...state.loading.modelx.effectx
 }))
}
```

Probably the best is modifying actual loading plugin to handle this, so users with loading functionality can just use loading functionality and if users want control of his effects can pass that option.

Feel free to post your opinion! @tianzhich your opinion is important here too about what's the best for types.

**Comment by keithpickering** [comment]
Yeah, adding error + success to the loading plugin would be the best route. That makes it into a total powerhouse and basically halves the amount of reducers people will need to write in their models.

**Comment by semoal** [comment]
Alright then, i have the same opinion, I'll try to work on it this weekend if i got some free time from writing Rematch's book :D

**Comment by keithpickering** [comment]
> Alright then, i have the same opinion, I'll try to work on it this weekend if i got some free time from writing Rematch's book :D

Thanks so much! I love this library btw. Never made sense to me that actions, reducers, and async effects all had to be in separate files. This makes redux actually fun to use.

**Comment by keithpickering** [comment]
Oh also, I guess logically whenever `loading` is set to true for an effect, `success` and `error` should both be cleared/reset

**Comment by semoal** [comment]
I'll work on this feature the next week :) Couldn't find free time yet

**Comment by semoal** [comment]
Finally, after a long time... Maintaining multiple OSS projects + Writing a book + Eating for surviving it's so damn it complex.

Enjoy the feature mate, feel free to open any issue if you see something to improve.
