### ISSUE TITLE
Type of property 'dolphins' circularly references itself in mapped type 'ExtractRematchDispatchersFromModels<RootModel>'.ts(2615)

### ISSUE THREAD

**Issue by ibufu** [rematch/rematch#878]
Type of property 'dolphins' circularly references itself in mapped type 'ExtractRematchDispatchersFromModels<RootModel>'.ts(2615)

**Describe the bug**

**Reproduce Link**
https://codesandbox.io/s/lucid-sunset-oe8yo?file=/src/models/dolphins.ts

**To Reproduce**

Return effect in effect function

**Expected behavior**

**Screenshots**

**Desktop**

**Additional context**

**Comment by semoal** [comment]
https://rematchjs.org/docs/getting-started/typescript#effects-returning-values
