### ISSUE TITLE
Example has issue with dependency cyle

### ISSUE THREAD

**Issue by stefensuhat** [rematch/rematch#882]
**Describe the bug**
typescript example will produce `ESLint: Dependency cycle detected.(import/no-cycle)`

**Expected behavior**

**Screenshots**

**Desktop**

- OS: [MacOS Big Sure]
- Browser [Chorme]
- Version [latest]

**Additional context**

![Screen Shot 2021-04-07 at 5 58 47 PM](https://user-images.githubusercontent.com/10653041/113848307-87a32e00-97c2-11eb-96e9-9ed6c8716aad.png)

**Comment by stefensuhat** [comment]
the only solution for now is disabled it manually like this: `// eslint-disable-next-line import/no-cycle`

**Comment by semoal** [comment]
Yes, we spoke already about this. To get the Typescript typings to work we have to this "DEPENDENCY CYCLE" which is not when we speak about types.

I recommend to use:

```tsx
import type { RootModel } from "."
```

And you won't see that "error" again

**Comment by semoal** [comment]
Also, I recommend to check the all-plugins-react-ts example which is the most complete example of Rematch, with all the plugins working and classes/and hooks :),

ps: https://github.com/rematch/rematch/commit/ae874738b474c33bb15ef39546389b6286399303 Just pushed a commit with this fixes to the example, feel free to take it a look :)
