### ISSUE TITLE
Complex state declaration with @typescript-eslint/consistent-type-assertions

### ISSUE THREAD

**Issue by julytang** [rematch/rematch#883]
## 📚 Documentation

I wrote some code followed by the documentation below.
![Screen Shot 2021-04-21 at 6 26 06 PM](https://user-images.githubusercontent.com/6831587/115539277-5a30a700-a2cf-11eb-9e98-e62756c68367.png)
And I got a eslint error like this.
![Screen Shot 2021-04-21 at 6 28 50 PM](https://user-images.githubusercontent.com/6831587/115539337-6f0d3a80-a2cf-11eb-92f8-007c3a77a5c0.png)

How to solve it but not turn the rule off. Thanks a lot.

**Comment by semoal** [comment]
As you could see Rematch models are just pure objects you can do two things:

1st option:
```ts
type MallInfo = any
type UserCenterState = {
  mallList: MallInfo[]
}
const userCenterState: UserCenterState = {
  mallList: []
}
const userCenterModel = createModel<RootModel>()({
  state: userCenterState,
  reducers: {},
  effects: {}
})
```

2nd option:

```ts

type MallInfo = any
type UserCenterState = {
  mallList: MallInfo[]
}

const userCenterModel = createModel<RootModel>()({
  state: {
    mallList: []
  } as UserCenterState,
  reducers: {},
  effects: {}
})
```

**Comment by julytang** [comment]
> As you could see Rematch models are just pure objects you can do two things:
> 
> > Typescript eslint rule complains about using as with a type which is not defined, if you extract the `as` type to an isolated type, typescript-eslint won't complain :)
> 
> 1st option:
> 
> ```ts
> type MallInfo = any
> type UserCenterState = {
>   mallList: MallInfo[]
> }
> const userCenterState: UserCenterState = {
>   mallList: []
> }
> const userCenterModel = createModel<RootModel>()({
>   state: userCenterState,
>   reducers: {},
>   effects: {}
> })
> ```
> 
> 2nd option:
> 
> ```ts
> type MallInfo = any
> type UserCenterState = {
>   mallList: MallInfo[]
> }
> 
> const userCenterModel = createModel<RootModel>()({
>   state: {
>     mallList: []
>   } as UserCenterState,
>   reducers: {},
>   effects: {}
> })
> ```

Thank you so much.

**Comment by semoal** [comment]
To you, for using Rematch =) 
Feel free to open another issue or question you have :)

**Comment by julytang** [comment]
> To you, for using Rematch =)
> Feel free to open another issue or question you have :)

I tried both of the options.
the second options doesn't work. But the first option works fine.
I have used rematch for a long time, it's really a great tool and helped me a lot. Thanks.
