### ISSUE TITLE
📚  Suggestions to improve the documentation/book

### ISSUE THREAD

**Issue by semoal** [rematch/rematch#884]
## 📚 Documentation

Hello folks 👋🏻,

I would like to know if there's any topic you see unclear in the documentation or something we didn't cover enough.

Also, I'm open to listen any recommendation or topics you would like to see in the official Rematch book!

**Comment by fkrauthan** [comment]
Ether I am stupid but I can't find out what the official API is for

```
Reducers may also listen to actions from other models by listing the 'model name' + 'action name' as their key (see example).
```

As none of the examples seem to show it. If I have a model called `items` and a reducer called `finishedLoading` what would be the proper syntax in a different model. Do I define a reducer called `itemsfinishedLoading` or `itemsFinishedLoading` or items/finishedLoading`?

**Comment by semoal** [comment]
> Ether I am stupid but I can't find out what the official API is for
> 
> ```
> Reducers may also listen to actions from other models by listing the 'model name' + 'action name' as their key (see example).
> ```
> 
> As none of the examples seem to show it. If I have a model called `items` and a reducer called `finishedLoading` what would be the proper syntax in a different model. Do I define a reducer called `itemsfinishedLoading` or `itemsFinishedLoading` or items/finishedLoading`?

The API Reference, documents how Rematch it's based on the `init()` method to initialize the store, then the models and his structure, Redux and how you can inject native middlewares/plugins into Rematch, Store how can you use the store to lazy load models or which functions are exposed through the store...

About your question:

You can do two things -> 1st using the global dispatch:

```js
export const items = {
  state: { finishedLoading: false, items: [] },
  reducers: {
    finishedLoading: (state, payload) => return {
        ...state,
        finishedLoading: true
     },
  }
};
```

```js
export const otherModel = {
  effects: (dispatch) => ({
    dispatch.items.finishedLoading();
  })
};
```

In the same way on React view, you can use the `useDispatch` hook offered by React-Redux and you can dispatch that reducer from anywhere.

If in a different model, you want to listen to another reducer execution, you can use:

```js
export const otherModel = {
  reducers: {
   'items/finishedLoading': () {}
  }
};
```

Hope this helps you! (I'll update a bit that section)
