### ISSUE TITLE
Dynamically adding a model to the store with disabled redux devTools using store.addModel breaks @rematch/persist

### ISSUE THREAD

**Issue by mvilledieu** [rematch/rematch#890]
When using `@rematch/persist` along with trying to dynamically add a model after the `init()` using `store.addModel()`, it stops persisting the data. 

1. create a `store` using the `init` function with `plugins: [persistPlugin(persistConfig)]`
2. add a model asynchronously to the `store` using `store.addModel()`
3. Make a modification to persisting data
4. Reload the page, and realize the data isn't persisting.

**Expected behavior**

On reload the data should be properly persisted

**Desktop**

- OS: MacOS
- Browsers - All
- Version - All

**Comment by semoal** [comment]
I'll take a look tonight, thanks for reporting this mate

**Comment by semoal** [comment]
https://github.com/rematch/rematch/pull/891
I've tried to reproduce it mate and couldn't find the issue.

Which version of Rematch are you using?

**Comment by mvilledieu** [comment]
Hi Semoal, thanks for looking into this. Here are the versions I am using. 

```
"@rematch/core": "^2.0.1",
"@rematch/persist": "^2.0.1",
"@rematch/select": "^3.0.1",
"redux-persist": "^6.0.0",
```

I think I found out about the edge case by looking at the differences between your example and mine I realized you do not have a setup for `redux` in the `init` store function, I do. 

```
 const store = init({
    models,
    plugins: [persist(persistPluginConfig), selectPlugin()],
    redux: {
      middlewares,
      devtoolOptions: { disabled: true },
    }
})
```

Apparently, disabling the devTool is causing this issue, whenever I turn the `devtoolOptions`  to not be disabled it is not working anymore.

**Comment by mvilledieu** [comment]
Just tested in your branch was able to reproduce by adding disable devtoolOptions: 

```
export const store = init<RootModel, FullModel>({
	// @ts-ignore
	models,
	plugins: [
		updated(),
		loading(),
		persist({
			key: 'persist-storage',
			storage,
			whitelist: ['settings'],
		}),
		immerPlugin({
			whitelist: ['settings'],
		}),
		selectPlugin(),
	],
	redux: {
		devtoolOptions: { disabled: true },
	},
})
```

**Comment by semoal** [comment]
Yes, totally agree that the problem is the Redux Devtools does something extra that we though it was working for everyone. 

I'll try to get a fix this weekend asap for this, thanks for reporting this mate

**Comment by semoal** [comment]
https://github.com/rt2zz/redux-persist/issues/1287
Looks an issue with redux-persist itself, I'm going to try to fix this issue from Rematch side :)

**Comment by semoal** [comment]
Found a workaround:

Pass `manualPersist: true` to the persist plugin:

```tsx
persist(
	  {
		  key: 'persist-storage',
		  storage,
		  whitelist: ['settings'],
	  },
	  {},
	  {
		  manualPersist: true,
	  }
),
```

After that you need to run on a use effect(() => persistor.persist(), in that way the application is persisted at the init and the loading persistor gate won't be stuck:

```tsx
import { getPersistor } from '@rematch/persist'
import { PersistGate } from 'redux-persist/integration/react'

const persistor = getPersistor()
const PreviewSelector = () => {
	const [showHooks, setShowHooks] = useState<boolean>(true)
	useEffect(() => {
		persistor.persist()
	}, [])
	return (
		<PersistGate loading={'loading'} persistor={persistor}>
			<div>
				<button type="button" onClick={() => setShowHooks(true)}>
					Show Application with hooks
				</button>
				<button type="button" onClick={() => setShowHooks(false)}>
					Show Application with classes
				</button>
				{showHooks ? <App /> : <AppWithoutHooks />}
			</div>
		</PersistGate>
	)
}
```

When you load dynamically your new model, you want to tell redux-persist to listen to that new model so:
```tsx
import { getPersistor } from '@rematch/persist'

const persistor = getPersistor()


React.useEffect(() => {
	store.addModel(settings)
	persistor.persist()
}, [])
```

Tried it in the example provided and worked nicely without the devtools option. Anyways I'll try to take a look to redux-persist codebase if I can fix this from the redux-persist side.

**Comment by semoal** [comment]
I know this is a bit tricky but Redux-persist doesn't got updates since 2019, so this is the current solution I can offer, hope someone gets time and takes the role of maintaining redux-persist :)

**Comment by mvilledieu** [comment]
No this is great, thanks a lot for your help Semoal 🙌🏼

**Comment by mvilledieu** [comment]
I think this will require a little work on my end to make sure the model is already available when first calling persist to prevent it from clearing the previous persisting elements from localStorage because they aren't here yet. So I think I have a path forward.

**Comment by semoal** [comment]
I'm taking a look to the plugin if we can do something in the lifecycles of Rematch exposes.

**Comment by semoal** [comment]
I think i found a fix mate!!
Give me 30 minutes to refactor the code and i'll create a merge request

**Comment by semoal** [comment]
The fix I've found worked well without devtools but breaks with it... amazing
