### ISSUE TITLE
npm naming

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#90]
Thoughts on the npm name and the way to name the plugins?

### rematch
`rematch-x`
`rematchjs`
`re-match`
`redux-rematch`
`rematch-redux`

### plugins 
Maybe do it the way babel does it?
`rematch-x-plugin-loading`
`rematch-x-plugin-persist`

**Comment by ShMcK** [comment]
Check this out: http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages.

In other words, we own the name `@rematch`.

We can name packages `@rematch/loading`, `@rematch/persist`

**Comment by ShMcK** [comment]
So the question remains, what to name the core package?

**Comment by blairbodnar** [comment]
Very cool!

Yeah, I like `@rematch/core`. Nice and short. And just like babel.

That will work so nicely with the plugins too. 👍
