### ISSUE TITLE
Rational behind triggering effects when same reference is returned  in reducer

### ISSUE THREAD

**Issue by hb1998** [rematch/rematch#905]
**Describe the bug**

> Effects functions that share a name with a reducer are called after their reducer counterpart.

this feature is really helpful to modularise the effects triggering logic but when we return the same reference of the state in the reducer, the `mapState` subscriptions doesn't trigger but the effects are triggered.

Not sure if this is intentional, as far as I'm concerned, i feel they shouldn't be triggered.

**Reproduce Link**

https://codesandbox.io/s/silly-jepsen-gxh9m?file=/src/App.tsx

**To Reproduce**

- Note that when  `+1` is clicked `render triggered` is not consoled meaning mapState is not triggered but `effect triggered` is consoled

**Expected behaviour**

Effect shouldn't be triggered when state reference is not changed 

**Desktop**

- OS: macOS
- Browser: chrome

**Comment by semoal** [comment]
Rematch in overall is Redux, and as you would know if you don't change the state reference Redux will never repaint the screen.

Effect is triggered because it's dispatched, there's none relation between repaints <-> effects.

**Comment by ArulValan** [comment]
@semoal If that's the case can we get previous state in the effects callback. Because there should be a way to know if the state has changed or not.

**Comment by semoal** [comment]
What's the use case for that?

**Comment by ArulValan** [comment]
I'm calling a reducer to close a menu if there is a change in state the canvas space changes then I wanna trigger a recalculation in respective effect.
But in cases when the menu is already closed the reducer returns the same state, then there's no need to call recalculation as the state is same anyways.

**Comment by semoal** [comment]
Your use case should be solved in user interface in not in the data layer. Actually changing this behaviour imply a breaking change that we can't afford right now.

You could give it a try to Rematch Plugins where probably you could create something to override this logic.

Or just simply use the user interface to handle this.

If you're using React hooks, you could perfectly do:

```jsx
import { useEffect } from "react"
import { useSelector, useDispatch } from "react-redux"

export const App = () => {
  const dispatch = useDispatch()
  const isOpen = useSelector(state => state.x.isOpen)

  useEffect(() => {
    isOpen && dispatch.x.loadOptions()
  }, [isOpen])
}
```

Solving this in the data layer is not a good idea, and your use case should be declarative, creating magic to solve this problem will cause future problems in your codebase.
