### ISSUE TITLE
Unhandled promise rejection with the Loading plugin

### ISSUE THREAD

**Issue by SpiriaJWF** [rematch/rematch#906]
A Warning Unhandled promise rejection is thrown when having a Promise.reject using async function with the Loading plugin

**Reproduce Link**

Base : https://codesandbox.io/s/rematch-todos-demo-forked-xlq9k?file=/models.js

**To Reproduce**

1. In the method asyncRemove add at the top a throw (eg: throw "error"; )
2. Where the asyncRemove is called surround it with a try catch
2. Open the debugging console
3. In the web view click on the button async delete

**Expected behavior**

In the loading wrapper it should catch the error and rethrow ii

**Platform**

Web
Mobile (React-Native)

**Comment by semoal** [comment]
Sorry, but I'm not sure why should do that the loading plugin?

**Comment by SpiriaJWF** [comment]
I think there is a try{} finally{} that wraps the effect call. There is no catch so the warning is thrown. When I remove the loading plugin, I don't have this problem.

**Comment by SpiriaJWF** [comment]
I updated the step to reproduce. I surround the code that is calling asyncRemove with a try catch. But even with that I have an unhandled promise rejection.
