### ISSUE TITLE
feat: subscriptions

### ISSUE THREAD

**Issue by NoahStepheno** [rematch/rematch#919]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when use React with hooks. I always divide different logic codes into hook modules. And be called in React component. Ex:
```javascript
export function useSomeHooks() {
    React.useEffect(() => {
        // do some stuffs about this module or transform data. Maybe this is async. And then dispatch actions.
    }, [someState // from store])
}
````

I want to organize this code more suitable.

I think this code should not be a part of React Component.  And don't want to put it into the react pages or components.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/64339985/126075698-45c8bcd8-b1b5-4f4b-a99c-540b7d5f1ed2.png)

In my opinion, It should be part of the data. And probably this logic should be written in store. And trigger when the dependencies change.

**Describe alternatives you've considered**
Such as I know, redux is about MODEL or VIEW MODEL. But I'm not sure subscriptions are reasonable enough to be added.

If so, I'm willing to contribute the feature.

**Comment by semoal** [comment]
I'm practically sure that this feature can be made through Rematch plugins. If you want to contribute to Rematch and work on this plugin. I'll be happy to add it to the Rematch codebase. :)

Kind regards
