### ISSUE TITLE
Copy to clipboard button doesn't work

### ISSUE THREAD

**Issue by saud-otaibi** [rematch/rematch#920]
## 📚 Documentation

Hello everyone,

I was reading through the documentation to get started with Rematch and noticed that the command copy to clipboard buttons in (https://rematchjs.org) aren't working as expected. I know this isn't the biggest of issues but it would be nice to fix it.

I am using Firefox and also tried on Chrome and the same issue happens.

**Comment by semoal** [comment]
Thanks mate for reporting the issue, didn't notice! It's fixed with the latest commit!
