### ISSUE TITLE
Typescript : Meta parameter in Effects not recognize in mapDispatch

### ISSUE THREAD

**Issue by SpiriaJWF** [rematch/rematch#925]
When I use a method from my effects with a 'meta' parameter inside mapDispatch, Typescript only recognize my first parameter : payload

**Expected behavior**

Typescript should indicate that a meta parameter is needed

**Screenshots**
My model
```
export const panel = createModel<RootModel>()({
  state: [] as Panel[],
  reducers: {
    ...
  },
  effects: (dispatch) => ({
    updateGeolocation: async (payload: GeolocationUpdate, state, meta) => {
        console.log(meta));
    },
  }),
});
```

How I use it 
```
const mapDispatch = (dispatch: RematchDispatch<RootModel>) => ({
  updateGeolocation: dispatch.panel.updateGeolocation,
});
```

Typescript translate the method to 
```
const updateGeolocation: (payload: GeolocationUpdate) => Promise<void>
```

**Comment by semoal** [comment]
You have to type the `meta` parameter with the data that is expected.

**Comment by SpiriaJWF** [comment]
Nice it worked, thanks!
