### ISSUE TITLE
An argument for 'payload' was not provided.

### ISSUE THREAD

**Issue by puckey** [rematch/rematch#944]
**Describe the bug**

The following code produces a typescript error for the `dispatch.dolphins.fetch()` call:  
```
Expected 1 arguments, but got 0.ts(2554)
types.d.ts(124, 7): An argument for 'payload' was not provided.
```

```ts
export const dolphins = createModel<RootModel>()({
  state: 0,
  effects: (dispatch) => {
    return {
      async initialize() {
        await dispatch.dolphins.fetch();
      },
      async fetch(_, rootState) {
        console.log(rootState);
      }
    };
  }
});
```

**Reproduce Link**

https://codesandbox.io/s/late-wood-u4sel?file=/src/models/dolphins.ts

**To Reproduce**

Visit the link and check the typescript error

**Expected behavior**

I would expect this not to produce an error.

**Version**
rematch/core v2.1.1
typescript 4.4.4

**Comment by tianzhich** [comment]
Check [this](https://github.com/rematch/rematch/discussions/924) for how to use optional payload in rematch effects. In your example, you could define `_?, rootState?` as parameters.

**Comment by puckey** [comment]
awesome that fixes it - thanks!
