### ISSUE TITLE
Arguments Conflict with TS

### ISSUE THREAD

**Issue by codercodingthecode** [rematch/rematch#949]
**Describe the bug**

The function arguments conflicts with eslint/typescript
![image](https://user-images.githubusercontent.com/20182536/141380301-02d205eb-9b8e-45e1-977f-d81613ffcdfd.png)

![image](https://user-images.githubusercontent.com/20182536/141380456-c25761f8-a1b3-492a-8812-fd648e0bebd4.png)

No matter the output, eslint always catches it.
This is the same to effects as well.
It worked at some point in the past.
```
        "@rematch/core": "^2.2.0",
        "@rematch/loading": "^2.1.1",
        "@rematch/select": "^3.1.2",

**Comment by semoal** [comment]
Can you provide a minimal repo where we can help? 
Eslint is not failing is Typescript itself and I think that you have typed the effect getBookingById and doesn’t expect a string.

**Comment by codercodingthecode** [comment]
Unfortunately, I can't share the repo, but the functional calls are the same.

It is the same flow a standard models
```
{
 ...
  state,
  reducers...,
  selectors ....,
  effects...
```
I came across the same issue with the effects before, however, for the selector, I'm having a different issue, that appending ? to the arguments won't solve the issue.
![image](https://user-images.githubusercontent.com/20182536/141381427-039ee518-3457-4db7-a4d9-d9c0ffe50a5f.png)

**Comment by semoal** [comment]
No no... is not the same problem of effects. Selectors under the hood uses "reselect" that doesn't accepted for a long time parameters in his selectors.

I'm right now on the bed ready to sleep, search on Google passing arguments to Reselect and should help you.

Tomorrow I'll help you more in detail if you're still stuck and I'll update the documentation accordingly 

Thanks for using Rematch ❤️

**Comment by semoal** [comment]
Here you have an example mate:

```ts
   getCartProductById() {
      return createSelector(
        [slice, (state) => state.shop.products, (_, id: string) => id],
        (_, products, id) => {
          return products.find((product) => product.id === id);
        }
      );
    },
```

Test case: 
```ts
expect(
        store.select.cart.getCartProductById(
          {
            shop: {
              products: [
                {
                  id: "ID",
                  price: 9.99,
                },
              ],
            },
            cart: {},
          } as any,
          "ID"
        )
      ).toEqual({ id: "ID", price: 9.99 });
```

Hope this is helpful for you.

**Comment by codercodingthecode** [comment]
Thank you very much for the help.
Yes, that did help me understand the call signature of the library. And I got it to work.
Seems like the key for this is to use the Array as the first argument for the createSelector.
Without the array, the arguments need definitions, and the circular ts types kick in. It does seem like it tries to infer the types, although not so successful at it, but it works.

However, the linting still complains about it on the consumer side. Seems like the optional argument doesn't help much in this case.
![image](https://user-images.githubusercontent.com/20182536/141512366-54bcd38f-4911-49d2-9167-b93f6ae5c92c.png)

![image](https://user-images.githubusercontent.com/20182536/141512851-3b3a8062-e85d-4a59-b091-cb78bd57f9a4.png)

**Comment by codercodingthecode** [comment]
Given explanation addressed the issue.
