### ISSUE TITLE
Type errors when calling effects which utilize rootState without needing a payload

### ISSUE THREAD

**Issue by acnebs** [rematch/rematch#959]
I have some effects that don't take in a payload but *do* use the `rootState`, like, so:

```ts
async init(_, rooState) {
  // do stuff with rootState here
}
```

But when I try to call such an effect from elsewhere in the code:

```ts
dispatch.user.init()
```

TS throws an error saying `Expected 1 arguments, but got 0`. Is there a way to get around this? Right now I'm passing in `undefined` like so:

```ts
dispatch.user.init(undefined);
```

But I'd prefer not to have to do that if possible.

**Comment by semoal** [comment]
Hi! Which version of Rematch are you using?

**Comment by tianzhich** [comment]
maybe duplicate with https://github.com/rematch/rematch/issues/944

**Comment by semoal** [comment]
https://github.com/rematch/rematch/blob/main/packages/core/test/ts_typings/dispatcher-typings.test.ts#L319

Yep, exactly that. You have to make both optional by a design limitation of JavaScript itself. A required argument can't follow an optional one.

**Comment by acnebs** [comment]
Yep, duplicate, somehow didn't find that in my search! Thanks for the rapid response guys.
