### ISSUE TITLE
Preserving Rematch.js state between server and client side in Nextjs

### ISSUE THREAD

**Issue by snk-js** [rematch/rematch#961]
I'm using Rematch in production for Banking contexts, because of all non boilerplates, and also because is easy to replicate for other developers in my context.

But one problem I'm facing right now, is using Nextjs with Rematch and still can't figure out how to preserver Rematch State between client side and server side of the app. Is that I want to use the state constantly between server and client side in Nextjs because it's far lot more efficient to update and get state also in serverside.

The solution I proposed:
I didn't know the next steps to accomplish that, that's why I need some help to start implement by my own. Because in the past, passing the global redux object between a getStaticProps was a deal (but actually not best practices cause it would turn off some nextjs optimization). Today Rematch It's seems complicated to do this

any ideas?

**Comment by semoal** [comment]
Under the hood Rematch uses Redux, it should work as traditional Redux. Feel free to check nextjs/ examples folder they have examples with Rematch
