### ISSUE TITLE
@rematch/loading 0.1.0 - ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#97]
This following code generates the error: "ReferenceError: regeneratorRuntime is not defined"
```js
import RematchLoading from '@rematch/loading'

init({
  plugins: [RematchLoading()]
})s
```

**Comment by blairbodnar** [comment]
Didn't get a chance to look into this yet, but I'm wondering if it might be the same issue that we fixed with publishing `@rematch/core`? ([The babel fix we made going from 0.1.0-alpha.1 to 0.1.0-alpha.2](https://github.com/rematch/rematch/commit/433c90d9f059105618b78527d379012ffb7fcfd0)) 

Also, I haven't tried `@rematch/persist` yet... I'm gonna guess that this issue might be there as well.

**Comment by ShMcK** [comment]
I think you're right.  I have a quick fix...

**Comment by ShMcK** [comment]
I'll push a fix, but it may be worth looking into #93.

**Comment by ShMcK** [comment]
Ah, it seems you're in an environment that is not supporting Async/Await.

You may need to use babel, typescript, or a polyfill. Learn more [from this babel issue](https://github.com/babel/babel/issues/5085)

**Comment by suazithustra** [comment]
Would it be counterintuitive to just use fetch.then.catch in the effects instead?

**Comment by suazithustra** [comment]
Babel is just fine, thanks.
```
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "10" } }]
  ]
}
```
