### ISSUE TITLE
Installation step for @rematch/immer installs immer 10

### ISSUE THREAD

**Issue by chickoocoutinho** [rematch/rematch#983]
## 📚 Documentation

`
npm install immer @rematch/immer
`

**@rematch/immer** is compatible with immer 7, immer 8, immer 9.

The above command installs immer 10.

Need to change the command to

`
npm install immer@9 @rematch/immer
`

**Comment by Kris-Pelteshki** [comment]
Thanks for the comment. I was wondering why it wasn't working.
👍Saved me a lot of time

**Comment by sien75** [comment]
Yes, immer@10 has changed their api, from
`import produce from 'immer'`
to
`import { produce } from 'immer'`
Using @rematch/immer@2 with immer@10 will cause "TypeError: Object(...) is not a function".
@rematch/immer plugin should lock its immer peerDependency to not higher than 9, and explain this in the document.
