### ISSUE TITLE
Rematch website is down

### ISSUE THREAD

**Issue by aditasha** [rematch/rematch#989]
**Describe the bug**

Cannot access rematch js website

**Reproduce Link**

https://rematchjs.org/

**To Reproduce**

1. Go to https://rematchjs.org/
2. Error 'Connection closed'

**Expected behavior**

Able to access website

**Screenshots**

![Screen Shot 2024-02-15 at 11 21 00 (2)](https://github.com/rematch/rematch/assets/83056427/793e0f04-7d6d-4797-9069-5b14fb47937d)

**Desktop**

- OS: [MacOS]
- Browser [Chrome]
- Version [Big Sur 11.7.10]

**Comment by ratnabh** [comment]
I still cant access the website, are there any updates ?

**Comment by fqycugb** [comment]
I also come across this problem.

**Comment by itsfaraaz** [comment]
also down from me, anywhere else to see the docs?

**Comment by tianzhich** [comment]
@semoal Hi mate, can you help with this?

**Comment by semoal** [comment]
Yes will renew the domain asap guys, I'm sorry for the troubles
