### ISSUE TITLE
Consider some thoughts from this Github stars article

### ISSUE THREAD

**Issue by blairbodnar** [rematch/rematch#99]
Saw this today. Might be a couple ideas we can take away from it.

[https://medium.freecodecamp.org/how-to-get-up-to-3500-github-stars-in-one-week-339102b62a8f](https://medium.freecodecamp.org/how-to-get-up-to-3500-github-stars-in-one-week-339102b62a8f)

**Comment by ShMcK** [comment]
I'm really inspired by the [README examples](https://github.com/matiassingers/awesome-readme).

We could definitely use a Rematch logo / banner. Also, explaining concepts with images may be more powerful.

**Comment by blairbodnar** [comment]
Check out these [sketch notes](http://chantastic.io/2016-reactjs-conf). Years ago Michael was sitting near me at [Ember conf 2014 Portland doing notes in that style](http://chantastic.io/emberconf2014) and I thought it was really cool!

Anyways, I'm thinking of playing around with a style like that, but using my iPad pro + pencil and [the paper app like this](https://www.fiftythree.com/think). 

I have a couple ideas up my sleeve for maybe making "best practices vs rematch", your "comparisons" chart, etc in this style. I'll play around with it.

**Comment by ShMcK** [comment]
Sounds cool. But also keep in mind images may be hard to translate.

**Comment by ShMcK** [comment]
Also - You can modify styles within a README with a `<style>` tag at the top. We currently do this already.

If we can write it as text, but with an interesting font / style, it would be translatable.
